### ISSUE TITLE
Black screen if you start video after picture

### ISSUE THREAD

**Issue by boot2k3** [xbmc/xbmc#14643]
### Describe the bug
Here is a clear and concise description of what the problem is:

Black screen instead of video if video is loaded right after picture in the same directory. 
I hear sound stream of video, but no video

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video have to be on screen, not a black screen

### To Reproduce

1. Go to pictures and open directory where you have image and video files 
2. Open image
3. Go to next picture. If next file is not picture but video than you see black screen

### Debuglog

The debuglog can be found here:
https://pastebin.com/aw93QPAK

### Your Environment
Used Operating system:

 - [X] Android
 - [X]  Linux with AMLogic
 - [ ] iOS
 - [ ] Linux 
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android, Libreelec
 - Kodi version: Leia last nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by FernetMenta** [comment]
please post log for Linux too

**Comment by boot2k3** [comment]
Looks like it repeated only on amlogic box on both Android Kodi and and LE/CE
CE log if required: https://pastebin.com/ehq7q1zY

on x86 all works correctly

**Comment by memphissn** [comment]
Same situation persist also for Raspberry Pi platform. Video is played on background, but when i click to "esc" and return to menu i see currently played video on transparent background. Maybe issue appears with layers of GUI environment, because video is played, but video layer is hidden behind black screen :/

**Comment by DrSky2007** [comment]
Exactly the same problem with the Raspberry Pi 2 and OSMC (Kodi 17) and LibreELEC (Kodi 18).
It is like memphissn says: "Video is played on background, but when i click to "esc" and return to menu i see currently played video on transparent background."
Please fix it!

**Comment by Catscrash** [comment]
same here, this is a real issue

**Comment by githubhohdorfnet** [comment]
Excactly the same problem here, with Raspberry 3b and 3b+.

**Comment by Esokrates** [comment]
I can confirm the issue on Android TV. When selecting a video and clicking "Start slideshow from here", I can hear the sound in the background, but the video is not playing, all I see is the preview thumbnail of the video.

**Comment by Esokrates** [comment]
I reproduced on Linux (Ubuntu) too, Kodi 17.6 and Android TV, latest Google Playstore version. 

Files to reproduce can be found here: https://vtugit.ocloud.de/index.php/s/Rx6GGiwq6AkobB6

1. Extract the zip file
2. Add folder to Kodi
3. Select the mts video file and select "Start slideshow from here"
4. You will hear sound, but the video is not playing, all you see is the first frame of the video

When moving the mouse pointer the screen gets repainted to the current frame in the video, so constantly moving the mouse pointer makes the video show.

**Comment by Esokrates** [comment]
@FernetMenta Tested the flatpak version (18.3) since I found out that Kodi 17.6 does not contain your fix.

The fix https://github.com/xbmc/xbmc/pull/13031 definitely improves the situation, however it does not fix the issue. The steps to reproduce as written above work still work, with the exception, that the moving mousepointer does not workaround the issue anymore.

When starting the slideshow beginning with the video, it does not work, however when exiting the slideshow and restarting the slideshow the video plays fine in the slideshow. As soon as the Pictures menu is left again, the problem reappears.

Steps to workaround:
1. Start slideshow with video and wait until the slideshow has transitioned to the next picture
2. Exit slideshow
3. Start slideshow again
4. Now the video plays fine

**Comment by FernetMenta** [comment]
I can't reproduce on OSX and X11. As mentioned many times, this issue is related to platforms that do not render video to gui layer. You have to poke the platform devs who care about those systems.

**Comment by Esokrates** [comment]
@FernetMenta Thanks for the quick reply and your try to reproduce. I'm new to Kodi, could you please tell me how to poke platform devs and where I could reach them? Who are the respective platform devs? Is this issue here on Github not the right place?

Would this issue have to be fixed for each platform specifically or is there some layer in-between for those platforms?

I would really like to help with this issue, although I do not really have experience with large C++ projects I can at least apply patches and help with testing.

Regarding OSX/X11, isn't it strange that OSX/X11 is so much different from Linux/X11?

**Comment by FernetMenta** [comment]
> Regarding OSX/X11, isn't it strange that OSX/X11 is so much different from Linux/X11?

There is not OSX/X11. I tested on OSX AND Linux X11. I always explicitly state X11 because there is a huge difference to other Linux platforms. If you experience that issue on X11, please post a log.

btw: the label Linux on this bug report is maximum nonsense. It is only misleading.

**Comment by Esokrates** [comment]
@FernetMenta I tested it on Linux/X11 too, Ubuntu 19.04 fully upgraded, Kodi flatpak from Flathub. I'll follow up with the log info.

**Comment by wsnipex** [comment]
just FYI, the flatpak package provides kodi x11 and GBM. If you start kodi from your x11 based desktop, it will automatically use the correct version

**Comment by Esokrates** [comment]
@wsnipex correct version of what? you mean the respective backend?
So you are saying the flatpak version on an X11 based desktop does not necessarily use X11?
In any case, I'll also recompile Kodi 17.6 from Ubuntu repo with the patch applied and provide the log also.

**Comment by FernetMenta** [comment]
I won't look into a log of 17.6 patched version. That's a waste of time.

**Comment by FernetMenta** [comment]
I tried another time on my system and indeed it failed on OSX too. Reason:
https://github.com/xbmc/xbmc/commit/d7e5ea390e606ade98650d6944ab2a90c8fb34c9#r34639047

**Comment by Esokrates** [comment]
Debug log from Kodi 18.3 on Ubuntu/X11 installed from https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa can be found here: https://vtugit.ocloud.de/index.php/s/CHqaqAtJNcL6rbD

**Comment by Esokrates** [comment]
@FernetMenta Thank you very much for trying again. I think I also observed one case where it suddenly worked but all the other times it failed again.

**Comment by ksooo** [comment]
> I tried another time on my system and indeed it failed on OSX too. Reason:
d7e5ea3#r34639047

Cannot reproduce and cannot see how above commit could be the cause of this issue. Can you please tell me how I can reproduce the issue on OSX?

**Comment by FernetMenta** [comment]
> Can you please tell me how I can reproduce the issue on OSX?

Use the provided pictures above and try several times. Your changes made my fix https://github.com/xbmc/xbmc/pull/13031 useless because the video gets a picture tag and as a result MarkDirtyRegion is not called on the video.

Maybe there is some other thing on your system that renders the window dirty. Set a BP on the patch I did and you'll notice that it won't get called anymore.

**Comment by ksooo** [comment]
Ah, now I see how things are related. I will try to reproduce and will come up with a fix hopefully soon.

**Comment by ksooo** [comment]
@FernetMenta I can reproduce the issue on my Shield and applied the following fix attempt, which ensures that the video item does not get a pictureinfotag. Unfortunately, this does not fix the black screen issue, because `MarkDirtyRegion` still does not get called, because `g_application.GetAppPlayer().IsRenderingGuiLayer()` returns `false`.

```
diff --git a/xbmc/guilib/guiinfo/PicturesGUIInfo.cpp b/xbmc/guilib/guiinfo/PicturesGUIInfo.cpp
index c38b1c42c5..69905f20d0 100644
--- a/xbmc/guilib/guiinfo/PicturesGUIInfo.cpp
+++ b/xbmc/guilib/guiinfo/PicturesGUIInfo.cpp
@@ -92,15 +92,20 @@ CPicturesGUIInfo::~CPicturesGUIInfo()
 
 void CPicturesGUIInfo::SetCurrentSlide(CFileItem *item)
 {
+  if (m_currentSlide && item && m_currentSlide->GetPath() == item->GetPath())
+    return;
+
   if (item)
   {
-    CPictureInfoTag* tag = item->GetPictureInfoTag();  // creates item if not yet set, so no nullptr checks needed
-    if (!tag->Loaded()) // If picture metadata has not been loaded yet, load it now
-      tag->Load(item->GetPath());
-
+    if (item->HasPictureInfoTag()) // Note: item may also be a video
+    {
+      CPictureInfoTag* tag = item->GetPictureInfoTag();
+      if (!tag->Loaded()) // If picture metadata has not been loaded yet, load it now
+        tag->Load(item->GetPath());
+    }
     m_currentSlide.reset(new CFileItem(*item));
   }
-  else
+  else if (m_currentSlide)
   {
     m_currentSlide.reset();
   }
```

**Comment by ksooo** [comment]
> Your changes made my fix #13031 useless because the video gets a picture tag and as a result MarkDirtyRegion is not called on the video.

Although the fixes for `CPicturesGUIInfo::SetCurrentSlide` you suggested are absolutely okay, the unpatched code neither causes the black screen issue, nor do the patches fix it. Root cause is not `m_slides.at(m_iCurrentSlide)->IsVideo()` returning `false`, but `g_application.GetAppPlayer().IsRenderingGuiLayer()` returning `false. This happens with and without your suggested fixes.

**Comment by FernetMenta** [comment]
Shield and all systems that render video to a video layer is a different issue and should be treated separately.
Fixing CPicturesGUIInfo::SetCurrentSlide makes slideshow work again on OSX, X11, Windows, etc

**Comment by FernetMenta** [comment]
@ksooo this bug report is for Shield and friends and as you stated correctly, CPicturesGUIInfo::SetCurrentSlide has no impact here. It just restores the state that this bug here is only related to video layer systems.

**Comment by ksooo** [comment]
> Fixing CPicturesGUIInfo::SetCurrentSlide makes slideshow work again on OSX, X11, Windows, etc

 Okay, so my patch (see my previous comment) is okay to fix "systems that do not render video to a video layer "?

**Comment by ksooo** [comment]
> Fixing CPicturesGUIInfo::SetCurrentSlide makes slideshow work again on OSX, X11, Windows, etc

 Well, I have debugged on OSX and even with my patch `MarkDirtyRegion`does not get called because `g_application.GetAppPlayer().IsRenderingGuiLayer()` returns `false`. Confused.

**Comment by ksooo** [comment]
Okay, now I think I fully understand what's going on and I think my patch posted previuosly in this PR is correct and it actually fixes the black screen problem for "systems that do not render video to a video layer". @FernetMenta do you agree? If so; i will open a PR for the fix.

BTW: Do you have an idea how to fix this for "systems that do not render video to a video layer " like the Shield?

**Comment by ksooo** [comment]
The `CPictureInfoTag`that was created by the unpatched code, actually made "CFileItem::IsVideo() return false, but only for some video types. Namely, those for which we detect and fill CFIleItems mime member (like mov, which I used in my initial tests) do work and others (like mts, provided with the test files in this PR) for which we do not fill CFileItem's mimetpe do not work. For details see the implementation of `CFileItem::IsVideo()`. Order of the checks done there is responsible for that behavior. Presence of a `CPictureInfoItem` makes 'IsVideo' return early false for those video items with no video mimetype set. But if there is no `CPictureInfoTag` set, a check for a known video file extension at the very end of `CFileItem::IsVideo()` will match.

**Comment by FernetMenta** [comment]
> Okay, now I think I fully understand what's going on and I think my patch posted previously in this PR is correct and it actually fixes the black screen problem for "systems that do not render video to a video layer". @FernetMenta do you agree? If so; i will open a PR for the fix.

This is correct.

> BTW: Do you have an idea how to fix this for "systems that do render video to a video layer " like the Shield?

Yes, the video needs to shine through the gui layer. To achieve this, the area that would obscure the video, needs to be rendered transparent. Check CGUIVideoControl. Not sure the code there still works.

**Comment by Esokrates** [comment]
Thank you both for having a look at this. Would be great if you could also fix the issue for Android TV Devices like the Shield, because such a slideshow with pictures and videos is really missing on that platform, as all the other apps (including the Albums App from Sony) I have tried do not support video at all and crashed often besides lacking configuration options, as well as good slide transitions.

**Comment by ksooo** [comment]
Fix  is in master and was back ported for 18.4

**Comment by nls-GitHub** [comment]
I tested with the new release of OSMC which now has Kodi 18.4, and the video file plays along with the slides.  But there is an issue.  I also play background music along with the slides, that is done via the autoexec,py in the .kodi/userdata folder, playing a music list in a repeat mode.  The playlist starts along with the slides, stops when the video file plays, but does not resume later after the video has ended.  I do not remember now how it was with Kodi 17.

**Comment by DaveTBlake** [comment]
> The playlist starts along with the slides, stops when the video file plays, but does not resume later after the video has ended.

I believe that that behaviour is to be expected. Muisc playback during a picture show only works while it only encounters images. Once a video has played there is no resume music feature.

**Comment by nls-GitHub** [comment]
The slideshow is in a continuous loop, and so is the music list.  The display does show the slides after the movie, and that loop does not stop.  So my expectation would be that the background music also start back up along with the slides, but I don't know how things are structured in code.

**Comment by DaveTBlake** [comment]
Well that might well be your "expectation" but it is not how this feature was implemented. In fact being able to play music while seeing pictures was more of an accident than a designed feature and changes to the videoplayer almost removed this feature completely.  But it was a very useful "accident", hence effort was made to keep the facility even with the inability to resume music once interrupted by video playback.  At the time the concern was that user would moan about resume being missing, but I hope you consider having the feature with limits is better than no feature at all (those were the options).

**Comment by nls-GitHub** [comment]
Yes, I fully agree that having the ability to play videos along with slides is more crucial than the background music.  But if there are any roundabout methods by which the background music could be resumed, please let me know.  Obviously there is no sync between the slides and the music, so it doesn't really matter where it picks up, if that is indeed possible.
