### ISSUE TITLE
Update of active skin fails

### ISSUE THREAD

**Issue by HeresJonny** [xbmc/xbmc#14663]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is a long standing bug in Leia that updating the active (third party) skin is not directly possible under Windows. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When an update for the skin is found the user then instructs Kodi to download and install it. Under Linux the update is installed on-the-fly.

## Actual Behavior

Under Windows, Kodi always returns an error for the active skin that the installation has failed.

## Possible Fix

At the moment the workaround is to select another skin, then restart Kodi, update the previous skin and after successful update make it active again.

### To Reproduce

1. Switch to a third party skin like "Estuary Leia mod by pkscout"
2. Wait for an update to be published and then try to install it

### Debuglog

The debuglog can be found here:

Sorry, I will have to wait for a skin update to capture this.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v18 [Leia]

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by MartijnKaijser** [comment]
Again we need something like https://github.com/xbmc/xbmc/pull/11520 or whatever else to fix this.

**Comment by linknetx** [comment]
@MartijnKaijser 

This PR #15310 fixes the textures.xbt file locking problem on Windows which is partly responsible for update of an active skin to fail.

This allows the active skin to be updated when installing updated skin via addons "Install from zip file". Tested with default textures and also with themes selected. Not tested when updating skin from online source which may possibly still fail due to antivirus locking the downloaded folder. Although I still believe that the main problem is due to the textures file lock.

This is essentially a copy of PR #11090 which was merged to Krypton but seems to have been omitted in Leia.

**Comment by MartijnKaijser** [comment]
fixed
