### ISSUE TITLE
Framerate change not work in 18, both x32 and x64

### ISSUE THREAD

**Issue by DeniR** [xbmc/xbmc#14675]
Auto framerate change broken in Kodi 18.
When I play 1080/50i video in Kodi17, it's change framerate on TV. There is nothing happens in Kodi 18, both x32 and x64.
Fullscreen mode (not windowed) and autochange are enabled in settings.
But fullscreen mode not work too, it's look like windowed mode forced. There is no "SetFullScreenInternal" in Kodi 18 log, like in 17.
[kodi17.log](https://github.com/xbmc/xbmc/files/2503468/kodi17.log)

[kodi18.log](https://github.com/xbmc/xbmc/files/2503460/kodi18.log)

**Comment by MartijnKaijser** [comment]
Have you enabled Whitelisting?
Also you did not follow our issue template

**Comment by DeniR** [comment]
WTF is Whitelist ? Why it's empty by default ? Where it placed ? Why google not found it ? Why you broke years-worked setup and add hidden 'feature' and there is no information or attention in download section about this incompatible issue ?
You can warn users in "Download" section, you can warn users on installation phase, you can open whitelist tab on first run, you can show some window on playstart with attention "This resolution and framerate not in whitelist, do you want to add now?"
Instead, you simple do nothing, and every user spent weeks to find this error or to rollback to previous version. Too bad, Kodi, too bad.

**Comment by MartijnKaijser** [comment]
Jeez stop whining.

**Comment by da-anda** [comment]
you realize that v18 is still not released, right? When implementing the whitelist approach (because of user demand) we decided to do some additional changes to prevent your issue, but unfortunately forgot about it after the feature got in (so many things had been going on in that time). So 👍 for the reminder and 👎 for not writing a proper bug report using our template and another 👎 for your last comment.
