### ISSUE TITLE
NFO Local Info Scraping Paths configurations.

### ISSUE THREAD

**Issue by antoniocaruso** [xbmc/xbmc#14911]
## Roadmap or todo suggestion
Add an option to advancedconfig.xml to set paths for nfo and images (.jpg, .png, .gif) files that will be used by kodi to search for localinfo (nfo file and artworks).

I have a very large collection of movies, all in the same folder. I really like to take the movie files by themself, without mixing them to others different kind of files. 
Actually if I want to store localinfo (nfo) or artwork, the only way for Kodi to see them is storing the files in the same folders and with the same filename of the movie.
What I'm proposing is to add the possibility for users/scrapers to add a specific path
<nfopath> option in advancedconfig.xml that specify one alternative folder to search for nfo
and a <artwork> option that set another folder as artwork folder.
Maybe it is ok to support just a single folder, but I believe that have two different folder for
nfo (xml) files and for the images and artworks will be even better.

### Context

Using a file browser with a lot of movies and for each of them the .nfo file and the different kind of images for poster, backgrounds, and other kind of artworks is a mess. It would be much better to keep them in another folder at least as an 'advanced option'.

Usability, as above.

### Possible Implementation

I read, about scraping plugin, and Nfo, kodi always search the nfo and artworks in the same folder
of the movies. This works if all movies are in a proper folder with their artwork but it is a mess if
all movies are in a single folder with all artworks and nfo file. So, as a simple implementation:
1) Add options for advancedoptions.xml to support at least another folder that will be used to search for nfo/artworks.
2) If and only if the option is used, search for nfo/artworks in that folder. (Here, the developers must decide if searching in the original folder is still a good idea, together to searching in the new folder).
3) Provide maybe an API for scrapers, that would add this as an option within their gui, to ask users if they want to add a path for nfo/artworks.

### Additional context, screenshots or links
Here are some relevant links or screenshots

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by DaVukovic** [comment]
>I have a very large collection of movies, all in the same folder.

That's why we recommend to store movies in their own folders matching the movie name. I know it's a lot of work doing that now if you have a huge library, but it would be the way to go. 

Storing all movies in a single folder will ofc end up in a complete mess if you export to separated nfo files. 

You could export the library to a single file. That isn't really a file, it's a folder with the following structure:

-  kodi_videodb_<date_of_export> (that's the library folder)
-- actors (stores all the actor thumbs)
-- movies (stores all the movie fanart and posters)
-- tvshows (contains subfolder for each tv show)
--- tv-show-name (for example "Game of Thrones" ... stores all the fanart, thumbs and posters for the tv show, the season and the episodes)
-- videodb.xml (that's the xml similar to the NFOs but it's a single file containing all the info for each movie in your library).

So using the export to a single file simply solves your issue. As everything is stored at the location you want  it to have.

**Comment by MartijnKaijser** [comment]
Please post suggestion/request on the forum
