### ISSUE TITLE
Kodi 18 Blu-ray and DVD menu regressions on Raspberry Pi

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#14986]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a lot of DVDs and Blurays in my collection with this issue - the on-disc menu navigation is broken because the button highlight overlays (or whatever they are called) don't work. The issue is only present in Kodi 18, no such issues in Kodi 17.6.

[Blu-ray sample](https://www.dropbox.com/s/km1khud1zm4ygl1/BDMV.7z?dl=1)
[DVD sample](https://www.dropbox.com/s/g4arcfcnibofjvo/dvd_menu_sample.7z?dl=1)

### To Reproduce

Just play any of my samples on RPi with MMAL hw acceleration enabled.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/awedicegiq.kodi

### Your Environment
Used Operating system:

 - [x] Raspberry-Pi

 - Operating system version/name:  LibreELEC (current Milhouse builds)
 - Kodi version: 18 (current master)

**Comment by popcornmix** [comment]
@FernetMenta I've been digging into this issue and it seems dvd menu is only rendered when hardware decoder produces a new ``m_picture.videoBuffer``.
With menus and still frames mmal decode produces ``m_picture.videoBuffer==nullptr`` as there is no new decoded frame and that results in dvd menus not udpating.

https://github.com/popcornmix/xbmc/commit/edbecaca8cfeeafc4b167cd8272819080b7331eb makes the dvd menus work again. Obviously a hack to show what's required, but I'd like to know what you think the correct solution to this issue is.

**Comment by FernetMenta** [comment]
@popcornmix I am sure we talked about this already: m_picture.videoBuffer has to stay valid until decoder produces the next pic. That allows VPV to render the same frame again.

**Comment by popcornmix** [comment]
Thanks for hint. I guess https://github.com/popcornmix/xbmc/commit/4918913a0f8eb0b4917037f6fba1efed6c8d509a is what you are suggesting.
Let me do some testing that it doesn't cause any mmal issues and I'll PR.

**Comment by popcornmix** [comment]
@smp79 Can you confirm if tonight's Milhouse build resolves this issue?

**Comment by smp79** [comment]
It did resolve the issue. Thanks!
