### ISSUE TITLE
Passthrough sometimes not working

### ISSUE THREAD

**Issue by DJRAVEN** [xbmc/xbmc#15049]
### Describe the bug
Here is a clear and concise description of what the problem is: On Kodi 18 RC2 passthrough is sometimes not starting properly. When you start a movie from BLURAY menu it always works. When you start a file directly it only works when you change the Audio track in Audio settings to a Different language and switch back. 
 Because it worked on Former Releases with settings unchanged. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
 Passthrough bitstream should Start itself

### To Reproduce

1. Start a file with DTS,AC3 or DTS-HD
2.Passthrough on
3.look what happens

### Debuglog

https://paste.kodi.tv/wuledumefa !--- A debuglog is always mandatory when creating an issue. Provide one! -->
The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
@puttu 

If you enable "sync playback to display", passthrough is automatically disabled as Kodi has to touch the audio and the video stream for that function. 

I'm not familiar with the FireTV sticks at all, so I can't tell anything about potential problems using "adjust display refresh rate". 

Anyway, and please don't get this wrong, we don't need bug reports which are based on Kodi 17.6. That version won't receive any updates/fixes anymore. So if you want to create a bug report, please make sure you installed Kodi 18 as that's the version developers focus on currently.

**Comment by puttu** [comment]
Thanks, @DaVukovic. Indeed, after installing v18 RC2 the problems went away. Turned out also that I misunderstood the sync functionality; I believe turning on "sync playback to display" when "adjust display refresh rate" is enabled should (in theory at least) do nothing.

**Comment by DaVukovic** [comment]
Generally true, yes. A case where you might need "adjust display refreshrate" disabled might be, if your TV doesn't support a fps given by the video and therefore it starts stuttering (for example, playing a 24fps video at a 60fps monitor where 24fps is not supported because the monitor is not able to do that). Then you will need "sync playback to display" to get rid of the stuttering. To achieve that, Kodi needs to drop/dupe audio and video packages and bitstreaming the audio isn't possible at this moment anymore, because it needs to modified by Kodi. 

This ^^ might technically not be 100% true, as I haven't written the code ;) . But that's how I understand the reason.
