### ISSUE TITLE
Kodi 18 rc3 Android Audio drop outs DD 

### ISSUE THREAD

**Issue by krille30** [xbmc/xbmc#15085]
### Describe the bug
Here is a clear and concise description of what the problem is:

Getting random Audio drop outs when playing DD or DTS videos in Kodi 18 rc2 and rc3. Having Android box Minix u9h connected to AVR Onkyo 626 through hdmi. 

Issue comes randomly somtimes every minute sometimes it can take 15min. In other video apps playing same video I dont get issue e.g VLC.

Noticed same isdue also on kodi 17.6

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expecting not to have audio drop outs when playing DD or DTS. 

## Actual Behavior

Getting randomly audio drop outs.

### To Reproduce

1. Play video with DD or DTS
2.
3.

### Debuglog

The debuglog can be found here:
Here is the debug log file https://paste.kodi.tv/eyenelevik

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:18 rc3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Where is your debug log?

**Comment by krille30** [comment]
Sorry rather new to this. Here is the log file https://paste.kodi.tv/eyenelevik
Can add that when playing file this time when logging I got issue after
First 4 min
Second 5 min
Third 7 min

**Comment by KarellenX** [comment]
Thanks @krille30 

Unfortunately your install is packed full of banned add-ons which makes you ineligible for support and this Issue report Invalid and subject to close.

Please read...
Forum Rules... https://kodi.wiki/view/Official:Forum_rules
Banned Add-ons example list... https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

In future, instead of jumping straight into reporting issues at Github, post in the forum to iron out all the "bugs" in your report first. If it is a valid bug a Team Member will then suggest you make your report here.

The forum moderators have determined that [[Banned_addons]] are present on your system. To receive assistance here, these banned items must be removed. If a clean log is not submitted within 3 days, then the relevant post(s) will be removed after this time.

**Comment by DaVukovic** [comment]
3 days passed, no clean log. Issue closed
