### ISSUE TITLE
Update audio library crashes Kodi 18 RC

### ISSUE THREAD

**Issue by bartmans** [xbmc/xbmc#15090]
When updating my audio library in the last three weeks (since december 1st 2018) on Kodi 18, the update stops and then crashes Kodi.

Using Windows 10 latest update. And using MariaDB for storing music dbase.

I checked the folder where the update stops, I see nothing unusual there (like really long filenames).

Kodi 17.6 readily accepts this folder when it updates.

[kodi_stacktrace-18.0-RC4 Git_20181217-4a52640cf3-20181219-095107.txt](https://github.com/xbmc/xbmc/files/2694026/kodi_stacktrace-18.0-RC4.Git_20181217-4a52640cf3-20181219-095107.txt)
[kodi.log](https://github.com/xbmc/xbmc/files/2694027/kodi.log)

**Comment by pkerling** [comment]
Unfortunately your stack trace (which would be most helpful) is truncated and not usable. Please reupload. Also, please stick to the issue template in the future.

**Comment by bartmans** [comment]
[kodi_stacktrace-18.0-RC4 Git_20181217-4a52640cf3-20181220-200811.txt](https://github.com/xbmc/xbmc/files/2700173/kodi_stacktrace-18.0-RC4.Git_20181217-4a52640cf3-20181220-200811.txt)
[kodi.log](https://github.com/xbmc/xbmc/files/2700174/kodi.log)

[kodi_crashlog-18.0-RC4 Git_20181217-4a52640cf3-20181220-200811.dmp.txt](https://github.com/xbmc/xbmc/files/2700177/kodi_crashlog-18.0-RC4.Git_20181217-4a52640cf3-20181220-200811.dmp.txt)
Changed the extension on the crashlog to .txt
Hope the upload is better.

**Comment by pkerling** [comment]
Stack trace is still only 33 bytes.

**Comment by Rechi** [comment]
@pkerling windows doesn't resolve the stack trace if the pdb file is missing.

**Comment by pkerling** [comment]
@Rechi do we have instructions for how to get proper traces on Windows somewhere? Can't really help here (although I assume the issue is platforma-gnostic).

**Comment by bartmans** [comment]
Sorry closed it by accident.

There are no folders in 0 - C. There are 68 mp3 files. 

Scanning from folder, or even trying to access the folder makes Kodi crash.

Can't say for sure which beta Kodi 18 this started. I never had this problem om 17.6.

How can I use portable mode and which versions do you recommnend testing?

**Comment by DaveTBlake** [comment]
Ok, so the issue has not just gone away.
>Scanning from folder, or even trying to access the folder makes Kodi crash.

So you can not navigate into this folder in file view and see the list of mp3 files? That is interesting and implies a tag reading issue or maybe folder/file access permissions - handling will have changed  since v17.6. To confirm that go to System > Settings > Media > Music - Files section and disable "Enable tag reading" setting (which disables the tag reading during file view). Then try to navigate into this folder from file view. Does it still crash?

>Can't say for sure which beta Kodi 18 this started. I never had this problem om 17.6.

Initially you said "since december 1st 2018" so I wonder if you were running v18 before then, or was that when you switched to v18?

>How can I use portable mode and which versions do you recommnend testing?

Portable mode is invoked by adding "-p" to the target of the Window shortcut used to inkoke Kodi. See https://kodi.wiki/view/Windows_FAQ#Portable_mode.  It is a good way to try out multiple versions of Kodi without changing your main installation. 

For investigating this issue (that is possibly related to your file access or files) I would start with a _clean_ test installation (put Kodi in a separate folder and use portable mode) and run stand alone using SQLite (not client servrer using MariaDB). Then I would add just that folder as a music source, initially say no to scanning into the library and just see if Kodi can access it and play the files from file view.

**Comment by bartmans** [comment]
I have found the mp3 causing the crash. Would that be of use to you? And can I upload it here? Removing this single mp3 solved the problem. 

Tomorrow will try from fresh install without the MySQL dbase in advancedsettings.xml with 17.6 and most recent nightly.

**Comment by pkerling** [comment]
Yes, the file would be very useful so we can see whether other OSes are also affected. You could.g. share it on some cloud hoster and remove the file when we have found the problem. Please be aware that we cannot take responsibility for any potential copyright issues.

**Comment by bartmans** [comment]
I put the file here: http://www.gufp.nl/kodi/Coca-Cola%20(Techno%20Remix).mp3

**Comment by DaveTBlake** [comment]
Thanks @bartmans you can remove that link now, I have grabbed the file for the team.

The issue is the tagging which is causing the version of Taglib used in Leia to read the tags to crash. It is Finding a UFID frame with junk in it. Kodi's use of Taglib needs to be more robust to avoid the crash, and Taglib needs to handle this file better too (I will raise it with them).

The solution for you is to clear the tags and retag this file. Mp3tag shows in only having two tags (album and title), but I suspect a bit by bit analysis of the header will show something else.

**Comment by bartmans** [comment]
I cleared the tags from the file and retagged it. Kodi doesn't crash anymore, so my direct problem is solved.
