### ISSUE TITLE
error: undefined reference to 'png_set_longjmp_fn'

### ISSUE THREAD

**Issue by wallon-ines** [xbmc/xbmc#15283]
### Describe the bug
Here is a clear and concise description of what the problem is:

Il have an error when try to install kodi 18.0rc5.2-Leia in fedora 26 

```
cd /usr/src/xbmc-18.0rc5.2-Leia/kodi-build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /usr/src/xbmc-18.0rc5.2-Leia /usr/src/xbmc-18.0rc5.2-Leia /usr/src/xbmc-18.0rc5.2-Leia/kodi-build /usr/src/xbmc-18.0rc5.2-Leia/kodi-build /usr/src/xbmc-18.0rc5.2-Leia/kodi-build/CMakeFiles/dvdnav.dir/DependInfo.cmake --color=
CMakeFiles/TexturePacker.dir/src/decoder/PNGDecoder.cpp.o:PNGDecoder.cpp:function PNGDecoder::LoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DecodedFrames&): error: undefined reference to 'png_set_longjmp_fn'
collect2: error: ld returned 1 exit status
```

```
rpm -qa | grep png
libpng-1.6.28-2.fc26.x86_64
libpng12-devel-1.2.57-1.fc26.x86_64
libpng12-1.2.57-1.fc26.x86_64
libpng-devel-1.6.28-2.fc26.x86_64
 ```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 26
 - Kodi version: 18.0rc5.2-Leia

**Comment by pkerling** [comment]
Hi,

please discuss build issues in the [forums](https://forum.kodi.tv/forumdisplay.php?fid=52) as long as you are not sure that there is a problem on the Kodi side.

PS: Fedora 26 is EOL since May 29, 2018, which means that is quite unlikely that someone will spend time investigating and fixing (i.e. you are on your own). You should upgrade to a recent release.
