### ISSUE TITLE
ISO Playback hangs on Shield TV playin ISO from SMB share

### ISSUE THREAD

**Issue by Grunthos** [xbmc/xbmc#15380]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since upgrading from 16,x to 18, no ISO on my local SMB share will play for more than 30 seconds. I hace uninstalled/resinstalled etc, same result. Screen freezes in DVD menu, UI interaction becomes  impossible. Can return to Shield Home scrren and kill Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ISO should play.  

## Actual Behavior

Freezes after 10-30 seconds. Interaction not possible.

## Possible Fix

Downgrade?

### To Reproduce

1. Add the SMB source, 
2. navigate to any DVD ISO, 
3. click on ISO 
4. Wait for hang.

### Debuglog
The debuglog can be found here:

https://paste.kodi.tv/uyogohenaj

### Your Environment
Used Operating system:

Android Shield TV, latest OS. Network with SMB servers.

Kodi version: 18.0

**Comment by Markman-B** [comment]
Same problem here with extracted ISO files (VIDEO_TS/AUDIO_TS)). All my dvd files can't be played. I started converting them to .mkv files.

**Comment by Frodonf** [comment]
Same problem for me too. I can't read DVD ISO since v18 official release.

Clean install, starting ISO file, the DVD menu appears with background video, but nothing is responding: can't select a different menu item and pressing Enter does nothing. After a few seconds, everything freezes and I have to force Kodi to quit from the Shield app menu. 

Log file here: https://paste.kodi.tv/duqopofuri

Everything is working fine on a clean install of RC 5.2 (kodi-18.0-Leia_rc5.2-arm64-v8a.apk).

**Comment by KarellenX** [comment]
Forum thread on this issue... https://forum.kodi.tv/showthread.php?tid=339983

**Comment by DaVukovic** [comment]
@Grunthos @Markman-B @Frodonf 

please take a look at: https://forum.kodi.tv/showthread.php?tid=339983&pid=2817051#pid2817051

and please report back if that also solves your problem.

**Comment by Frodonf** [comment]
> @Grunthos @Markman-B @Frodonf
> 
> please take a look at: https://forum.kodi.tv/showthread.php?tid=339983&pid=2817051#pid2817051
> 
> and please report back if that also solves your problem.

The problem is solved on my side with the 64bit version of that build.

Thanks!
