### ISSUE TITLE
Unable to add smb share

### ISSUE THREAD

**Issue by VictorHartman** [xbmc/xbmc#15412]
### Describe the bug
Here is a clear and concise description of what the problem is:
Whenever I try to add a SMB-share through the files section, I get 'connection refused'.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
I should get a windows to ask me for an username and password.

## Actual Behavior
The prompt asking me for an username and password does not show up. Instead I get a 'connection refused' message.

## Possible Fix
My username and password are never asked for, so that should happen.

### To Reproduce
1.  Go to files section
2. Add videos...
3. I entered the path of my share: smb://x.x.x.x:450/x/x
4. I get a 'connection refused' message.

### Debuglog
The debuglog can be found here:
http://paste.kodi.tv/ujiposubip

Line 480 says: ERROR: Control 18 in window 10129 has been asked to focus, but it can't. 
This sounds like my issue.

This debuglog is using Coreelec.  I first noticed this issue using libreelec. I tried using this fork, but the issue remains. I believe the issue does not depend on the distribution used. 

### Your Environment
Used Operating system:
 - [x] Linux (ARM, Odroid C2) 

Note: I'm using Libreelec 9.0 on Odroid C2. I went back to Libreelec 8.2.5. and everything worked fine.

 - Operating system version/name: Libreelec 9.0/Coreelec
 - Kodi version: 18.0

**Comment by DaVukovic** [comment]
CoreELEC have their own forums. So please visit their forum if you have problems with that OS.

Also you have to add the share via the "Add network location" section while setting up the sources. At his section and if you select "Windows network (SMB)" you are able to setup a username and a password. So this is generally more a forum question rather than a bug report.

So please head over to the CoreELEC forums: https://discourse.coreelec.org/
