### ISSUE TITLE
screensaver should be disabled while picture show

### ISSUE THREAD

**Issue by beta-tester** [xbmc/xbmc#15418]
### Describe the bug
Hello, i have LibreELEC (official) 9.0.0 (Kodi 18.0) installed on my Raspberry Pi 3.
in the system settings i have Screensaver "Dim" thats aktivates after 1 minute.
in the player settings i have for Picture show duration of 100 seconds.

when i play a picture, then the screensaver starts after 1 minute to dim the screen. but while playing a picture / a picture show, i don't want to see the screensaver get aktivated, because my intention is to watch the picture/pictures without the screensaver.

## Expected Behavior
no screensaver during playing a picture show.

## Actual Behavior
the screensaver aktivates and ruin the picture show.

## Possible Fix
disable screensaver for picture/picture show

### To Reproduce
1. setup screensaver to "Dim" and aktivation after "1m"
2. setup picture player to show eack picture "100s"
3. choose in the main media menu Picture, navigate to a folder, where the one picture is you want to show.
4. the picture is shown in fullscreen...
5. ... wait 1minute until...
6. ... the screensaver will dim the picture /picture show.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official) 9.0.0
 - Kodi version: 18.0

**Comment by DaVukovic** [comment]
IIRC you are out of luck for this. If I'm not mistaken there's no player active while showing pictures. Kodi simply shows them, then it's idling until the next picture is shown. While that time of idling, there's nothing active for Kodi and the screensaver will jump in. But I would like a dev to confirm that. 

For the time being, and if I'm correct with my assumption, I would recommend to set the screensaver to jump in after 2 minutes, which should solve the problem in your case. 

If my assumption is correct, then this is also more a feature request rather than a bug report and that should still be handled at our forums at the specific feature request subforum.

**Comment by beta-tester** [comment]
> For the time being, and if I'm correct with my assumption, I would recommend to set the screensaver to jump in after 2 minutes, which should solve the problem in your case.

but not, then you have one single picture to show.
for example, if you have a test image to adjust your TV/monitor and that may take longer than the 2 minutes screensaver delay...
it is annoying when you have to disable the screensaver for that.
even on a picture show, when you want to pause one picture to watch one picture longer...

thats the reason, why i hope it will be fixed (be added an option to disable screensaver for pictures) in the future.
