### ISSUE TITLE
KODI Leia V18 SMBv1 not working with legacy NAS - Apple Time Capsule SMBv1

### ISSUE THREAD

**Issue by pininy** [xbmc/xbmc#15502]
### Describe the bug
KODI Leia V18 SMBv1 not working with legacy NAS - Apple Time Capsule SMBv1

## Expected Behavior
KODI v17 no Time out on SMBv1 Apple Time Capsule - network file sharing.

## Actual Behavior
Clean install KODI Leia v18 - SMBv1 Time out on Network share, trying to add files. does not read. Keeps time out. install local Network browser - no issues.

## Possible Fix
I think need to look at the changes made between v17 and v18. No issue working with v17.
Tried forcing legacy security on SMBv1 didn't help.

### To Reproduce
Reinstalled KODI v18, re-add the Movie Network drive... half way time out need to restart KODI to reestablish connection.

### Debuglog
Logging captured - 

https://paste.kodi.tv/asahudizos

### Your Environment
Used Operating system:
 - [ X ] Android TV Box 7.1.2 - MeCool M8s Pro LB

 - Operating system version/name: 7.1.2
 - Kodi version: v 18

**Comment by chewitt** [comment]
TimeCapsules are from an era when Apple was using their own 'special' version of SMB in products and over time (as bugs have been fixed) things that follow SMB spec. correctly have lost the ability to speak to things that don't. It's not technically a bug in smbclient (the bug is in the TC) and we're not going to revert back to old versions of smbclient to support a declining population of old (insecure) Apple boxes. On that basis i'm going to close the ticket. 

However: On a normal Linux install it's possible to workaround the problem by mounting the remote SMB share to a local folder and then configuring Kodi to use the /local/folder as a source, e.g.

```
mount -t cifs //172.16.40.100/SHARE /storage/tcshare -o user=kodi,password=kodi,sec=ntlm,vers=1.0
```

Android is mostly Linux underneath, so something similar may be possible.

**Comment by pininy** [comment]
Hi,

Thanks for the reply Chris, okay I will try to alternative if it's possible
to mount the smb on the TV box.

Also would the <SMB Client> support legacy SMBv1 security? as I see that is
an option on the KODI leia v18?

best regards,
Thomas

**Comment by chewitt** [comment]
I was using a TimeCapsule as a NAS for a long time and beyond a certain release (which I forget) no combination of smbclient options will work, legacy or otherwise. Use the exact mount options shown above and kernel level mounts will work. NB: username/pass are required, but the username can be anything as the TC only allows a password to be set (an example of Apple not following SMB spec.)

**Comment by pininy** [comment]
hi chris,

thanks for the tips, i did managed to mount the TC using cifs, but not sure
why it's hidden from Kodi just can't see it.

maybe I need to chown or chmod.

anyway, thanks you have a great day!

best regards,
thomas

**Comment by AlexHFOkumura** [comment]
Hi, i solved my problem using my raspberry, since i have time capsule mounted on a folder using cifs, i simply instead of connecting directly to my TC, i connect to it through my raspberry smb, so it doesnt loose connection anymore, i hope you understand my english!
