### ISSUE TITLE
windows high cpu usage and many tcp to 127 when open allow remote control via UPnP

### ISSUE THREAD

**Issue by rufengsuixing** [xbmc/xbmc#15583]
### Describe the bug
high cpu usage when idle when open allow remote control via UPnP
so many tcp link from and to 127.0.0.1

## Expected Behavior
less than 4 percents of cpu usage when idle as my firefox browser does
not so many tcp link from and to 127.0.0.1

## Actual Behavior
always more than 40 % of usage when idle ,a lot of tcp socket from and to 127.0.0.1

## Possible Fix
fix 127.0.0.1 tcp connect to itseif

### To Reproduce
1. just open kodi  open allow remote control via UPnP and tasker to see the usage
2.netstat -nba
### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2894591/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![tianruo_2019-2-22-636864739641392488](https://user-images.githubusercontent.com/22387141/53251556-e6e37880-36f7-11e9-8a19-00defcf53d0e.png)
![tianruo_2019-2-22-636864738110520906](https://user-images.githubusercontent.com/22387141/53251559-e945d280-36f7-11e9-81e1-15fc0f61369f.png)

### Your Environment
Used Operating system:

  windows 1803 17134.619 
 cpu 6700hq gpu 970m

 - Operating system version/name:
 - Kodi 18.1

**Comment by rufengsuixing** [comment]
here is the netstat -nba result，there is so many 127 address between svchost.exe and kodi.exe
[network.txt](https://github.com/xbmc/xbmc/files/2896254/network.txt)

**Comment by DerDonut** [comment]
I had and issue which had the same symptoms from Kodi 18 RC4 to v18.0. After updating to v18.1 the problem was still there. After some time, the problem disappeared somehow - maybe because of an windows update?
Installing the same version in portable mode on a different machine (with nVidia graphics) never had the problem, so my guess was a graphic driver issue.
Because the issue is gone now, i cannot check if the UPnP setting was the source of the behavior.
Compare to my post in kodi forums: https://forum.kodi.tv/showthread.php?tid=339055

**Comment by DerDonut** [comment]
From Kodi v18 RC4 to v18.0 I observed the same behaviour. I posted this in the kodi Forums (https://forum.kodi.tv/showthread.php?tid=339055) and tested the behaviour in protable mode on different machines. Only on my system with Intel HD graphics this problem was present, so my guess was a graphic driver issue.
After updating to v18.1, the problem was still there. A few days later, after I did not checked regularly, the problem was gone. It is not entirely  clear why, maybe it was a windows update.
So now, I do not have the problem anymore and therefore cannot confirm if UPnP was the cause. It may be possible that in some versions a default setting was UPnP activated.
