### ISSUE TITLE
ID & PASSWORD are in plain text in the webdav HTTPS URL

### ISSUE THREAD

**Issue by prog-amateur** [xbmc/xbmc#15664]
Hello, I use Kodi Linux Flatpak version (18.1), because Debians Kodi version is still v17. 

The issues I meet is that : 
1. when I add a webdav (HTTPS) location, then edit the source and enter in the URL : the editable link contains ID & PASSWORD. 

2. Moreover, the webdav destination is not reachable in the flatpak version while it is reachable in Kodi 17 Debian (same setup).

Could you reproduce this issue as well ? What do you think ? Thank you

**Comment by DaVukovic** [comment]
> What do you think ?

That you should have followed our issue template ;)

Please provide a debuglog while trying to access the webdav location. 

If you don't know how to provide a log, read this: https://kodi.wiki/view/Log_file

Thanks in advance

**Comment by pkerling** [comment]
@prog-amateur Please make this two separate issues, do not delete the template but fill it out (twice), and most importantly for the first issue add screenshots :-) I know our issue submission process can be a bit frightening at first, but it is required so that we can somehow handle the volume of incoming requests. Thanks for following up on your prior comment.

**Comment by DaVukovic** [comment]
7 days passed, no response. Issue closed
