### ISSUE TITLE
After upgrade to HWE 18.04 OSD uses 1080p30

### ISSUE THREAD

**Issue by pmarkkula** [xbmc/xbmc#15670]
### Describe the bug
Here is a clear and concise description of what the problem is:
With Ubuntu HWE 18.04 Kodi chooses 1080p30 for OSD.

I recently upgraded my bionic system to HWE 18.04. After the upgrade Kodi OSD runs at 1080p30. Watching live tv changes mode correctly to 1080p50, but when it is stopped and Kodi goes back to OSD only, mode is set back to 1080p30. Before upgrade Kodi was using 1080p60 for OSD, which is also what my desktop is using. When Kodi is showing only OSD, I can change the display mode to 1080p60 in terminal with xrandr, but when Kodi changes from video back to OSD, it again chooses 1080p30.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

OSD should use 1080p60 display mode like it used to.

## Actual Behavior

OSD display mode is 1080p30.

### To Reproduce

1. Upgrade to HWE 18.04
2. Start Kodi.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/2927650/kodi.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.0.2 LTS
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Move ~/.kodi to somewhere else and check with clean profile, please.

**Comment by DaVukovic** [comment]
I would say, it's because you set the Kodi GUI to run at 30fps:

2019-03-04 19:39:26.252 T:140580493464512    INFO: GUI format 1920x1080, Display HDMI1: 1920x1080 @ 30.00Hz

What is available at: Settings -> System -> Display -> Resolution ?

For example, my PC monitor here is capable of doing 1920*1080 @ 60fps and 50fps. Nothing more. And I have "1920*1080p" listed twice at the section mentioned above. But the FPS for them isn't shown (might be another bug).  Currently Kodi is running for me at 60fps. If I change to the other "1920*1080p" setting, Kodi runs on 50fps. 

2019-03-04 19:28:06.669 T:140246945260480    INFO: GUI format 1920x1080, Display DVI-D-0: 1920x1080 @ 50.00Hz

So I would suggest you take a look at your Kodi settings as I'm using the same HWE stack as you on Ubuntu 18.04

**Comment by fritsch** [comment]
I wanted to make sure the IDs of the modes did not change, therefore I asked for the clean kodi. But yes, from the log one sees that the gui switches to 1080p30.

Btw. this is also not the HWE stack, but a custom 4.20 kernel from ubuntu mainline

**Comment by pmarkkula** [comment]
Renaming .kodi fixed the problem. Is there need for debug log when things work?

**Comment by fritsch** [comment]
No. We still think you made a wrong setting :-) Never the less. closed.

**Comment by pmarkkula** [comment]
In System/Display/Resolution (FH resos only):

NOK: 1080p 1080i, 1080p selected.
OK: 1080p 1080i, 1080p selected.

I don't understant how that could be wrong.

**Comment by pmarkkula** [comment]
@fritsch 

Found out what was causing this. This change to guisettings.xml fixed it:

```
-    <setting id="videoscreen.screenmode">0192001080030.00000pstd</setting>
+    <setting id="videoscreen.screenmode" default="true">DESKTOP</setting>
```

I have no idea how that value got there.

**Comment by pmarkkula** [comment]
@fritsch 

That screenmode got there, because after upgrade I first started Kodi wth 4k desktop and I chose 1080p resolution from System/Display/Resolution.
