### ISSUE TITLE
Support SSL_CERT_FILE for Linux?

### ISSUE THREAD

**Issue by mbakke** [xbmc/xbmc#15726]
### Describe the bug

I have the need to override the built-in certificate store from libcurl.  It would be great if SSL_CERT_FILE was supported on all platforms.

## Expected Behavior

Running `SSL_CERT_FILE=/etc/my-certificates.crt kodi` should let me browse my custom TLS site from my favourite media center.

## Actual Behavior

Attempts to use functionality that requires TLS (plugins, etc) fails.

## Possible Fix

Factorize SSL_CERT_FILE handling to be the same on all platforms.  Fall back to libcurl or bundled certificates if not set.

### To Reproduce

1. Build libcurl with `--with-ca-bundle=/dev/null`.
2. Build Kodi against this libcurl.
3.Try using TLS functionality.

### Debuglog

The debuglog can be found here:

```
2019-03-10 22:43:41.521 T:140567828752128   ERROR: CCurlFile::FillBuffer - Failed: SSL peer certificate or SSH remote key was not OK(60)
2019-03-10 22:43:41.521 T:140567828752128   ERROR: CCurlFile::Open failed with code 0 for https://mirrors.kodi.tv/addons/leia/plugin.video.youtube/plugin.video.youtube-6.4.0.zip:
2019-03-10 22:43:41.521 T:140567828752128   ERROR: Could not fetch addon location and hash from https://mirrors.kodi.tv/addons/leia/plugin.video.youtube/plugin.video.youtube-6.4.0.zip
2019-03-10 22:43:41.521 T:140567828752128   ERROR: CAddonInstallJob[plugin.video.youtube]: failed to resolve addon install source path
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: N/A
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Hi,

`SSL_CERT_FILE` handling is built into OpenSSL and not something we can change. As far as I am aware, it will only be used if your libcurl is built without *any* CA bundle or path setting. You can try by specifying `--without-ca-bundle --without-ca-path`. Otherwise, libcurl will always set that path and will not use OpenSSL defaults (which allows overriding via `SSL_CERT_FILE`). On typical Linux distributions, system libcurl always has a default CA path set, so this environment variable gets ignored. libcurl itself does not have a built-in mechanism for default path override via environment variables.

Now we could emulate support for this by setting the corresponding curl options (`CURLOPT_CAINFO`/`CURLOPT_CAPATH`). But this would not help for Python add-ons that make requests directly with `urllib` or similar. This also uses libcurl in the end but we cannot control any options there.

PS: Please discuss feature requests and such at the forums in the future :)

**Comment by Rechi** [comment]
Instead of generating a single complete CA certificates file, I would add the missing one into the system certificate store. That way it will work for all programs using the default cert store.

As you haven't posted your complete log (with debug logging enabled) and also haven't mentioned which OS and version you are using I can't give you any instructions how to do that.
