### ISSUE TITLE
V18 Listcontrol in a WindowXmlDialog will not focus if ListControl Id = 50

### ISSUE THREAD

**Issue by jmooremcc** [xbmc/xbmc#15749]
### Describe the bug
Here is a clear and concise description of what the problem is:

Like most beginners, I modified tutorial code that demonstrated how to create/use a list control in a WindowXmlDialog. That tutorial example set the id of the list control to 50. Under V18, I found out that you cannot set focus on the list control if the list control id is 50. Changing the id to a different value, such as 800, allows the list control to achieve focus.
I verified this by using Web-Pdb to debug my code. When the id=50, self.getFocusId() returns a value of zero. When I changed the id to 800, self.getFocusId() returned the correct value 800.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Assigning the list control an id = 50 should not prevent the control from achieving focus.

## Actual Behavior

Assigning the list control an id = 50 prevents the control from achieving focus.

## Possible Fix

The workaround I implemented was to change the id of the listcontrol to 800.

### To Reproduce

1. In your xml file, assign 50 as the listcontrol id.
2. Set 50 as the default control in the xml file
3. In your GUI onInit function, run self.setFocusId(50)

### Debuglog

The debuglog can be found here:

https://pastebin.com/embed_js/usCfnciw

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec V9.0.1 (Kernel: Linux 4.19.23)
 - Kodi version:
   V18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I couldn't reproduce this in Matrix although the issue description is too incomplete (no source code provided, no information about which script is run and from which window, etc).

`WindowXMLDialog` is a subclass of `Window`. Means that dialogs overlay over the previous window but are managed by the window manager (it is the same window that is being displayed with a few more controls added to it). If your windowdialogxml assigns id's to controls that were already defined by the skin window, you're effectively asking focus for the other control (invoking the base class) and not to the one you define in your dialog. You should avoid using id's such as 50, they are known to be used by skin viewtypes/list controls. In my scripts I use to assign ids > than 32500 for all controls defined in my windowdialogxml files to avoid clashes.

I don't think there's anything to fix here. This is by design.
