### ISSUE TITLE
The InfoLabel "Player.Filenameandpath" returns wrong values in kodi 18.1

### ISSUE THREAD

**Issue by emadmahdi** [xbmc/xbmc#15856]
Problem in Kodi 18 Leia v18.1 Android v7.1.1 release 20190311-a456bde2ef
.
.
The problem appear when using one of my skins "skin.metropolisEMAD18" installed on Kodi 18.1 ... while when using the same skin and the same skin xml files but installed on Kodi 17.6 the problem does not appear !!
.
.
On Kodi 18.1 ... The InfoLabel "Player.FileNameAndPath" returns wrong plugin url ... examples:
plugin://plugin.video.something/?mode=122&page=1
plugin://plugin.video.testing/?mode=2&page=3&name=any
.
.
On Kodi 17.6 ... The same InfoLabel returns the actual video url ... examples:
http://somewhere.com/somefolder/filename.mp4
https://website.com/somevideo/myfile.m3u8
.
.

**Comment by pkerling** [comment]
Likely DynPath fallout, does someone know whether this is/was intended? @notspiff ?

**Comment by emadmahdi** [comment]
i don't think it is intended ... i think it is wrong ... because we already have another InfoLabel "ListItem.FileNameAndPath" that suppose to return the plugin url

**Comment by emadmahdi** [comment]
With more investigations ... I found that the InfoLabel "ListItem.FileNameAndPath" is always empty while the InfoLabel "Player.FileNameAndPath" works only when playing videos using the function "xbmc.Player().play(url,play_item)" !!
.
But when playing videos using the function "xbmcplugin.setResolvedUrl(addon_handle, True, play_item)" then the same InfoLabel "Player.FileNameAndPath" gives the plugin url instead of the actual video url !!

**Comment by enen92** [comment]
@FernetMenta sorry to bother. Do you know why `Player.Filenameandpath` is available either in `PlayerGUIInfo.cpp` and `VideoGUIInfo.cpp`? 
This issue happens because when the list of providers is iterated, the `VideoGUIInfo` provider comes first and returns the value stored in the video infotag (`plugin://`). However what makes more sense is for  `PlayerGUIInfo` to return the value (since is already resolved to the DynPath and is the player that is "holding" the item).

I am a bit unsure what a proper fix could be. If storing the resolved url in the infotag and keep everything as it is or remove the "player link" to those infolabels here https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/guiinfo/VideoGUIInfo.cpp#L95-L105 (keeping in only available for ListItem).
You input, as always, is greatly appreciated.

**Comment by DaVukovic** [comment]
Is this still valid for kodi 18.6?

**Comment by DaVukovic** [comment]
No response since months. Closing this one
