### ISSUE TITLE
Scroll bar in any list view is inaccessible

### ISSUE THREAD

**Issue by quicktrick** [xbmc/xbmc#15887]
### Describe the bug
Here is a clear and concise description of what the problem is:

In any list view of Kodi 18.1 the scroll bar never gets focus while hovering on it.

There is no way to scroll the list with mouse/air-mouse using the scroll bar, because it never gets focus while hovering on it. I cannot click on the scroll bar, I cannot "take" and move the slider. If I try to click on the scroll bar, the adjacent movie starts instead of scrolling.
There was not such an issue with Kodi Krypton.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Scrolling the list when clicking on the scroll bar or moving the slider with mouse.

## Actual Behavior

If I click on the scroll bar, the adjacent movie starts instead of scrolling.

## Possible Fix

The scroll bar never gets focus while hovering on it. Fix that please.

### To Reproduce

1. Go to any list view of Kodi 18.1 Leia.
2. Hover on the scroll bar with the mouse and click on it -- the adjacent movie starts instead of scrolling.

### Debuglog

The debuglog can be found here:
https://pastebin.com/6myPa58F

### Screenshots 
Here are some links or screenshots to help explain the problem:

![capture](https://user-images.githubusercontent.com/18548503/55778883-cfe0c600-5aac-11e9-9d60-c16c111a2dd7.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC (official): 9.0.1, kernel: Linux x86 64-bit version 4.19.23
 - Kodi version: 18.1-Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
It shouldn't be able to move the scrollbar even if it's focused (using the keyboard) as that feature is not implemented yet. The same happens at the settings sections. You can't "click and move" a visible scrollbar at those sections as well. 

Naming it, it's more a feature request then a bug report for me. I'll leave it open as one of the core devs should decide if it's able to be done or not.

**Comment by quicktrick** [comment]
@DaVukovic , thanks for your reply!  As I mentioned above, Kodi Krypton had that feature of mouse scrolling with the scroll bar, and it worked flawlessly.  I hope, you implement it in Kodi Leia too, because it's very inconvenient to scroll the long lists without that feature.

**Comment by DaVukovic** [comment]
Confirmed. I installed Kodi 17.6 and it was indeed possible. Sorry that I missed that line where you mentioned Krypton.

**Comment by DaVukovic** [comment]
I looked at the difference between Kodi 17.6 and current master and there was a group added to "CommonScrollBars"

here: 
https://github.com/xbmc/xbmc/blob/4077a17fa001a19ddaf1ddbc60af3154b3240a88/addons/skin.estuary/xml/Includes.xml#L42-L46

and here: 
https://github.com/xbmc/xbmc/blob/4077a17fa001a19ddaf1ddbc60af3154b3240a88/addons/skin.estuary/xml/Includes.xml#L63-L68

Maybe @phil65 or @ronie can shed some light into it.

**Comment by Captain-Coder** [comment]
This bug is annoying me to no end. I have several very long lists and it's very annoying to have to slow scroll through them with the mouse wheel. I put some log statements in the OnMouseEvent and discovered that the hit rectangle on the vertical (only care about this one) scroll control is wrong.

In my situation it only spans (x: -30, y: 0) to (90, 100) on a full screen full height list. My screen is higher than 100px. If I place the mouse in this region the scrollbar actually works as intended. When switched to a WideList the scrollbar HitRect spans (-20, 0) to (60, 0), height 0 and it is effectively impossible to interact with the scrollbar.

In the file pointed to by @DaVukovic there is an explicit hit rectangle for the scrollbar(s) defined. Having spent only around 2h setting up the dev env and digging through the code I might be way off the mark, but I think either the HitRect is not getting parsed right, or the wrap up in a control group is causing the sizing to be off. Didn't have more time to investigate.

@quicktrick As a quick workaround it is possible to remove the troublesome <hitrect>. Open /usr/share/kodi/addons/skin.estuary/xml/Includes.xml (or adjust for your install location) and remove the <hitrect ... /> line of the vertical scrollbar. Restart kodi. It works on my machine :P Ok I should say functionally good, with only a few minor quirks.
