### ISSUE TITLE
Display off (no signal) after 10 minutes (screen mode as window)

### ISSUE THREAD

**Issue by fraort** [xbmc/xbmc#15959]
The display, in my case HDMI output is disconnected (display off, without signal) exactly at 10 minutes.

Description of the bug:
This bug only appears when I start "desktop session" of Kodi (Linux) and in Kodi the display is set in window mode instead if I select full screen the bug does not occur.

I have done the same test in Linux Mint 19, Cinamon desktop and in Ubuntu 18.04, Gnome desktop.

First: In Linux I have disabled the screen saver, suspend and hibernate and I have also disabled the standby of the hard disk. I have disabled these modes in the Linux GUI and for security also from terminal I have even disabled the DPMS with the following commands:

xset dpms 0 0 0
xset s reset
xset s off
xset -dpms

Restart the system. I enter with Linux session. All perfect Kodi. I select "full screen" display mode. I have disabled kodi to turn off the screen. Kodi only enters the protection mode (Dimmer) at the pre-established time, without problems everything OK.

Second: I now adjust in Kodi in screen mode as a window. Kodi appears in a window on the Linux desktop. All OK even if I "maximize" the window. The display does not turn off since in Linux I have DPMS all off (off).

IMPORTANT: Remember that I have left the screen mode in window mode (although I have left it maximized) and I have left Kodi and restarted the computer ...

Third: Now I go directly into "Kodi session" since Linux (Ubuntu and Linux Mint) create a user for this purpose which consumes less memory resources, CPU and makes Kodi work much more fluid minimizing problems of "buffering"

Kodi seems to work correctly until exactly 10 minutes! (as long as no mouse or keyboard activity has been detected) the display turns off (Off, no signal)

I have tried playing Youtube content or a video in straming or stored on local disk. No matter what I'm visualizing, at exactly 10 minutes the display goes off, with no signal.

Finally, I re-adjust the screen mode in full screen in Kodi. Restart I re-enter "Kodi session" and the screen does not turn off Kodi works perfectly as in the first point.

I have reproduced this fault several times and in different computers and it is always true that every time the screen mode is set to window mode (even if it is maximized) and whenever I open "Kodi session" the error always appears, at 10 minutes the screen goes off (off).

In contrast the screen mode to full screen there is no problem and it does not matter if I log in user Kodi or user session Linux desktop.

Environment:
HDMI display connection.
Linux (Mint 19 and Ubuntu 18.4)
Kodi 17

**Comment by fritsch** [comment]
```
xset dpms 0 0 0
xset s reset
xset s off
xset -dpms
```

Those are not permanent and vanish right away when you restart.

**Comment by fraort** [comment]
OKAY. Actually the command "xset" I used to check that the settings made from the control panel of Linux (see answer d xset q) were correct.

DPMS (Energy Star):
   Standby: 0 Suspend: 0 Off: 0
   DPMS is Enabled
   Monitor is On

Where the only thing that I have observed is that DPMS continues activated.
Maybe DPMS "turns off the screen" at 10 minutes? And if so, why exactly at 10 minutes?

**Comment by ObiDriftKenobi** [comment]
Sorry for bumping this issue, but I'd like to add a solution (or a workaround more like) for people who will experience this in the future. Tested this myself, and it works.

**1) Make a bash (.sh) file anywhere you want, preferably in your home directory. In this file, write:**
`xset dpms 0 0 0`
`xset s reset`
`xset s off`
`xset -dpms`
(which are the commands mentioned earlier in this post.) Remember the path to this file!
**2) Navigate to your userdata folder (You'll probably have it in /home/username/.kodi/userdata/). Make a file called "autoexec.py". In this file, write:**
`import os`
`os.system("bash /path/to/your/bash/")`
Replace /path/to/your/bash/ with your actual path. Mine is: /home/obidriftkenobi/fixmykodi.sh
**3) Start Kodi as you normally would. The problem this issue is about should be gone.**

There's probably a more elegant and "linux-y" way to do this, but this works well too and is easy to do.

**Comment by DaVukovic** [comment]
```
Environment:
HDMI display connection.
Linux (Mint 19 and Ubuntu 18.4)
Kodi 17
```
Try Kodi 18 and open a new issue if it still exists
