### ISSUE TITLE
Estuary - [Addon Youtube] - Settings "API" is not reachable by the mouse

### ISSUE THREAD

**Issue by wwark** [xbmc/xbmc#16059]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Kodi 18.2, with the skin Estuary, the settings API of youtube add-on is not reachable by the mouse.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

All settings of addons accessible by the mouse.

## Actual Behavior

settings API of youtube add-on is not reachable by the mouse.

### To Reproduce

1. Open Kodi 18.2 with Estuary skin and youtube add-on installed
2. Open settings of Youtube add-on
3. Try to reach API settting with the mouse

### Debuglog

The debuglog can be found here:
Log doesn't show anything

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot from 2019-05-04 10-12-09](https://user-images.githubusercontent.com/469461/57176204-2d222a00-6e55-11e9-9252-919bc2918189.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
The log would have been helpful in that case, hence we said it's always mandatory. 

That would have shown, that you are obviously NOT using Estouchy, because the setting section for the Youtube add-on looks like this if you use Estouchy:

![grafik](https://user-images.githubusercontent.com/7235787/57176290-9d7d7b00-6e56-11e9-893a-055e5af2742b.png)

So, the screenshot you provided above is Estuary in that case: 

![grafik](https://user-images.githubusercontent.com/7235787/57176304-cbfb5600-6e56-11e9-9ef5-7b32176f7fe2.png)

And I can reach any part of that setting section. Simply scroll down using the mouse wheel to reach the bottom parts.

**Comment by wwark** [comment]
Sorry I was wrong I want to say Estuary and not estouchy.
I managed to acces API settings with the mouse wheel and click on "API" with the mouse. So can you confirm it is the correct behavior ?
It seems weird we cannot click with the mouse something shown on the screen.

You can find the log below.
[kodi.log](https://github.com/xbmc/xbmc/files/3144214/kodi.log)

Thank you.

**Comment by DaVukovic** [comment]
Yes, I agree and I can confirm that not everything which is visible is also able to be selected. 

Maybe @ronie will have a look.

**Comment by ronie** [comment]
https://github.com/xbmc/xbmc/pull/16067

**Comment by wwark** [comment]
Thank you @DaVukovic and @ronie !!!
