### ISSUE TITLE
Unable to view/search/browse new SMB (Samba) shares from Kodi

### ISSUE THREAD

**Issue by iz8mbw** [xbmc/xbmc#16107]
## Bug report
With Kodi 19 is not possible to view/search new SMB (Samba) shares.
**This happens also with most recent nightly of Kodi 18.**

### Describe the bug
Unable to view/search new SMB (Samba) shares from Kodi.
Also if it's impossible to view/search new SMB (Samba) shares from Kodi, Kodi can anyway access to my Windows shares (SMB) located on my NAS because the path is specified on the Kodi file "sources.xml".
In others word Kodi is able to access on Windows shares (SMB) thanks to "sources.xml" but it's not more able to view/search new SMB (Samba) shares...

## Expected Behavior
I expect, as in the past, to be able to view/search new SMB (Samba) shares available in my LAN.

### To Reproduce

1. Open Kodi
2. Go to Video
3. Select File
4. Select "Add Video"
5. Select "Browse"
6. Select "Windows share (SMB)"

Now you see the list is blank and is not possible to add/view/browse shares available on my LAN (in my case I have multiple IP serving shares and multiple shares per IP).

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/anehadezas.kodi

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Android 8 (Nvidia Shield)
 - Kodi version:
19.0-ALPHA1 Git:20190507-46b6abdf86

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
That's most likely the problem, that your share might be a SMB2 share and browsing for SMB shares was a SMB1 feature which is generally disabled on Windows 10 machines. Most likely your NAS is also set to SMB2 now and you should probably use the "Add network location" option for adding sources instead of the "Windows (SMB)" option. 

After the "Add Network Location" option you get another window where you are able to specify the protocol you want to use (SMB in that case) enter the IP, Username, Password, path to the share etc..... 

Could you please confirm that this option works for you?

Even if you NAS is set to SMB1 and your Android device is set to SMB2 (not too sure about that), your Android device won't see the NAS. That means, that you have enabled SMB1 on your Windows machine and your NAS is also set up to use SMB1, that you are for sure able to see the share on the Windows side. Generally we do not recommend to enable SMB1 as that is known vulnerable.

**Comment by iz8mbw** [comment]
Sorry but my NAS's Samba version is not changed and my QNAP NAS is serving SMBv2:
```
[~] # smb2status

smbd (samba daemon) Version 4.4.16
smbd (samba daemon) is running.
max protocol SMB 2.1 enabled.
```


With older Kodi 18 nightly version I was able to browse.
I can confirm that also with "Add network location" and then "Browser" the list is blank.

**Comment by iz8mbw** [comment]
And my Nvidia Shield (Android 8) is able to mount the shares on my NAS.

**Comment by iz8mbw** [comment]
I have also tried to enable SMB 3 on my NAS:
```
[~] # smb3enable
Shutting down SMB services: smbd smbd-notifyd cleanupd nmbd.
Shutting down winbindd services: winbindd.
max protocol SMB 3 ... enabled.
locks path was set to /share/HDA_DATA/.locks
Shutting down winbindd services: winbindd.
Starting winbindd services:Starting SMB services:.

smbd (samba daemon) Version 4.4.16
smbd (samba daemon) is running.
max protocol SMB 3 enabled.
[~] # smb2status

smbd (samba daemon) Version 4.4.16
smbd (samba daemon) is running.
max protocol SMB 3 enabled.
[~] #
```

But still not able to to view/search/browse new SMB (Samba) shares from Kodi.
But Kodi is still able to access on my movies thanks to "sources.xml", Nvidia Shield is still able to access directly to my NAS.

**Comment by DaVukovic** [comment]
> Add network location" and then "Browser" the list is blank.

As expected. As said, browsing for shares is a SMB1 feature and doesn't work for SMB2. 

If it works on the Windows side then this means your Windows is using SMB1 which is not recommended at all anymore. 

I would suggest you seek assistance on the forums. As I highly guess we are not talking about a Kodi bug. Currently we are talking about support and support is given at the forums.

If you already have opened a forum thread for this, then please link me to.

**Comment by iz8mbw** [comment]
So, since my Windows PC serve SMBv2 (I configured it in the past) and my NAS is serving SMBv2 and SMBv3 you are saying that it's normal that Kodi cannot view/search/browse for SMBv2/v3?

**Comment by iz8mbw** [comment]
>As I highly guess we are not talking about a Kodi bug. Currently we are talking about support and support is given at the forums.
In my opinion it's a bug because with Kodi 18.1 I was able to browse....

**Comment by iz8mbw** [comment]
> So, since my Windows PC serve SMBv2 (I configured it in the past) and my NAS is serving SMBv2 and SMBv3 you are saying that it's normal that Kodi cannot view/search/browse for SMBv2/v3?

**Comment by chewitt** [comment]
Kodi needs to add support for the newer and completely different Windows host/share discovery process. Until then the legacy discovery process continues to work correctly (as coded) but your network no longer matches the requirements (shares must be downgraded to SMB1 which is a bad idea). This is a bug tracker not a feature-request list and there is no bug so i'm closing the ticket. Please take further discussion and opinion to the forum. Thanks.

**Comment by iz8mbw** [comment]
@chewitt thank you!
I hope Kodi will be upgraded to support host/share discovery for SMBv2 and SMBv3 soon!
Thanks!!

**Comment by Vikimaus** [comment]
Reason: (FTP://forever:)

**Comment by Vikimaus** [comment]
So I found in another forum reason.
in KODI go to STETTING/SERVIS/SMB set to min. SMB1 - max SMB3
Restart KODI and Router
Finish

**Comment by iz8mbw** [comment]
But if your SMB Server (example the PC where with Kodi wants to access) do not have SMB version 1 enabled you anyway cannot browse.
So this is useful.

**Comment by chewitt** [comment]
> in KODI go to STETTING/SERVIS/SMB set to min. SMB1 - max SMB3

If you set min SMBv1 and max SMBv3, the Kodi smbclient will default to (the Samba default) SMBv2 because v1 is considered bad and should not be used. As a result you will never successfully connect to a v1 share. The only way to force SMBv1 use is to set min/max to SMBv1, else leave min/max unset and it will use SMBv2/v3 - the server end will negotiate SMBv3 use if the server supports it even if you initially connect at SMBv2, but it cannot negotiate down (as SMBv1 servers will not understand the SMBv2 connection).

**Comment by rafi-d** [comment]
IMHO, this should have been fixed long ago already. People are still failing to access Windows SMB2 shared drives :( :( 
https://forum.kodi.tv/showthread.php?tid=360606&pid=3054463#pid3054463
