### ISSUE TITLE
no sync pc to tv

### ISSUE THREAD

**Issue by hagi1422** [xbmc/xbmc#16574]
cant see login page on tv that I put on my pc to sync

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@hagi1422 

This is not a support forum or help desk. 

Please use the kodi forum for assistance. Once somebody understands what you are trying to report, and if it turns out to be a Bug in Kodi, then you can open a new Issue. 

This issue will be closed due to a severe lack of information and your single sentence sounds like a support request.
