### ISSUE TITLE
[Android] [security] surely passwords stored in plain text are a bad idea...

### ISSUE THREAD

**Issue by unic0rn** [xbmc/xbmc#16659]
### Describe the bug
...especially when they're accessible to every android app with storage access permission. right?

and surely someone has a very good reason why it's done in such an insecure way, right?

folks, there's internal storage for a reason. i know, userdata, portability and so on - but this whole folder just cannot be accessible to other apps. some addon users are storing youtube api keys there.

that's NOT how this should work under android. security-wise, it's a disaster.

## Expected Behavior
sensible data should NOT be accessible to other apps, regardless of their permissions.

## Actual Behavior
every app with storage permission can access sensitive data like passwords.

## Possible Fix
use internal storage for userdata folder.

### To Reproduce
no steps required.

### Debuglog
none.

### Screenshots 
non applicable.

### Your Environment
Used Operating system:
 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 7.0
 - Kodi version: latest stable

**Comment by unic0rn** [comment]
i guess noone cares and we're just waiting until bot closes this, right?

**Comment by user8446** [comment]
I would agree this is a security and privacy issue.
Can a team member please remove the ignored rules label as there is sufficient information and wouldn't apply beyond what @unic0rn already posted

**Comment by unic0rn** [comment]
as a follow up, i think the easiest solution would be to generate some encryption key and store it in internal storage, then encrypt all configs - including those from the addons - with it. that way userdata in its entirety would stay where it is, with the only drawback being that moving it to another device would require decrypting it first (built in export with decryption - decrypt and pack into zip?).

alternative solution would be a bit messy (splitting userdata into sensitive data and not sensitive - possibly everything but thumbnails going into internal storage, including addon configs, with a fallback that if an addon stores too much data there, it gets moved to regular storage as a result, and reading the data would try reading from internal storage, then regular storage if it's missing in internal). overall a mess, and doesn't make exporting the data any easier, so i guess encryption is the way to go as far as portability is concerned.

as for the rationale, it's obvious that installing any app on an OS like windows or linux gives such app a lot of access to local data - it can be mitigated by using different (app-specific) user accounts and filesystem permissions, but in general that's not what people do. if they install the app, they trust the app.

android is different, everything is sandboxed by default, and storage permission is there for a reason, but internal storage is also there for a reason. people expect apps given storage permission to have access to their external storage - photos, videos, music, other data - that may be sensitive, but they're aware of it. they know what they're sharing with those apps.

what they don't know is that an app like kodi may store its configs, including sensitive data like passwords to network shares or youtube api keys in case of specific addon, in that external storage, because apps are expected to store their sensitive data in internal storage instead, where no other app - nor the user, unless having root - can access it.

the way it works currently, considering how multiplatform kodi is, and considering portability issues, may look sensible, but from android user perspective it makes no sense at all.

i apologize for sounding a bit harsh at the beginning, but when i've discovered this issue, i was caught off guard by how blatant disregard to security this is. again, different platforms have different security measures and user expectations are also different, depending on which platform they're using at the moment. ignoring those expectations is just wrong.

**Comment by thezoggy** [comment]
or use a db for plugin data (which would allow you to store sensitive info and make kodi a bit more portable) ?

**Comment by yol** [comment]
Hey,

thanks for the report and you are absolutely right that the way it is done now does not fit very well for the way Android works.

> or use a db for plugin data (which would allow you to store sensitive info and make kodi a bit more portable) ?

Whether you store data in a database file or an XML file is a technicality and unrelated to this problem

> as a follow up, i think the easiest solution would be to generate some encryption key and store it in internal storage, then encrypt all configs - including those from the addons - with it. that way userdata in its entirety would stay where it is, with the only drawback being that moving it to another device would require decrypting it first (built in export with decryption - decrypt and pack into zip?).

This does not sound very simple. You would also have to do an importer that reencrypts it on a new device, for example. But it does solve the problem of course.

> alternative solution would be a bit messy (splitting userdata into sensitive data and not sensitive - possibly everything but thumbnails going into internal storage, including addon configs, with a fallback that if an addon stores too much data there, it gets moved to regular storage as a result, and reading the data would try reading from internal storage, then regular storage if it's missing in internal). overall a mess, and doesn't make exporting the data any easier, so i guess encryption is the way to go as far as portability is concerned.

Well, minus the moving the data to regular storage if it's too big (which does not make sense from a security POV), it is a comparatively tangible solution.

Downside of both of these solutions is that users have no easy way to access their profile data any more. You can't just edit your `advancedsettings.xml` (or any other settings file), either because it is encrypted or because it is completely on internal storage in the first place. I don't use Kodi on Android personally, but I think that would be pretty annoying.

Another alternative is to have an *explicit* way for core and add-ons to store sensitive data such as passwords or API keys and only put exactly that into private data. I think that would be the cleanest solution. And I also think it would be fine to have to reenter logins if you decide to copy your profile to anothre device (i.e., we could get around building an importer/exporter). Of course it also might be the most work.

As you have probably noticed, valid as your concern may be, no Android dev (we don't have many to start with) seems to be interested in working on this at the present time :-( If I may give you a hint, issues that come with a pull request are most likely to get fixed ;-)

**Comment by yol** [comment]
I'll add the corresponding tags if someone can confirm this is also an issue on iOS, tvOS or UWP

**Comment by kambala-decapitator** [comment]
on non-jailbroken iOS and tvOS devices apps are sandboxed, so an app can't access files beyond its sandbox. Still, there's system Keychain (on macOS as well) exactly for storing sensitive data like passwords.

**Comment by malard** [comment]
I'm closing this ticket, mainly because this is a conceptual change across the board for Kodi, there are so many places that this touches and so this isn't really a bug. That said, should someone ever decide to overhaul the entire security platform of Kodi then they can create the relevant pull request. 

In my personal view, the security of the type of content that Kodi needs or wishes to access to provide its features should not require any elevated permissions, therefore if you are using an administrator or admin like account to access media then in the first instance should be changing the permission level there. To trust a platform such as Kodi with privileged credentials is a bad idea anyway.
