### ISSUE TITLE
19 crashes on tidal app

### ISSUE THREAD

**Issue by Tecko71** [xbmc/xbmc#16726]
Kodi crashes on tidal Kodi 19 nightly build (06-10)

When I playing a song in Tidal kodi is crashing. Hope this is the right please to reported. TIdal2 should be the standerd because it have mqa option. 

here the log: 
[kodi (1).log](https://github.com/xbmc/xbmc/files/3694403/kodi.1.log)

**Comment by DaVukovic** [comment]
Beside the fact, that you are already using tidal2 (in case that tidal2 comment was some kind of request), please be aware that this seems to be a beta version: 

2019-10-06 15:06:02.133 T:11994  NOTICE: CAddonMgr::FindAddons: plugin.audio.tidal2 v2.0.0-beta19 installed

I also don't see anything interesting in that log because you missed to enable debug logging. The only thing I see is: 

`2019-10-06 15:06:51.552 T:12062   ERROR: [TIDAL2] tidalapi: Username or password is wrong`

If that causes Kodi to crash, then you should probably consider to report that at the add-on dev. Regarding the add-on dev....it seems you downloaded the tidal2 plugin from here: 

https://github.com/arnesongit/plugin.audio.tidal2

At least he's the one providing that add-on in that version. So that's probably the best place to report as it's nothing which is officially provided by us.

**Comment by Tecko71** [comment]
I enabled debugging maybe you can find something. I will report anything else on tidal2. By the way I can not enable debugging at the tidal settings.
[kodi (2).log](https://github.com/xbmc/xbmc/files/3695949/kodi.2.log)

**Comment by a1rwulf** [comment]
Can you please try to enable the `inputstream.rtmp` addon?
I found that TIDAL addons don't work for me, when I do not use it.

**Comment by Tecko71** [comment]
I can not change any settings in kodi 19. They are not there or visible. In tidal2 it is even worse.

**Comment by a1rwulf** [comment]
It's not in the TIDAL settings, it is a separate addon.

**Comment by Tecko71** [comment]
failed to install inputstream

**Comment by Tecko71** [comment]
found it , it works now ...thx
