### ISSUE TITLE
Watched flag and sometimes thumnail disappears when step back to previous page or after watch a video.

### ISSUE THREAD

**Issue by DjDiabolik** [xbmc/xbmc#16999]
### Describe the bug
I obtain this little trouble whit latest youtube addons..... descripted the issue below.

## Expected Behavior
N/A

## Actual Behavior
N/A

## Possible Fix
N/A

### To Reproduce
1. Download and install last version (currently 6.5.2) youtube addons
2. Enter to one section.... for example "My Subscription" or "History"
3. You can see the video list. The alreay watched video it's correctly flagged out and you can also see all thumnail
4. Scroll down and open the "Page 2". Video List appears and also here all video watched it's flagged etc etc.
5. Return to previous page using the ".." or using the "Back" button on remote
6. List of video "Page 1" it's be reappears on screen but now all watched video it's not anymore flagged. All checkmarks it's be disappears. If you use Estuary skin only the checkmarks disappears. In my case i have also tryed whit "Estuary Mod V2" and here also the thumnail of all video disappears. Need a refresh video list to reobtain all correctly.

### Debuglog
The debuglog can be found here: ---
Removed for moment....

### Screenshots 
I need to do some photo to my tv if need..... let me ask.

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC
 - Kodi version: latest 18.5

**Comment by DaVukovic** [comment]
The problem here is more, that there are banned add-ons installed. Please remove those and provide a new log. 

Thanks in advance.

**Comment by nkestrel** [comment]
**STR:**
1. Install Reddit Viewer addon in a clean Kodi 18.5 installation on Windows 10.
2. Open Reddit Viewer and go to the "videos" list.
3. Play several short videos until completion (or skip ahead).
4. Play a video and stop it before reaching the end so that it returns to the cached list.

**Expected:**

Video list items have a tick mark indicating they have been watched.

**Actual:**

None of the list items have a watched tick.

The problem occurs only when navigating back to a cached list, when a list is reloaded the watched flags display correctly.

Last good: [KodiSetup-20191102-e398fc1a-Leia-x64.exe](http://mirrors.kodi.tv/nightlies/windows/win64/Leia/KodiSetup-20191102-e398fc1a-Leia-x64.exe)
First bad: [KodiSetup-20191104-52c5ddc8-Leia-x64.exe](http://mirrors.kodi.tv/nightlies/windows/win64/Leia/KodiSetup-20191104-52c5ddc8-Leia-x64.exe)

Regressed by #16806.

**Comment by DjDiabolik** [comment]
@DaVukovic i can try to disable/unistall the banned repo/addons following the official wiki:
https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

I don't think this is the cause but.............

**Comment by DaVukovic** [comment]
There's still no log provided. If @DaveTBlake wants to have a look and wants to jump in, he might reopen this issue again. I'm going to close that for now.

**Comment by nkestrel** [comment]
I have provided concise STR and identified the regressing issue, this should be more than enough for the bug to be actionable.

**Comment by arnova** [comment]
> I have provided concise STR and identified the regressing issue, this should be more than enough for the bug to be actionable.

No it's not, rules apply to everyone including you. If you refuse to provide something simple as a debug log, I'm pretty sure that won't help your cause.

**Comment by DaveTBlake** [comment]
> 1. Install Reddit Viewer addon...

As soon as something needs addons installed to reproduce I'm not inclined to pick it up. I would say ask the addon author as first point of call

**Comment by nkestrel** [comment]
reddit is just an example addon, this happens with all video list addons, including youtube as was originally reported.

**Comment by DjDiabolik** [comment]
OMG... I had totally forgotten about the matter ..... after the holidays I will try to do something.
