### ISSUE TITLE
Identifying Python 3 compatible addons

### ISSUE THREAD

**Issue by ronie** [xbmc/xbmc#17326]
**Problem:** Addon developers have been submitting py2/py3 compatible addons to the Leia (and lower) repos.
We currently have no way of checking if an addon in those repos is python 3 compatible.

**Solution 1:**
Add a new attribute to the addon.xml file which indicates py2/py3 compatibility
The suggested format was:
`<import addon="xbmc.python" version="2.1.0" target="3.0.0"/>`

this requires:
- someone who can write the core code for this new attribute
- someone who can update our repo generator script to process this attribute
- addon devs to re-submit their addon to the repo, with this new attribute in their addon.xml file

**Solution 2:**
Only allow addons with a xbmc.python version of 3.0.0

this requires:
- a 1 line change in core: https://github.com/xbmc/xbmc/pull/17188
- a 1 line change in the repo generator config: https://github.com/xbmc/repo-scripts/pull/1286
- addon devs to re-submit their addon to the Matrix repo, with xbmc.python set to 3.0.0

**Comment by gusandrianos** [comment]
I think solution 2 is better because it can be implemented faster and will solidify the transition to Py3. Solution 1 is too complex.

**Comment by CastagnaIT** [comment]
I do not agree with solution 2

in this way you oblige all developers to create two projects/release of every addon for different versions of Kodi... it's already enough to manage a release, so don't make it even heavier!

for all the addons who can't release into the official repository, will create more confusion for end users who also have to figure out which version of the addon to choose, in addition to a possible complex installation (eg netflix on rasperry system)...

I think that add the new "target" tag only for Matrix build is the best solution,
it is managed only on Matrix and it is not mandatory for the devs to send the xml changes immediately
and the addons can remain retrocompatible

I also propose that the "target" tag is not mandatory
so, when it is not present it means that "version" is equal to the missing "target" value
in this way in the future it can be used as always.

**Comment by gusandrianos** [comment]
@CastagnalT Say we implement solution 1, if we don't make the target variable required, what do we assume the add-on is targeted for? 

If we assume python 2 by default, we'll have the majority of add-ons covered but we can't do that because python 2 is dead. If we assume python 3, all the add-ons who aren't updated for 3 won't work. 

My point is, if we add the target variable, there's almost certainly a need to update and resubmit add-ons. Furthermore, it'll probably push back the release of matrix, given the complexity.

It's hard to maintain two add-ons but progress comes at a cost. Users will eventually move to matrix.

**Comment by CastagnaIT** [comment]
i think I explained myself wrong, this is my idea:

in my opinion the problem is that the version check here is not very well, "version" tag do not means a specific version, but it means a minimum version that is required, and does not provide any verification checks, and it may be fine, but not for all cases

it would be a good idea to start changing things,
can be an idea implementing a first version check mode like nuget package versioning: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning
open the link and go down until `allowedVersions` tag examples

by introducing the tag `allowedVersions` you can have more control over which versions to install and how to manage a dependecy version,
every developer will have the opportunity to better manage the dependencies as Kodi evolves, so nothing is ever left broken

This require a minimum of support logic for the controlling characters `()[],` 
you don't need to implement them all, three cases are enough

Then:
This old format, will use the same behaviour of Kodi 18, nothing changed:
`<import addon="xbmc.python" version="2.1.0"/>`
of course, the addons that specify version 2.1.0 and do not have "allowed-versions" tag will not compatible, read below.

Addons compatible with both Kodi18/19 (py3 migration) have to add the new "allowed-versions" tag:

This means: compatible from 2.1.0 to 3.1.0
`<import addon="xbmc.python" version="2.1.0" allowed-versions="(,3.1.1)"/>`

This means: compatible only with 3.0.0
`<import addon="xbmc.python" version="3.0.0" allowed-versions="[3.0.0]"/>`

This means: compatible with 3.0.0 and all higher versions
`<import addon="xbmc.python" version="3.0.0"/>` old format
`<import addon="xbmc.python" version="3.0.0" allowed-versions="3.0.0"/>` new format

in this way addons can have also backward compatibility with Kodi18,
and with Kodi 19 and future evolutions more possibilities to better manage version compatiblity,
could be used in the future for other evolutions

this is what i think is right

**Comment by fuzzard** [comment]
I'll be blunt, what you propose still needs someone to implement it. Core issue is someone stepping up to do option 1 in a timely manner, ie weeks not months.

As ronie stated, option 2 is a one line change, without someone doing option 1 (or any alternative like it), option 2 becomes the defacto due to time/effort requirements

**Comment by gusandrianos** [comment]
What he proposes sounds ok to me but unless someone starts implementing and testing it ASAP, I don't see how it is an option. What @ronie suggested is a quick way of fixing things (by breaking lots of addons unfortunately). 

One suggestion I'd like to make is, if we decide what @CastagnaIT proposes is viable to implement, it can be done eventually to introduce backwards compatibility with what hasn't been updated but I'm worried it might make little difference since a large amount of add-ons might be updated by then and we'll require yet another update.

**Comment by ronie** [comment]
just for the record, option 2 is not a 'quick fix' ;-)
it is how our addon repo is designed to work.
we do exactly the same thing for skins on every release.

**Comment by CastagnaIT** [comment]
can you post a link of some files involved in these possible changes?

**Comment by ronie** [comment]
ok, option 2 is what it is going to be.

i will:
- make a post on the forum asking addon devs to re-submit their addon to the matrix branch
- update a large number of script.module.* addons and submit them to the matrix branch
- merge https://github.com/xbmc/xbmc/pull/17188 and https://github.com/xbmc/repo-scripts/pull/1286 in a few weeks

**Comment by lorkadiscovery** [comment]
@ronie 

https://forum.kodi.tv/showthread.php?tid=220547&pid=2925271#pid2925271

Looks like the change to script.module.trakt messed up with a typo.

It will not update on Matrix as <import addon="script.module.six" version="1.174.0"/> doesnt exist. The latest version is 1.14.0 not 1.174.0

https://mirrors.kodi.tv/addons/matrix/script.module.six/

**Comment by ronie** [comment]
thanx for the heads-up!

updated version is on it's way to the addon repo:
https://github.com/xbmc/repo-scripts/commit/8f8143aed4630643992fa242b9f3629ee3e40e84

**Comment by lorkadiscovery** [comment]
@ronie Is it worth maybe keeping this open for people to report module issues?

For example I have just updated nightly and have a dialog telling me ElementTree, SimpleCache and Embuary Info are all now disabled as they are not compatible.

They all work fine in PY3 I just assume they are not now set to use xbmc.python 3.0.0

Even version check is now saying its not compatible.

**Comment by ronie** [comment]
for third party addons, please use support thread of the on the forum.
as that's not something we can fix for you :-)

Elementree -> is included in python itself, there's no need anymore for a script.module
SimpleCache -> community addon, please use the forum
Embuary Info -> PR pending https://github.com/xbmc/repo-scripts/pull/1307
Version Check -> PR pending https://github.com/xbmc/repo-scripts/pull/1320

**Comment by mediaminister** [comment]
**Solution 1** is not a solution, this adds unacceptable complexity to the workflow of add-on developers!
Every single add-on developer now has to submit twice and maintain two separate branches to preserve compatibility with Kodi 18 and Kodi 19.

The only legit solution is a single `addon.xml` that is both compatible with Kodi 18 (and older) and Kodi 19!

**Comment by lrusak** [comment]
> The only legit solution is a single `addon.xml` that is both compatible with Kodi 18 (and older) and Kodi 19!

Feel free to implement it then 😸 No one on the Kodi team wanted to implement option 1 so option 2 became the default. Once Kodi 19 is released then you only have to maintain one add-on version again 👍

**Comment by mediaminister** [comment]
How many time is left to implement this before the Kodi 19 release?
Almost 25% of our add-on users are still using Kodi Krypton, so do we have to dump these users once Kodi 19 gets released?

**Comment by fuzzard** [comment]
No, just have 2 branches. One for <=18 and one for 19+

**Comment by mediaminister** [comment]
Ridiculous, 2 branches, 2 releases and 2 submissions just because one number in an xml file has to change.
I rather release for <=18  only then.

**Comment by fuzzard** [comment]
That's your prerogative as the add-on Dev then i guess.
As has been said before, If no one steps up to implement the code of your preferred method, how can that progress? There needed to be a distinction between py2 and py3 add-ons in repos.

**Comment by knaerzche** [comment]
I'm personally not having any prob with this decission, but I think it should be thinked over anyways - i guess there will be a lot addon-devs sharing the oppinion with @mediaminister. There will be lot  working, unmaintained py2 only addons which will fall appart with the move to matrix anyways - with this decission there will be devs unwilling to maintain 2 different versions. endusers might ask: What was the reason I should move to matrix again?
I have zero knowlege about how this internally works in kodi, but parsing another attribute from an xml-file, and do some comparing seems to mean nothing compared to all the time  already wasted with discussions about that and to the exponential work addon devs and repo maintainers will have in maintaining 2 different versions with every single release. From here it all looks a bit like unwillingness to implement that (which I could understand either)
What me bothers: It is neither documented nor announced anywhere

**Comment by fuzzard** [comment]
What it comes down to is everyone here is volunteering their free time, including everyone in team kodi. Discussions about how to do this have been around as long as the py3 branch work was done (in gsoc 2018 or something). No team member has had the desire/motivation to do it. Again, everyone is a volunteer who spends their time as they see fit working on what they want to work on.

This change is a way to move forward, that can/has been done. Everything around py3 involves major changes, and unfortunately this adds extra work for all involved (devs and reviewers, who are short on time as is).

As an addon dev, if you choose to only support <=18, theres nothing stopping you from spending your time as you see fit.

**Comment by lrusak** [comment]
> There will be lot working, unmaintained py2 only addons which will fall appart with the move to matrix anyways - with this decission there will be devs unwilling to maintain 2 different versions.

That's fine, it's a way to clean out the old unmaintained cruft.

>endusers might ask: What was the reason I should move to matrix again?

Because Python2 is EOL.

> I have zero knowlege about how this internally works in kodi, but parsing another attribute from an xml-file, and do some comparing seems to mean nothing compared to all the time already wasted with discussions about that and to the exponential work addon devs and repo maintainers will have in maintaining 2 different versions with every single release.

Then please feel free to implement it 👍 

> What bothers me: It is neither documented nor announced anywhere

It was announced on the forum 18 days ago
https://forum.kodi.tv/showthread.php?tid=351745

@ronie also did a huge amount of work adding many of the relevant script modules to the matrix repo already. You can see that here https://github.com/xbmc/repo-scripts/tree/matrix

**Comment by knaerzche** [comment]
Nobody questions the move to Python 3 ... this should/could have been done with leia or earlier already - Python3 is more the 11 years old now. Thing is: Up until now it was nowhere announced that there will have to be 2 different versions of each addon, thats why most devs made efforts to make their addons py2/3 compatible (as volunteers, as you might guess) - wasted time as comes out now. As said: I don't share this oppinion, but I can understand the annoyedness

**Comment by fuzzard** [comment]
As until upto ~20 days ago, people were still hoping (for >2 years mind you), someone would come through with an implementation of method 1. Its come to a point where v19 alphas want to be started, and we cant have a heap of py2 addons in the repo that fundamentally wont work. I dont know the specifics of how the repos work, so all that stuff is for others to comment on if they see fit, but what ive gathered is theres no way to distinguish currently between py3/compatible and py2 only addons in the existing repo system for displaying to the end user.

lrusak pointed to the forum announcement by ronie. Dont think anyone prefers this route, its again, no one has implemented any alternative.

**Comment by knaerzche** [comment]
I completly understand your point. I didn't know about that issue before ... and TBH: for about 5 minutes I really thought about implementing it ... but looking at your PRs from non "Team Kodi" members immeditatly changed my mind - descission had been made. Done.

**Comment by lrusak** [comment]
> I completly understand your point. I didn't know about that issue before ... and TBH: for about 5 minutes I really thought about implementing it ... but looking at your PRs from non "Team Kodi" members immeditatly changed my mind - descission had been made. Done.

It's this attitude that hurts more than anything. We are simply a group of volunteers and have to consider our own time also. If you don't have the time or attitude to do it what makes you think we do?

**Comment by knaerzche** [comment]
Why you guys always become personal, when you have no professional argument? (Almost) everybody is an voulnteer in opensource world - I did lots of contributions in various ways: So I'm not sure if its my "attiude" whats the problem here. Just take a look at some closed/more that 1 year open PRs: You might guess what keeps me from doing this. Anyways: Good Luck!

**Comment by ronie** [comment]
if people want to wine and bitch, please by all means, open your own issue ticket.
this one is now locked.
