### ISSUE TITLE
Menus loading slow due to a lot of cached thumbnails

### ISSUE THREAD

**Issue by acixx** [xbmc/xbmc#17344]
Since I have added a huge collection of audio files to my Kodi database and listened to a lot of music, navigating through menus became very very slow, I mean PITA-slow, it takes up to a minute to load a single page and navigating to the desired content takes up to 10 minutes, no matter if I'm browsing local or remote content. 

This seems to be due to Kodi digging through all the tens of thousands of cached thumbnails when loading menus, as the problem is gone when I delete ~/.kodi/userdata/Database/Textures13.db and ~/.kodi/userdata/Thumbnails/* - until the folder is cluttered again after while. 

Steps to reproduce:
1. Fill your database with about 150 GB of music
2. Use it a as a music player for a while. 

Maybe Kodi should not cache thumbnails for every single audio, but only for an album and not  load/save generic thumbnails. 

I'm on a Raspberry Pi 3B+ running LibreELEC 9.2 (Kodi 18.5). 

[Debug-Log](https://github.com/xbmc/xbmc/files/4174047/kodi.log)  (unfortunately only after cleaning)

**Comment by DaveTBlake** [comment]
>, it takes up to a minute to load a single page and navigating to the desired content takes up to 10 minutes, no matter if I'm browsing local or remote content.

Can you clarify what you mean by both the above and "menus loading". I think you mean navigating artists, albums and songs nodes, is that correct? 

With lots (~100k) of songs then viewing the songs node unfiltered i.e. all the songs, is going to be very slow. That is a known issue and relates to how the GUI is based upon all the data being fetched into local memory before even the first page is displayed. It could happen to other nodes too if they have thousands of entires. 

However that issue is not about loading art from cache. Loading art takes place in the background, hence sometimes users see a page without art which then populates later. So I'm not sure if you are reporting a known issue, or if you have something else happening.

**Comment by acixx** [comment]
The problem occurs not only when navigating through albums, songs etc, but everywhere, ie also navigating through apps like Youtube becomes very slow and every single page takes a minute or two to be shown. 

After deleting the mentioned files/folders everything became quick again. 

I think it's more a general problem with a huge thumbnail-database, not specifically for thumbnails for a huge collection of audio-files. Maybe it's even cluttered by thumbnails cached from youtube-searches and other apps (if those are cached too), sorry for misleading title.

**Comment by HitcherUK** [comment]
Are you allowing Kodi time to actually build the cached thumbnails?

**Comment by DaveTBlake** [comment]
Ah, so not _just_ a music library thing :) 
Yes the texture db gets cluttered with every image Kodi displays (or could display even if you don't browse to the next page of a list). I browsed my photo library once when  testing art selection, it all ended up in cache!  Image cache maintenance is a tricky issue and the current implementation is flawed (errs on the side of keeping more than is needed and this gets cluttered and can be slow to refresh user local art changes).

But AFAIK cluttered textures is not known for making GUI use slow because image loading is done in the background. So can you let this issue build up again, and when you notice GUI slowness then take a copy of Textures13.db before deleting it. Particularly interested in just how big is huge! Also a debug log taken during slow use could be helpful. 

I would not be suprized at a bloated image cache being a problem, but would like to be able to quantify it. Also it could even be an SD card issue your end. I have over 200k of songs on a RPi2, never cleaned the texture db and never had an issue, then again I only just started using a video lib and I don't youtube so maybe I don't clutter it enough.

**Comment by zag2me** [comment]
I think the artwork beef add-on has an option for pre-caching the music artwork. Might be useful on slower systems.

**Comment by acixx** [comment]
@zag2me I think this would make it worse, as the problem occured only when the thumbnail-cache was already huge. After deleting the database everything is running smooth again, it will probably take a while until the issue arises again.
