### ISSUE TITLE
[Python] <episodeguide> flawed

### ISSUE THREAD

**Issue by KarellenX** [xbmc/xbmc#17341]
## XML Scrapers
The XML scrapers use `<episodeguide>` URL's as follows:

**TVDB**
```xml
<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:364093}|Content-Type=application/json</url>
```

**TheMovieDB**
```xml
<url cache="tmdb-85949-en.json">http://api.themoviedb.org/3/tv/85949?api_key=6a5be4999abf74eba1f9a8311294c267&amp;language=en</url>
```

As you can see the `<episodeguide>` URL's from the two providers are different and only the correct scraper will read them. The wrong scraper will simply fail to scrape anything.

## Python Scrapers
The new Python scrapers are using a differently formatted `<episodeguide>` URL. The format for each provider is listed below

>`<episodeguide>73965</episodeguide>` - From TVDB
>`<episodeguide>73965</episodeguide>` - From TV Maze
>`<episodeguide>73965</episodeguide>` - Expected format for TheMovieDB

The issue with this new format is that any scraper will recognise and use the `<episodeguide>` URL that comes from a different provider. 

For example, picking a show at random:

>ID 85353 at TVDB belongs to the following tv show:
>upin-and-ipin - https://www.thetvdb.com/series/upin-and-ipin

>ID 85353 at TheMovieDB belongs to the following tv show:
>Chandra Nandini (2016) - https://www.themoviedb.org/tv/85353-chandra-nandini

or

>ID 4624 at TheMovieDB belongs to the following tv show:
>Roswell (1999) - https://www.themoviedb.org/tv/4624-roswell?language=en-US

>ID 4624 at TV Maze belongs to the following tv show:
>Take Me Out - https://www.tvmaze.com/shows/4624/take-me-out

(At this time the TV Maze numbering has not caught upto TVDB, but will in a few years time.)

**This can obviously lead to some very confusing results for the end user:** 
* A user may attempt to add new episodes to an existing show not remembering that two weeks ago he swapped scrapers. 
* Or using NFO files where some or all episode nfo files are missing, a different scraper has been set to the one originally used to create the tvshow.nfo file

All leading to confusion and frustration for the user (and moderators on the forum :) )

I believe that this could potentially be a major problem reported on the forum. "I am trying to scrape Roswell, but why am I scraping episodes from a dating tv show?"

Maybe an alternative method is required? 

@scudlee

**Comment by ScudLee** [comment]
The XML scrapers explicitly need the episodeguide to be a functioning URL to work, as Kodi fetches the contents of that URL directly itself, and the function will just fail if it's not a valid URL.  It's the reason the tvdb scraper episodeguide URL is so weird.  Without a token, the only valid URL is the login, but it still needs the series id hidden in there to know what show to scrape.

For Python scrapers, though, I would assume they handle the URL retrieval themselves, so are free to put whatever they like as the episodeguide, so long as they can parse it and turn it into the actual URL they need.  Hence why they just use the series id.  It's the simplest choice.

My first thought would be to expand it to use something like JSON, and store the episodeguide as:
 `<episodeguide>{"tvdb":73965}</episodeguide>`
so the source of the id is included.  

It would also allow you to potentially store multiple ids like:
 `<episodeguide>{"tmdb":4624,"imdb":"tt0201391"}</episodeguide>` (whatever is available)
That could then make switching potentially easier, as both tmdb and tvdb would hopefully at least share the same imdb id, and their respective episodeguide functions could both fall back to using that if they don't find the primary id in the episodeguide. (With tmdb, at least, you could probably also just get the tvdb id itself as well anyway.)

Something like that, maybe.  You could also do XML, I suppose, but I would guess JSON is easier for a Python scraper to create and parse.   
I'm not fully up on Python scrapers, though, so this could all be nonsense.

**Comment by rmrector** [comment]
> My first thought would be to expand it to use something like JSON

This is what I do with the TMDB movie scraper. They don't actually get stored for movies but otherwise the "URL" in the search results work the same for Python scrapers.

**Comment by vbat99** [comment]
I can only request that changes incorporate backwards compatibility as changing a nfo to only suit Kodi 19 above python scraper, but not being able to be scraped into Kodi 18, Kodi 17 would be detrimental and frustrating as hell for users of 3rd party scrapes like Media Companion.

**Comment by KarellenX** [comment]
@vbat99 
Have already made one request here for the python TVDB scraper...
https://github.com/xbmc/metadata.tvdb.com.python/issues/13

**Comment by jkirsch2** [comment]
Small question...
With the new Python scrapers, is it really necessary to continue to use the <episodeguide> field ?
Can't we simply use the id fields that are already available ?

**Comment by Razzeee** [comment]
FYI I think we have workedaround this in the scrapers, a proper fix would still be a good thing.

**Comment by KarellenX** [comment]
How? Has the format of the <episodegude> been changed and I missed it?

**Comment by Razzeee** [comment]
I might be wrong then. But I thought we tested that case and circumvented it causing the problem. But if anyone knows it would be you @KarellenX

**Comment by KarellenX** [comment]
First reported issue of the overlapping ID's...
https://forum.kodi.tv/showthread.php?tid=368272&pid=3114237#pid3114237

**Comment by romanvm** [comment]
As I understand, this issue affects the following scenarios:

1. A user changes a scraper without re-scanning their collection.
2. A user has tvshow.nfo files generated by another scraper.

For the 1st case we may indeed need some convention for `episodeguide` format. The suggestion to use JSON format seems reasonable. But we should also agree on the behavior when a Python scraper cannot process episodeguide info (passed to `getepisodelist` call). I'd suggest throwing an error with a clear message about the problem. Because if a scraper ignores invalid episodeguide then a user will come to the forum anyway asking "why Kodi didn't scrape a new episode of show X?".

For the 2nd case a scraper should do reasonable efforts to extract a valid TV show info from an .nfo file. You can see how it's done in TVmaze scraper. But if a scraper cannot process a tvshow.nfo file then it should also throw an error as well with a clear error message.

To be able to use episodeguide/tvshow.nfo info across scrapers a Python scraper should save as many unique IDs from different information providers as possible. It also helps if an information provider allows to search entities by foreign IDs (like TVmaze does) but this is beyond our control.

**Comment by KarellenX** [comment]
Another report of this issue... https://forum.kodi.tv/showthread.php?tid=369896&pid=3118240#pid3118240

@romanvm 

The problem is that the `<episodeguide>` is definitely valid. ie, the id does exist and is attached to tv shows.
**Its that the ID's are valid but pointing to the wrong tv show.**
It would be a different problem if the ID's did not exist and the API returned a "Not found" error.

I don't think there is any way to make a scraper intelligent enough to decide, _hey this is a valid episodeguide, but it is the wrong tv show._

I think the only way to fix this is to use this JSON format to distinguish which site the ID comes from.

**Comment by romanvm** [comment]
@KarellenX 
> The problem is that the <episodeguide> is definitely valid. ie, the id does exist and is attached to tv shows.
Its that the ID's are valid but pointing to the wrong tv show.

If the episodeguide string cannot identify a TV show then it's definitely invalid.

>I don't know if anybody is interested in fixing this?

This is not a Kodi issue as such. Each Python scraper can use any string value as episodeguide as long as it allows the scraper to correctly identify a specific TV show. Historically, in my TVmaze scraper I used a database ID for this purpose. Other guys who used TVmaze scraper as the base did the same. I admit that I didn't predict this issue and with hindsight I would have done differently.

Anyway, this needs to be fixed in each Python scraper and will require full library rescan. I will fix this in my TVmaze scraper as soon as I can given my specific circumstances. As for formatting convention, JSON seems good, although other options like an API URL (e.g. https://api.tvmaze.com/shows/1/episodes ) for the list of episodes is also possible.

**Comment by KarellenX** [comment]
So only the scrapers need to be updated and no Kodi core changes are required. That makes it a bit easier.

@pkscout do you have time to look at this also? Is the JSON method with multiple provider values the best way?

We'll also need @scott967 at TVDB to keep an eye on this also.

**Comment by pkscout** [comment]
Based on my read, the json approach seems best. I'm happy to update the TMDb TV show scraper, but I need to know for sure that everyone has agreed to one standard, that have a common way how we're handling errors (as noted previously), and that we have some understanding of how we're going to deal with existing legacy data.

**Comment by KarellenX** [comment]
Thanks @pkscout 

You and @romanvm are the only two current TV Show scraper developers, so its just you and romanvm that need to agree. 

I've had another two reports yesterday of this issue, and for every report here on the forum, I wonder how many users are at home cursing how f*$#&ed up Kodi is. So to get the ball rolling... 

I think romanvm has already mentioned the JSON approach as a good method. romanvm also mentioned using API URL, but I think that limits you to a single site episodeguide only as opposed to the JSON that lets you add multiple sites.

1. I think where available TMDB, TVDB and TVMaze id's should be scraped as described by scudlee `<episodeguide>{"tmdb":76479,"tvdb":355567,"tvmaze":15299}</episodeguide>`
2. IIRC TVMaze uses multiple identifiers, another being TVRage. They need to be converted back to tvmaze
3. Conversions for existing setup. I don't see how that can be done, because the scrapers are not intelligent enough to know which tv show the user wants and whether the episodeguide matches the scraper in use. We'll probably just need to tell users to Refresh the tv show. Maybe do a compare on the default UniqueID?

**Comment by pkscout** [comment]
I don't know that @romanvm and I are the only scraper developers, we're just the only ones on the team.  The TVDB folks need to get on board with this, as theirs is going to have to be updated as well.  I guess if we get the Big Three (TMDb, TVMaze, TVDB) we'll be OK, but there are other, smaller scraper developers too (I did one on the side for the SportsDB for instance).

To your point of conversions, I would agree.  I don't see any way to do on the fly conversion.  The best case is we can keep assuming that a numeric ID in that field belongs to our scraper, which will make it no worse than now.  But a refresh would be required to get the IDs to the new format (and maybe even a rescrape, we will need to test that).  The worst case is we stop using the numeric and force complete rescrapes for anything to work again.  I'm definitely not advocating for the worst case, BTW.

Either way I consider this a breaking change.  In my opinion we should only do breaking changes during a major version upgrade of Kodi, and I don't think we should introduce a breaking change this late in the Nexus development cycle.  So that would mean holding this fix for Kodi 21 and then somehow bump something the scrapers require from core in a way that will force a scraper to either update or be incompatible with Kodi 21.

**Comment by KarellenX** [comment]
>Either way I consider this a breaking change. 

Why? Are you planning on not having a fallback to the current single value episodeguide? Like you said, assume that the current ID belongs to the scraper in use.

> So that would mean holding this fix for Kodi 21

Nooooooooo. Honestly I don't want to spend the next two years helping users fix this problem. I am hoping this gets done ASAP.  I reported this issue almost three years ago. And now it has finally hit us, so another two years of help is not something I want to get involved with. It is quite time consuming and frustrating with many members trying to decipher their posts, get a debuglog, get them to rescrape and then figuring out the problem is the episodeguide.

Geez, I went through this with that damn TVDB v1 to v2 upgrade and that was a nightmare.

Is my frustration of this prospect coming through? :)

**Comment by pkscout** [comment]
What happens when a scraper that hasn't been updated runs into JSON in that field?  Will it crash? Maybe abort the scan part way through, destroying the database?  Or just fail?  I don't know.  And thus it is, in my opinion, a breaking change.  I'm going to wait for @romanvm  to weigh in here.  If he thinks we can pull it off without major issues, we can look at moving forward.

Even if we do move forward, I feel like if we don't get TVDB on board it isn't going to matter.  If they keep using just the numeric ID, then anyone who changes from that scraper to another will cause all the same problems, and anyone moving from the updated scrapers to the TVDB will be even more screwed because there won't be an ID in there to match.  All three major scrapers likely must move together.

**Comment by KarellenX** [comment]
>What happens when a scraper that hasn't been updated runs into JSON in that field? Will it crash? Maybe abort the scan part way through, destroying the database? 

I suppose that is where I come in with all the testing.

>I feel like if we don't get TVDB on board it isn't going to matter.

I have pinged scott from TVDB in an above post. I have previously made him aware of this issue. If he chooses not to comment or get involved, there is nothing we can do about it, and he will just have to update his scraper to keep it working with Kodi and to keep TVDB's users happy. Anyway this is a Team decision for the best effectiveness of Kodi. Other developers will have to follow suit, pretty much like what happens when we make other changes in Kodi. But I cannot see why this **fix** has to be tied to a major release. And this is a bug fix, not an upgrade or enhancement or a new feature.

**Comment by KarellenX** [comment]
>We'll also need @scott967 at TVDB to keep an eye on this also.

Oh bugger. Wrong scott. 
I'll ping scott at TVDB on their Slack channel.

**Comment by szsori** [comment]
Hi folks.  We (TVDB) noticed this issue as well and are on board with switching to the json format for <episodeguide>.  We'll just have to set aside the resources for doing so.  If any of the other plugins have an expected timeline for rolling out this change, let us know so we can try matching that.

**Comment by pkscout** [comment]
Not sure where else to track this right now, but I have a question about naming for the fields.  By default, The Movie Database has everything stored as `<name>_id`, and I can obviously lop off the `_id` from all the entries if everyone else stores them that way.

If we do that, I do have a question though.  Does anyone know what the `freebase_mid` is?  The Movie Database has that and `freebase_id` in their dataset.  I wasn't planning to filter out anything The Movie Database has for unique IDs, so we might have to agree that `freebase_mid` stays as is and the rest drop the `_id`.

Just as an FYI, here's what the episode guide entry looks like in the database (reformatted slightly for readability here) if I dump everything The Movie Database has (this is Shining Girls).
```
<episodeguide>
    {"tmdb_id": 106388,
     "imdb_id": "tt2953250",
     "freebase_mid": null,
     "freebase_id": null,
     "tvdb_id": 385810,
     "tvrage_id": null,
     "wikidata_id": null,
     "facebook_id": null,
     "instagram_id": null,
     "twitter_id": null}
</episodeguide>
```

**Comment by rmrector** [comment]
I suggest to use the keys and values passed to Kodi in the uniqueid structure. String values always, like uniqueid.

**Comment by pkscout** [comment]
OK, I have a beta version of the TMDb TV Shows scraper for Nexus.  It seems to work.  For newly scraped or refreshed shows, it stores the TMDb, IMDB, and TVDB IDs in episodeguide as JSON.  The values are strings as suggested.  For things with the old episodeguide, it continues as is using the digits as a valid show ID (meaning the problem of different shows with the same ID across providers still exists).  It also continues to parse NFO files and tries to convert any that aren't TMDb ids into TMDb ids.

A few things:
1. Converting IDs requires one or two additional API calls, so it will slow things down some if a TMDb ID is not found.
2. Unless you refresh or rescrape the show, I can't find any way to update the episodeguide from the episodelist call, so it's possible that someone who moves over from another scraper will complain about how slow it is.  If so, they need to refresh/rescrape all their shows to get rid of the thing I mentioned in number one above.

Available to test on Nexus at:

https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/tree/nexus

Once this has all settled out some, I will backport this to the Matrix version of the scraper.

**Comment by romanvm** [comment]
So let's summarize all this.

- The common convention for episodeguide is a JSON string with keys and values in the same format as in uniqueid DB table.
- The scraper should support the old format of DB ID for backward compatibility. I'd recommend to log a warning in this case for a user to re-scrape this specific show. 
- If a scraper cannot resolve episodeguide because it's missing the necessary ID and the scraper's info provider does not support alternative IDs, then the scraper should raise an exception with a clear error message explaining why this has happened.

If nobody objects to this then this info should be added to the Wiki: https://kodi.wiki/view/Python_tv_scraper_development I'll try to do it but if I won't do it within the next week and go incommunicado then someone else please do update the Wiki.

> What happens when a scraper that hasn't been updated runs into JSON in that field? Will it crash?

Most probably if we are talking about switching scrappers. But I guess it's better that silently download wrong info.

**Comment by pkscout** [comment]
That sounds good to me.  Quick question.  What exception would you suggest we raise?  For a generic Python one, maybe ValueError?  Or were you thinking of something Kodi specific?

**Comment by romanvm** [comment]
I'd normally raise a `RuntimeError`.

**Comment by DanCooper** [comment]
As a developer of an external media manager (Ember Media Manager) I've some questions, because I've no idea, how the internal Kodi scrapers works. I understand the issues with <episodeguide> and switching scrapers, but:

- Why you don't use the <uniqueid> to determine the correct tv show?
- Why do you want to store the same data in a second node?
- Why do you save JSON in an XML? Just that you don't have to add a new node in the Kodi NFO class or database? Sounds like a workaround for me which shall remain forever... It's the same like has been done for <set> when changing it from a single text field to multiple fields for name and plot. It's always a pain when trying to determine what type a node is. In a perfect world no one whould change a database type from e.g. String to an Integer...

**Comment by romanvm** [comment]
@DanCooper @vbat99 I guess you have missed the point of the discussion and some explanation needs to be done. To retrieve the list of episodes Kodi passes `episodeguide` string the a Python scraper as `url` query parameter. And a Python scraper can pass an arbitrary string to Kodi as `episodeguide`. This is how Kodi interacts with Python scrapers it cannot be changed without changing Kodi core code. But given our shortage of core developers I doubt it can be changed any time soon. And in any case this will be a breaking change that should be done done in a new Kodi version that will be released God knows when. So as scraper developers we are discussing how we can mitigate the situation from our side right now.

**Comment by KarellenX** [comment]
I've tested the Beta scraper by @pkscout using various scenarios and all worked as expected.

The guide is created in the DB as follows:
`<episodeguide>{"tmdb": "68427", "imdb": "tt4939064", "tvdb": "316345"}</episodeguide>`

In an nfo file, it exports as:
`<episodeguide>{&quot;tmdb&quot;: &quot;68427&quot;, &quot;imdb&quot;: &quot;tt4939064&quot;, &quot;tvdb&quot;: &quot;316345&quot;}</episodeguide>`

TVDB have stated they would start work on this soon. @romanvm do you have any time for TV Maze?

**Comment by romanvm** [comment]
I do want to update TVmaze scraper but can't tell when and if I'll be able to do it given my specific circumstances.

**Comment by KarellenX** [comment]
Ok, thanks @romanvm 

I hope you are staying safe over there.

**Comment by KarellenX** [comment]
I believe this issue is now resolved, so I'll go ahead and close this issue report.

More information of the fixes can be found on the forum here... https://forum.kodi.tv/showthread.php?tid=370489

**Comment by KarellenX** [comment]
Bookmark... https://github.com/xbmc/xbmc/pull/26945
