### ISSUE TITLE
If you delete a TVShow via the JSON API (not tried GUI), it will be missing forever even if present on disk

### ISSUE THREAD

**Issue by jcea** [xbmc/xbmc#17393]
### Describe the bug

If you delete a TVShow via the JSON API, it will be not rescanned again. I haven't tried via de GUI, since I don't want to lose more TVSHOWs!! (I have tried several times via JSON API, losing more and more shows :)

Deleting a TVSHOW and rescanning the library would be useful if you changed thetvdb database, for instance, and you want your library to reflect those changes.

## Expected Behavior

1. Delete the TVSHOW from the library.
2. Update the library.
3. The show is found and the library is populated with up to date content.

## Actual Behavior

1. Delete the TVSHOW from the library.
2. Update the library.
3. The show is missing although it is actually present in the disk.

New episodes in the TVSHOW directory will NOT solve the issue. The show will be simply missing... forever.

## Possible Fix

Drop any reference of the show in the library, so a library update would pick a "new" tvshow (never seen before) on disk.

### To Reproduce

1. Delete a TVSHOW from the library. The TV Show is still on disk.
2. Update the library.
3. The show is missing in the library, although it is actually present in the disk.

### Your Environment
Used Operating system:

OSMC fully updated running on a Raspberry PI 3B+.

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC
 - Kodi version: 18.5

Thanks!!!.

**Comment by KarellenX** [comment]
Please provide a debug log which captures the rescan and tell us the name of the tv show. Are you rescanning via the GUI?

Also provide the JSON syntax you are using.

**Comment by DaVukovic** [comment]
I can't reproduce this issue with Kodi 18.5

Using: 
`curl -s --data-binary '{"jsonrpc": "2.0", "method": "videolibrary.removetvshow", "params": { "tvshowid": 21 }, "id": 1}' -H 'content-type: application/json;' http://localhost:8080/jsonrpc`

removes the tvshow with the id "21" from my library (in my case this was "Vikings"). After using "update library" via GUI or via JSON command, the TVshow was added to my library again. 

Unfortunately the debuglog doesn't tell anything obvious after executing this command. So that log might be useless for debugging what happens after that command was executed. But it might be interesting for what happens after the library was updated again, to see where the scan fails.

**Comment by jcea** [comment]
Sorry for wasting your time. After quite a few new tests, puzzling and inconsistent results, etc., I think the issue is rooted in TheTVDB website flaky behaviour.

Sorry for wasting your time. Closing the issue... for now at least :-)
