### ISSUE TITLE
xbmc-18.6-Leia/build/libdvd/src/dvdread/src/ifo_print.c:221:5: warning: this statement may fall through [-Wimplicit-fallthrough=]

### ISSUE THREAD

**Issue by dcb314** [xbmc/xbmc#17425]
Source code is

  case 2:
    printf("mpeg1 ");
  case 3:
    printf("mpeg2ext ");

**Comment by dcb314** [comment]
I believe the automated bot sent a message in error.

**Comment by smp79** [comment]
I believe it didn't.

**Comment by DaVukovic** [comment]
No, the bot is correct. 

You simply decided to completely ignore our template which is mandatory for a valid bug report. 

Please get us a more detailed description of what the problem is, what issue it causes, how to reproduce the issue followed by a debug log. 

The same counts for the other issues you opened. As the bot says, we will close your issues in 7 days if you haven't added the missing infos.

**Comment by dcb314** [comment]
>You simply decided to completely ignore our template

Indeed. Open source is all about getting help from strangers.
Sometimes strangers don't do things how you want them, but do provide
useful information.

I simply ran cppcheck, a static analyser, over your code and opened some
bug reports. What you do with them is up to you, but placing all sorts of restrictions
in the way of reasonable bug reports won't help your project.

No, I am not doing a pull request.

**Comment by fuzzard** [comment]
All 3 warnings are actually in upstream projects.

If you actually want to assist, you would be better to send through to their respective upstream.

Libdvdread - https://code.videolan.org/videolan/libdvdread
ffmpeg - https://www.ffmpeg.org/developer.html#Contributing

**Comment by dcb314** [comment]
All three bugs are already fixed in upstream projects.

I suggest this project needs to update their copies.
