### ISSUE TITLE
Toast messages are too short

### ISSUE THREAD

**Issue by kekukui** [xbmc/xbmc#17441]
Toast messages are truncated & disappear before the text can be read

![Estuary update bug](https://user-images.githubusercontent.com/20834957/76015955-0526ab80-5eea-11ea-9892-2e6ea9dc3a9a.png)

Recommendation:

- Increase default delay time
- Include an option in skin settings:
    `Time to display toast messages on screen (in seconds)`

Consider using [xperience1080](https://github.com/xperience1080/skin.xperience1080) skin as a design guide for toast message presentation ; the animation is also quite polished and worthy of emulation

![XP update bug](https://user-images.githubusercontent.com/20834957/76016712-52efe380-5eeb-11ea-898f-df8db1047af0.png)

**Comment by CastagnaIT** [comment]
I had this problem too
but since it's customizable, I've increased the timeout, as needed

in order to avoid these problems, it would be more appropriate for the notification to be closed only at the end of the scroll of the text

but i suspect there's no such thing as a callback that gets hit when the scroll ends
