### ISSUE TITLE
Failed parsing some file links in html index file when using "web server directory" protocol

### ISSUE THREAD

**Issue by PeterDaveHello** [xbmc/xbmc#17623]
### Describe the bug

When using http or https ("web server directory" in Kodi) protocol to watch video, the file list is a html file containing hyper-links of files, fetched from the web server.

I found that some valid html links in index files can't be parsed/displayed properly, the video files won't show up in the file list.

## Expected Behavior

I expect that every file links in the html file with valid html syntax will be properly parsed and displayed in the file list

## Actual Behavior

The files aren't displayed in the file list

## Possible Fix

Since I didn't trace the source code so I don't have strong idea here, but maybe need a stronger html parser

### To Reproduce

1. Setup an http server with a `index.html` text file use following content:

```html
<html>
  <head>
    <title>Page title</title>
  </head>
  <body>
    <a href="video.mkv">
      video.mkv
    </a>
    <a href="video0.mkv">video0.mkv</a> <a href="video1.mkv">video1.mkv</a>
    <a href="video2.mkv">
      video2.mkv
    </a>
    <a href="video3.mkv">video3.mkv</a>
  </body>
</html>
```

The html tag `<a> </a>` of file `video3.mkv` is in the same single line, and the `video.mkv` `video2.mkv` are using multi-line separately, `video0.mkv` `video1.mkv` shares the same line.

2. Add a Video source in Kodi, using web server directory protocol, and navigate to the http server that contains the testing `index.html` from previous step

3. Visit the added file source to see the file list, you'll see that only `video3.mkv` is displayed, and the all the others are not.

### Debuglog

The debuglog can be found here, I have the same issue in all my Kodi environment, so I only attach one log from one of my laptops that using Linux Mint, hope it should be enough:

[kodi.log](https://github.com/xbmc/xbmc/files/4442684/kodi.log)

## Additional context

Some http servers like [Caddy](https://caddyserver.com/) generate file list index in multiple line format, which is valid html, but can't be used by Kodi.

### Screenshots 
Here is the screenshots to help explain the problem:

Screenshot of the bug reproduce procedure:
![image](https://user-images.githubusercontent.com/3691490/78575253-adb78a80-785d-11ea-8a2a-eb49e59ca781.png)

Screenshot of the file source from Caddy server generated file list:
![image](https://user-images.githubusercontent.com/3691490/78572959-b5296480-785a-11ea-9827-5ddbd078c7e2.png)

### My Environment

Used Operating system(though I thought that the problem is OS independent):

 - [x] Ubuntu 18.04
 - [x] Linux Mint 19.3
 - [x] Raspberry-Pi 3 B+ With LibreELEC 9.2.1 / OSMC 2020.03-1
 - [x] Windows 10
 - Kodi version: v18.6 Leia

**Comment by lrusak** [comment]
Would need to see a debug log to prove that kodi is failing to parse the index.html.

Otherwise I would also check the permission of the files on the web server to make sure they are readable by the public (without authentication)

**Comment by PeterDaveHello** [comment]
Hi @lrusak ! I've attached the debug log, thanks!

The file permission is totally correct, it's only the index causing the issue, and I have no problem to browse and open those files from a web browser like Firefox and Chrome, so I guess it's a html parsing issue 🙂

**Comment by djp952** [comment]
While I can't help directly (I suck at Regular Expressions), the place where this would seemingly need to be addressed is here:

https://github.com/xbmc/xbmc/blob/16d333916573d2dc5c4bb6a38b4888a3cfca79e6/xbmc/filesystem/HTTPDirectory.cpp#L45

I played with it a little since I thought I might be able to contribute something here, but I couldn't come up with any expressions that would work for multi-line anchor tags. I was able to come up with an expression that caught all of the single-line anchor tags as opposed to just the one based on your sample HTML, but it wasn't compatible with Kodi's regex engine and returned nothing at all.  My amateur hour help is to identify the line of code that an expert might be able to tweak for ya.

**Comment by lrusak** [comment]
> While I can't help directly (I suck at Regular Expressions), the place where this would seemingly need to be addressed is here:
> 
> https://github.com/xbmc/xbmc/blob/16d333916573d2dc5c4bb6a38b4888a3cfca79e6/xbmc/filesystem/HTTPDirectory.cpp#L45
> 
> I played with it a little since I thought I might be able to contribute something here, but I couldn't come up with any expressions that would work for multi-line anchor tags. I was able to come up with an expression that caught all of the single-line anchor tags as opposed to just the one based on your sample HTML, but it wasn't compatible with Kodi's regex engine and returned nothing at all. My amateur hour help is to identify the line of code that an expert might be able to tweak for ya.

try `<a href=\"(.*?)\">(.*?)</a>`

see, https://www.ultraedit.com/support/tutorials-power-tips/ultraedit/non-greedy-perl-regex.html

**Comment by djp952** [comment]
Thanks @lrusak!

The replacement expression appears to pick up video0 and video3 from the sample .HTML, which is a definite improvement!  Do you have any RegEx-fu that might be able to handle the multi-line anchor tags and/or having more than one anchor tag on the same line?  Happy to test since I'm set up to do so.

**Comment by lrusak** [comment]
> Thanks @lrusak!
> 
> The replacement expression appears to pick up video0 and video3 from the sample .HTML, which is a definite improvement! Do you have any RegEx-fu that might be able to handle the multi-line anchor tags and/or having more than one anchor tag on the same line? Happy to test since I'm set up to do so.

We seem to already use PCRE_DOTALL which should do multi line matching. I’m out of ideas but you can play around using an online regex tester like this https://regex101.com/

**Comment by fuzzard** [comment]
Maybe something like `<a href=\"(.*?)\">(\s?)(.*?)(\s?)(.*?)</a>`

**Comment by djp952** [comment]
That expression works. Digging deeper, it turns out the HTML file is being parsed line-by-line and only looks at the first match on any given line, so the results will still not match the expectation.  I'll take a crack at adjustments for both and see how they turn out.

**Comment by djp952** [comment]
Hi @PeterDaveHello, with @lrusak and @fuzzard's help above, I do have a rough solution to the problem that with some additional work could be proposed as a PR:

![Untitled](https://user-images.githubusercontent.com/706055/78955145-522f0c00-7aac-11ea-9ed8-796feab94a9f.png)

However, I'm not sure this is a good idea and I think it would be difficult to get a PR approved.  This code is actually designed to read specific HTTP directory listing formats, for example what you might see somewhere like [https://mirrors.edge.kernel.org/pub/](https://mirrors.edge.kernel.org/pub/):

![Capture](https://user-images.githubusercontent.com/706055/78955233-9fab7900-7aac-11ea-9cbc-8afc4ddc3498.PNG)

All of the supported formats do require the anchor tag to be on a single line, as they are subsequently followed by the additional information you see on the same line.  Kodi currently supports the HTML format provided by **lighttp**, **nginx**, and **apache**.

I don't think it will be difficult to finish it up and still have those formats work, but in order to continue here the .HTML must be parsed as a whole instead of line-by-line like it is today.  This could introduce some unexpected side effects and difficult to catch regressions.  For example, the expected text after the anchor would now be allowed to cross line boundaries, so the patterns themselves could match things they shouldn't and cause problems.

There also doesn't appear to be any unit tests for HTTP directories in the current code base, and I think a change of this scope would need one to be added.

I am perfectly willing to continue and try to get a PR accepted to solve this (and maybe add the IIS directory format), but after really digging into this I think it's working the way the author intended it to and this may be more of a documentation issue than a technical issue.  If it's not clear somewhere that "Web server directory" locations require conformance to specific format(s), it probably should be.

Let me know what you think.  I honestly have almost nothing better to do right now, and submitting flawed PRs to Kodi that need lots of rework is kind of my thing™ :)

**Comment by PeterDaveHello** [comment]
Thanks @djp952, very appreciate your effort here, I don't know the policy or convention here about this kind of pull requests, though I would like to see the html parsed been enhanced very much, do you think it's possible to use html parser library like https://github.com/lexborisov/myhtml https://github.com/google/gumbo-parser to complete the "Web server directory" feature?

**Comment by djp952** [comment]
No worries, I seem to have it all working, including a minor enhancement to capture the date/time and size from a more generic listing like IIS or a non-fancy apache provides.  I have to figure out how to get the formats it's supposed to support working somewhere to test them, but once that is done and looks OK I will submit a PR and reference this issue.
