### ISSUE TITLE
nvidia shield IR remote issue

### ISSUE THREAD

**Issue by Alecta-shield** [xbmc/xbmc#17792]
### Describe the bug
I use nvidia shield 2017 and nvidia shield remote (new one, Nvidia Shield TV Remote - Updated Model 2019). When i turn on audio passthrough and start or stop video playback, TV remote sends IR signal to increase volume of my TV. You can see it here https://yadi.sk/i/tma7q2Z_6O2-gg
KODI version is latest 18.6. Nvidia shield firmware is latest 8.0.2.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Get us a logfile please

**Comment by Alecta-shield** [comment]
[Uploading kodi.log…]()

**Comment by Alecta-shield** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/4567407/kodi.log)

**Comment by Alecta-shield** [comment]
> Get us a logfile please

done

**Comment by DaVukovic** [comment]
As this is not a log from Kodi start, I again have to guess ;)

I see the mentioning of "Onkyo" at your TV. So I guess there's some AVR in between. Could you please test connecting your Shield directly to the TV (with no AVR in the HDMI-chain) and see if the behavior is the same?

If it's connected like that (Shield -> HDMI -> TV -> HDMI (ARC) -> Onkyo), then please try to connect the shield to the onkyo or configure your TV to not send the audio to the AVR. 

For what I can tell, I can't see Kodi sending anything. So I suspect probably some CEC issue which might be caused by either the TV or the AVR. But I'm only guessing in that case. I also would say that you should play around with the connections and see when it does or doesn't happen.

@fritsch @peak3d or am I missing something?

**Comment by fritsch** [comment]
On Android the volume keys are handled by the system. It is responsible for volume up / volume down. Kodi only gets a message when volume has changed to chow its volumebar.

**Comment by DaVukovic** [comment]
@fritsch just that you are aware. Noone is pressing volume keys in that case. The user is simply starting the video and the volume decreases automagically. 

Just in case you might misunderstood.

**Comment by Alecta-shield** [comment]
> If it's connected like that (Shield -> HDMI -> TV -> HDMI (ARC) -> Onkyo), then please try to connect the shield to the onkyo or configure your TV to not send the audio to the AVR.

It is connected shield->onkyo->tv. HDMI passthrough in turned on on receiver. It's just like there is no receiver at all. And if i close remote with my hand the volume on my tv does not change. That's because IR-signal does not pass. So this is not an CEC issue. I can connect shield directly to my tv if you insist (little later).

**Comment by fritsch** [comment]
Are you two guys sure you talk about the same thing?

**Comment by fritsch** [comment]
If I combine a mix of every post, I think I know what your problem is. You hit a workaround for PT of old Androids, which your shield does not need but hits you anyways.

When old Android did PT, it was sent with PCM, therefore the "volume" was ramped up to 100% before starting playback. After PT ended, volume was reset to old value, here some "rounding" issues apply and the volume does not end up where it started.

So what you can try (as you run the amd64 build) is the following:

a) Recommended: Install a v19 Leia nightly. This version has that issue resolved.
b) If you cannot upgrade to Matrix yet, I can create you a copy of the fritschfiretv build for arm64.

**Comment by Alecta-shield** [comment]
@fritsch  didn't understand a word, sorry. I just want this problem to be solved in next version of KODI which i'll install from google play.

**Comment by fritsch** [comment]
Okay - then wait until v19 is released.

**Comment by Alecta-shield** [comment]
by the way. when i use old remote, or gamepad (IR control is also turned on on them), everything works fine. Proplem appears only when i use new updated remote.
