### ISSUE TITLE
Issue installing pvr addons

### ISSUE THREAD

**Issue by Neelix57** [xbmc/xbmc#17791]
I tried installing kodi-tvr-iptvsimple. Got the error: 

`The following packages have unmet dependencies:
kodi-pvr-iptvsimple : Depends: kodi-api-pvr (= 5.10.3)
E: Unable to correct problems, you have held broken packages.`

I tried it with other kodi-pvr-<packages>. Got the same error.

![Capture d’écran_2020-04-30_19-21-35](https://user-images.githubusercontent.com/63342144/80740153-f4746980-8b17-11ea-9ef6-7afc63dca2c1.png)

**Comment by DaVukovic** [comment]
Please get me: `cat /etc/*release` from that system or tell me what OS that is. 

And maybe I will learn something new, but I don't know the command `ai` or is that an alias? If it's an alias could you please tell me what that `ai` stands for then?

To be fair. I highly guess it's a support questions which should have been asked at the forums, rather than a bug report. But we'll see

**Comment by phunkyfish** [comment]
The PVR API was changed yesterday so if you need both latest kodo and addon version assuming you are running 19.

**Comment by Neelix57** [comment]
I apologize, I'm running Kodi 18.6under Xubuntu Focal. And, yes 'ai' is an alias for apt-get install.

So, the link given by phunkyfish solved the issue. Thank you very much Guys.

**Comment by phunkyfish** [comment]
NP, in future please post on the forum if you have a support issue like this ;)
