### ISSUE TITLE
Problem with creating playlists

### ISSUE THREAD

**Issue by xmha97** [xbmc/xbmc#17835]
# Problem with creating playlists  
Hello Kodi team
In general, the playlist works and has no problems,
Unless Turkish names are used in the file name!
## 1. This is what Kodi has made:  
```
#EXTCPlayListM3U::M3U
#EXTINF:0,19. Çelik - Ayrlk Hüznü
G:\Music\Cem Tuncer & Kerem Turkaydin\Bizim Hikaye (Orijinal Dizi Müzikleri), Vol. 1\19 Çelik - Ayrlk Hüznü.mp3
```
This playlist cannot be played by Kodi and any other program because there is no file that has been referred to it.
## 2. This is what needs to be built:  
```
#EXTCPlayListM3U::M3U
#EXTINF:0,19. Çelik - Ayrlk Hüznü
G:\Music\Cem Tuncer & Kerem Turkaydin\Bizim Hikaye (Orijinal Dizi Müzikleri), Vol. 1\19 Çelik - Ayrilik Hüznü.mp3
```
This playlist can be play by Kodi and any other program and no problem.
## Comparison 1 and 2:  
(1) -> `~\19 Çelik - Ayrlk Hüznü.mp3`
(2) -> `~\19 Çelik - Ayrilik Hüznü.mp3`
## Screenshot:  
You can watch the below video  
[Screen Record.zip](https://github.com/xbmc/xbmc/files/4605620/KQg45qZf5c.zip)
---
Please fix this issue instead of closing it.
Thanks.

**Comment by DaVukovic** [comment]
>Please fix this issue instead of closing it.

Please follow our template instead of ignoring it over and over again. You have been warned more than one time already.

Anyway...
If you are referring to a file which does not exist on your machine, how will Kodi (or any other app) will be able to play that file? Simply rename your mp3 at: 

`G:\Music\Cem Tuncer & Kerem Turkaydin\Bizim Hikaye (Orijinal Dizi Müzikleri), Vol. 1\`
from
`19 Çelik - Ayrilik Hüznü.mp3`
to
`19 Çelik - Ayrlk Hüznü.mp3`

and use the playlist method you mentioned first. 

For the future, please use the forums for such questions. You have been told to do so multiple times already. 

If I might have misunderstood your issue, please explain it better, provide the missing info (e. g. a debuglog) and I will happily re-open this issue again.

**Comment by xmha97** [comment]
I opened this issue because of the bug I saw in the Kodi
And I have no question to ask it on the forum.

---

Are you watch this video?
https://github.com/xbmc/xbmc/files/4605620/KQg45qZf5c.zip

---

Kodi writes incorrectly the name of the files in the playlist file so it can't play it.
Of course, this happens when the file name is Turkish.
I don't want to write the names of the files in English.

---

You may not understand what I say
because my English is weak :(

**Comment by DaVukovic** [comment]
Show us the following: 

- how is the file named on your hard disk? (screenshot)
- how is the file tagged? 
- are the missing characters in "Ayrilik" compared to "Ayrlk" an `i` or are they something else? because what I see in your video: 
![image](https://user-images.githubusercontent.com/7235787/81525057-b9faa000-9353-11ea-950d-1b930edad5a2.png)
- get us a full debuglog, as our template asks for that

**Comment by xmha97** [comment]
I using MusicBrainz Picard app tor tagging and renaming files and organize folders.
![MusicBrainz Picard](https://user-images.githubusercontent.com/23485114/81588517-e3581200-93cd-11ea-8697-acb75f16d97c.png)
## 1. Files Names
https://pastebin.com/raw/zMg0QNni
### Screenshot
![Windows File Explorer](https://user-images.githubusercontent.com/23485114/81527532-c12fa700-936f-11ea-8df3-318b6df95cee.png)
## 2. Files Tags
https://beta.musicbrainz.org/release/447adf89-1999-4b3b-a48a-45c5ddf8209b
### Screenshot
![MusicBrainz Picard](https://user-images.githubusercontent.com/23485114/81536955-acf4a580-9381-11ea-8c6d-6f5aa87516f5.png)
## 3. Differences
https://www.diffchecker.com/EklbhjFF
### Screenshot
![Diff Checker](https://user-images.githubusercontent.com/23485114/81591476-bc034400-93d1-11ea-909d-0d0d2ccc3853.png)

### Problem
The following characters are deleted:

ı
\u0131

ş
\u015f

İ
\u0130

## 4. Log File
https://pastebin.com/raw/kJwhsVbi

**Comment by DaVukovic** [comment]
Thanks. I wouldn't have closed your issue if you would have provided the info from the start. So please note that for the future ;)

re-opened

**Comment by the-black-eagle** [comment]
It's a known issue.  It occurs because Kodi does not save the playlist in UTF-8.  There was some discussion in the forum regarding this -> https://forum.kodi.tv/showthread.php?tid=348581

**Comment by DaveTBlake** [comment]
Closing this as actually it is not an issue but designed behaviour. The specification for .m3u files is that they contain text encoded in the local system's default **non-Unicode** encoding, so what Kodi does is reasonable and does not need fixing. 

Writing Kodi .m3u8 files is a new feature, and we don't handle feature requests on Githib.

**Comment by xmha97** [comment]
> 
> 
> Closing this as actually it is not an issue but designed behaviour. The specification for .m3u files is that they contain text encoded in the local system's default **non-Unicode** encoding, so what Kodi does is reasonable and does not need fixing.
> 
> Writing Kodi .m3u8 files is a new feature, and we don't handle feature requests on Githib.

Where should I submit this request? In the forum?

**Comment by DaveTBlake** [comment]
>Where should I submit this request? In the forum?

Yes, worth checking if a thread already exists too, but also do not be too hopeful. Kodi is developed totally by volunteers who work on whatever they choose to work on, so it will be a matter of one day someone (on the team or an interested passer by) with the skills and knowledge wanting to implement such a facility and doing so. It sounds ad-hoc, but it is what made Kodi
