### ISSUE TITLE
Freeze during playback

### ISSUE THREAD

**Issue by Flattermann78** [xbmc/xbmc#17869]
### Describe the bug
Here is a clear and concise description of what the problem is:

During playback of an IPTV stream in our local network, kodi freezes from time to time. It seems that leaving the video/going into the menu has a higher propapility of triggering the issue. But we also noticed the issue at times of no user interaction. 

The device is still available using SSH. Only the UI is frozen. Restart of the device has a strange behavior as the system messages are only showing up after some time but the frozen video stays as a frame. 

Device used is a RPi 4, up-to-date raspbian and kodi 18.6 git 20200310-283bece277.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

UI freeze. The expected behavior is a playback respectively a switch to the UI. 

## Actual Behavior

UI freeze, video freeze. System still responsive using SSH. 

## Possible Fix

I already turned off hw acceleration with no success. 

### To Reproduce

1. Start IPTV stream
2. Wait. Unfortunately no clear way to reproduce 
3.

### Debuglog

The debuglog can be found here:

http://paste.debian.net/1146801/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: buster 5.4.35-v7l+
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Unfortunately the logfile you provided is not a debuglog. Please enable debug logging in: 

settings -> system -> logging -> enable debug logging 

and get us a new log

Thanks in advance

**Comment by sarbes** [comment]
Closed due to no response.

**Comment by Flattermann78** [comment]
I tried to capture the issue but failed utterly. The issue still persists but is really rare and happens after a longer uptime. This leads to  a really large debug file which turns out to be to large to handle. Any help in logging would be much appreciated ....

**Comment by Flattermann78** [comment]
Sorry for the long delay. I was able to determine that the issue was created by a faulty network cable that impacted the integrity of the packets. Nonetheless, there seems to be an issue with the processing of the video packets as I'm still experiencing freezes of the video playback.

Most times, the issue occurs when terminating a stream (pressing the stop button) and the menu does not show up. The log files seems to be not helpful here so far. As the issue is hard (or not even possible) to be recreated with a single file so far, I like to ask if it is possible to have a logging only on the video player (I moved the folder already to a network share to be able to host larger debug files) limiting the amount of data in the log.

The standard log is here: http://paste.ubuntu.com/p/NQvcnH9dNN/ I stopt the video around 18:08 and rebooted 20 minutes later.

**Comment by DaVukovic** [comment]
1. not the latest kodi. We are at Kodi 18.9 (you are running Kodi 18.7) currently and the release of Kodi 19 is not far away. So there won't be any bug fixes for Kodi 18 anymore
2. still not a debuglog. Please add the following to your advancedsetting.xml: 
```
<advancedsettings>
  <loglevel hide="true">3</loglevel>
</advamcedsettings>
```
3. the logfile starts at 13th of January and ends at 30th of January. So the Pi seems to be running for 18 days 24/7. Did you ever think of simply rebooting it from time to time? A RPi is not a server which is meant to run 24/7. It can, but there might be issues (for example those you are facing). Let's do the maths....18 days * 24 hours = 432 hours before something strange happens. I would call that "rock solid".

>I like to ask if it is possible to have a logging only on the video player 
There is no specific logging for the video player. You have to enable debug logging either at the GUI (which will cause an overlay on the screen) or via advancedsettings, like I explained above where you have the option to disable the on-screen-overlay. Then we will have a pretty good verbose logging of what the video player does. 

Beside the debug logging, which you always need to enable, you are able to enable "component specific logging" to create a more verbose logfile for a specific component. Look at settings -> system -> logging. 

But seriously, I wouldn't spend too much time on that. Running this toy for 18 days 24/7 and opening about 70 streams sounds good to me. Maybe you get an OOM due to that long time. This is nearly impossible to reproduce. So my advice still is....simply reboot it and I highly guess your issue will be solved.
