### ISSUE TITLE
kodi - database case

### ISSUE THREAD

**Issue by thezoggy** [xbmc/xbmc#17946]
### Describe the bug
I moved my kodi sql backend from windows to linux (export, then import). When starting up kodi, it ignored the imported `myvideos1##` and instead create `MyVideos1##`. I discovered that the cause is due to mariadb storing things differently based on host os.

**windows**
* table names and database names are stored in _lowercase_ and compared in a case-insensitive manner.

**linux**
* table names, table aliases, and database names are compared in a case-sensitive manner.

I modified my custom.cnf and with `lower_case_table_names=1` it forced the windows behavior and everything worked as expected.

for more info:
https://mariadb.com/docs/reference/es/system-variables/lower_case_table_names/

While I know this is probably not a common scenario (going from case insensitive os to one that is), but has there been any talk on just using lowercase to maximize data portability?

--

## Expected Behavior
Moving the kodi db between os should just work?

## Actual Behavior
Depending on host os, you have different outcomes.

## Possible Fix
Using mariadb override you can force the behavior of the lowest common denominator

### To Reproduce
1. Create kodi db on windows
2. Export DB
3. Import DB on linux

### Debuglog
The debuglog can be found here: xxx

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.7

**Comment by DaVukovic** [comment]
I'm confused (but maybe that's just me). Let's try to clarify some things ;)

> I moved my kodi sql backend

If you say "sql" then I understand Kodis internal local database, where I highly guess you are talking about a MySQL/MariaDB backend stored on a different machine. 

>(export, then import)

How did you do that? 
Because, if you say "export and import" I understand that you exported Kodis database (which might also be a MySQL/MariaDB) to NFO-files which sit next to the video files on your sources. Importing means to me, that you set up your advancedsettings.xml to connect to another location like before (as you moved from a Windows host to a Linux host) and then import the information by adding the sources again and populating the DB in that way. 
So I guess you did some kind of mysqldump?

In any way, as there are configuration options how table names are handled (case-(in)sensitive), I don't see where this could be a Kodi bug. 

And tbh, this section is for bugs only. Talks have to be done at the forums. 

So please tell me in which way this might be a Kodi bug. 

Thanks

**Comment by thezoggy** [comment]
Hey Dav, I tried to make it pretty clear that it's not a kodi bug directly but just a portability issue when you use MySQL/mariadb and change os. It was to bring up the idea of just using lowercase names to make it easier (although it is an edge case that most probably don't run into).

**Comment by DaVukovic** [comment]
While I know that you one of the most active guys on the forums and I really appreciate the report and the idea behind it, I have to admit that the discussion you have started should be made at the forums instead. 

If Kodi is not able to handle that (using the same table-naming standard over all platforms) and if this is a configuration issue on the MySQL/MariaDB software side of things, then I would kindly ask to continue this discussion at the forums as it doesn't match here (bug reports only).

If Kodi is able to handle that, then this might be a valid bug. But I doubt it. 

So, with your agreement, I would like to close this one.
