### ISSUE TITLE
Long text in input dialog does not scroll correctly

### ISSUE THREAD

**Issue by w4kodi** [xbmc/xbmc#17977]
### Describe the bug
Here is a clear and concise description of what the problem is:

If an input dialog is opened (e.g. using `xbmcgui.Dialog().input()`) and the text is too long (either from the default value or from what the user enters), and the cursor is moved to the far right, it is not visible anymore.

The text does scroll, but not enough.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The text should have scrolled far enough to see the cursor.

## Actual Behavior

The text does scroll, but not far enough.

## Possible Fix

I think the problem has something to do with how the needed width for the text is calculated. This is done through `CGUILabel::CalcTextWidth()` method. Here is how I came to this conclusion:

I added some logging code to `CGUIEditControl::RecalcLabelPosition()`. Then I inserted some long text, scrolled all the way to the left and then moved the cursor to the right edge. This showed me that the width reported from `CGUILabel::GetMaxWidth()` did not quite match the text width reported from `CGUILabel::CalcTextWidth()` for the part of the text up to the cursor.

My first thought was that the width reported from `CGUILabel::GetMaxWidth()` was wrong (some padding issue or the like). What made me change my mind was a weird behaviour when scrolling to the far right, then left again. The cursor is not on the far left of the text box as soon as it starts scrolling: There is a certain distance between the left edge and the cursor. This distance slowly gets smaller if I continue scrolling left, until it finally hits the edge when arriving at the beginning of the text.

However, the code of `CGUIEditControl::RecalcLabelPosition` does not even use the reported max width from `CGUILabel::GetMaxWidth()`. Also, the gradual movement to the left indicates that the error is proportional to the width of the text, which is perfectly explained by a wrong font size or similar issues.

### To Reproduce

1. Open an input dialog, for example from the library via the context menu -> Manage ... -> Change name
2. Enter a very long text, so it exceeds the available width
3. The cursor is not visible; it has moved out to the right.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/4707741/kodi.2.log)

It was created including my additional logging code. I edited xbmc/guilib/GUIEditControl.cpp as seen [here](https://github.com/w4kodi/xbmc/commit/cf77095673eb4a99194bf5196e2c03c3a70b9388#diff-f49f0f1b67f54dd376c4f89392c64c1d). The last time this logging code is executed (line 2522 in the log file) the cursor was already invisible, so afterCursorWidth should be greater than maxTextWidth. The opposite is true.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Screenshot 1: Cursor is visible, at the right edge](https://user-images.githubusercontent.com/65495559/83353420-cec6c400-a352-11ea-8316-5d90d27a489c.png)

Now, I move the cursor one to the right:

![Screenshot 2: Cursor is no longer visible](https://user-images.githubusercontent.com/65495559/83353465-0c2b5180-a353-11ea-884c-846566b5ea73.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:

       $ uname -srvmpio
       Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Kodi version: Leia 18.6, Matrix (master: 139b2af53d1856cb62c8207d66202a3d436b5b2b)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
@sualfred Is this the same issue when trying to edit the plot using your Metadata addon?

**Comment by sualfred** [comment]
nope. we were talking about the missing option to wrap the edit control to multiple lines. like a editable textbox.

**Comment by ronie** [comment]
did a bit of testing and just in case it might help someone:
1. can't reproduce if i set the movie title to aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2. can reproduce if i set the movietitle to xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3. not reproduceable at all if i switch the font to 'arial based' instead of 'skin default'

tested on linux with kodi v19

**Comment by amacchietto** [comment]
I dug through the code a bit. The issue looks to be due to CGUITextLayout::GetTextWidth(const std::wstring&) computing the width based on the assumption that each character is taking the font styling from the font. However, the input label is calling CGUIEditControl::SetStyledText() which does not apply any font styling by default (font styles can be turned on and off on a per character basis using special tags).

The Arial font has no styling which is why the issue doesn't manifest. The Estuary skin font NotoSans_Regular uses FONT_STYLE_LIGHT which causes GetTextWidth to return a smaller width than what is rendered.

You can verify by replacing the call to SetStyledText(text) in CGUIEditControl::ProcessText with m_label2.SetTextW(text).
