### ISSUE TITLE
Libbluray full menu's and seamless branched UHD and Blurays cause glitches/audio drops and frame skips

### ISSUE THREAD

**Issue by maff76** [xbmc/xbmc#18031]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi there
i have found that when using the full menu system for bluray and UHD's if the movie is what i believe to be called seamless branched or multi-angle, when these changes happen varying results happen, with my nvidia set up i get frame skips and audio drop outs until the file change has settled usually a few seconds, with an intel setup i get horrid pixel coruption and audio drop outs, so far i have the in UHD format the the Phantom Menace, Attack of the Clones do this when ever a scene requires the subtitles to be displayed for alien speak, X-men Dark Pheonix also does this, and for standard blu-ray X-men Days of Future Past the rogue cut does it as you can play theatrical version or the rogue cut

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

the film should play flawless without interuption

## Actual Behavior

the film does not play seamless and interupts the enjoyment

## Possible Fix

i so wish i was smart enough

### To Reproduce

1. the only steps i have found so far is to play a full blu ray rip using menu's and the movie use the seamless branching method or multi angle will try and update the movie list as and when i find more
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/zorocexezu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

forum topic i opened for this https://forum.kodi.tv/showthread.php?tid=354431

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

i have tested all the affected movies using VLC as this was the only other player i knew that used Libbluray, there latest version was using libbluray 1.2.0 and all films played back flawless, i tried moving those files to kodi and renaming to version 1.1.2 although the movie played it would only get to the language selection screen and i couldn't use the keyboard to progress, i then hunted down a version of VLC that used the same libbluray as kodi this was version 3.08 and again the movies played flawless with no skips or audio drop outs so it looks like a problem with Kodi and not libbluray

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10 2004
 - Kodi version: v19 nightly, v19 HDR branch and V18 coreelec branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
I'm 90% sure I found the root cause of this: sound/glitches and unstable (both video and Blu-Ray menus) until several seconds elapses to stabilize. The cause is related to file chunk size used in SMB.

Due a bug when is not used FileCahe file read chunk size (buffer) is only of 6144 bytes when using SMB.
And for Blu-Ray folders (BDMV) File cache is disabled even with buffer mode = 1 (cache all).

The sum of two things causes low chunk size that is insufficient for high bitrate reads through network (even is 1Gbps) and causes high CPU load due many small reads every second. 

This only happens in full Blu-Ray and not MKV because for MKV is always used file cache by default.

Chunk size should be 128 * 1024 bytes (same as NFS). 
In Android seems is used 64 * 1024 for SMB that is also fine.

**Comment by maff76** [comment]
thank you for looking into this, can't wait to test it

**Comment by thexai** [comment]
Omega test build:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20230306-d4bb827e-SMB-chunk-size-x64.exe

**Comment by maff76** [comment]
HI thexai

just had a quick test with the phamtom menace, it is a massive improvement but still get a tiny video pause and audio blip when the seamless branching happens and changes file but recovers instantly and no artifacts, can i ask why caching is completely disabled for rips?

**Comment by thexai** [comment]
Note that nothing directly related to seamless branching has been changed, not even with libbluray. These are general changes that improves SMB performance on all types of files. It is more noticeable in Blu-Ray only because FileCache is not used, the reason is that a Blu-Ray is not just one file but a set of hundreds or even thousands of them (.mpls, .clpi, .m2ts, etc.). 

FileCache is only intended to read a single file sequentially. i.e with seamless branching several .m2ts are played in a different order depending on the cut or angle chosen.

> just had a quick test with the phamtom menace, it is a massive improvement

So I understand that it is worth the SMB change and the backport to Nexus as a bug fix.  :)

For specific seamless branching issues, it might be worth testing without using the network (local files) to rule out network latency. 

In any case, in my tests I had cuts/glitches in the menus and when skipping from chapter or scene, etc. (even on disks without seamless branching) and all this has improved a lot.
