### ISSUE TITLE
Subtitle with overlapping timestamp show/disappear incorrectly

### ISSUE THREAD

**Issue by Doraemoe** [xbmc/xbmc#18298]
### Describe the bug
Subtitle with overlapping timestamp show/disappear incorrectly.

e.g. The following subtitle has a line shown on screen at upper right between 1s to 9s. In addition, it has another subtitle shown at normal position every 2 seconds between 0 to 10s. When Kodi plays it, the subtitle on the upper right will disappear between 6s to 8s while it should be on screen all the time. This has been tested on Kodi 18.8 Windows, macOS and CoreELEC.

```
[Script Info]
Title: [Test]
Original Script: Tester
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
YCbCr Matrix: TV.709
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,50,&H00FFFFFF,&HF0FFFFFF,&H007B66D0,&H808060E3,-1,0,0,0,100,100,0,0,1,2,1.5,2,10,10,13,1
Style: TOP,Candara,40,&H00FFFFFF,&HF0FFFFFF,&H00169CE1,&HF0FFFFFF,-1,0,0,0,100,100,0,0,1,1.5,0,9,10,12,8,128

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:09.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:08.00,0:00:10.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
```

## Expected Behavior

The subtitle on the upper right should show between 1s to 9s without disappearing.

## Actual Behavior

The subtitle on the upper right will disappear between 6s to 8s

## Possible Fix

I was suspecting this is caused by outdated [libass](https://github.com/libass/libass) library as [mpv](https://github.com/mpv-player/mpv) shows the subtitle correctly (which uses same libass library to render ass subtitle as Kodi but from master branch). I tried to compile Kodi with libass from master branch but the result is the same. I cannot guarantee I compiled Kodi with correct libass library correctly though.

### To Reproduce

1. Save the above subtitle to a file named `test.ass`.
2. Play any video longer than 10s with the test subtitle file.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ehiyudeqiw.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi test video at 7s, subtitle on top is not showing:
![kodi](https://user-images.githubusercontent.com/1129569/90388352-024ff980-e0cb-11ea-8e84-5a929e86fad8.png)

mpv test video at 7s, subtitle on top is showing:
![mpv](https://user-images.githubusercontent.com/1129569/90388365-07ad4400-e0cb-11ea-9874-35f6cc67a604.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, macOS Catalina, CoreELEC
 - Kodi version: 18.8

**Comment by enen92** [comment]
Hey @Doraemoe,

I took a look into this issue. The problem is not related to the libass version but seems to be the way kodi orders the subtitle overlay but rather the call to sort(). If your comment this line, the subtitle events will be displayed correctly:

https://github.com/xbmc/xbmc/blob/770c691bfeea88d561b39d2e38348ac434db3adc/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSSA.cpp#L54

I'll try to figure out what is going wrong in the sort logic. This was added and not changed 11 years ago :)

**Comment by enen92** [comment]
@Doraemoe after a a lot of wasted time I found the culprit. In addition to avoid touching the overlays start and stop pts (the block of code that was removed) we need also to ensure only a single overlay is passed to libass at a single instant of time. This is due to the fact that libass, when generating the overlay images, assigns a new one and signals a change if the new image is different from the last one. As we are rendering 2 overlays (sub from 0-2 and sub from 1-9), we are in fact calling libass twice: this causes the second image (that contains the top and bottom subtitles) to overlay over the previous image (that contains only the bottom subtitle). Hence, they appear duplicated.

The below patch solves the issue but I don't like neither the implementation nor the place for it:

```
From 90ebe8f4e67e43f1c35ee3dd7b1f131c518aafab Mon Sep 17 00:00:00 2001
From: enen92 <92enen@gmail.com>
Date: Tue, 25 Aug 2020 11:31:14 +0100
Subject: [PATCH 1/1] Ass temp fix

---
 .../cores/VideoPlayer/DVDOverlayContainer.cpp | 20 -------------------
 .../cores/VideoPlayer/VideoPlayerSubtitle.cpp |  5 ++---
 .../VideoRenderers/OverlayRenderer.cpp        | 17 ++++++++++++++++
 3 files changed, 19 insertions(+), 23 deletions(-)

diff --git a/xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp b/xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp
index ce9e559ccd..7c9e952db8 100644
--- a/xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp
+++ b/xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp
@@ -23,26 +23,6 @@ void CDVDOverlayContainer::Add(CDVDOverlay* pOverlay)
   pOverlay->Acquire();

   CSingleLock lock(*this);
-
-  // markup any non ending overlays, to finish
-  // when this new one starts, there can be
-  // multiple overlays queued at same start
-  // point so only stop them when we get a
-  // new startpoint
-  for(int i = m_overlays.size();i>0;)
-  {
-    i--;
-    if(m_overlays[i]->iPTSStopTime)
-    {
-      if(!m_overlays[i]->replace)
-        break;
-      if(m_overlays[i]->iPTSStopTime <= pOverlay->iPTSStartTime)
-        break;
-    }
-    if(m_overlays[i]->iPTSStartTime != pOverlay->iPTSStartTime)
-      m_overlays[i]->iPTSStopTime = pOverlay->iPTSStartTime;
-  }
-
   m_overlays.push_back(pOverlay);

 }
diff --git a/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp b/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp
index bdb2f718ad..18ef164ffc 100644
--- a/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp
+++ b/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp
@@ -193,7 +193,7 @@ void CVideoPlayerSubtitle::Process(double pts, double offset)
       m_pSubtitleFileParser->Reset();
     }

-    if(m_pOverlayContainer->GetSize() >= 5)
+    if (m_pOverlayContainer->GetSize() > 0)
       return;

     CDVDOverlay* pOverlay = m_pSubtitleFileParser->Parse(pts);
@@ -215,7 +215,6 @@ void CVideoPlayerSubtitle::Process(double pts, double offset)

 bool CVideoPlayerSubtitle::AcceptsData() const
 {
-  // FIXME : This may still be causing problems + magic number :(
-  return m_pOverlayContainer->GetSize() < 5;
+  return m_pOverlayContainer->GetSize() == 0;
 }

diff --git a/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp b/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp
index 2cf59dc7e2..13cba96b38 100644
--- a/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp
+++ b/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp
@@ -74,6 +74,23 @@ void CRenderer::AddOverlay(CDVDOverlay* o, double pts, int index)
   SElement   e;
   e.pts = pts;
   e.overlay_dvd = o->Acquire();
+
+  if (e.overlay_dvd->IsOverlayType(DVDOVERLAY_TYPE_SSA))
+  {
+    auto currentOverlay = static_cast<CDVDOverlaySSA*>(e.overlay_dvd);
+    for (auto it = m_buffers[index].begin(); it != m_buffers[index].end(); ++it)
+    {
+      if (it->overlay_dvd->IsOverlayType(DVDOVERLAY_TYPE_SSA))
+      {
+        auto assOverlay = static_cast<CDVDOverlaySSA*>(it->overlay_dvd);
+        if (assOverlay->m_libass == currentOverlay->m_libass)
+        {
+          m_buffers[index].erase(it);
+          break;
+        }
+      }
+    }
+  }
   m_buffers[index].push_back(e);
 }

--
2.24.0
```

Personally I think the correct place to fix this is within the ASS parser to ensure that when we generate the overlay collection they are in fact sequential. We need to change the start and stop pts of some of the items so that we can create something similar to a timeline, with no overlapping overlays. That way the overlay collection time will appear as if they were continuous.
