### ISSUE TITLE
Some mp4 files won't play when connected by FTP

### ISSUE THREAD

**Issue by Sopor** [xbmc/xbmc#18379]
### Describe the bug
Here is a clear and concise description of what the problem is:

When connected by FTP it seems that some mp4 files won't play in Kodi 18.8/19.0. If i play them locally or over LAN with Kodi 18.8/19.0 all mp4 files works. I have successfully played the non-working mp4 files in VLC and Media Player Classic Homecinema and even the old Media Player Classic will play the files.

If there was some compatibility issues with these mp4 files they shouldn't play at all in Kodi, but they work if i don't use the FTP protocol.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should play the video as it do when not connected by FTP.

## Actual Behavior

When i click on the file i only get a black screen and after 3 seconds the video time stops and it continues to show a black screen until i press stop.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/wocibotugo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

As you can see in the log file i'm running AUTH=TLS and i use TLS v1.2 with explicit encryption.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 18.8/19.0 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Does it work if you disable hardware acceleration?

**Comment by Sopor** [comment]
No, exact same happens.

**Comment by arnova** [comment]
This is your problem:

`2020-09-07 00:07:23.611 T:11640 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-09-07 00:07:23.625 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 867609986
2020-09-07 00:07:23.690 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 915873324
2020-09-07 00:07:23.751 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 1156794741
2020-09-07 00:07:23.815 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 32359
2020-09-07 00:07:23.891 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 48214745
2020-09-07 00:07:23.961 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 96413059
2020-09-07 00:07:24.025 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 144676910
2020-09-07 00:07:24.086 T:20652   DEBUG: CurlFile::CReadState::Connect - Resume from position 385679405
2020-09-07 00:07:24.118 T:11640 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer`

Your MP4-files probably have very bad A/V sync or something since Kodi is seeking "to death". This can't be fixed/worked around for ftp (and http etc.), you need to fix the files themselves.

**Comment by DaVukovic** [comment]
If that's the case (not saying it isn't ;) ), @Sopor can you please confirm that the same happens if you play the same file locally from the Kodi machine in use?

If the file is the problem it shouldn't matter where it is played from.

**Comment by arnova** [comment]
> If that's the case (not saying it isn't ;) ), @Sopor can you please confirm that the same happens if you play the same file locally from the Kodi machine in use?
> 
> If the file is the problem it shouldn't matter where it is played from.

That's not correct. Specifically streamed filesystems like ftp/http/webdav can't handle files with eg. bad a/v sync. So even if the files play fine locally or from smb/nfs, it doesn't mean they also play properly from ftp. The fact that you see also those "Connect - resume" messages means that there's excessive seeking causing the play buffers to never fill up.

**Comment by Sopor** [comment]
If i play the mp4 files locally or with smb it will play as any other normal file. I have tested it from different computers too, but it will not play when using ftp.

If i convert the files to mkv with MKVToolNix i can play them over ftp. I was hoping to avoid that step, but if something is wrong with the files i have to do this extra step to get them to work.

**Comment by arnova** [comment]
Unfortunately remuxing (in your case converting the files with MKVToolNix) is the only way to fix it. There isn't much we can do about it.

**Comment by Sopor** [comment]
I understand! Thanks anyway ...

**Comment by Sopor** [comment]
It seems that almost none DVD iso will play over FTP. That can't be the same issue as mentioned here? All iso files are in STORED multi archive RAR files.

**Comment by Dnkhatri** [comment]
> It seems that almost none DVD iso will play over FTP. That can't be the same issue as mentioned here? All iso files are in STORED multi archive RAR files.

It's the same issue ftp protocol is not designed for your use case.

**Comment by Sopor** [comment]
But all ISO files can't have sync issues as arnova explained.

**Comment by arnova** [comment]
It makes sense that compressed stuff over ftp/http/etc. doesn't work properly. Again: not much we can do about it as only huge caches could work around this issue probably (which isn't going to happen). Please also note: ISO != MKV/MP4/AVI

**Comment by Sopor** [comment]
> Updated: Yes, it will play if i extract the ISO file

I mean that if i extract the ISO file from the RAR files i can play the ISO file, so i assume this is another vfs.rar issue and i have reported it there.

**Comment by Sopor** [comment]
@arnova It is working in Kodi 17.6, so why shouldn't it work in Kodi 18 and 19?
