### ISSUE TITLE
Deal breaker

### ISSUE THREAD

**Issue by crogonint** [xbmc/xbmc#18484]
## Bug report
After the recent update, Kodi CLAIMS that it uninstalled 742 add-ons and moved them all to the repository, and that if I want them I have to reinstall them from there.

## Expected Behavior
Don't ask the end user to reinstall 742 add-ons

## Actual Behavior
End user says: GO TO HELL!! I'll uninstall the software first.

## Possible Fix
Put them back.

### To Reproduce
1.  Install the update

## Additional context or screenshots (if appropriate)
I'm not even going to start Kodi. Please tell me you didn't ACTUALLY uninstall all of the end user add-ons. If you did, I'm done. I'm not doing all of that again. Please respond and verify if all of my add-ons have been uninstalled, and whether or not there is a way to revert. If there is no way to revert, I'm done.

### Your Environment
Win7 64x
 - Kodi version: latest

**Comment by fuzzard** [comment]
No idea about your addons without a log.

You need to provide more information. You updated, from what version to what version.

**Comment by enen92** [comment]
Due to the number of installed addons I guess the big majority come from outside the kodi repo. If that's the case, repo maintainers have to update their addons to python3. There are also ways to limit the list of addons to serve between kodi versions (see https://github.com/xbmc/xbmc/pull/18371).
Addons in the official repo should migrate just fine (if a py3 compatible version is already available). Unfortunately there isn't much we can do. Please either provide a log file or bring the issue to the external repo maintainers and/or addon developers.

**Comment by crogonint** [comment]
Hey, sorry, for some reason, github didn't notify me of these replies. Tell me how to get which log you need, I'd be more than happy. Especially if this isn't normal.

**Comment by DaVukovic** [comment]
Simply load the newest Kodi 18 version which is available. Actually this is Kodi 18.8 and there will not be another one as all focus now is on Kodi 19. You can also download a Kodi 19 nightly from here: 

http://mirrors.kodi.tv/nightlies/windows/win64/master/

and test that. 

For your test (and I guess you update from let's say Kodi 18.6 to Kodi 18.7) you can get any Kodi 18 version from here: 

http://mirrors.kodi.tv/releases/windows/win64/

For the log file, start reading here: https://kodi.wiki/view/Log_file

**Comment by crogonint** [comment]
What am I supposed to test exactly?? I thought you wanted a log of somthing?

Look, the last update told me that it archived all of the add-ons. I just want to know if that's an actual thing that happens. If it is, I want to revert. If I can't, I'm done. I am NOT going through all of that setup crap again.

**Comment by crogonint** [comment]
@enen92 Could you unclose this so I can get an official response please?

**Comment by lrusak** [comment]
Use the forum for support requests.

**Comment by crogonint** [comment]
SUPPORT?? I'm not asking for support! You know what? Go @#$% yourselves. I've had it up to my eyeballs with incompetant developers that can't tell their @$$hole from a hole in the ground.

I was bringing up an apparently catestrophic issue with an update, and all I get is flak. Repeatedly.

I'm out.

Good luck! 

NOT!

**Comment by garbear** [comment]
I'm afraid that you've violated our [code of conduct](https://github.com/xbmc/xbmc/blob/master/docs/codeofconduct/CodeOfConduct.md), which is why you got the "forum support" response. A team member instructed you on the next step:

> Please either provide a log file or bring the issue to the external repo maintainers and/or addon developers.

A debug log is the precise thing they need to better understand the problem. Please respect the developers by working with us to solve your problem.
