### ISSUE TITLE
legacy smb implementation still at the gui

### ISSUE THREAD

**Issue by CvH** [xbmc/xbmc#18840]
### Describe the bug
Here is a clear and concise description of what the problem is:

When adding a smb networks share at Kodi it still shows the the "Windows Network Share" option that is not working with an recent system. So as user you need to know that this option is not working and they need to add it with "add network Location".
![image](https://user-images.githubusercontent.com/1355173/99901798-aabcbd80-2cb9-11eb-8f45-15687f4ab6dc.png)

The out of the box experience should just work and should not depend at highly insecure and outdated stuff that is not existing anymore at any recent system.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If you select the windows network you should be able to add windows network shares.

## Actual Behavior

If you select the windows network you can't add windows network shares.

## Possible Fix

- Rename that option to make clear that is just for the legacy SMB1 protocol nobody should use today.
- Remove that option completely
- maybe other ideas ?

### To Reproduce

1. add a network share
2. select windows network

### Debuglog

The debuglog can be found here:
no debuglog needed

### Screenshots 
Here are some links or screenshots to help explain the problem:

screenshot above

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

-

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows/LE10
 - Kodi version: 19.0 Beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by jjd-uk** [comment]
While we can't browse SMB2/3 then yes this should probably be hidden. Not sure it should be removed in code as browsing SMB2/3 shares is possible with WS-Discovery, however the problem is neither Samba or Libsmb2 currently support WS-Discovery. Samba did receive a patch to add WS-Discovery 5 years ago, see https://bugzilla.samba.org/show_bug.cgi?id=11473 but it seems no one the Samba team are progressing it.

If anyone is thinking of looking at this then some further background I personally found useful https://fitzcarraldoblog.wordpress.com/2020/06/16/using-ws-discovery-to-enable-windows-10-to-browse-smb-shares-in-my-home-network-of-linux-computers/

There are also some daemons that support WS-Discovery, 2 examples
https://github.com/christgau/wsdd
https://github.com/Andy2244/wsdd2

**Comment by jjd-uk** [comment]
Reopened as referenced PR was for Windows only. WS-Discovery implemention or another solution is still needed for other platforms to enable browsing of SMB shares again, if not then maybe this needs to be hidden on the other platforms so that only Windows has this option.
