### ISSUE TITLE
"Play using..." always select default player for emby source

### ISSUE THREAD

**Issue by strech345** [xbmc/xbmc#18868]
### Describe the bug

I add a external Player. If i open the context menu on a video from emby source and select `Play using...` there is the internal and the external player. But if i choose the external, the internal player will open the video. 
```
<playercorefactory>
	<players>
		<player name="MPC-HC" type="ExternalPlayer" audio="false" video="true">
			<filename>C:\Program Files\MPC-HC\mpc-hc64.exe</filename>
			<args>"{1}" /fullscreen /close</args>
			<hidexbmc>true</hidexbmc>
		</player>
	</players>
</playercorefactory>
```

if i add the rule 

```
	<rules action="prepend">  
		<rule video="true" player="MPC-HC"/>  
	</rules>
```

the videos will always be opend by externel, also if i choose internal player.
This only happend for emby source. Smb sources workes like it should.

So always the default player is choosen

### To Reproduce
1. install emby for kodi
2. add external player
3. open emby video by using the `play using...` button

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/himerazeju.kodi
it shows that a external player (default) was used but internal was choosen by me.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64bit 
 - Kodi version:18.9

**Comment by strech345** [comment]
@xbmc-gh-bot sent in error

**Comment by teletcl** [comment]
I think that must be some issue with `xbmc.Player().play()` method, because for `setResolvedUrl()` works.
So, if we replace code:
```
xbmc.Player().play(link)
```
with
```
listitem = xbmcgui.ListItem(path=link)
xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, listitem)
```
External Player works.


Maybe, we have to do also some other thinks in code, like:
```
list_item.setProperty('IsPlayable', 'true')
```
Can developers check why `xbmc.Player().play()` method does not call External Player on demand?

**Comment by enen92** [comment]
Plugins should not use `xbmc.Player().play()` - that interface is for scripts which design its own interface with a custom videocontrol in custom windows - this is by design.
Instantiating external players when initializing the `Player()` used to be an option but was removed long ago as it caused all sort of issues. If you want your plugin to be integrated with the Kodi environment (external players, watched status, context menus, etc) you should use the `setResolvedUrl`
