### ISSUE TITLE
JSON-RPC: Property hastimer of PVR.GetBroadcastDetails is set to always false

### ISSUE THREAD

**Issue by b-jesch** [xbmc/xbmc#18969]
### Describe the bug
Here is a clear and concise description of what the problem is:

Property hastimer of PVR.GetBroadcastDetails is always false, even if a timer for this broadcast is set. This behaviour is 
 independent from type of timer (recording or reminder).

### To Reproduce

1. Pick up a valid broadcastid and call PVR.AddTimer or set a timer or reminder within Kodi (EPG timeline or similar)
2. call PVR.GetBroadcastDetails with the broadcastid and parameter hastimer
3. hastimer is always set to false

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.3 LTS
 - Kodi version: 19.0-BETA2 (18.9.821) Git:20201221-c9da8b4d98 Media Center Kodi

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
Well, some properties of broadcasts were removed from the core for v19, but I obviously forgot to remove them from the RPC API. Sorry for that.

Code:

  value["hastimer"] = false; // compat
  value["hastimerrule"] = false; // compat
  value["hasrecording"] = false; // compat
  value["recording"] = ""; // compat

Those properties should never have been added to the API, because it is conceptually wrong that a broadcast knows something about timers and recordings.

Have to think how an actually working replacement could be implemented if people need that, but for sure timer/recording related information will not be added back to broadcasts.

**Comment by b-jesch** [comment]
Ok. It is sufficient for me if the associated broadcast ID is available again in the timer properties: https://github.com/xbmc/xbmc/issues/18960

Feel free to close this issue.
