### ISSUE TITLE
v19 Beta 2 - Kodi IEC packer stopped working on Fire TV Stick 4K

### ISSUE THREAD

**Issue by muncrief** [xbmc/xbmc#18985]
### Describe the bug
Here is a clear and concise description of what the problem is:

I'd been running both v19 beta 1 and 2 on my Fire TV Stick and they worked perfectly until Thursday evening. But then there was no passthrough sound, and I discovered it's because the Kodi IEC packer no longer works. If I set "Audio passthrough device" to "AudioTrack (RAW), Android IEC packer" it works as it did in Kodi 18. So I don't have the option for DTS passthrough, just Dolby Digital. 

By the way, I also run Kodi v19 b2 on my Nvidia Shield Pro 2019 in the living room and the Kodi IEC packer still works fine, so I expect Amazon updated the Fire TV Stick OS, because as I said everything worked great until Thursday.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I should be able to set "Audio passthrough device" to "AudioTrack (IEC), Kodi IEC packer" and Dolby Digital and DTS passthrough should work.

## Actual Behavior

When I set "Audio passthrough device" to "AudioTrack (IEC), Kodi IEC packer" all video sound is muted.

## Possible Fix

Setting "Audio passthrough device" to "AudioTrack (RAW), Android IEC packer" enables Dolby Digital passthrough, but not DTS passthrough.  Non-Dolby Digital audio is output as PCM. However that's the way it used to work in Kodi 18. 

### To Reproduce

1.  Using a Fire TV Stick 4K set "Audio passthrough device" to "AudioTrack (IEC), Kodi IEC packer"
2. Try to play video. all sound will be muted.

### Debuglog

The debuglog can be found here:

https://mega.nz/file/FD4EBCQC#1_tNi2rn8oPpY2ekR9-yJMd763dbXqXtGXRdj1FnGgQ

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Fire TV Stick 4K OS
- [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Fire TV Stick 4K OS
 - Kodi version:
Kodi version 19 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Pentaphon** [comment]
Lots of discussion about this from this post onward: https://forum.kodi.tv/showthread.php?tid=336151&pid=2993133#pid2993133

**Comment by fritsch** [comment]
File a bug with amazon, they broke it - most likely by intention.

**Comment by fritsch** [comment]
As a workaround: Use v19 (beta), here you can choose the RAW method instead of the IEC one. Alternatively the unofficial fritschfiretv version was used to test the v19 beta code and has the ability to switch to the RAW version again.

It is personally beyond me, why their FW update would be able to break it. IEC Audiotrack format is just writing 16 bit Integers to the audio sink in exclusive mode with digital bits set. Therefore for me it seems, that they wanted to stop especially DTS and DTS-HR passthrough, which they don't sell nor support.

In any case: Kodi cannot fix the firmware, especially not if they broke standard Android audio functionality.

**Comment by fritsch** [comment]
Looking with adb:
[quote]
12-27 08:02:23.245   282 13393 W AudioFlinger: pause because of UNDERRUN, framesReady = 21600,minFrames = 4096, mFormat = 0xd000000
12-27 08:02:23.288   282 13393 W AudioFlinger: pause because of UNDERRUN, framesReady = 24960,minFrames = 4096, mFormat = 0xd000000
12-27 08:02:23.304 12845 12867 V Kodi    : static bool CXBMCApp::EnableWakeLock(bool): true
12-27 08:02:23.306   608  1510 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:10166 PID:12845 Tag:org.xbmc.kodi
12-27 08:02:23.308  1166  1557 D Vizzini:MediaSessionLib.MediaSessionControllerStateMgr: Playback State Changed org.xbmc.kodi
12-27 08:02:23.308   733   956 V Avrcp   : MediaController playback changed: PlaybackState {state=3, position=-98, buffered position=0, speed=1.0, updated=336713856, actions=-1, custom actions=[], active item id=-1, error=null}
12-27 08:02:23.309  1166  1557 D Vizzini:MediaSessionLib.MediaSessionControllerStateMgr: Playback State Changed org.xbmc.kodi
12-27 08:02:23.309  1166  1557 D Vizzini:MediaSessionLib.MediaSessionControllerStateMgr: Playback State Changed org.xbmc.kodi
12-27 08:02:23.331   282 13393 W AudioFlinger: pause because of UNDERRUN, framesReady = 27360,minFrames = 4096, mFormat = 0xd000000
12-27 08:02:23.374   282 13393 W AudioFlinger: pause because of UNDERRUN, framesReady = 30336,minFrames = 4096, mFormat = 0xd000000
12-27 08:02:23.417   282 13393 D AudioTunnelStreamOut: setVolume() left 1.12, right 1.12
12-27 08:02:23.417   282 13393 E AudioTunnelStreamOut: setVolume() Invalid left 1.12
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processPayloadQueue() Pure PCM Payload
12-27 08:02:23.417   282 13393 D AudioTunnelStreamOut: processHeaderBlock() Error, mCurrentPtsInfo.size()=0, Then No reference info
12-27 08:02:23.417   282 13393 I AudioTunnelStreamOut: getFirsHwSyncBlock() ret -22, Header-HW-Block:kId 0, kAttri 0, kPts 0, kStart 0, kEnd 0
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: writeMiddleProcess() No 1st PTS in buffer(), give a little chance
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processPayloadQueue() INVALID tailBlk.kAttri = 3
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processHeaderBlock() Abnormal: haderBlock.kAttri = 3, Happen deteckQueue.size() > 1
12-27 08:02:23.417   282 13393 D AudioTunnelStreamOut: write() INVALID payload
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processPayloadQueue() INVALID tailBlk.kAttri = 3
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processHeaderBlock() Abnormal: haderBlock.kAttri = 3, Happen deteckQueue.size() > 1
12-27 08:02:23.417   282 13393 D AudioTunnelStreamOut: write() INVALID payload
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processPayloadQueue() INVALID tailBlk.kAttri = 3
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processHeaderBlock() Abnormal: haderBlock.kAttri = 3, Happen deteckQueue.size() > 1
12-27 08:02:23.417   282 13393 D AudioTunnelStreamOut: write() INVALID payload
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processPayloadQueue() INVALID tailBlk.kAttri = 3
12-27 08:02:23.417   282 13393 W AudioTunnelStreamOut: processHeaderBlock() Abnormal: haderBlock.kAttri = 3, Happen deteckQueue.size() > 1
12-27 08:02:23.417   282 13393 D AudioTunnelStreamOut: write() INVALID payload
12-27 08:02:23.418   282 13393 W AudioTunnelStreamOut: processPayloadQueue() INVALID tailBlk.kAttri = 3
12-27 08:02:23.418   282 13393 W AudioTunnelStreamOut: processHeaderBlock() Abnormal: haderBlock.kAttri = 3, Happen deteckQueue.size() > 1
12-27 08:02:23.418   282 13393 D AudioTunnelStreamOut: write() INVALID payload
12-27 08:02:23.418   282 13393 W AudioTunnelStreamOut: processPayloadQueue() INVALID tailBlk.kAttri = 3
12-27 08:02:23.418   282 13393 W AudioTunnelStreamOut: processHeaderBlock() Abnormal: haderBlock.kAttri = 3, Happen deteckQueue.size() > 1
12-27 08:02:23.418   282 13393 D AudioTunnelStreamOut: write() INVALID payload
[/quote]

It seems that they broke not IEC by itself, but the switching to the RAW output. As you see above, they try to parse the blocks which indicates that they did tag the output, but then don't properly switch.

[quote]
12-27 08:02:23.010   282 12239 D AudioFlinger: min buf count is limited to 2 times HAL buf
12-27 08:02:23.012 12845 12878 V Kodi    : Debug Print: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 48000 format: AE_FMT_S16LE (AE) method: IEC (PT) stream-type: STREAM_TYPE_DTSHD_CORE min_buffer_size: 30800 m_frames: 1925 m_frameSize: 4 channels: 2
12-27 08:02:23.015   282 13393 I AudioFlinger: AudioFlinger's thread 0xa807e000 ready to run
12-27 08:02:23.016   608  5826 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.016   282 13393 D AudioTunnelStreamOut: +standby() mStreamState SETUP
12-27 08:02:23.016   282 13393 D AudioTunnelStreamOut: -standby() mStreamState SETUP
12-27 08:02:23.017   608  5826 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.022   608  5826 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.022   282 13393 D DolbyAudioHwDeviceProxy: setActiveDevice(0xa9859000): device(0x400) mActiveDevice(0x400)
12-27 08:02:23.022   282 13393 D DolbyAudioHwDeviceProxy: createAudioPatch(0xa9859000) patch created from mix port to device 0x400 with handle 6. 2 patches active
12-27 08:02:23.023   608 20803 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.025   282   344 I AudioFlinger_fosExt: setParameters_fosExt_setParamWithIoHandle, ioHandle: 22, keyValuePairs: routing=1024
12-27 08:02:23.027   608  4664 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioIn
12-27 08:02:23.028   608 20803 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioIn
12-27 08:02:23.031   282 13393 W AudioFlinger: pause because of UNDERRUN, framesReady = 0,minFrames = 4096, mFormat = 0xd000000
12-27 08:02:23.032 12845 13379 I MediaCodecLogger: updateFormatChanged width = 1920 height = 800
12-27 08:02:23.036 12845 13379 I MediaCodecLogger: updatePTSTime [HW.video.avc] First PTS after Flush or reset = 0
12-27 08:02:23.036 12845 13379 I MediaCodecLogger: [ASAP] HW.video.avc Got First Frame Ready 336713585
12-27 08:02:23.050   608  4664 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.059   608  5826 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.061   608  5826 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.061   608  5826 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.063   608  1558 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.063   608  1558 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.064   608   919 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.065   608   919 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.066   608  4664 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.067   608   919 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.069   608 20803 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.070   608 20803 I AmazonPowerManagerVendorCallback: Wakelock released UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.071   608  1510 I AmazonPowerManagerVendorCallback: Wakelock acquired UID:1041 PID:0 Tag:AudioDirectOut
12-27 08:02:23.074   282 13393 W AudioFlinger: pause because of UNDERRUN, framesReady = 9120,minFrames = 4096, mFormat = 0xd000000
[/quote]

It seems they don't come out of the underrun while having plenty enough frames to do so. 9120 > 4096 ...

So from my POV, you can only hope that someone of them has interest in fixing this functionality for an upcoming release.

**Comment by fritsch** [comment]
Reopening it. Please link upstream bugs for amazon here: e.g. exoplayer, amazon ticket.

If you find a working player, which uses official android api and still works also welcome.

**Comment by muncrief** [comment]
> Reopening it. Please link upstream bugs for amazon here: e.g. exoplayer, amazon ticket.
> 
> If you find a working player, which uses official android api and still works also welcome.

I want to be clear that both v19 betas work perfectly on my Nvidia Shield Pro 2019 @fritsch. They also work on Linux and Windows 10.

So among 4 platforms it's only the Fire TV Stick that stopped working, and since Fire OS is essentially a rogue Android distribution, and not officially supported by Kodi, it's really incumbent on Amazon not to break basic APIs. On the other hand I know a lot of users are on Fire TV Sticks so it's a bit of a dilemma.

As for me personally I'm planning on getting another Shield within a few months because I'm tired of running out of application memory and having to live with partial passthrough. I've spent so much money on so many Fire TV Sticks over the years that I realized buying a Shield is actually cheaper in the long run.

**Comment by fritsch** [comment]
Amazon has broken it with their latest firmware, it worked 100% fine before. I used a Firetv 4K to implement v19 audio enhancements. There is absolutely nothing I can do about that.

Kodi has no workarounds for Shield or other devices in code. We only use what Audiotrack offers. Windows and Linux use different APIs obviously in kodi's Sink Implementation.

**Comment by muncrief** [comment]
> Amazon has broken it with their latest firmware, it worked 100% fine before. I used a Firetv 4K to implement v19 audio enhancements. There is absolutely nothing I can do about that.
> 
> Kodi has no workarounds for Shield or other devices in code. We only use what Audiotrack offers. Windows and Linux use different APIs obviously in kodi's Sink Implementation.

I understand and agree that Kodi can't go back to the old days of hacks and workarounds for every device under the sun @fritsch. I think those of us who want to run Kodi on Android are going to have to abandon Fire OS, and as I said earlier it's cheaper to get a Shield or some other official Android device in the long run anyway.

In retrospect I shouldn't have filed a bug for an unsupported platform in the first place, but at the time I wasn't certain what the issue was and since Kodi is in beta I erred on the side of reporting the issue. But now that's in been confirmed as a Fire OS problem this bug should probably be closed.

Thank you for taking the time to look into it, and while I have a developers ear I just want to say that everyone who works on Kodi is doing an amazing job. I sincerely appreciate the many years of tireless effort that have made Kodi the amazing entertainment center software that it is today.

**Comment by fritsch** [comment]
Firetv and FireOS are _not_ unsupported platforms. Kodi supports all Android boxes / products out there by implementing the offical Android SDK as found here: https://developer.android.com/reference

The Shield has other bugs, especially with refreshrate switching / audio enumeration, which are also only solvable in firmware.

I really liked the firetv 4k / Cube for myself. They are in fact running in my living room - I don't have any other Android devices here (oh I have such a new google device, but did not yet care to even plug it in ;-) perhaps I should do that at a point).

In general I still think that the FireTV is a nice kodi device. In v19:
Choose Android RAW as PT device
Set Speakers to 2.0
Enable AC3, DD+ and Dolby Transcoding.

That way everything that is multi-channel or a codec embedding multi channels is output as Dolby, which is fine for a very large amount of users. Infact one "only" looses DTS and DTS-HD-HR, which for the soundbar users makes no difference anyways.

So as a budget device I still like them a lot.
