### ISSUE TITLE
Problem Navigating to add-on home directory in Matrix

### ISSUE THREAD

**Issue by jmooremcc** [xbmc/xbmc#19053]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Matrix and Leia, when you launch an add-on from the add-on screen, clicking the ".." does not return you to the add-on screen. Instead you are taken to the video home screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The expected behavior is that we should go back to the screen we launched from when you are only one level down. If you launch the add-on from the add-on screen and are only one level down, you should return to the launch screen. Please note that pressing the back button is not the same as clicking on ".." in this case. The back button will take you back to the launch screen.

## Actual Behavior

If you click on an add-on from the add-on screen and then click on the "..", it will not take you back to the add-on screen. Instead it takes you to what I believe is the video home screen.

### To Reproduce

1. Select Add-ons
2. Load the WNBC add-on
3. Launch the WNBC add-on
4. Click on ".." to return to add-on screen

### Debuglog

The debuglog can be found here:
https://pastebin.com/embed_js/1epHVN8X

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00000](https://user-images.githubusercontent.com/13182213/104214109-0e837d00-5405-11eb-9f71-b9b463ae0d6b.png)
![screenshot00001](https://user-images.githubusercontent.com/13182213/104214173-1f33f300-5405-11eb-8929-3706f7e2f970.png)
![screenshot00002](https://user-images.githubusercontent.com/13182213/104214209-28bd5b00-5405-11eb-9de0-109231a8a71a.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

1. The 1st screenshot is the add-on launch screen showing the WNBC add-on.
2. The 2nd screenshot is the result of clicking on the WNBC add-on.
3. The 3rd screenshot is the result of clicking on ".." in the previous screenshot which is only one level down. I call this screen the video home screen.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi Matrix (19.0-BETA2 (18.9.821)
Nightly build: KodiSetup-20210106-4c1c7e74-master-x64.exe

Kodi Leia (18.9 (18.9.0)
kodi-18.9-Leia-x64.exe

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
I understand that you might think that this should be the case, but I have to say, that Kodi does everything correct. 

As you can see in your 2nd screenshot after you opened the add-on you are at "Videos/WNBC Programs" section. So this is the video section and there are simply files shown as a list. So you have to image this section like a subdirectory of the video-section. Clicking ".." simply gets you one level up which is the video-section. 

If you launch the add-on via `Videos -> Video Add-ons -> WNBC Programs` and then hit the `..` you will end up at the `Video Add-ons`-section where you launched the add-on from. That's because the video add-ons at the "Videos" section are also shown as a list of add-ons (imagine them as executable files) and Kodi remembers the parent directory you came from. If you launch the add-on from another section (`Add-ons -> Video Add-ons -> WNBC Programs` for example, as you did) and that opens a file-browser (which that add-on is basically) and you hit ".." to navigate one level up, Kodi doesn't know which parent directory you came from and so you will end up at the Videos-section. 

Video add-ons like these open the window "Videos (MyVideoNav.xml)" at launching. See:
![image](https://user-images.githubusercontent.com/7235787/104426359-203e5f00-5582-11eb-9365-4b110eb010cf.png)

It's the same window if you enter the "Videos" section from the home screen:
![image](https://user-images.githubusercontent.com/7235787/104426467-449a3b80-5582-11eb-864c-e14c4b67dd06.png)

And as you already confirmed yourself, "back" (in meaning selecting backspace) or `ESC`, will get you back to the window you expect.

You have to understand that `..` is not like "exiting" the addon. `..` means: "Navigate one level up" and Kodi does exactly that. I highly guess this behavior exists since ever and is the correct behavior from my POV

If it annoys you, you could disable this setting:

![image](https://user-images.githubusercontent.com/7235787/104425321-d5701780-5580-11eb-82f3-d03b5551f443.png)

and those ".." will not show up anymore

**Comment by jmooremcc** [comment]
I understand what you're saying but disagree with the design principle involved. 
As developers, we create abstract concepts all the time that represent more complex actual operations taking place beneath the surface of the application. For example, a floating point number is an abstract concept that hides the complexity of how it's actually implemented at the CPU level. The end user doesn't have to be aware of the technical details of implementation to use floating point numbers. They expect certain behaviors to happen consistently as long as they follow the rules.

Kodi's virtual file system is a similar abstract concept that empowers end users with the ability to navigate the list of files and folders in the virtual file system. When the end user navigates from Folder A to Folder B, they expect the back button and ".." to take them back to Folder A regardless. IMHO, Kodi's design violates this basic principle when an exception to this rule is thrust upon the end user. Navigating to a folder that's not in the navigation history is an inconsistency that causes confusion because it it is not an expected behavior.

**Comment by JayDee696969** [comment]
I agree, the back button should go back to the last folder you were in, now i have to keep clicking back and never end up in the previous place i was in.
