### ISSUE TITLE
[Windows 10 N/KN] Matrix RC startup raises mfplat.dll missing -> Media Feature Pack not installed

### ISSUE THREAD

**Issue by BigDoom** [xbmc/xbmc#19075]
### Describe the bug
Here is a clear and concise description of what the problem is:

Yesterday I've upgraded by HTPC to Matrix RC after some testing on my laptop where everything worked fine. Installation went fine but when starting Kodi the error 'mfplat.dll missing' and the program wouldn't start. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Regular start of Kodi Matrix after upgrading from v18.

## Actual Behavior

Error message mfplat.dll missing, program won't start.

## Possible Fix

It seems that my HTPC is running a Windows 10 N version, which don't come with the Media Feature Pack. Manually installing this (pre 1903 versions) or enabling it via 'turn windows features on or off' and rebooting the computer fixed the issue.

The Media Feature Pack provides the missing dll file but it not installed on Windows 10 N or KN versions.

### To Reproduce

1. Install Matrix on a Windows 10 N or KN version without Media Feature Pack already enabled
2. Start Kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows **N version**
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
it is normal not a bug, Windows N is designed to facilitate market competition
so media player libraries and others software are not included and must be installed manually..

**Comment by BigDoom** [comment]
> it might be an idea to add the prerequisite directly into the Kodi installer to ease installation and avoid the problem

That's exactly why I posted this, could be usefull to add it as a prerequisite because you only get the error message after you upgraded and it's a bit anoying to upgrade and the first thing you see is an error message :)

**Comment by nambpgh** [comment]
This is a **show-stopper** (also for me, also Windows without Media Feature Pack)!
Upgrade v18 to v19 and you cannot start Kodi anymore.

I see no real reason to make Kodi depending on the Media Feature Pack. It was not needed for v18. Why should it be necessary for v19?
I don't want the Media Feature Pack. This is, why I use alternative software, like Kodi.

Maybe some features my not work without the Media Feature Pack in Kodi but I should not be impossible to use it.
Having the dependency is IMHO a wrong approach.

Also to say: It's not good to get no info for the need of the Media Feature Pack (not in the setup, no other info).


P.S.: It's also very disappointing to have no documentation for a new release. https://kodi.wiki/view/Kodi_v19_(Matrix)_changelog has only info at "1.7 Live TV and PVR (Personal Video Recorder)". The wiki itself is old/outdated on many sites. I didn't saw at least one site updated for v19 by now. In the best case I see "Page updated for v18".

**Comment by DaveTBlake** [comment]
> P.S.: It's also very disappointing to have no documentation for a new release. https://kodi.wiki/view/Kodi_v19_(Matrix)_changelog has only info at "1.7 Live TV and PVR (Personal Video Recorder)". The wiki itself is old/outdated on many sites. I didn't saw at least one site updated for v19 by now. In the best case I see "Page updated for v18".

You free to volunteer your time and contribute to the wiki, all the change information is available in Github.

**Comment by nambpgh** [comment]
Oh, what a sarcastic response.

First, it must be possible to start Kodi but with v19 it is not running anymore (without the fu**ing Media Pack).

Second, it is not possible to me. If you are not a hardcore developer in (mainly C++) it is not possible to understand the code and the system at all. The code is mostly undocumented and without any comments. There are mostly no good documented requirements, not analysis documents, etc.
Resources found are often totally outdated.
I know how professional software developing has to be done and the development of Kodi (and many other open source projects) is far away from well-established processes. Kodi is, like many other open source projects, a hacking project.
I know, developers often don't like to write documents but without it is often not possible for non-developers to contribute.

I tried several times to contribute the project over the years (in the forum, feature requests, writing bugs). In most cases it come to nothing. Bugs have been ignored and came to no fixing. In the forum my issues often get no helpful/qualified response at the end.

**Comment by lrusak** [comment]
it looks like this problem is related to the FFmpeg bump introduced in #18071

@Paxxi looking at ffmpeg it looks like we can disable the inclusion of AMF code by using the `--disable-amf` and mediafoundation via `--disable-mediafoundation` switch. It looks like these are encoders which we don't need anyways. Can you investigate?

see,
https://github.com/FFmpeg/FFmpeg/blob/51a9f487ae2a12fa51db916315c88e6f38adca15/configure#L330
https://github.com/FFmpeg/FFmpeg/blob/6b6b9e593dd4d3aaf75f48d40a13ef03bdef9fdb/configure#L307

**Comment by nambpgh** [comment]
Ok, thx for info.

If the issue is because of FFmpeg it might be interesting: Isn't FFmpeg just used for _video_? I wonder why it prohibits Kodi from starting.
In case it is just used for _video_ (and it would not prohibit Kodi from starting) Kodi might be used for _audio_ or _pics_, I guess.

If AMF and MediaFoundation are not needed, it should be fine to deactivate them. If they have any advantage (e.g. on AMD chips, or maybe for HDR or so) they should just be activated if the libs are present or it's a supported chip.
If the Media Pack is needed in any case (I don't hope so) this should be checked already at setup (installation/upgrade), since they don't exist on every version of Windows.

**Comment by lrusak** [comment]
> Ok, thx for info.
> 
> If the issue is because of FFmpeg it might be interesting: Isn't FFmpeg just used for _video_? I wonder why it prohibits Kodi from starting.
> In case it is just used for _video_ (and it would not prohibit Kodi from starting) Kodi might be used for _audio_ or _pics_, I guess.

It's because ffmpeg is a library that is linked into the Kodi binary. The ffmpeg library requires `mfplat.lib` (when the aforementioned config switches are enabled), thus the Kodi binary requires the `mfplat.lib` library as well. We don't dynamically load ffmpeg only when needed.

> If AMF and MediaFoundation are not needed, it should be fine to deactivate them. If they have any advantage (e.g. on AMD chips, or maybe for HDR or so) they should just be activated if the libs are present or it's a supported chip.
> If the Media Pack is needed in any case (I don't hope so) this should be checked already at setup (installation/upgrade), since they don't exist on every version of Windows.

It looks like they only provide encoder functionality so should be fine to be disabled. This is likely just an oversight when we updated the FFmpeg version.

**Comment by afedchin** [comment]
only `mediafoundation` should be disabled, `amf` isn't used actually. see the log from latest build https://jenkins.kodi.tv/job/WIN-64/15943/consoleFull
```
16:36:46 External libraries:
16:36:47 libdav1d                openssl
16:36:47 mediafoundation         zlib
```

**Comment by lrusak** [comment]
> only `mediafoundation` should be disabled, `amf` isn't used actually. see the log from latest build https://jenkins.kodi.tv/job/WIN-64/15943/consoleFull
> 
> ```
> 16:36:46 External libraries:
> 16:36:47 libdav1d                openssl
> 16:36:47 mediafoundation         zlib
> ```

I just grepped FFmpeg for the missing symbols from the FFmpeg bump PR.

```
14:25:16      Creating library F:/builds/workspace/WIN-64/kodi-build.x64/Release/kodi.lib and object F:/builds/workspace/WIN-64/kodi-build.x64/Release/kodi.exp
14:25:16 avcodec.lib(mfenc.o) : error LNK2019: unresolved external symbol MFCreateMediaType referenced in function mf_choose_output_type [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mfenc.o) : error LNK2019: unresolved external symbol IID_ICodecAPI referenced in function mf_init [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mfenc.o) : error LNK2019: unresolved external symbol IID_IMFMediaEventGenerator referenced in function mf_unlock_async [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFStartup referenced in function ff_instantiate_mf [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFShutdown referenced in function ff_free_mf [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFCreateAlignedMemoryBuffer referenced in function ff_create_memory_sample [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFCreateSample referenced in function ff_create_memory_sample [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol IID_IMFTransform referenced in function ff_instantiate_mf [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
14:25:16 F:\builds\workspace\WIN-64\kodi-build.x64\Release\kodi.exe : fatal error LNK1120: 8 unresolved externals [F:\builds\workspace\WIN-64\kodi-build.x64\kodi.vcxproj]
```

so
```
MFCreateMediaType 
IID_ICodecAPI 
IID_IMFMediaEventGenerator
MFStartup 
MFShutdown 
MFCreateAlignedMemoryBuffer 
MFCreateSample 
IID_IMFTransform 
```

results in
```
$ git grep -E "(MFCreateMediaType|IID_ICodecAPI|IID_IMFMediaEventGenerator|MFStartup|MFShutdown|MFCreateAlignedMemoryBuffer|MFCreateSample|IID_IMFTransform)"
configure:mediafoundation_deps="mftransform_h MFCreateAlignedMemoryBuffer"
configure:check_func_headers mfapi.h MFCreateAlignedMemoryBuffer -lmfplat
libavcodec/mf_utils.c:    hr = MFCreateSample(&sample);
libavcodec/mf_utils.c:    hr = MFCreateAlignedMemoryBuffer(size, align - 1, &buffer);
libavcodec/mf_utils.c:    hr = MFStartup(MF_VERSION, MFSTARTUP_FULL);
libavcodec/mf_utils.c:    MFShutdown();
libavcodec/mf_utils.c:        hr = IMFActivate_ActivateObject(activate[n], &IID_IMFTransform,
libavcodec/mfenc.c:        hr = MFCreateMediaType(&out_type);
libavcodec/mfenc.c:    hr = IMFTransform_QueryInterface(c->mft, &IID_IMFMediaEventGenerator, (void **)&c->async_events);
libavcodec/mfenc.c:    hr = IMFTransform_QueryInterface(c->mft, &IID_ICodecAPI, (void **)&c->codec_api);
```

```
$ git grep " mf_utils.o"
libavcodec/Makefile:OBJS-$(CONFIG_AAC_MF_ENCODER)          += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_AC3_MF_ENCODER)          += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_H264_MF_ENCODER)         += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_HEVC_MF_ENCODER)         += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_MP3_MF_ENCODER)          += mfenc.o mf_utils.o
$ git grep " mfenc.o"
libavcodec/Makefile:OBJS-$(CONFIG_AAC_MF_ENCODER)          += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_AC3_MF_ENCODER)          += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_H264_MF_ENCODER)         += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_HEVC_MF_ENCODER)         += mfenc.o mf_utils.o
libavcodec/Makefile:OBJS-$(CONFIG_MP3_MF_ENCODER)          += mfenc.o mf_utils.o
```

So yes, Look like just mediafoundation. Not sure where I saw AMF.

**Comment by lrusak** [comment]
Can someone test this build to see if it fixes the issue -> https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210403-c980dc5d-PR19506-merge-x64.exe

**Comment by nambpgh** [comment]
> 
> 
> Can someone test this build to see if it fixes the issue -> https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210403-c980dc5d-PR19506-merge-x64.exe

I did a quit test and it is working for me.

I'm on a different machine (with Windows 10 Pro N, Media Feature Pack **deinstalled**). Installation run fine. Migration of DB and Addons okay. I only did a test with a video-stream (addon) and this was okay. At a first view I saw no problems.

**Comment by lrusak** [comment]
> > Can someone test this build to see if it fixes the issue -> https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210403-c980dc5d-PR19506-merge-x64.exe
> 
> I did a quit test and it is working for me.
> 
> I'm on a different machine (with Windows 10 Pro N, Media Feature Pack **deinstalled**). Installation run fine. Migration of DB and Addons okay. I only did a test with a video-stream (addon) and this was okay. At a first view I saw no problems.

@nambpgh thanks for testing, was really just looking if the installation went ok. This build is based on Kodi 20 but we can backport it to Kodi 19.

**Comment by nambpgh** [comment]
> was really just looking if the installation went ok. This build is based on Kodi 20 but we can backport the fix to Kodi 19.

Backport to v19 would be fine! (I was astonished that it was already a v20 build.)

N.b.: The original sadly issue did not appear at installation but only at running, afterwards. However, the changes of the new build looks good (even if I have no other media to test on this machine, just online streams).

**Comment by DaveTBlake** [comment]
> Oh, what a sarcastic response.

@nambpgh no, simply pointing out the reality - the wiki is created by the wider community not the devs. Instead of being "disappointed" with or critical of the efforts of others why not contribute your time for free to make it better.

> If you are not a hardcore developer in (mainly C++) it is not possible to understand the code and the system at all. The code is mostly undocumented and without any comments. There are mostly no good documented requirements, not analysis documents, etc.
> Resources found are often totally outdated.

Yes having the design fully documented  would make drive-by contributions much easier, but again it needs people to create and maintain it. Resources (people with skills, interest and spare time to volunteer) are very limited, so how are those best spent - on retrospectively writing documents or code fixes? Also  people work on entirely what they choose, as no one has volunteered to document the design it remains largely undocumented. 

But the situation is not impossible, with enough patience and persistence it is possible to work through the code and the discussions in Git and forum etc. and deduce how Kodi works, what changes have been made etc. All of us that do contribute to Kodi (not just devs) have made that effort. 

> Kodi is, like many other open source projects, a hacking project.

There is a big difference between undocumented software and hacking (a catch-all term for any type of misuse of a computer to break the security of another system to steal data). So no Kodi is not a "hacking project". Perhaps think of it as a huge hobby project, created by numerous enthusiasts over many years,  that now has millions of users over multiple platforms.

> I tried several times to contribute the project over the years (in the forum, feature requests, writing bugs). In most cases it come to nothing. Bugs have been ignored and came to no fixing. In the forum my issues often get no helpful/qualified response at the end.

Who do you expect to fix the bugs, answer your questions and satisfy your requirements? Who do you expect to make it easy for you? Not sarcasm, I genuinely wish non-team members would re-examine their inherent expectations and have a more realistic  view of the resources the project currently has. It would be great those of us actively working on Kodi had the additional spare time to nurture  and mentor you, but we don't. Frustrating as it may be the onus is on you to try harder, be patient yet persistent, do the deductive work necessary or at least encourage those of us that are already doing the best that we can.
