### ISSUE TITLE
FireTV Cube video playback - High bitrate stuttering 19.0-RC1

### ISSUE THREAD

**Issue by replicants** [xbmc/xbmc#19123]
### Describe the bug
Here is a clear and concise description of what the problem is:
Playback of high bit rate files on Fire Cube TV (AFTR) are buffering after 30s or so
Bit rates of under 20Mbit/s play ok. Those near 50Mbit/s produce buffering stalls.
Don't have any files between the two ranges to narrow down any further. 

Infrastructure testing:
iperf3 tests to file server show solid 100Mbit/s network connection (wired ethernet) from the Cube. 
Test runs from a test PC on same network show file server performance to be around 400MByte/s read/write

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Video file plays without buffering

## Actual Behavior

Playback stutters after 10-30 seconds

### To Reproduce

1.  Play high bit rate video file
2.
3.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/gabezehoso.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Issue reported by others in forums https://forum.kodi.tv/showthread.php?tid=347239&pid=3003280#pid3003280
Also noted a very long pause at a black screen after pressing stop during video playback before it displayed the kodi interface

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.0 RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Your log is not a debug log

I highly guess this is more a support question rather than a bug report. If the machine which the video plays or the machine which serve the files does anything else network-wise, then the bandwidth of 100Mbit/s might not be enough. I guess (because I don't have the hardware) that the FireTV Cube doesn't provide a gigabit ethernet connection. So I would suggest to play around with the advancedsetting.xml and play around with the video cache:

https://kodi.wiki/view/Advancedsettings.xml#cache

But we might know more after we have seen the full debuglog

**Comment by replicants** [comment]
I've updated post with a debug log and some extra info
