### ISSUE TITLE
Option to remove new client-side decorations (in windowed mode)

### ISSUE THREAD

**Issue by harrisonthorne** [xbmc/xbmc#19491]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi has this (new? since Matrix?) client-side decoration/title bar, and I'm trying to figure out how to hide it or get rid of it: [Reddit post](https://www.reddit.com/r/kodi/comments/mfur4i/how_to_remove_the_titlebarwindow_controls_in/)

I didn't seem to have this issue with Leia.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should have an option to disable the window controls in windowed mode. (If it already does, where is it?)

## Actual Behavior

I can't find an option to disable the titlebar/window controls

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot](https://i.redd.it/jxzc2ce750q61.png)

Instead of just a video, there are also the minimize, maximize, and close buttons in the top-right.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

*"What were you trying to accomplish?"*

I'm trying to have a picture-in-picture sort of setup with my Linux environment so I can watch videos while I work on schoolwork or other projects. The client-side decorations, however, are a little bothersome to me and slightly distracting.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Window manager: Sway (Wayland)
 - Operating system version/name: `Void 5.10.25_1 x86_64`
 - Kodi version:

```
19.0 (19.0.0) Git:20210316-nogitfound Media Center Kodi
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv
```

**Comment by enen92** [comment]
@yol something for you to take a look/answer or close :)

**Comment by yol** [comment]
> Kodi has this (new? since Matrix?) client-side decoration/title bar, and I'm trying to figure out how to hide it or get rid of it

The CSD bar is used with Wayland to allow people to move and minimize/maximize/close the window, since most Wayland compositors do not have server-side decoration support like X11. Nothing has changed in this regard since Leia.

What has changed, though, is that we now have a unified binary that combines Wayland and X11. Previously, you might have just not been using Wayland. You may try `kodi --windowing=x11` to get your old behavior back for now.

Aside from that, we only use GitHub issues for actual bugs and not feature requests and general support, so please go to the [feature requests forums section](https://forum.kodi.tv/forumdisplay.php?fid=9) if you want to take this further :)

**Comment by harrisonthorne** [comment]
Sounds good to me :) Thank you for your work! The new release is awesome.

**Comment by yol** [comment]
@harrisonthorne If you open a forum thread, please link it here and describe your use case in some more detail. Switching to X11 might be a solution but going forward it would be nice if you could use Wayland :) Also there's the open roadmap ticket #15219 which might solve the problem, but it will depend on what exactly you want.

**Comment by norpol** [comment]
Maybe you could re-visit whether you want to treat this as a bug, not being able to hide the controls will result in odd automatically switching to fullscreen on swaywm, causing everything to be shifted downards for the height of the (invisible) decoration.

You have to open kodi, go back in windowed mode and then go in fullscreen again in order to remove this bar.

A workaround for me is now starting kodi, disabling fullscreen and then reenabling fullscreen to get rid of the decoration.

`{ kodi & sleep 1s; swaymsg '[app_id="Kodi"]' fullscreen toggle; sleep 1s; swaymsg '[app_id="Kodi"]' fullscreen toggle; fg; }`

Other people already opened a relevant bug-report on swaywm side a while ago: https://github.com/swaywm/sway/issues/4366

`kodi --version` reports `19.0 (19.0.0) Git:20210219 Media Center Kodi` (I'm on nixos)

Setting fullscreen in `advancedsettings.xml` to false is ignored, it will always launch in fullscreen.

I also believe adding xdg-decoration support might resolve this issue.

![image](https://user-images.githubusercontent.com/2230917/115020209-8b1d7000-9eba-11eb-95c8-da1a3926ac59.png)

**Comment by yol** [comment]
@norpol The sway issue seems to be about something else, as far as I can tell. I haven't seen this behavior (offset rendering) with any other WM, so I would flag it as a sway issue for the time being.

It would of course go away when no decorations are rendered. PRs for this feature are welcome.

**Comment by Ape** [comment]
Is there actually way to disable the client side decorations in windowed mod? I have server-side decorations on sway and would like to just use those.

**Comment by popcornmix** [comment]
We have this requirement on RPiOS which uses wayland with server side window decorations (as the client side ones are so ugly). I've disabled it for our build:
See: https://github.com/popcornmix/xbmc/commit/71fd67a144faff4a1a221b93db845d72728b5fcb

**Comment by fbo25** [comment]
If it can help...

**Detect if compositor support decoration**

Generate Wayland headers :
```console
$ wayland-scanner private-code </usr/share/wayland-protocols/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml >xdg-decoration-unstable-v1-protocol.h
$ wayland-scanner client-header </usr/share/wayland-protocols/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml >xdg-decoration-unstable-v1-client-protocol.h
```

Include generated headers :
```c
// [...]
#include "xdg-decoration-unstable-v1-client-protocol.h"
#include "xdg-shell-client-protocol.h"
```

Add zxdg_decoration_manager_v1 to your globals :
```c
typedef struct {
	// Globals
	struct wl_display *wl_display;
	struct wl_registry *wl_registry;
	struct wl_compositor *wl_compositor;
	struct xdg_wm_base *xdg_wm_base;
	struct zxdg_decoration_manager_v1 *xdg_decoration_manager;

	// Objects
	struct wl_surface *wl_surface;
	struct xdg_surface *xdg_surface;
	struct xdg_toplevel *xdg_toplevel;
	struct zxdg_toplevel_decoration_v1 *xdg_toplevel_decoration;
// [...]
} Wl_State;
```

In your registry global listener :
```c
static void pl_wl_registry_global(void *data, struct wl_registry *wl_registry, uint32_t name,
						const char *interface, uint32_t version) {
	// [...]
	if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
			state->xdg_wm_base = wl_registry_bind(wl_registry, name, &xdg_wm_base_interface, 1);
			xdg_wm_base_add_listener(state->xdg_wm_base, &pl_wl_xdg_wm_base_listener, state);
	}
	// Bind XDG decoration manager
	else if (strcmp(interface, zxdg_decoration_manager_v1_interface.name) == 0) {
			state->xdg_decoration_manager = wl_registry_bind(wl_registry, name, &zxdg_decoration_manager_v1_interface, 1);
	}
}
```

On decoration initialization :
```c
Wl_State state // [...]

state->xdg_surface = xdg_wm_base_get_xdg_surface(state->xdg_wm_base, state->wl_surface);
xdg_surface_add_listener(state->xdg_surface, &pl_wl_xdg_surface_listener, self);
state->xdg_toplevel = xdg_surface_get_toplevel(state->xdg_surface);
xdg_toplevel_add_listener(state->xdg_toplevel, &pl_wl_xdg_toplevel_listener, self);
xdg_toplevel_set_title(state->xdg_toplevel, "Kodi");

// If compositor supports window decoration
if (state->xdg_decoration_manager) {
	state->xdg_toplevel_decoration =
			zxdg_decoration_manager_v1_get_toplevel_decoration(state->xdg_decoration_manager, state->xdg_toplevel);

			// Following is optional on Sway, don't know about others :
			zxdg_toplevel_decoration_v1_set_mode(state->xdg_toplevel_decoration, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
}
else {
	// TODO use our own window decoration
}
```

Tested on Sway (server decoration) and Weston (no xdg_toplevel_decoration support)
