### ISSUE TITLE
Passthrough disabled in PVR LiveTV

### ISSUE THREAD

**Issue by Lunatixz** [xbmc/xbmc#19779]
### Describe the bug
Here is a clear and concise description of what the problem is:

According to this old thread (below), passthrough was disabled in PVR deliberately; I'd like to suggest since Kodi's PVR is no longer limited to only live content; ie VFS is playable... PCM enforcement ought to be removed.

https://forum.kodi.tv/showthread.php?tid=284580&pid=2385467#pid2385467

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Content from Kodi's VFS when played through the PVR ought to allow Passthrough audio.

## Actual Behavior

PVR is locked to PCM audio.

## Possible Fix

Revert code that enforces PCM and replace it with a VFS sources check.

### To Reproduce

1.  Play nonlive content through the PVR.
2. Download and use PseudoTV Live which converts Kodi's library to PVR through m3u/xmltv & IPTV Simple. (https://forum.kodi.tv/showthread.php?tid=355549)
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Lunatixz** [comment]
Reading this thread was this resolved: https://forum.kodi.tv/showthread.php?tid=342388
@fritsch Do you remember if this was resolved? Passthrough for LiveTV?

**Comment by fritsch** [comment]
There is nothing to resolve. When you have a bitstream and you run out of sync you can basically do nothing, you can drop - that will make pscccht noise and when you duplicate packages your AVR looses sync as this is not allowed.

So before someone is coming up with a nice algorithm combining pause bursts in a way that neither happens, everything else will be a hack. Mechanisms like in the PI where you can "alter the clocks" a bit to compensate are no general solutions.

**Comment by fritsch** [comment]
As this is a feature request, please drive it forward in the forum. For those with only SPDIF or 2 PCM channels available, fell free to enable Sync Playback to Display and AC3 transcode with 2 PCM channels set. That way you get the AC3 from live tv nicely compensated and output as AC3.

**Comment by Leatherface75** [comment]
It would be better to have PCM as a setting there you can turn it on or off.

**Comment by wolfallein** [comment]
Hi, I think I have the same problem.

I'm trying to play VOD from my IPTV provider which has TrueHD Dolby Atmos but my soundbar doesn't receive the atmos stream. It seems that Kodi is decoding to PCM first. I still have all the audio channels though.

If I download the video and play the file locally with Kodi I get the Atmos flag on my Soundbar.
I tried on Windows and ATV (Chromecast with GTV) with the same behavior. My soundbar is connected to my TV with eARC enabled, and the PC (Windows) or Chromecast is connected to the TV.

Is it possible to disable the decoding enforcement in Kodi for streams? How can I check the decoding that Kodi is doing?

**Comment by da-anda** [comment]
@wolfallein I think in your particular case the add-on that you are using for liveTV would have to not mark this VOD content as live stream so that it is using a different code path in KODI (at least from what I recall).
But for anything marked as live stream, audio passthrough will not be possible at the moment, because KODI will attempt to render the stream ASAP (for faster channel switch times) and thus only use a very small buffer, which is not large enough to compensate for stream errors and keep passthrough in sync. It certainly would be fixable like fritsch mentioned above, but somebody would have to write the algorithm he mentioned.

**Comment by Lunatixz** [comment]
@da-anda Last time I looked into this issue Kodi's core player treats all playback via PVR regardless of  "live source" differently; and disregards audio processing.

**Comment by da-anda** [comment]
@Lunatixz I'm unfortunately not really a dev. But since recordings IIRC do support passthrough, not the entire PVR system is affected. Have you talked to @ksooo or @phunkyfish about this? They have the most insight of our PVR system and might be able to help finding a solution.

**Comment by Lunatixz** [comment]
@fritsch It would be great if we could resolve these issues with the player. Kodi's PVR has expended beyond only "live feeds".

**Comment by fritsch** [comment]
If it was so easy. When there is a PCM stream and data runs empty or on channel switch when buffers are still empty a small resample of the audio can keep the visual quality and audible quality in place. No one wants to wait 5 seconds until buffers are filled. You would hear the goal in a soccer game multiple seconds later than your neighbour 

 With such PT streams the only thing Kodi can do and this also only for IEC PT devices is dropping audio packages to maintain sync or skip video frames. AVRs don't like dropping audio pt packages which is why it defines the wall clock and video needs to be synced with it. Does really look bad on channel switch, dry buffer cases. We also cannot technically create audio frames in the mentioned codecs, but only draft pause bursts by replacing a pt package content with a container burst, also not for Android default raw devices.

Just disable the single place in AE stream to reenable pt on live and you know what I mean.

What would definitely work is buffering more, some seconds, assuming stream is stable which it is not for DVB streams, sacrificing switching times and enable PT again?

So distinguishing between DVB S and DVB C pvr and enabling buffer plus pt for the others. Above issues apply: no guaranteed Datarate, buffer fill state, evil will happen.

**Comment by Lunatixz** [comment]
@fritsch Kodi's videoplayer assumes that all sources played via the PVR are streams; IMO this is flawed logic. If the PVR attempts to play a local source VFS, ex. (smb://foo/bar.mkv, plugin://plugin.video.foobar/somevideo) why can't the player decode the audio as expected? I believe the issue is how the player blindly disables pass through on all PVR origin calls.

**Comment by fritsch** [comment]
```
bool CInputStreamAddon::IsRealtime()
{
  if (m_ifc.inputstream->toAddon->is_real_time_stream)
    return m_ifc.inputstream->toAddon->is_real_time_stream(m_ifc.inputstream);
  return false;
}
```
```
bool CDVDInputStreamFFmpeg::Open()
{
  if (!CDVDInputStream::Open())
    return false;

  m_aborted = false;

  if (StringUtils::CompareNoCase(m_item.GetDynPath(), "udp://", 6) == 0 ||
      StringUtils::CompareNoCase(m_item.GetDynPath(), "rtp://", 6) == 0)
  {
    m_realtime = true;
  }

  return true;
}
```
```
bool CInputStreamPVRBase::IsRealtime()
{
  bool ret = false;

  if (m_client)
    m_client->IsRealTimeStream(ret);

  return ret;
}
```

^^ Most likely the last one is your problem, which tells the VideoPlayer: I am live stream. Player is only doing what it is told. Player does nothing blindly, it is kindly asked by an inputstream. There is no logic to disable that in Player ... either demuxer, addon or pvr base client.

**Comment by fritsch** [comment]
iptv simple: https://github.com/kodi-pvr/pvr.iptvsimple/blob/Omega/src/iptvsimple/PlaylistLoader.cpp#L66
pvr hts: https://github.com/kodi-pvr/pvr.hts/blob/Omega/src/Tvheadend.cpp#L396

Which client / backend are you using? Seems it might signal all the time:  PVR_STREAM_PROPERTY_ISREALTIMESTREAM as true.

**Comment by Lunatixz** [comment]
@fritsch IPTV-Simple

**Comment by fritsch** [comment]
Seems it hard codes that property for basically everything: https://github.com/kodi-pvr/pvr.iptvsimple/blob/Omega/src/iptvsimple/PlaylistLoader.cpp#L192 besides VOD (Video on Demand?)

So yeah - not sure what Player should fix for that. That we cannot properly sync passthrough on RealTimeStream sadly I already explained. Setting VOD tags :P in the playlist is not what you should use as a workaround I think.

**Comment by Lunatixz** [comment]
@fritsch thanks again, what do you think a proper workaround is? if `PVR_STREAM_PROPERTY_ISREALTIMESTREAM ` is the real-time flag the player is looking for, makes sense to me that it be dynamic depending on the source... ie. setting via properties. is the only solution available to iptv-simple.

**Comment by wolfallein** [comment]
> 

Well... At that time, I "fixed" the issue for me by commenting on some lines in the code... I think it was `m_realtime = true;`. It worked well for the VODs I had.. and even for live streams. I had very few problems. I only remember hearing some "pops" very rarely...

I understand what @fritsch said about buffer and everything and that it would not work for most cases. I think having an option to "force passthrough on live content" in the menu would be a good addition.

**Comment by jdrouhard** [comment]
Or a configurable buffer? Default of 0 to mean current behavior, or force passthrough or something? Trade off between faster channel switch and being closer to live vs smoother playback with no audio stutters. 

I would personally prefer a slower channel switch time and being a couple seconds behind "real live" if I could eliminate audio pops and stutters.

**Comment by phunkyfish** [comment]
> THX @fritsch IPTV-Simple @phunkyfish can we move `PVR_STREAM_PROPERTY_ISREALTIMESTREAM ` to KODIPROP or optionally disabled via properties?

You can just set the M3U entry as VOD. Then realtimestream will not be set.

**Comment by fritsch** [comment]
> Or a configurable buffer? Default of 0 to mean current behavior, or force passthrough or something? Trade off between faster channel switch and being closer to live vs smoother playback with no audio stutters.
> 
> I would personally prefer a slower channel switch time and being a couple seconds behind "real live" if I could eliminate audio pops and stutters.

Don't forget the commercials, which might have to reconfigure audio channels, which is why Optimized was invented in audio settings, though without effect when passthrough is done. I am not against anything here, just want to draw the full picture before there are different expectations before hand and then someone feels kicked by reality.

Also saying once again: while it is possible to sync a stream with pause bursts into every direction, it won't work on systems that don't support IEC passthrough like 99% of android or WebOS.

**Comment by da-anda** [comment]
@fritsch since PVR realtime(!) streams mostly have (E-)AC3 streams that would require passthrough, couldn't we simply turn on "ac3 encoding" if the user has enabled passthrough and the source also was (E-)AC3? So basically keep the current buffer handling etc but automatically re-encode to (E-)AC3 so that users get the result they would expect?

**Comment by fritsch** [comment]
Nope. One is transmitted with 2 channels 192 khz,the other with 2 channels 48 khz.

If you prefer AC3 all the time: set speakers to 2.0 and enable AC3 and AC3 transcode.

**Comment by Lunatixz** [comment]
Issue was resolved https://github.com/kodi-pvr/pvr.iptvsimple/commit/6437ad18d33b1dce132dd1cc4034285388c93206
