### ISSUE TITLE
SMB is disconnecting after a while with Kodi 19.1 on android

### ISSUE THREAD

**Issue by rafi-d** [xbmc/xbmc#19934]
Please see here for details (suspected root cause and workaround): 
https://forum.kodi.tv/showthread.php?tid=360606&pid=3047025#pid3047025

**Comment by DaVukovic** [comment]
Using SMB2 shares (which do require a username and a password) is not a workaround. It's the default nowadays since SMB1 is deprecated and vulnerable. 

And as you haven't reported a bug report here (because of just ignoring our template and not even provided a debuglog), I'm going to close this one. Please continue the discussion at the forums

**Comment by rafi-d** [comment]
I probably was not clear: 
A password is NOT mandatory in Windows, while w/o setting one it seems that Kodi will not connect...
