### ISSUE TITLE
Add ability to change playback speed or tempo in jsonp api

### ISSUE THREAD

**Issue by chepe263** [xbmc/xbmc#19988]
### Describe the bug
Here is a clear and concise description of what the problem is:
In order to add playback speed support to Kore, the API needs to support a method to change the playback speed.
There’s no such thing in the current API.
Is there a possibility to add a new method to the API to change the playback speed?

Some “add new method to the API” example would be helpful as well.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix
Add new method to Json api

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
The ability to change the playbackspeed or tempo (in meaning `TempoUp` or `TempoDown`) depends on the settings "sync playback to display". By turning this setting on you will loose audio passthrough of digital audio tracks such as "DolbyDigital", "DTS" and similar. 

So in order to get this working, you will at least need something from Kore which checks if this setting is enabled or not.

But yes, you will still need the API call for changing this which doesn't exist yet. For me this sounds more like a feature request which should be submitted to our forums: 
https://forum.kodi.tv/forumdisplay.php?fid=9

This, normally, is a bug-report section. And unfortunately, your report doesn't sound like a bug ;)

**Comment by chepe263** [comment]
In the api, I'm not sure but using the Skin commands, It is possible to change the playback speed.

**Comment by jubalh** [comment]
@chepe263 Can you tell me how?

**Comment by DaVukovic** [comment]
@jubalh As I explained above (in fact directly above your initial question): 

- enable "Sync playback to disaplay" (be aware that this will disable audio passthrough, so you will loose the ability to receive digital audio formats like "DolbyDigital", "DTS" and so on). *It won't work otherwise* 
- then use the "built in function" `PlayerControl(Command)` like explained here: https://kodi.wiki/view/List_of_built-in_functions#Player_built-in's
  - in your case for `TempoUp` or `Tempo(Down)` the function has to be used like: `PlayerControl(TempoUp)` or `PlayerControl(TempoDown)`

You have a bunch of possibilities how you are able to use that. You are able to map a key on your keyboard or remote control to use that function. You are able to modify the skin, create a new button(s) on the VideoOSD which will trigger the mentioned command. 

For this issue here (in regard of the JSON API), no such call exists and therefore you won't be able to use a smartphone app like "Kore" or the iOS Kodi Remote app to change the playback speed. Hence I closed this "issue" as it's a feature requests and those requests need to be done at the foruims. Link already posted above. 

I'm now unsubscribing from this issue, as everything is already explained more than enough and I won't be bothered by mails anymore. Have fun experimenting. ;)

**Comment by chepe263** [comment]
If you move the mouse, click something or press Y in xbox controller, there’s an overlay with playback controls. At the end there’s a gear icon with a menu to adjust subtitles, audio and playback speed. 

You need a recent version of Kodi and “ Sync playback to display” enabled.  

Good luck.

**Comment by DaVukovic** [comment]
Yeah, that's true as well...

Once this setting is enabled and you enter the settings while playing a video you will have this option:

![image](https://user-images.githubusercontent.com/7235787/217465182-510730dd-cf0f-4eaf-8ea1-ec1c5d9774c9.png)

Which also will change the playback speed

![image](https://user-images.githubusercontent.com/7235787/217465358-9b0b8200-221d-4b39-8e09-66e13891cb7f.png)

But, as said, you will need to enable "Sync playback to display"
