### ISSUE TITLE
Improve 'No route to host' error handling

### ISSUE THREAD

**Issue by tbertels** [xbmc/xbmc#20040]
### Describe the bug
Here is a clear and concise description of what the problem is:

We need to improve what the user is shown when the connection to a remote host (a NAS, a computer...) gets interrupted and the video freezes.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

An error dialog with the message "Connection to host [host name] lost". Trying to reconnect..." (ideally with animated "..." or image) is shown.
Below the message in the same error dialog, a button "Cancel" is shown so the user can abort if wanted.

## Actual Behavior

Nothing is shown, the video just freezes and stays like that for 60 seconds or more. Then the video closes and an error message "No route to host" (without the name of the host) is shown.

## Possible Fix

Once the video freezes (since the video buffer has already had time to get empty), show immediately the error message and abort button mentioned in "Expected Behavior".

### To Reproduce

1. Play a video stored in a remote host (NAS, computer...)
2. Disconnect the remote host
3. Wait for the video buffer to get empty.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6986519/kodi.log)

Excerpt:
````
2021-08-14 11:39:33.051 T:4049     INFO <general>: CVideoPlayerAudio::Process - stream stalled
2021-08-14 11:39:33.681 T:3985    ERROR <general>: Read - Error( -1, 110, Connection timed out )
2021-08-14 11:39:33.681 T:3985    ERROR <general>: Process - <smb://DISKSTATION/3 Tera Backup/Download/Spring 2019/Spring 2019.mkv> source read failed with -1!
2021-08-14 11:39:33.724 T:3981    ERROR <general>: ffmpeg[0x61e4b78X]: [matroska,webm] File ended prematurely
2021-08-14 11:39:33.725 T:3981     INFO <general>: CVideoPlayer::OnExit()
2021-08-14 11:39:33.725 T:3981     INFO <general>: VideoPlayer: eof, waiting for queues to empty
2021-08-14 11:39:33.725 T:3981     INFO <general>: Closing stream player 1
...
2021-08-14 11:40:37.447 T:2609    ERROR <general>: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USERNAME:PASSWORD@192.168.1.5/3%20Tera%20Backup/Download/Spring%202019'
                                                   unix_err:'71' error : 'No route to host'
````

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: XBian 2021.07.30 rpi4
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Hi

Thanks for your report. 

Kodi doesn't create this error message. It comes from the underlying OS. Not sure which section is in use. It might probably be SMB or maybe CURL or the network service itself

See:

https://github.com/xbmc/xbmc/blob/master/xbmc/platform/posix/filesystem/SMBDirectory.cpp#L309-L310

So it's nothing we can improve as such network errors might have different reasons.

**Comment by tbertels** [comment]
Indeed, I thought it was a good way to describe what happens when a file can't be accessed anymore. It turns out it's not.

The purpose of this bug report is to improve the handling of such events: the connection to a remote host is lost.
I tried it on Windows 10, the same kind of thing happened: Kodi stopped responding for a minute or so.
This doesn't happen when the file is on a USB device.

Here's the log for the Windows version of Kodi accessing a file on a NAS: [kodi-windows-nas.log](https://github.com/xbmc/xbmc/files/6988104/kodi-windows-nas.log)

And here's the log for the Windows version of Kodi accessing a file on a USB device: 
[kodi-windows-usb.log](https://github.com/xbmc/xbmc/files/6988122/kodi-windows-usb.log)

Should I open a new issue with a better title or is it ok to just edit the title for this one?

**Comment by DaVukovic** [comment]
Improvements are seen as "feature requests". Those should be submitted to our forums:

https://forum.kodi.tv/forumdisplay.php?fid=9

To explain, what happens on your logs:

NAS:
Kodi retries to read from that source. And it does that for a couple of times. And for the possibility, that it might get readable again, Kodi will continue the playback. That's the reason why it takes so long. 

So if we would follow this:

> Once the video freezes (since the video buffer has already had time to get empty), show immediately the error message and abort button mentioned in "Expected Behavior".

Kodi won't have the chance retrying to read from that source and users might get annoyed by a dialog because their network has a little hickup. So we should at least give Kodi the option to retry to read from that source. In all other cases one should be simply be pointed at the logfile. But not with a dialog. This can be done with a notification which says "One or more item failed to play. Please check the log for more details". Notifications do have the benefit that the user doesn't need to interact with an additional annoying dialog. 

USB:
Those devices mostly don't need any kind of buffer as there shouldn't be a lag at all. The bandwidth of USB devices should be way enough to play any kind of video. So there's no much buffering at all. This behaviour can be adjusted by using the advancedsettings.xml file. 
If a file stops playing (because the USB drive was removed by accident), a similar notification should be shown, telling the user to check the log. As the log is pretty clear what the issue was:

> CWinEventsWin32::WndProc: Drive F:\ Media was removed.

So...I wouldn't open a new bug report and I also think there's no need to edit the title from this and reopen it as we don't talk about bugs. We are talking about feature requests and improvements. So please create a thread at our forums and explain your wishes over there.
