### ISSUE TITLE
Kodi fails to open, HDMI/resolution related?!

### ISSUE THREAD

**Issue by gbxx69** [xbmc/xbmc#20221]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi fails to open on laptop after using kodi to output via hdmi to Samsung tv. This seems to happen when outputting in 4k
resolution full screen and hdmi cable is disconnected before Kodi is closed. Later on, after kodi is closed (when the cable had been removed prior to closing), Kodi won't open again UNTIL I reconnect the hdmi cable as it assumes hdmi is the only output acceptable to open.
I've also noticed reinstalling the app FIXES the issue completely, BUT this is a crappy work around.. putting the cable back is also a solution, but NOT if your out and about with the laptop and you have no hdmi output device available-- one would have to reinstall to get kodi to work again.. so I'm thinking this is an output resolution issue. FWIW, this is an Acer Nitro 5 series laptop with AMD 4600.  

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Open kodi, connect cable
2. Output to 4k full screen resolution
3. Disconnect cable before kodi in full screen closes, then later close kodi

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
19.1
win10 home

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
You missed to provide a debuglog

Could you please test if the following will solve/workaround your issue as well?

* delete guisettings.xml before opening Kodi again
or
* don't use 4k resolution. Try 1080p for a test.
  * Open Kodi
  * connect cable
  * set to 1080p 
  * disconnect cable

If you try to open Kodi and it won't open, it might be that Kodi crashes (see if Kodi id listed at the taskmanager). If Kodi crashed, there should be a Kodi crashlog. Provide that as well. 

I'll mark this issue as "ignored rules" for the time being because of the missing log
