### ISSUE TITLE
Some MusicBrainz identifiers not exposed via Python API as expected

### ISSUE THREAD

**Issue by Freso** [xbmc/xbmc#20570]
### Describe the bug
Here is a clear and concise description of what the problem is:

Even though MusicBrainz Release and Release Group MBIDs are in both file tags and in Kodi’s database, they are not returned when using the `xbmc.Player.getMusicInfoTag().getMusicBrainzAlbumID()` and `.getMusicBrainzReleaseGroupID()` methods. `.getMusicBrainzAlbumArtistID()` also just returns an empty list.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected `.getMusicBrainzAlbumID()` and `.getMusicBrainzReleaseGroupID()` to return strings with a UUID/MBID, and `.getMusicBrainzAlbumArtistID()` to return a list of at least one UUID/MBID string.

## Actual Behavior

`.getMusicBrainzAlbumID()` and `.getMusicBrainzReleaseGroupID()` returned empty strings, and `.getMusicBrainzAlbumArtistID()` returned an empty list.

### To Reproduce

1. Run code similar to https://gitlab.com/Freso/service.listenbrainz/-/blob/c45d467245a4b4d09e7f334f4cc1d797e268c289/listener.py#L267-268 to inspect the output.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/etipaliwul.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I probably missed something in my PR for these methods when I implemented them in Python: https://github.com/xbmc/xbmc/pull/15849 – alternatively, maybe the C functions are not working, which means that Python is trying to get values from the C API that the C API itself cannot currently get?

Tracking the issue for service.listenbrainz at https://gitlab.com/Freso/service.listenbrainz/-/issues/29

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
This was added to master in https://github.com/xbmc/xbmc/pull/19459

It will be present in Kodi v20.

**Comment by enen92** [comment]
@lrusak unless I misunderstood the issue report I think the op is saying he can't get those 2 infotags from python  
when playing items from the musicdb which likely indicates they are not set in the infotag somewhere around the way. The pr you linked is probably unrelated (set infotags/new API)

**Comment by lrusak** [comment]
> @lrusak unless I misunderstood the issue report I think the op is saying he can't get those 2 infotags from python  when playing items from the musicdb which likely indicates they are not set in the infotag somewhere in the pipeline. The pr you linked is probably unrelated (set infotags/new API)

Disregard then

**Comment by DaveTBlake** [comment]
I think this all arisies from misunderstandings about what is stored in `CMusicInfoTag` and when. This one data structure used in various ways, which made sense back in the day when memory was limited but can confuse people now. Just because `CMusicInfoTag` has a read method for some data does not mean that data is populated. 
 @Freso I think you are expecting `xbmc.Player.getMusicInfoTag()` to return data that it simply was not designed to return.

When scraping metadata from music files all the tag data for a music file is saved in a `CMusicInfoTag` instance. Later for the GUI or API access to data Kodi uses `CMusicInfoTag` instances for a song, album or artist. A song does not have MusicBrainz Release and Release Group MBIDs, these are album data and a song belongs to an album. Similarly the song does not have the artist biography or other artist details such as MBID. 

When JSON API accesses MusicBrainz Release and Release Group MBIDs for the currently playing item (a song) it does so by doing additional processing reading from the database etc., this data is not part of `CMusicInfoTag` for the currently playing item.

**Comment by Freso** [comment]
> A song does not have MusicBrainz Release and Release Group MBIDs, these are album data and a song belongs to an album.

But `CMusicInfoTag`/`InfoTagMusic` does have methods for these… ?

**Comment by DaveTBlake** [comment]
Yes @Freso  `CMusicInfoTag` has set and get methods for all the fields of the class, BUT that does not mean that these fields are always populated with data.  As I said `CMusicInfoTag`  is used in a variety of different ways, which fields have data depends greatly on the use.

The CMusicInfoTag instance returned for currently playing **song** does not have  MusicBrainz Release and Release Group MBIDs field values.
