### ISSUE TITLE
[wayland] refresh rate adjustment doesn't work & doesn't adjust the output

### ISSUE THREAD

**Issue by SupervisedThinking** [xbmc/xbmc#20614]
### Describe the bug
At the moment you can't adjust/match the refresh rate as you can do using X11/GBM

## Expected Behavior
The refresh rate matches the media, you can alter the refresh rate in Kodi settings

## Actual Behavior
Nothing - you can't set the refresh rate.

## Possible Fix
Adopt the wlroots [wlr-output-management-unstable-v1](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-output-management-unstable-v1.xml) protocol in a similar way [wlr-randr](https://git.sr.ht/~emersion/wlr-randr/tree/master/item/main.c) did.

While you run Kodi, or whatever you like, it's possible to adjust the output by `wlr-randr` - all wlroots based compositors should be able to use this protocol e.g. Sway, Wayfire etc. so at least with those compositors Kodi would be able to adjust the refresh rate.

`wl-test:~ # wlr-randr --output HDMI-A-1 --mode 800x600@75`
```
HDMI-A-1 "BenQ Corporation BenQ GL2250 59E00256019 (HDMI-A-1)"
  Physical size: 480x270 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000000 Hz (preferred)
    1680x1050 px, 59.953999 Hz
    1600x900 px, 60.000000 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1280x800 px, 59.810001 Hz
    1280x720 px, 60.000000 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 75.000000 Hz (current)
    800x600 px, 60.317001 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 59.939999 Hz
  Position: 2880,0
  Transform: normal
  Scale: 1.000000
```

`wl-test:~ # wlr-randr --output HDMI-A-1 --mode 1920x1080@60`
```
HDMI-A-1 "BenQ Corporation BenQ GL2250 59E00256019 (HDMI-A-1)"
  Physical size: 480x270 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000000 Hz (preferred, current)
    1680x1050 px, 59.953999 Hz
    1600x900 px, 60.000000 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1280x800 px, 59.810001 Hz
    1280x720 px, 60.000000 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 60.317001 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 59.939999 Hz
  Position: 2880,0
  Transform: normal
  Scale: 1.000000
```
### To Reproduce
Wayland + Kodi -> adjust refresh rate = meh

### Your Environment
Linux kernel 5.15.y
Mesa 21.3.0
LibreELEC master + wlroots/sway: https://github.com/SupervisedThinking/LibreELEC-RR/commits/wl_compositor
Kodi version: https://github.com/xbmc/xbmc/commit/08b7599d63e063545e34a24bb17fc3738cd4dde7
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
 
 @lrusak @CvH since we talked about refresh rate adjustment

**Comment by lrusak** [comment]
@emersion any idea what to do here? AFAIK we have to wait for the wayland protocol to support resolution change requests.

**Comment by SupervisedThinking** [comment]
Is one of those [MR's](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests?scope=all&state=opened&search=%22refresh+rate%22) the needed protocol?

**Comment by emersion** [comment]
Wayland doesn't allow clients to change the refresh rate of the output. This is by design.

There have been discussions about letting clients send a hint about the expected refresh rate of their surface to the compositor. This would let compositors use VRR to match that rate or perform a quick output refresh rate switch if the hw supports it.

**Comment by SupervisedThinking** [comment]
@emersion 

> Wayland doesn't allow clients to change the refresh rate of the output. This is by design.

Wayland as Weston and the "vanilla wayland-protocols"? Because I can use `wlr-randr` to change the refresh rate or at least to tell the compositor to do it. What's the difference between the cli tool or stuff like [wdisplays](https://github.com/artizirk/wdisplays) & Kodi if it comes to this topic? Of course they all depend on wlroots & and compositor based on this lib.

**Comment by emersion** [comment]
The wlroots protocol is designed to be used by system settings and similar UIs. That means that it shouldn't be used by regular clients like video players or games. Access to the protocol will be restricted in the future.

The reason is that changing the output refresh rate changes it for all Wayland clients (it's global state), and can result in a black screen for a few seconds. So we don't want to have random clients do it or clients fight over it.

Kodi is an edge case, because as I understand this issue is about Kodi's settings UI?

**Comment by SupervisedThinking** [comment]
> The wlroots protocol is designed to be used by system settings and similar UIs. That means that it shouldn't be used by regular clients like video players or games. Access to the protocol will be restricted in the future.

But especially clients like games & video players would benefit and most likely those aren't some background processes which go nuts & fight over the screens refresh rate. An easy solution would be to only allow the client in focus to adjust the refresh rate on the active screen, so if you run vlc & some game only on at the time could adjust it. And of course this shoul be an opt-in.

> The reason is that changing the output refresh rate changes it for all Wayland clients (it's global state), and can result in a black screen for a few seconds. So we don't want to have random clients do it or clients fight over it.

Well IMHO sounds more like a theoretical problem than an actual one. The amount of clients that usually change the refresh rate is most likely pretty low? With X11 I could run `xrandr` in scripts to change it on the fly e.g. to adjust the rate for NTSC/PAL emulation or whatever was needed.

> Kodi is an edge case, because as I understand this issue is about Kodi's settings UI?

Kodi can adjust the refresh rate on the fly to match the media e.g. at start & stop of a movie with 23.976FPS it would change the panel refresh rate to 29.976Hz to avoid stuttering, this works flawless on X11/GBM.

**Comment by emersion** [comment]
I won't continue to argue here, I've done it countless times already elsewhere.

But one thing is clear: it's not appropriate for Kodi to use this wlroots protocol.

**Comment by SupervisedThinking** [comment]
What's the appropriate solution then?

**Comment by CvH** [comment]
> The reason is that changing the output refresh rate changes it for all Wayland clients (it's global state), and can result in a black screen for a few seconds. So we don't want to have random clients do it or clients fight over it.

So just allow fullscreen programs to adjust the refresh rate is not a proper fix ? Wondering why this works without noticeable problems at X11, Windows, Android ...

Also sway supports variable refresh rate, those major features get removed too ? Its basically the same feature. Sounds very strange if you ask me.

From user perspective this is horrible overall, you want a working desktop and not a half assed alternative. 
Currently it sounds like kodi is doomed to not work properly at wayland, what a bright future :(

**Comment by ngrigoriev** [comment]
My external monitor can do 60Hz (3840x1600) but I know that my laptop, no matter if I use HDMI or USB-C hub, can only do 30Hz on this monitor. On X11 setting 30Hr refresh rate would fix the flickering and allow using of the monitor. With Wayland I seem to be stuck at 60Hz, unable to set the mode I want.

**Comment by toupeira** [comment]
> But one thing is clear: it's not appropriate for Kodi to use this wlroots protocol.

It seems like Kodi on X11 shells out to `xrandr` to change the refresh rate, as I see this in `kodi.log`:

```
info <general>: XRANDR: /app/lib/kodi/kodi-xrandr --screen 0 --output DP-1 --mode 0x4f
```

(I'm using the Flatpak version, which bundles its own version of `xrandr`)

If that's the case, I guess on Wayland Kodi could shell out to similar tools like `wlr-randr`? So it wouldn't be Kodi using the `wlr-output-management-unstable-v1` protocol directly, but rather calling a dedicated configuration tool, which presumably would be permissible?

Of course there's still the problem that `wlr-randr` only works on wlroots-based compositors. KDE has its own protocol `kde-output-management` (and `kde-output-management-v2`), and GNOME offers a DBUS protocol `org.gnome.Mutter.DisplayConfig` which tools like [`gnome-randr-rust`](https://github.com/maxwellainatchi/gnome-randr-rust) use.

It's sad to see this fragmentation, and I guess it would be silly for Kodi to try and support all these different protocols. Maybe DEs will agree on a shared protocol at some point? Or maybe somebody will write a generic `xrandr`-like tool that supports all of these protocols?

**Comment by in-plaintext** [comment]
^ There's also [gnome-monitor-config](https://github.com/jadahl/gnome-monitor-config/) for Wayland users, which has been packaged for Fedora.

**Comment by bam80** [comment]
> I won't continue to argue here, I've done it countless times already elsewhere.
> 
> But one thing is clear: it's not appropriate for Kodi to use this wlroots protocol.

@emersion I think the followed up comments still need your response, especially the last one.
Sorry if you have the answers elsewhere, would you like to enlighten us?

**Comment by emersion** [comment]
The intended way on Wayland to change the refresh rate is for the user to configure it in their compositor configuration file. Wayland _by design_ doesn't let regular apps change a screen's refresh rate or mode, because this results in a full modeset (black screen for a few seconds), results in apps stepping on each other's toes, results in apps overwriting the user's preferences, and behaves badly when the fullscreen mode isn't exactly the traditional fullscreen mode that apps are used to (some compositors allow fullscreen multiple outputs, some split fullscreen with multiple apps, etc etc).

There are other ways to improve refresh rate handling for video players, without giving direct modeset access to all regular clients. See e.g. https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/22

Sway now blocks the `wlr-output-management-unstable-v1` protocol for Flatpak apps, and we will continue to tighten the security rules.

Shelling out to `wlr-randr` doesn't help. Using an external tool is equivalent to directly using the protocol from the compositor's perspective, since it would be running in Kodi's security context. Either way, the matter of fact is that the compositor-specific APIs to configure outputs is not for use by regular clients.

**Comment by bam80** [comment]
> The intended way on Wayland to change the refresh rate is for the user to configure it in their compositor configuration file. Wayland by design doesn't let regular apps change a screen's refresh rate or mode, because this results in a full modeset (black screen for a few seconds), results in apps stepping on each other's toes, results in apps overwriting the user's preferences, and behaves badly when the fullscreen mode isn't exactly the traditional fullscreen mode that apps are used to (some compositors allow fullscreen multiple outputs, some split fullscreen with multiple apps, etc etc).

Whether it's Wayland protocol or DBus protocol - it doesn't change the point:
there should be a standard way for apps to communicate to Compositors the desired refresh rate/mode.
In case of DBus, the "black screen" problem you mentioned is probably easy solvable as it's backed by Polkit (if that problem exists at all).
And even if it's not, it doesn't cancel the need of such common protocol/API.



> There are other ways to improve refresh rate handling for video players, without giving direct modeset access to all regular clients. See e.g. https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/22
> 
> Sway now blocks the `wlr-output-management-unstable-v1` protocol for Flatpak apps, and we will continue to tighten the security rules.

Before blocking something, it reasonable to provide the alternative first.
As I can see, neither from the link above was implemented yet?

The wording "There are ways to improve refresh rate handling for video players" raises concerns:
are you claiming these ways are fully fulfill our needs? Half measures won't probably work here.

**Comment by fooishbar** [comment]
> There have been discussions about letting clients send a hint about the expected refresh rate of their surface to the compositor. This would let compositors use VRR to match that rate or perform a quick output refresh rate switch if the hw supports it and the surface is fullscreen.

This comment has the important part.

We want people to be able to display content as intended, which includes matching refresh rate where appropriate. This is best done by the surface declaring the ideal refresh rate of its content, allowing the compositor to switch the native refresh rate to match.

'I want a script which changes the refresh rate of the current output until the session is restarted' is the wrong hammer for this nail.

**Comment by bam80** [comment]
There can't be a wrong hammer as long as you took out all the instruments.

**Comment by fooishbar** [comment]
Yes, we don't have the per-surface refresh-rate stuff right now. Getting help and contribution from people who care about media players would be extremely welcome to get this.

But as you've discovered, we also don't have a universal output-control protocol, and never will, so if we keep stretching this analogy then you're arguing over two theoretical hammers. Or something.

**Comment by benjamindaines** [comment]
At this point the proper action would be to go up stream and try to get whatever functionality is necessary to have kodi work properly added into wayland in order to have the same functionality that is available when using x.  Then kodi can support the functionality without debating whether or not one should use a hammer or not do the job when they don't have the screwdriver they need.

**Comment by tamodolo** [comment]
> At this point the proper action would be to go up stream and try to get whatever functionality is necessary to have kodi work properly added into wayland in order to have the same functionality that is available when using x. Then kodi can support the functionality without debating whether or not one should use a hammer or not do the job when they don't have the screwdriver they need.

VRR support should be enough to solve this. Those who want to use this do it because one have a 24Hz capable of even cadence. This is mostly achieved by 120Hz native TVs nowadays that also supports HDMI Forum VRR.

One can consider just running at 120Hz mode as it is a common multiple of many common video speed. But we all know that GPUs miss delivering timing God knows why making the experience much more chopier. Propper VRR should solve that.

I know this issue is closed as not planned but this feature is actualy desired.

**Comment by fooishbar** [comment]
> At this point the proper action would be to go up stream and try to get whatever functionality is necessary to have kodi work properly added into wayland in order to have the same functionality that is available when using x.

This one. Anyone who is interested in driving this forward and is willing to work on the protocol definition and implementation, ideally as well as at least one compositor implementation, please ping me (here, or daniels on fd.o GitLab, or daniel@fooishbar.org), and I’ll happily walk you through the Wayland specifics and signpost you to others who can help.

**Comment by AverageHoarder** [comment]
I'm surprised that there is still no way for an application to switch the refresh rate in wayland.. 3,5 years down the road. It's such a fundamental feature for cinephiles who don't use the latest hardware (with gsync, freesync etc.).

I actually wanted to use Linux for my htpc (mainly used for kodi + mpv) 1,5 years ago but the lack of this feature in wayland (and another similarly misguided decision in mpv) forced me to use Windows instead. On Windows, frame rate matching/switching is easily achieved in Kodi as well as in mpv (via [this plugin](https://github.com/CogentRedTester/mpv-changerefresh)).
Since my htpc is unsupported by Windows 11 but still capable of playing anything I want, I thought I'd give Linux another shot. My expectation was that there has to be a way to achieve framerate matching/switching in wayland by now (even if it's hacky).

After reading this thread, I'm considering to simply remove the gateway from my Windows 10 htpc once the support ends instead of switching it to Linux.

Having choppy playback of my media or using half-assed "solutions" like frame interpolation, audio transcoding or having to manually check the refresh rate and then manually changing it for every single thing I watch is a deal-breaker for me.

It's hilarious that in Linux a user can easily run something like `sudo rm -rf /*` but wayland draws the line at: A fullscreen application wants to change the TV refresh rate to 23.976Hz to match the video fps.

**Comment by bam80** [comment]
I wonder how this problem is solved on mainstream Smart-TV devices based on Tizen, WebOS, etc.?
AFAIK, all of them use Wayland with possibly downstream extentions.

Maybe that extentions do the job, among other things?
Some research might be needed.
It should help that beforementioned OSes are all quite open nowadays..

**Comment by bibitocarlos** [comment]
Nothing is solved, linux+wayland doesnt allow any kind of switching refres rate, kodi doesnt allow to double all refresh rates ( not only 30 and 50 fps) to match VRR range, and people without VRR ( does it work with hdmi ln linux ?) are stuck with an issue long solved on other platform.

**Comment by BieJay93** [comment]
For those of us who were using Kodi on Gnome with X11 and now are "blessed" with Wayland because of the latest Gnome update:
I wrote a little addon for Kodi, which uses gdctl to automatically switch display refresh rates on playback start/stop:
https://github.com/BieJay93/Kodi-Refresh-Rate-Switcher

**Comment by dariusmiles2123** [comment]
I think it should be written in Kodi's Wiki (https://kodi.wiki/view/Settings/Player/Videos#Adjust_display_refresh_rate) that Wayland doesn't allow refresh rate adjustement.

I had to ask for help to know where the issue was coming from.

**Comment by tamodolo** [comment]
> I think it should be written in Kodi's Wiki (https://kodi.wiki/view/Settings/Player/Videos#Adjust_display_refresh_rate) that Wayland doesn't allow refresh rate adjustement.
> 
> I had to ask for help to know where the issue was coming from.

I think that's probably for the better. While some 60 Hz TVs has perfect candenced 24 Hz mode these TVs are very old now. The vast majority of TVs that have a true 24 Hz mode also have a native 120Hz. Playing 24 Hz over 120 Hz container is a problem only on Windows where switching modes can solve the horrible incorrect video cadence caused by whatever windows is doing.

Adding to this, wayland blocking screen mode switch can be actually good because KODI does not allow this to be disable when HDR content is played while in SDR mode triggering a mode switch. In case of Wayland, SDR content is supperb on HDR mode and much more desirable over native TV's SDR. This limitation blocks KODI from switching to the worser mode to play SDR content witch is very good.

**Comment by dariusmiles2123** [comment]
I clearly don’t have the knowledge to know if it’s good or bad. I just think that Kodi should gove you the information that Wayland doesn’t allow such a thing.

**Comment by AverageHoarder** [comment]
> I think that's probably for the better. While some 60 Hz TVs has perfect candenced 24 Hz mode these TVs are very old now. The vast majority of TVs that have a true 24 Hz mode also have a native 120Hz. Playing 24 Hz over 120 Hz container is a problem only on Windows where switching modes can solve the horrible incorrect video cadence caused by whatever windows is doing.
> 
> Adding to this, wayland blocking screen mode switch can be actually good because KODI does not allow this to be disable when HDR content is played while in SDR mode triggering a mode switch. In case of Wayland, SDR content is supperb on HDR mode and much more desirable over native TV's SDR. This limitation blocks KODI from switching to the worser mode to play SDR content witch is very good.

You completely disregard the fact that there are also 25/50fps videos that aren't displayed stutter-free on 60 or 120Hz.
Switching the refresh rate for TVs that don't have vrr is essential for many people, regardless of their TV's age.

I also don't think that displaying SDR in the HDR mode of a TV is inherently better. Rather the opposite. Calibrating a TV in HDR mode ranges from hard-to-do to being impossible or inaccurate. Meanwhile it's easily achievable in SDR mode with a colorimeter.

I personally prefer to watch my SDR movies at the exact frame rate of the media and with correct colors.

At least on KDE this is fairly easy to achieve with [kscreen-doctor](https://linuxcommandlibrary.com/man/kscreen-doctor) and global hotkeys.
With mpv as the external player in Kodi, I start playback, press `i` to see the correct refresh rate and then set my TV to that mode.
Memorizing
```
ctrl+alt+1=60hz
ctrl+alt+2=23.976hz
ctrl+alt+3=24hz
ctrl+alt+4=25hz
ctrl+alt+5=50hz
ctrl+alt+0=HDR on/off
```
isn't that hard. Additionally I have set up mpv to use a color correction mode only when videos are SDR.

That way I get smooth playback of all my media, color correct SDR and normal HDR.

This even has the advantage over letting Kodi/mpv switch the refresh rate that for TV shows I only have to switch the mode once and can binge however many episodes I want.

**Comment by toupeira** [comment]
> At least on KDE this is fairly easy to achieve with [kscreen-doctor](https://linuxcommandlibrary.com/man/kscreen-doctor) and global hotkeys.

FWIW, Gnome also has the `gdctl` CLI tool which lets you change modes, refresh rates, and color settings.

**Comment by STPKITT** [comment]
See [https://github.com/xbmc/xbmc/issues/20614#issuecomment-3343263383](url) for a Kodi addon using gdctl.
