### ISSUE TITLE
KODI 19.3 cannot show the CPU info on Firetv 4k Max

### ISSUE THREAD

**Issue by sunanan** [xbmc/xbmc#20619]
### Describe the bug
On Firetv 4k Max, the system info of KODI 19.3 does not show the CPU info. all info is empty.
the info is showing in Kodi 18.9 on Firetv 4k Max.

## Expected Behavior
Show Cpu info

## Actual Behavior
Cpu info is empty.

### Screenshots 
Here are some links or screenshots to help explain the problem:
![WechatIMG2](https://user-images.githubusercontent.com/5479289/144353338-6358adba-b353-4af7-a1ac-484c2741b1e6.jpeg)

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Firetv 4k Max, Android 9
 - Kodi version: 19.3, armv7a 
 - Kodi nightlies version: kodi-20211129-01079c43-Matrix-armeabi-v7a

**Comment by enen92** [comment]
Log file?

**Comment by GGNIGHTSTIKE** [comment]
Mine shows the samething and the memory also shows 100% full why is this happening

**Comment by quietvoid** [comment]
Can confirm the hardware info being empty, but memory is fine for me.  
Log: [kodi.log](https://github.com/xbmc/xbmc/files/7650100/kodi.log)

I don't think there's anything useful in there, though.

**Comment by enen92** [comment]
Looks like this is caused by the cpuinfo rework by @lrusak  (https://github.com/xbmc/xbmc/pull/16098)
Android was probably using the Linux path in the past. However the regression itself might be intentional, the Android platform should use the android API for that info as much as possible. Kodi doesn't have an android maintainer at the moment so we might well have to deal with it until someone steps up and contributes the feature back (properly) :)
