### ISSUE TITLE
Locked source state not honored in favorites

### ISSUE THREAD

**Issue by CursedDevelopment** [xbmc/xbmc#20687]
### Describe the bug
Usually, media from locked sources aren't even shown to the user unless the source is unlocked first. But if you favorite such media, they are displayed despite of the lock state and are freely accessible while the source is locked.

## Expected Behavior
A favorite from a locked source should not be visible unless the corresponding source was unlocked first (or master mode is enabled).

## Actual Behavior
Locked but favorited media is always visible and is played without having to unlock the source first.

## Possible Fix
Either don't show these favorites unless their source was unlocked or master-mode was enabled (preferred solution).
Or at least present the user with the appropriate unlock dialog before playing.

### To Reproduce
1. Favorite a movie
2. Lock the source of the movie
3. Access your favorites
4. See/Play the locked title

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 10.0.1
 - Kodi version: 19.3

**Comment by DaVukovic** [comment]
I did a quick look at this and AFAICT, there's no setting written if one locks a source. 

![image](https://user-images.githubusercontent.com/7235787/146677248-19019c0c-33a8-4f60-b4c6-19d7083c2998.png)

The only written setting I could find is in profiles.xml:`<lockmode>1</lockmode>`

While using the lock settings, one is able to lock "settings", "video" and such and we do have a tag for that at profiles.xml: 
```
        <lockfiles>false</lockfiles>
        <lockmusic>false</lockmusic>
        <lockvideo>false</lockvideo>
        <lockpictures>false</lockpictures>
        <lockprograms>false</lockprograms>
        <lockgames>false</lockgames>
```
But we do not have anything for "sources".
As we don't have this setting, I guess we currently can't do anything quick to fix it, as it would probably mean, that we need a new boolean-condition to check for: https://kodi.wiki/view/List_of_boolean_conditions

So I`m not sure if this is more a feature request rather than a bug report.

@CursedDevelopment What would you expect if the locked state would be honored in favourites? Just don't display the items from locked sources?

**Comment by CursedDevelopment** [comment]
@DaVukovic every locked source has a lockmode and lockcode assigned in ~/.kodi/userdata/sources.xml. As for the expected behavior - as stated above, it should reflect the same behavior as is currently used in the movies / tv series section. Titles are not shown at all until the corresponding source was unlocked (or master-mode was enabled which implicitly unlocks all sources).

**Comment by howie-f** [comment]
@CursedDevelopment i've uploaded a build for you to test
https://drive.google.com/drive/folders/1o0viNcyr91b06V5GLeAsRBMv1pJ1Mkcb

it is a patched LibreElec 10 for RPi4/arm. any feedback appreciated

**Comment by CursedDevelopment** [comment]
@howie-f This is a start. Attempted playback now at least asks for the unlock code; providing the correct code will unlock the media source (which will remain unlocked after playback).
Restricted media remain visible to everyone (both for already existing and newly added favorites).

**Comment by howie-f** [comment]
ok, new version up if you would like. location is the same
