### ISSUE TITLE
Startup crash, error "sglSwapBuffers failed (EGL_BAD_ALLOC)

### ISSUE THREAD

**Issue by raananelefant** [xbmc/xbmc#20782]
---

### Describe the bug
Here is a clear and concise description of what the problem is:

Ran fine a few times, now crashes on startup.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should start.

## Actual Behavior

Doesn't start.

### To Reproduce

1. kodi <Enter>
2. Fail! :)
3. Rince and repeat ;)

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Latest Raspian (Bullseye)

 - Kodi version:

19.3 (19.3.0) Git:20211118-a22c0ba337

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by raananelefant** [comment]
Added debuglog, please reevaluate bug.

**Comment by lrusak** [comment]
Debug log doesn’t show anything (including the failure). You should use some form of pastebin when posting logs (https://paste.kodi.tv/)

**Comment by raananelefant** [comment]
I'm not recieving new logs following these instructions: https://kodi.wiki/view/Log_file/Advanced

Could you attach .xml files which will make logs?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DaVukovic** [comment]
If Kodi crashes (in meaning it closes itself) it should create a crashlogfile in your users home directory. Is that the case? If so, please provide the crashlog on the mentioned paste site. 

I've removed the log above. The label stays until you provided a usefull log on a paste site. 

Thanks in advance.

**Comment by raananelefant** [comment]
Unfortunately no, that's not the case. ~/.kodi/userdata/ contains old logfile.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DaVukovic** [comment]
> ~/.kodi/userdata/ 

That's not the home directory of your user. That's most likely: `/home/<username>/

**Comment by raananelefant** [comment]
I'm on linux, so yes, ~/.kodi/userdata is the correct dir, sir :)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DaVukovic** [comment]
> I'm on linux, so yes, ~/.kodi/userdata is the correct dir, sir :)

That's not true

![image](https://user-images.githubusercontent.com/7235787/149566796-aa529ce7-e6cb-4602-b5b0-4e0dfe96c05e.png)

As you can see (and I'm on Linux as well) that's my home-directory and that contains crashlogs. It might be, that there are no crashlog-files in your users home directory. If that's the case, that would simply mean that Kodi is not crashing. 

It might also be the case that raspbian stores the crashlog on  a different location. Then simply search for that:

`find $HOME -regex ".*crash.*.log"`
or
`find / -regex ".*crash.*.log"` which might need additional permissions due to searching in `/`

Both commands will perform a recursive search. 

Be aware that we will close this issue on sunday as there's no useful log provided.

**Comment by raananelefant** [comment]
Realized earlier you are right, sorry

Sent from ProtonMail mobile

-------- Original Message --------
