### ISSUE TITLE
Kodi doesn't add new episodes of existing shows to library

### ISSUE THREAD

**Issue by stantond** [xbmc/xbmc#20954]
### Describe the bug
Here is a clear and concise description of what the problem is:

Once a TV show has been added to the library, Kodi is unable to detect newly added episodes. It can only detect newly added TV shows.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Library scans should detect new episodes and add them to the library.

## Actual Behavior

New episodes are not detected.

## Possible Fix

Manually browse to the file in file browser to play the video.

### To Reproduce

1. Have TV Shows already in library
2. Add a new episode to storage with correct naming in the correct folder
3. Trigger a library update, manually or by exiting and reopening Kodi.

### Debuglog

The debuglog can be found here:

Will add shortly

### Screenshots
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - Operating system version/name: Android TV (Nvidia Shield)
 - Kodi version: 19.x (most recently 19.3)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Please take your query to the forum. Kodi has no problems adding new episodes as I do that often.

Remember to provide a debuglog that captures the issue.

**Comment by killemov** [comment]
Running Kodi 19.4 on a Pi with a Sickchill setup on a NAS and this happens to me too on a rare occasion. The missing episode just would not be added using any regular update method so I'm glad the refresh metadata hack works.

In my case it is a show by airdate. With the same show the episode of the day before is fine and the episode of the day after is fine. I removed the episode including metadata and had Sickchill re-add it. Still not picked up by Kodi. Hope this helps.

@KarellenX I dislike the given dismissive reply. Just because it did not happen to you, yet ... And how would you capture something that does not happen?

**Comment by KarellenX** [comment]
>Just because it did not happen to you, yet 

I've been using Kodi for over 10 years, and this Issue is from two years ago. If it was going to happen, it certainly would have happened by now, don't you think? Where are the millions of other complaints if this was truly a problem with Kodi?

Have you checked what is happening at the scraper site?
Where is your debuglog so I can determine what you are doing wrong?
You can see I asked the other member to head over to the forum. Why don't you do the same?

**Comment by killemov** [comment]
> > Just because it did not happen to you, yet
> 
> I've been using Kodi for over 10 years, and this Issue is from two years ago. If it was going to happen, it certainly would have happened by now, don't you think? Where are the millions of other complaints if this was truly a problem with Kodi?

It is a very minor issue and it hasn't happened to me in years. Most people just don't care at all and watch the episode through the file browser. @stantond Went a lot further not just by finding a fix, but also posting it here.

> Have you checked what is happening at the scraper site? Where is your debuglog so I can determine what you are doing wrong?

I can't reproduce it now. The weird part is when I removed the episode again from Kodi and rescanned, the episode just shows up like it was supposed to in the first place.

> You can see I asked the other member to head over to the forum. Why don't you do the same?

To see topics like this with some very strange workarounds? https://forum.kodi.tv/showthread.php?tid=215316

The fix(?) posted here works and has the least amount of hassle.
