### ISSUE TITLE
Remove Categories widget and default to Titles on TV Shows/Movies

### ISSUE THREAD

**Issue by oliroe** [xbmc/xbmc#21133]
### Describe the bug
Here is a clear and concise description of what the problem is:

Currently (19.4) when you remove the Categories widget selecting TV Shows or Movies from the main menu takes you to Categories (Genres, Titles, Years etc). It's not possible to go straight to Titles

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect to be able to remove both the Categories widget and not then have to select the category when selecting TV Shows/Movies. Either that or have the option of selecting a default and bypass the selection screen

## Actual Behavior

Selecting TV SHows/Movies when the Category widget is disabled requires you to then select a category

## Possible Fix

Give the ability to default a category

### To Reproduce

1. Disable Category Widget
2. Select TV Shows or Movies
3.

### Debuglog

The debuglog can be found here:
Debug log not required

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Screenshot not required

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4

 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
This is not a bug. That´s by design. 

If we are going to change that, others will complain that there´s no way to reach the categories instead of going to the movie listing and then use the `..` to get one level up. 

If you then also disable the "Show parent folder items" setting, then you don´t have the option to reach the categories anymore. 

In case you want to customize the skin yourself as you might feel this is somewhat wrong (which is ok ;) ), please have a look at this section:

https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Home.xml#L907-L908

You can either modify line 907 that it also contains the `titles/` or you can remove the conditions completely (delete line 907 and 908) and use this onclick then:

` <onclick>ActivateWindow(Videos,videodb://movies/titles/,return)</onclick>`

**Comment by oliroe** [comment]
Appreciate it isn't a bug, just my personal preference that I don't want to use the categories at all.

Really appreciate your detailed response and I'll make the change manually

Thanks again
