### ISSUE TITLE
Windows Kodi freezes in menu access when network share is mounted but inaccessible

### ISSUE THREAD

**Issue by amosstorkey** [xbmc/xbmc#21191]
### Describe the bug
Here is a clear and concise description of what the problem is:

When a windows network drive is mounted but not accessible, kodi freezes for about 20-40 seconds on menu traversal at any point that requires file or directory access, and takes aver 30 secs to boot up. This happens even if that network drive plays no part in the kodi installation - i.e. no library items or file mounts in kodi are at that network location. The mere existence of the share on the device is sufficient to scupper kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Mounted but inaccessible drives on a windows machine is normal in many settings (portable devices, drives dependent on VPN, kerberos authenticated shares etc). Kodi should not be rendered inoperable in such settings. No other applications suffer from this deficit, so this seems to be a kodi implementation issue. Kodi should smoothly move through menu items independent of an unrelated setup regarding the windows network.

## Actual Behavior

Kodi is rendered unusable as it stalls at every menu item or traversal involving directory or file access: going in to any main menu item, into files, into settings etc. The stalls are significant - generally 10-20 seconds, but sometimes longer.

## Possible Fix

Sadly I do not know the cause of this at this time.

### To Reproduce

1. Mount a network drive in windows.
2. Detatch the machine with the mounted drive from the network
3. Perform a fresh install of kodi
4. Load kodi
5. Traverse kodi menus, especially menus that require drive access (e.g. Music Menu, Settings: Files menu or other such menus).

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/amurejirut.kodi

Vanilla kodi install
Log details:
12:03:18 - disconnect mounted windows network drive - everything fine before then
12:03:45 - first freeze (> 1 min)
12:05:33 - second freeze (22 secs)
12:06:31 - third freeze (22 secs)

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This bug renders kodi effectively inoperable.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 19.4 fresh install, no user addons. Git 20220303-e12e66e019

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Seems that delay is caused due use `GetVolumeInformationW` for network drives (mapped shares) here:

https://github.com/xbmc/xbmc/blob/426bd7ebf776b9b5e6b0ef47f0b3865b7ed1974d/xbmc/platform/win32/storage/Win32StorageProvider.cpp#L204

I'm testing alternate method to use "remote name" instead of "volume name" on remote drives.

Y: is a unavailable network drive ---> volume name cannot be obtained 

Volume name:
![Captura de pantalla 2022-03-27 104440](https://user-images.githubusercontent.com/58434170/160274402-3e1f1b9e-75b7-499d-bfe0-2177f6c9d454.png)

Remote name:
![Captura de pantalla 2022-03-27 103846](https://user-images.githubusercontent.com/58434170/160274409-44269df4-2f52-40a7-a434-77e80b97a608.png)

In my case I can only reproduce delays of 5-6 second in any case. I'll do a test build to confirm it's the same issue.

**Comment by thexai** [comment]
master v20 test build:
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220327-2e980de0-fix-remote-drives-x64.exe
