### ISSUE TITLE
Auto refresh rate switching is broken for .ts files after PR #21372 also .m2ts (AVCHD, DVD, Blu-Ray, etc.)

### ISSUE THREAD

**Issue by smp79** [xbmc/xbmc#21447]
### Describe the bug
Here is a clear and concise description of what the problem is:

Auto refresh rate switching  stopped working for  any .ts files  when "Adjust refresh rate" is set to "On start/stop". It now only works when it is set to "Always". 

## Possible Fix

Reverting #21372 fixed it.

### To Reproduce

1.  Play any .ts file. Like [this one here](https://www.dropbox.com/s/6r4nja2jewgxjup/50i-MBAFF.ts?dl=1).

### Debuglog

The debuglog can be found here:
[Debug log](https://www.toptal.com/developers/hastebin/ibehiyusox.yaml)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
The PR you mention is not the rootcause. The issue is your TS file (mbaff, interlaced). The tsparser does not know before hand and fails to parse it properly on stream start.

See:
2022-05-24 19:25:30.479 T:1009    DEBUG <general>: CRenderManager::Configure - change configuration. 1920x1080. display: 1920x1080. framerate: 0.00.

with old behaviour you most likely heard / have seen the file for a split second and then only refreshrate switched.

Fix the tsparser would be the best solution. As kodi is in "workaround mode" -> don't go into the reconfigured state when refreshrate deteced was 0.

**Comment by CastagnaIT** [comment]
i confirm before was "working" because the fps of the video were detected during playback and not at start of playback
then that PR highlights that the problem come elsewere as @fritsch mentioned

I am about to add a new start/stop setting to allow VFR videos
and this will restore the workaround for your case, but the problem is still not solved at root

**Comment by thexai** [comment]
Confirmed and reproduced in Windows x64 and Xbox. Is broken in both master and **Matrix**.

Is broken for TS streams (PVR add-ons), and M2TS stream (DVD, AVCHD, Blu-Ray, etc.) at least when is playing from .m2ts files directly:

**This is with "adjust display refresh rate at Start/Stop"**
![screenshot00002](https://user-images.githubusercontent.com/58434170/170661511-22e571d6-dd48-47ee-a211-2071e62f2563.png)
