### ISSUE TITLE
Subtitle setting Bottom of Video

### ISSUE THREAD

**Issue by bokkoman** [xbmc/xbmc#21555]
### Describe the bug

The subtitle position setting `Bottom of Video` is not actually the bottom of the video. 
Looks more like bottom of the screen.

## Expected Behavior

For the option `Bottom of Video` I expect the subtitle to be on the bottom of the video.
Now when the aspect ratio is not 16:9, the subtitle will appear half in the black bar or completely in black bar. 

## Possible Fix

Instead of taking the screen resolution, use the video resolution.
And make the bottom of the video option behave as it describes. 

### To Reproduce

1. Set subtitle position to bottom of video. 
2. Play movie/show with aspect ratio other 16:9, 21:9 for example
3. See how subtitle is not on the bottom of the video. 

### Your Environment
Used Operating system:

 - [x] Android Nvidia Shield Pro
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
only in some cases the subtitle engine have the ability to understand where the black bands are
depends on how the video has been encoded

since many people complained about that the default subtitles position being too high
then having by default a more bottom position of subtitles is intended for v20

but i also see the difference between kodi 19/20 position setting
ATM i do not remember if this is something that can be reintroduced

**Comment by bokkoman** [comment]
IMO, it doesn't matter if the video is encoded with black bars or without. It should be possible to know what the bottom of the video is, since it can read the resolution of the video. For example a 4k movie with aspect of 2.39:1 `4096x1716`, does not fill complete screen. Most movies are not encoded with black bars, or removed.
The player should be able to read the lowest pixel of the video, and put the subtitles an X offset from there.
In Kodi 20, this offset can be set, which is fantastic! Unfortunately, like my issue describes, it puts the offset from bottom of screen instead of bottom of video.

**Comment by CastagnaIT** [comment]
ofc implicitly i also meant cropping case
but doing so is not so simple, the engine is entirely changed from kodi 19

pointing out variable names does not change anything
it needs to be figured out if this function can be reintroduced in some way,
otherwise we would have to rename the position settings entries to avoid misunderstandings

**Comment by bokkoman** [comment]
They want to align to screen. To keep the subtitles in correct AR, not deformed.

Is there no way they can apply the AR of video to the subtitles? Or use the AR of screen, but use the offset of the video?

**Comment by CastagnaIT** [comment]
> Then found this:
> 
> { // We should have a re-encoded/cropped (removed black bars) video source. // Then we cannot align to video otherwise the subtitles will be deformed // better align to screen by keeping the aspect-ratio. m_align = ALIGN_SCREEN_AR; m_width = static_cast<float>(o->width); m_height = static_cast<float>(o->height); m_source_width = static_cast<float>(o->source_width); m_source_height = static_cast<float>(o->source_height); }
> 

this code has nothing to do with this, is for images subtitles

"bottom" for subtitle engine means text aligned from bottom only, not means "inside video"
margins/position or other that influence the position is set by:
the "vertical margin" is considered to shift subtitle text from top/bottom aligned text (also for forced tags)
the ass_set_margins to set frame margins
the line "position" to shift text from bottom despite all margins sets

i tried change ass_set_margins but without success for now
IMO the vertical margin cannot be used for this use case its a style type not in rendering scope
and the line "position" should not be influended from external factors like resolutions

**Comment by bokkoman** [comment]
Can you point me to the file that handles regular subtitles (like .srt?)

I know bottom means bottom. But saying `Bottom of Video` is not equal to `Bottom of Screen`. There is a difference in that, which can be quite large :P

**Comment by CastagnaIT** [comment]
kodi 20 has differents behaviour of subtitle position setting than kodi 19,
just for the sake of clarity, current meaning in Kodi 20 of position setting:

`Bottom of Video` -> Means text aligned from bottom, nothing else
`Below video` -> Means (if possible) text inside the bottom black bar

instead on Kodi 19:
`Bottom of Video` -> Means text aligned from bottom, but inside video
`Below video` -> Means (if possible) text inside the bottom black bar

since in kodi 20 the subtitle engine is changed,
reintroduce the kodi 19 behaviour is not so simple and not sure it is possible

for text subs the rendering part of our interest is in OverlayRenderer.cpp and DVDSubtitlesLibass.cpp

**Comment by bokkoman** [comment]
I knew about that behaviour.
I never liked the `Bottom of Video` in Kodi 19, because it was too close to the actual bottom, almost touching the edge.

Now Kodi 20 introduced that offset setting in percentages. Which is exactly what I wished for, for a long time. But now they decided to change the behaviour of `Bottom of Video` :(

Is there no possibility to make another align setting, `Bottom of Screen` would be the current Bottom of Video.
Then change `Bottom of Video` to actually do what it says, be on the bottom of the video like in Kodi 19. But not like the Kodi 19 engine, but with Kodi 20 engine?

**Comment by CastagnaIT** [comment]
so if i understand correctly, you would like to do:
`Bottom of Video` -> restored as Kodi 19 behaviour
add new `Bottom of Screen` -> to kept the current Kodi 20 behaviour

yes the idea could be good
if a solution can be found without apply hacks

**Comment by CastagnaIT** [comment]
building and debug is not something that can be explained is two words,
if you like to learn there are documentation: https://github.com/xbmc/xbmc/tree/master/docs
guidelines, and doc for each operative system

if you have no experience, it is best that you wait for us to evaluate the situation,
which is what i am already doing

> Which file does the SRT handling, OverlayRenderer.cpp or DVDSubtitlesLibass.cpp?
> And which file has the subtitle alignment options?

both, is not for SRT only, but all text subtitles types and propertary ass/ssa

**Comment by bokkoman** [comment]
> if you have no experience, it is best that you wait for us to evaluate the situation,
> which is what i am already doing

Thank you, that you put this higher up! If there is anything I can help with, like testing, I'd be more than willing.


> both, is not for SRT only, but all text subtitles types and propertary ass/ssa

Ok, I see. Of course I want ASS/SSA untouched. They already work as intended.

**Comment by CastagnaIT** [comment]
@enen92 after asked to libass i understand how to do, this is a test:
https://github.com/CastagnaIT/xbmc/commit/a47baadd6601428c8ea8c250ded84ad1dd75c035
(to replicate it, change vertical margin to 0, and set "Position on screen" to "bottom of video", play a cropped video with a SRT)

however, reimplement in this way the old "bottom of video" of kodi 19, leads to some side effects:
- all libass things are rescaled, the most obvious one is the font size that no longer match the user settings
- set ass_set_storage_size by using the frame size is fine as long as the frame has the right proportions with video size, e.g. if you resize kodi window very narrow in width then you can see the text not match the video position anymore

the result is this:
![immagine](https://user-images.githubusercontent.com/3257156/178280943-ef0a493d-ab31-4f60-9ff8-615c6758c075.png)
as you can see the text size will result different (the correct font size is the white text i added above)

if you have any ideas in the basket i will be waiting,
otherwise we just rename the text of the items of "Position on screen" setting to avoid misunderstandings, a kind of:
```
Manual
Bottom (old: Bottom of video)
Bottom, inside black bar (old: Below video)
Top  (old: Top of video)
Top, inside black bar (old: Above video)
```
IMO its more understandable

**Comment by CastagnaIT** [comment]
updated my post above, the only problem now is the text size

**Comment by CastagnaIT** [comment]
in windowed mode Kodi is different from other mediaplayers because have a window frame unlinked to video played
then you can resize the kodi window enlarging the frame and losing the frame aspect ratio (black borders become wider)
this affect also the margins, maybe we can be ignore this... but before we find the font size problem

not all media player use same sub renderer i am sure that MPV use same kodi renderer, then i can use this last one to compare

the weird thing is that with MPV seem to be not affected of the "small" font size problem when we "align inside video",
where instead this happens in kodi, which i did not understand why...

this by using: `mpv.exe --sub-margin-y=0 --sub-use-margins=no`

**Comment by bokkoman** [comment]
I believe mpc-hc uses directvobsub?
I've never used MPV. 
On PC i always used MPC.

**Comment by CastagnaIT** [comment]
after a deep search i think i found the solution on this MPV commit https://github.com/mpv-player/mpv/commit/63266d43720dfce15f89c06f200e9a3350642542
i tried to do a rude backport it to kodi and the text size now its correct
i will investigate better next days

**Comment by bokkoman** [comment]
You're the best!

**Comment by CastagnaIT** [comment]
@bokkoman can you test and report? this is the test build
Android ARM64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220718-aaf7d5d3-subtitle_pos-23631-arm64-v8a.apk

in shorts i have restored Kodi 19 behaviour in full

**Comment by bokkoman** [comment]
> @bokkoman can you test and report? this is the test build Android ARM64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220718-aaf7d5d3-subtitle_pos-23631-arm64-v8a.apk
> 
> in shorts i have restored Kodi 19 behaviour in full

Sure. Does this install next to stable Kodi? Or does it overwrite?

**Comment by CastagnaIT** [comment]
you can try update over the previously installed version if android os not complains

**Comment by CastagnaIT** [comment]
only the test build of the link has the new changes
the new changes are not merged in master branch, so you will have to wait a month or two to get this change in a new official release

yes check how works position setting and vertical margins %
but if you can't test then it doesn't matter, this is just to get a external confirmation

**Comment by CastagnaIT** [comment]
dont worry, i am not asking for it at this moment
you can do it when you will have time also in the next few days

**Comment by bokkoman** [comment]
> dont worry, i am not asking for it at this moment you can do it when you will have time also in the next few days

It's working perfect! This is what I've been wanting for so long! Thank you so much!

**Comment by CastagnaIT** [comment]
thank you for the report

**Comment by bokkoman** [comment]
Might have found one issue with the sub handling.

On 4:3 content, the subs use the whole screen instead of only the video bit, as in goes into the black bars on the left&right.
Where usually it would stick inside the video.

**Comment by CastagnaIT** [comment]
When setting 'Bottom of Screen' position this is implied, this position will cover in full the screen area:
![BottomSCreeen](https://user-images.githubusercontent.com/3257156/179910558-536bc410-e6fe-46ae-b56c-2bbfad9b75e8.jpg)

When setting 'Bottom of Video' this position will cover only video area:
![BottomVideo](https://user-images.githubusercontent.com/3257156/179910627-277b537e-0c80-43be-a465-25393da59157.jpg)

if your use case is different, let me know the settings used and attach a screenshot

**Comment by bokkoman** [comment]
I have 'Bottom of Video' selected.
But it might have been due to it being anime, and probably being .ass subs.

**Comment by CastagnaIT** [comment]
I will have a look if it can be applied anyway
I also noticed a problem with the vertical margins (my screenshots) and it will take some time to find a solution

**Comment by bokkoman** [comment]
Usually the .ass subs stay within the video as well. If played with VLC or something.
As long as the subtitle formatting isn't changed, I'm fine with it. Don't want to loose all the special stuff .ass subs bring.
That will make all the anime lovers hate it.

**Comment by CastagnaIT** [comment]
i tried a 4/3 mkv with ass subtitle, but the text is shown correctly within the video area,
in following screenshot you see two lines of subtitles, but in reality it is a single line, since is too long is splited into two lines and both fall within the video area
![immagine](https://user-images.githubusercontent.com/3257156/181523767-197a02c1-4edf-4373-9572-a0682b440808.png)

its possible that in your video is a choice of the .ass author,
have you the opportunity to share part of your video file where is shown the text outside video area?
so i can test locally to see if there is something to do

**Comment by bokkoman** [comment]
I don't know how i could share it.
It's this release: `[CBT] Gintama S01 [DVD 760x576 x264 FLAC]` from nyaa.
First episode has it already.

![Kodi_20220728_182038](https://user-images.githubusercontent.com/7511367/181589769-321d1017-7c29-45f8-a5d8-03d232720fd2.png)

![Kodi_20220728_182230](https://user-images.githubusercontent.com/7511367/181589816-52746962-11f8-4211-982b-ebda79f1801d.png)

**Comment by CastagnaIT** [comment]
i found it thanks, so i check and this video has .ass subtitles
but by extracting mkv .ass subtitle file, the PlayResX/Y config values are wrong:

```
[Script Info]
; Script generated by Aegisub 2.1.8
; http://www.aegisub.org/
PlayResX: 640
PlayResY: 480
ScriptType: v4.00+
Video Aspect Ratio: 0
Video Zoom: 6
Video Position: 0
Last Style Storage: Default
```

these should have the same resolution of the video source or at least a resolution with same ratio
but we have a video of 760x576 and results in a different scale from what specified above (640x480), then also text position will result wrong

if i try change that values with video resolution, you can see that the text will be displayed in the right position, see screenshot:
![immagine](https://user-images.githubusercontent.com/3257156/181700594-6bc3d9d6-2d49-49d3-b535-22e67d446bdc.png)

however i will try to see if i can force keep the text inside video for these use cases

**Comment by bokkoman** [comment]
I tested it, and it works.
I'll let you know if I run into some kind of problem.

**Comment by bokkoman** [comment]
Maybe I'm doing something wrong.
But it seems it doesn't work.
I only tested the 4:3 episode from Gintama on previous post 
But now I tested a movie, and it isn't on the bottom of the video anymore.

![Kodi_20220806_211538](https://user-images.githubusercontent.com/7511367/183263285-a80e3640-69a0-44a9-a0e3-1e403d99c5dc.png)
![Kodi_20220806_211718](https://user-images.githubusercontent.com/7511367/183263287-714476cf-fe23-4acd-9161-6dd650ea52a9.png)
![Kodi_20220806_211742](https://user-images.githubusercontent.com/7511367/183263288-d43a161b-f1d1-4ab8-97e6-f3bcd4c2f76c.png)

Movies are Carter and Prey. 
I also changed the subtitle position a few times to maybe reset it? But didn't work.

**Comment by CastagnaIT** [comment]
> But now I tested a movie, and it isn't on the bottom of the video anymore

more likely your video is not cropped, please verify video file with a software like MediaInfo (for Windows) or similar
and and looks at video size info, if will results in a full 16/9 size then the screenshots above are right because the video is not cropped

**Comment by bokkoman** [comment]
> > But now I tested a movie, and it isn't on the bottom of the video anymore
> 
> more likely your video is not cropped, please verify video file with a software like MediaInfo (for Windows) or similar and and looks at video size info, if will results in a full 16/9 size then the screenshots above are right because the video is not cropped

Ah yes, i think you're right!
Why do they leave those black bars xD

**Comment by bokkoman** [comment]
Just one last question, since there's no forum post about this yet.

What is the shortcut to adjust `Vertical margin`?
You mentioned to use that, but i can't find it in the Keymap Editor.

**Comment by CastagnaIT** [comment]
Vertical margin setting cannot be changed while in playback, so shortcut keys currently is not applicable

as kind of alternative you can use shortcut key to change position setting
see `Subtitle position control` in https://kodi.wiki/view/Keyboard_controls
and map it in some way to your remote control

**Comment by bokkoman** [comment]
Yeah, that's what I figured. Little cumbersome.
Guess a new shortcut to change vertical margin wouldn't be that bad.
