### ISSUE TITLE
Modal custom windows xbmcgui.WindowXMLDialog opened with doModal() no focus

### ISSUE THREAD

**Issue by CastagnaIT** [xbmc/xbmc#21593]
### Describe the bug
Here is a clear and concise description of what the problem is:

Create a custom dialog window with xbmcgui.WindowXMLDialog
and using doModal() to open it, seems not receive focus
and twice key press are needed to intercept a key-press event

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

open the modal window, press enter key (or remote key) just ont time, to be able "click" on it (as Kodi 19)

## Actual Behavior

open the modal window, press twice enter key (or remote key) to be able "click" on it

### To Reproduce

I used my Netfl@x addon
1. Load a tv show like "young sheldon"
2. wait the "Skip" button on "modal window" appears on screen
3. press twice enter or remote button

the custom modal window is created with this xml:
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/skins/default/1080i/plugin-video-netflix-Skip.xml

i also tried add id, type and modality fields:
`<window id="2000" type="dialog" modality="modal">`
but not solve nothing

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/dofarevinu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

i suspect is due to the PR that introduced xml features for "modal type" that has broken something in python xbmcgui module

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, CoreElec, android 8
 - Kodi version: Builded from "master" branch and nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
I confirmed the issue, git bisect points at https://github.com/xbmc/xbmc/commit/aaf187f2f139071cf586a4b6d1ffa1f15e6fcd49 (fyi @sarbes)

**Comment by enen92** [comment]
I guess the IsVisible() check needs to be changed in CanFocus()

**Comment by enen92** [comment]
So I've taken a bit of time to look into this. The problem occurs because your control `6012` has a fade effect on window open and starts from 0% alpha to 100% alpha. Since https://github.com/xbmc/xbmc/commit/aaf187f2f139071cf586a4b6d1ffa1f15e6fcd49 controls would be rendered (hence visible) unless they have an alpha channel > 0.01 (99% of transparency pretty much means invisible to me).
The problem is that when the window loads it tries to focus your default controller:

https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIWindow.cpp#L335-L339

At the moment this occurs, the control is still invisible (alpha = 0) and kodi sets the default controller to the default (control id 0). This happens because `focusedControl->CanFocus()` returns `false` since it internally calls `IsVisible()`. No focused controller exists anymore since this point in time.
Later when you provide input to kodi, with the button already visible, your button will get focus (hence the need for 2 clicks):

https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIWindow.cpp#L430-L433

The main issue here is that any change/conditional setting we might add to kodi is highly likely to cause regressions. The change @sarbes provided provides quite a performance boost and I think it's applied in the correct place.
So my suggestion @CastagnaIT is to add a little change on the addon code by adding:

`<visible allowhiddenfocus="true">true</visible>`

to your button definition. This will make sure that the button will receive focus even if still not visible (because of `allowhiddenfocus`) as it still fading in. 

Will this work for you?

**Comment by sarbes** [comment]
I guess it's a bit of a philosophical question what constitutes being visible. I'll leave it entirely up to you how to proceed. Reverting the commit would be totally fine with me.

**Comment by CastagnaIT** [comment]
unfurnately setting this to the button not works
`<visible allowhiddenfocus="true">true</visible>`
still return "error cant focus" in log so `allowhiddenfocus` is unusable

maybe you can change in some way the proprity in `CGUIControl::CanFocus()`
so to allow `allowhiddenfocus` tag to works

i confirm that changing the effect by starting from 1 instead of 0 works
`<animation effect="fade" start="1" end="100" time="200">WindowOpen</animation>`

**Comment by CastagnaIT** [comment]
my fail...
i have now updated kodi to last nightly and `allowhiddenfocus` works as expected also with animation start from 0
so we can close thanks for the support
