### ISSUE TITLE
[Kodi 20][WebVTT] Subtitles of the previous video are displayed and mixed with the current one

### ISSUE THREAD

**Issue by Arias800** [xbmc/xbmc#21643]
### Describe the bug
Hello,
I'm working on an addon for the website Viki.
This website has a mpd manifest that have embedded subtitles.

The bug happen when you change the episode without stopping the player.
The subtitles of the previous content still display by Kodi alongside the subtitles of the current episode.

A video that show the issue :
https://streamable.com/oc2mfy
 
It doesn't seem to be a bug from my code, because the manifest seem correct and that doesn't happen if I stop the player before changing the content.
So I supposed it's relate to Inpustream and the way it handles these kinds of manifest.

## Expected Behavior
Only the subtitles of the current episode should be display.

## Actual Behavior
Both current and previous subtitles are displayed.

### To Reproduce
You can find an example of the manifest here : https://github.com/Arias800/Fichier-divers/blob/master/subtitles.mpd
If you want to reproduce, you need this addon.
https://github.com/Arias800/plugin.video.vikir

You have to open any content, and you have to switch to another one without stopping the player.

### Debuglog
https://github.com/Arias800/Fichier-divers/blob/master/kodi.log

### MPD/M3U8s/ISM
https://github.com/Arias800/Fichier-divers/blob/master/subtitles.mpd

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint and Android TV
 - Kodi version: Kodi 20 lastest nightly
 - inputstream.adaptive version: 20.2.2

**Comment by CastagnaIT** [comment]
@enen92 i am investigating in this problem,
and the problem happens because of `SetOverlayContainerFlushable(false)`
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/OverlayCodecWebVTT.cpp#L158

that prevent to delete the overlay on flush
because when you play a video over another one, only the flush will be done for the overlaycontainer, here:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp#L111
and not a "clear" operation that delete all overlays

the reason behind of SetOverlayContainerFlushable use, is that we are playing a video with webvtt "as single file"
without it the VideoPlayerSubtitle call flush and will delete the overlay,
and since the packet is sent to kodi only at playback starts, no more packet arrive to kodi, and no future overlay's are generated == subtitle not displayed/broken

a solution for this is set `CloseStream(false)` that will perform `m_pOverlayContainer->Clear()` here:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp#L121
this will delete the old overlay set as not flushable, just before open a new overlay subtitle
but im not sure if this is a safe operation, so if the overlay pointer could be used somewhere while we clear it

**Comment by CastagnaIT** [comment]
tested a bit by playing 4-5 subsequential videos but i dont see problems

in the past VideoPlayerSubtitle was calling the Clear method in container overlays 
https://github.com/xbmc/xbmc/blame/af565d68220b4fa272203d77b7c5303b6c319d5b/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp#L109-L110
i think should not a problem if done just before open the new parser
