### ISSUE TITLE
Folders are empty. No files are showing.

### ISSUE THREAD

**Issue by BIG1** [xbmc/xbmc#21701]
### Describe the bug
Here is a clear and concise description of what the problem is:

I installed kodi 20 nightly (coming from matrix 19.4).
When I view files in folders they are empty. There is no way to start movies.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To view the files in the folder

## Actual Behavior

No files is shown

## Possible Fix

I dont know

### To Reproduce

1. Start kodi
2. Video - media sourves (external hdd)
3. Navigates to folder, they folder are empty.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/pumotemivi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 20 nightly. kodi-20220721-928ff9c9-master-23651-arm64-v8a.apk)
 - Nvidia shield tv 9.1
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Could you please tell us which kind of files are located at that storage. 

I can partly confirm this issue. 

What I've tried:

I plugged a USB stick to my machine which held some e-books (some *.epub files, some *.pdf). After accessing the storage in the way you did it... video -> files -> 'my usb stick' -> 'some e-book folder' ... I wasn't able to see any of those files inside Kodi. 

After that I created a folder "movies" on that usb-stick and placed an empty file into it and named it "test.mkv". That file could be seen by Kodi and if it would have been a real video file, I highly guess I would have been able to play it. 

So Kodi is only able to list those files which Kodi probaby expects as "video files". So I would be interested in what kind of files are on your external storage. Probably you could share a screenshot of some file bowser which shows the extension?

Thanks.

**Comment by BIG1** [comment]
All kind of files. It is mkv.srt and .zip.
External hdd connected with usb cable.

Also tried the file browser, none files visible.

**Comment by DaVukovic** [comment]
Please head over to our forums. As this is not an issue at all

As you can see: 

![image](https://user-images.githubusercontent.com/7235787/180616271-6ed900fb-b888-45d8-aafb-5ed28d332bda.png)

You can see on the file browser, that both files (test.mkv and test.zip) do exist. But Kodi only shows the MKV file. Kodi also won't show the srt files. So please make sure the file you want to access is not a zipped file. You could try to install an addon to make those files visible:

https://kodi.wiki/view/Add-on:Archive_support

Btw...in case you want to use the Kodi file browser you have to add the "Filmer" folder as a source at the File browser inside Kodi to make those files at least visible: 

![image](https://user-images.githubusercontent.com/7235787/180616490-de0d0e4b-b914-4d0d-b005-fb669a2ec99b.png)

After I added my USB-Stick as a source (please be aware that while browsing for the source and before adding it, Kodi will only show folders and not files, as files can't be added as a source...only folders), the zip file is visible as well. So I highly guess the folder mentioned in your log simply contains a zipped file and that won't show up. And that's expected behavior. 

For further support please open a thread at our forums. 

Thanks.

**Comment by BIG1** [comment]
Thank you. Changed permissions from "allow when app in use" to "allow all the time".

**Comment by brendanmeyer** [comment]
> Thank you. Changed permissions from "allow when app in use" to "allow all the time".

This worked, thank you

**Comment by Khalarin** [comment]
> Thank you. Changed permissions from "allow when app in use" to "allow all the time".

This worked for me too! Thank you =D

**Comment by Rio517** [comment]
For those searching for the answer:

> On Android TV go to Settings -> Apps - Kodi -> Permissions -> Files and Media and select "Allow all the time"

**Comment by larvata** [comment]
> For those searching for the answer:
> 
> > On Android TV go to Settings -> Apps - Kodi -> Permissions -> Files and Media and select "Allow all the time"

This fixed my issue, but I wonder why the “Allow only while using the app” is not work.

**Comment by drrohle** [comment]
Worked for me too, thanks!

**Comment by sdewolf-be** [comment]
Same problem over here on my shield. Thanks a lot, riot :-)

**Comment by vullnetyy** [comment]
> Thank you. Changed permissions from "allow when app in use" to "allow all the time".

This worked for me on my NVIDIA Shield TV Pro. 

Was very frustrated until I found this Closed Github issue... 

I wonder how many non-developers will find themselves here. Would be good if you guys gave this solution more SEO. Perhaps make some documentation that shows up high on search engines when "kodi nvidia mkv files not showing" is searched.

**Comment by Dudleydogg** [comment]
> Thank you. Changed permissions from "allow when app in use" to "allow all the time".

This threw me for a few minutes to find this post, fixed permissions working perfectly now, the give away was when you browse folders and see nothing, which led me to this post. thank you all for your comments.

**Comment by piyush97** [comment]
> Thank you. Changed permissions from "allow when app in use" to "allow all the time".

Worked like a charm!
