### ISSUE TITLE
full screen "never"

### ISSUE THREAD

**Issue by Aftergit** [xbmc/xbmc#21755]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using radio addon (version 3.0.9 Matrix.1 from Author Tristan Fisher, enen92)) and you select in  pvr & Live settings switch to full screen "never" and you play a radio station it switch to full screen, 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In Kodi Leia version it stay's in the home menu and it does not switch to full screen.

## Actual Behavior

In the Matrix version and Nexus version this issue occurs even when you switch's back to home menu after a while it switch back to full screen it does not stay in the home menu like it suppose to do when you have selected in pvr & Live settings switch to full screen "never" .

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix & Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*
![Screenshot 2022-08-14 120041](https://user-images.githubusercontent.com/88626814/184531925-5e8fd407-246d-47be-9ef6-21a6822381e7.png)

**Comment by ksooo** [comment]
Technically, the radio addon is not a PVR addon, thus the PVR and Live TV settings do not apply for that addon.

**Comment by Aftergit** [comment]
This answer i would expect from Microsoft or any other commercial software company, Technically if you don't care who am i to care about a bug in Kodi, so this was my first time i spend time to report a bug and if you cant give me a normal answer where i suppose report this bug.  guess what this is also also my last time i reported a bug.

**Comment by sarbes** [comment]
I don't know where you've read that ksooo doesn't care about your issue, as he was merely stating a fact. Otherwise, you would not get a response.

As for your issue, the behavior is by design (if I parse your blob correctly - please use some punctuation). You are playing an audio resource. On Matrix, the screensaver kicks in after three minutes. By default, Kodi switches to the (fullscreen) viz instead of the screensaver.

The PVR setting is not not applicable in this case. And even if turned off, the screensaver (by default the viz) would kick in after a few minutes I assume.

Overall, this is not an issue. The behavior is already configurable. I'm certain that your confusion stems from not understanding what the setting does and what PVR is.

**Comment by Aftergit** [comment]
Ye your right i am stupid and i don't know what a pvr is and that it does work in leia its because it's not by design but just i don't understand what a pvr is. Its not aan issue for me i just stay with leia i just thought i help out to report a bug but your toe's are so  long that i stand on them and i did hurt you so much in your ego and i will not hurt you again and bother you with a bug report.
