### ISSUE TITLE
[Kodi20] The position of ASS\SSA subtitle cannot be set to the bottom of video

### ISSUE THREAD

**Issue by TianZerL** [xbmc/xbmc#21860]
### Describe the bug
Here is a clear and concise description of what the problem is:

After I upgrade to Kodi20, the position of ASS\SSA subtitle cannot be set to the bottom of video, it seems that `Position of screen` option is not working, it will always be the bottom of screen. Kodi19 is working fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The position of ASS\SSA subtitle can be set to the bottom of video or the bottom of screen.

## Actual Behavior

The position of ASS\SSA subtitle can only display at the bottom of screen.

## Possible Fix

The subtitle position can be overwritten, and we can adjust it manually, but this will cause some bilingual subtitles to work abnormally.

### To Reproduce

1. Prepare a movie with ASS subtitles and will be black edges.
2. Play it.

### Debuglog

The debuglog can be found here:
[Log of ASS subtitles](https://github.com/xbmc/xbmc/files/9567849/kodi.old.log)
[Log of bilingual subtitles](https://github.com/xbmc/xbmc/files/9567978/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

#### Kodi 20, `Position of screen` is set to `bottom of video`:
![sub1](https://user-images.githubusercontent.com/41182852/190201403-a17f10f9-7141-410d-8bc0-15c39ae2e92f.PNG)
![sub2](https://user-images.githubusercontent.com/41182852/190201428-7f01d099-3f97-4893-bdf1-c0b43b97de00.PNG)
#### Correct position from VLC (Kodi19 is same):
![sub3](https://user-images.githubusercontent.com/41182852/190202550-2590f6e0-778c-4f89-bb3a-facf5e9781ff.PNG)
![sub4](https://user-images.githubusercontent.com/41182852/190202592-c6b29d3a-3db0-49f7-a35d-2adee8888792.PNG)
#### Overwritten the position will cause some bilingual subtitles to work abnormally:
![incorrect bilingual subtitles](https://user-images.githubusercontent.com/41182852/190204678-640d5161-ed06-4d2e-8664-c9cafab89054.png)
#### Correct bilingual subtitles:
![correct bilingual subtitles](https://user-images.githubusercontent.com/41182852/190204409-b3d08338-0b5e-485e-b3e5-6ba1eca5b20a.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I use Kodi on Windows and Android. Both of them have this problem. I think that the Kodi20 of all platforms may be the same.
Test file: [ASS Test Video.zip](https://github.com/xbmc/xbmc/files/9574318/ASSTestVideo.zip)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows11, Android11
 - Kodi version: Kodi20 Alpha3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
to investigate on this is needed that you share part of your video that cointains the text subtitles of the screenshots

**Comment by TianZerL** [comment]
@CastagnaIT 
[ASS Test Video.zip](https://github.com/xbmc/xbmc/files/9574318/ASSTestVideo.zip)

**Comment by CastagnaIT** [comment]
thanks for the sample,
this is the Windows test build with the fix for normal use case (so with `overridde subtitle styles` settings disabled):
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220915-ba350e8f-ass_margin_fix-x64.exe

Some remarks Kodi 20 is not exactly as Kodi 19 for subtitle functionalities, so:

In all cases if you set subtitle position `Bottom of video` you cannot move up/down manually text subtitles, this is a current kodi limitation.

If you want move up/down text manually with ASS/SSA subtitles you have to enable `overridde subtitle styles: position` setting and set position `Manual` or `Bottom of screen`.

If you want force change text positions defined by ASS/SSA authors and use Kodi `Position on screen` setting, you have to enable `overridde subtitle styles: position` setting.

Every time you enable `overridde subtitle styles` or `overridde subtitle fonts` this can lead to side effects to ASS/SSA subtitles, like your screenshot:
![immagine](https://user-images.githubusercontent.com/3257156/190453058-8a3761ca-3adc-4122-a309-a238a29a1f39.png)
this because is not always possible override ass/ssa styles
so the best is dont enable overridde settings.

Please test the build with more videos and let me know

**Comment by TianZerL** [comment]
@CastagnaIT
It works perfectly by default settings (`override subtitle styles settings` disabled and subtitle position is `Bottom of screen`), which is exactly what I want.

Just a question: does `Bottom of screen` and `Bottom of video` affect ASS/SSA subtitle? 
I switched it, but nothing happened. As far as I understand, `Bottom of screen` calculates the position of the subtitle from the bottom of the screen, while `Bottom of video` starts from the bottom of the video. Thus the subtitle may be in the black edge for `Bottom of screen`. I tried SRT subtitles, and it did work.

Anyway, it works, great job!.

![image](https://user-images.githubusercontent.com/41182852/190461051-5d6d2552-8801-403a-a71c-2d2ce954b1fc.png)
![image](https://user-images.githubusercontent.com/41182852/190461174-6eaa5760-18e7-4614-95f1-dc6c933649c7.png)

**Comment by CastagnaIT** [comment]
> Just a question: does Bottom of screen and Bottom of video affect ASS/SSA subtitle?

does not affect ASS/SSA,
if you want it, then you have to enable "overrides styles: position" setting

> I tried SRT subtitles, and it did work

you have to make sure that the video played with SRT is cropped, otherwise `Bottom of video` will not works and the text appears on bottom of screen

**Comment by TianZerL** [comment]
@CastagnaIT
Got it, thanks!
