### ISSUE TITLE
Kodi crash on start Aarch64 20.b1-Nexus

### ISSUE THREAD

**Issue by spikerguy** [xbmc/xbmc#22172]
### Describe the bug
Kodi 20.b1 Nexus crashes on Manjaro Arm using aarch64.

## Expected Behavior
Start kodi in gbm or x11 and create GUI interface.

## Actual Behavior

Fails to create GUI.

## Possible Fix

Jernej tried looking into the crash log to help me with this issue, here are some comments and possible issues.
1. Error obviously happen in CreateGUI() call when calling CServiceBroker::GetGameServices() but g_application.m_ServiceManager gets initialized in g_application.Initialize(), which is actually called a few lines afterwards, in short, object, which retroplayer needs, is instantiated later than first use. This is in xmbc.cpp
2. OR looks like a null pointer dereference, m_gameServices being null

### To Reproduce

1. Compile 20.b1-Nexus on arch linux or Manjaro unstable branch with all latest packages.

### Debuglog

Manjaro Arm Aarch64 GBM logs: http://ix.io/4guf
X11 Logs: http://ix.io/4guj

## Additional context or screenshots (if appropriate)
I tried to compile it with FFMpeg 4.4.1 external as well as internal. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.0-BETA1-Nexus

**Comment by lrusak** [comment]
@garbear it looks like this change might be the culprit https://github.com/xbmc/xbmc/commit/21b87fd89206fb402b47cfad74b98550080e6d0d#diff-1d016f5d5e71135b9e750e8d45a44652a5a9016da54f5a6a2a6fed449872557eR45

As `CGameServices` isn't available till `CServiceManager::InitStageThree` which is called in `CApplication::Initialize` which is called after `CApplication::CreateGUI`.

https://github.com/xbmc/xbmc/blob/master/xbmc/platform/xbmc.cpp#L36-L43

**Comment by lrusak** [comment]
Possible solutions:
 1) Make sure registration happens later (not at window system creation). This will be whack-a-mole as different platforms may register things at different times. (Which is why it works on x11 but not on wayland or gbm.
 2) don't call the createFunc during the registration -> https://github.com/xbmc/xbmc/blob/41de6b9949b132f02ca13dedc9396e0b250aca9a/xbmc/cores/RetroPlayer/process/RPProcessInfo.cpp#L93 This may be the best solution as Registration should simply be registration where the object creation happens later.
 3) Simply call `CServiceBroker::GetGameServices()` here https://github.com/xbmc/xbmc/blob/41de6b9949b132f02ca13dedc9396e0b250aca9a/xbmc/cores/RetroPlayer/rendering/RenderContext.cpp#L313 and here https://github.com/xbmc/xbmc/blob/41de6b9949b132f02ca13dedc9396e0b250aca9a/xbmc/cores/RetroPlayer/rendering/RenderContext.cpp#L318 Then remove the `CGameServices` member from `CRenderContext`

I think I would go for option 2.

**Comment by ericwoud** [comment]
I think I'm running in to the same problem here on Archlinux armv7h:
/usr/include/c++/12.1.0/bits/unique_ptr.h:445: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = KODI::GAME::CGameServices; _Dp = std::default_delete<KODI::GAME::CGameServices>; typename std::add_lvalue_reference<_Tp>::type = KODI::GAME::CGameServices&]: Assertion 'get() != pointer()' failed.
/usr/bin/kodi: line 181:   765 Aborted                 (core dumped) ${KODI_BINARY} $SAVED_ARGS

**Comment by spikerguy** [comment]
I was able to make it work by ignoring retroplayer when initwindowsystem call.
 https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/gbm/WinSystemGbmGLESContext.cpp#L59-L61
 
 Thanks to jernej for his advice. So it does launch fine when using GBM with gles. 
Waiting for a permanent solution. 


Thanks.

**Comment by garbear** [comment]
I left my approval on https://github.com/xbmc/xbmc/pull/22185. You can try that patch and see if it fixes the crash.

**Comment by spikerguy** [comment]
That PR fixes the issue as I have tested it on X11 and GBm only, need to test on wayland.
