### ISSUE TITLE
Kodi not auto-switching bit depth when watching UHD video using Intel integrated graphics

### ISSUE THREAD

**Issue by Windermyr** [xbmc/xbmc#22278]
### Describe the bug
Here is a clear and concise description of what the problem is:
When watching 4k UHD blu ray rips, Kodi does not auto-switch to 10 bits per channel colour depth. Graphics setting set to 3840x2160@60hz, 8bpc. When playing the file, it successfully switches HDR on and sets refresh to 24Hz, but remains at 8bpc. I can manually change colour depth to 10bpc, but Kodi will not automatically change it. This seems to be specific to Intel graphics. When I tested with another computer using an Nvidia card (RTX 3090), Kodi successfully changed bit depth.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
When playing 4k UHD files that are encoded at 10bpc, the expected behaviour is that the refresh rate is changed to 24Hz, HDR is enabled, and bit depth switched to 10 bit colour.

## Actual Behavior

Remains at 8 bit colour. HDR is enabled properly, and refresh rate is set appropriately.

### To Reproduce

1.  Use Intel integrated graphics (UHD 730 in my case)
2. Set desktop resolution to 3840x2160@60Hz, 8bpc
3. Play a 4k 10-bit HDR rip.
4.  Check settings on TV

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/gutagukare.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.imgur.com/PGoztui.jpg
https://i.imgur.com/0O7brwr.jpg
https://i.imgur.com/x2wE8JQ.jpg
https://i.imgur.com/CTtFLp8.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro 22H2
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
> Kodi successfully changed bit depth

False --> bit depth in Windows is handled only by video driver and graphics settings (Nvidia and Intel control panel).

This works fine with current NVIDIA graphics drivers on GTX / RTX 10x, 20x, 30x, 40x and
works fine in the Intel NUC's  i.e. NUC8i3BEK in Windows 10 and Windows 11.

Is not used 10 bit but 12 bit with padding because is more compatible with HDMI standard.

To be clear: Windows/video driver switches output automatically to 12 bit in INTEL and NVIDIA when outputs HDR10 signal.

I suggest you reinstall INTEL video driver clean and test with factory defaults settings.

You don't even need Kodi for this to work. In other words, toggling HDR ON in Windows must switch to 12 bit. If it doesn't, there's a problem, but it's not on Kodi.

Kodi toggles Windows HDR ON (with Win32 API) and Windows toggles 12 bit ON (when is supported by HDMI chain)

**Comment by Windermyr** [comment]
Well, more troubleshooting has narrowed it down to the Dr HDMI 4k that I'm using. Removing this from the chain allows Kodi to automatically change bit depth. Odd that Nvidia driver is able to work with the Dr HDMI without issue, but it seems to be an issue with the Intel driver.
