### ISSUE TITLE
Requirements document

### ISSUE THREAD

**Issue by PaulDaratzis** [xbmc/xbmc#22322]
Hello I would like to make the document of requirements for the project. Could you give me some information about the project?

**Comment by fritsch** [comment]
Sure thing! Let me give you the rundown on the XBMC project:

First and foremost, the most important requirement for this project is a love for binge-watching TV shows and movies. Without that, you'll just be lost in the sea of code.

Secondly, you'll need a top-of-the-line media center setup, complete with a couch that's comfortable enough to sit on for hours on end and a never-ending supply of popcorn. Trust me, you'll need it.

Finally, you'll need to be a master of procrastination, because let's face it, who actually has the time to write a requirements document when there are so many episodes of The Office to watch?

via chatgpt :-)

**Comment by PaulDaratzis** [comment]
thanks for the tips :-)

**Comment by basilgello** [comment]
@fritsch you forgot the embedded toilet to let this popcorn stream flow ;)
