### ISSUE TITLE
Kodi is unable to play an m3u8 file, but can play m3u8 inside it

### ISSUE THREAD

**Issue by joaopa00** [xbmc/xbmc#22534]
### Describe the bug
Here is a clear and concise description of what the problem is:
The file [test file](https://cdn-ue1-prod.tsv2.amagi.tv/avod/simplestream-lds-ldtimln/ODYPPCS001EP001/ODYPPCS001EP001.m3u8)
Kodi can not play it. Inside this m3u8 file, there are links for different versions of the stream. Kodi can play each of these stream, when directly called.

A note: MPV can play this file without any problem.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Kodi can play the stream throughout the initial m3u8 file.

## Actual Behavior
Kodi fails badly to play the stream.

### To Reproduce

1.   [ Link to the problematic file](https://cdn-ue1-prod.tsv2.amagi.tv/avod/simplestream-lds-ldtimln/ODYPPCS001EP001/ODYPPCS001EP001.m3u8)
2. Launch it through Kodi
3.

### Debuglog

The debuglog can be found here:
[log.txt](https://github.com/xbmc/xbmc/files/10471307/log.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  Kdo Matrix 19.5, Kodi Nexus 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
looks like your stream is malformed (http://players.akamai.com/stream-validator)

i tried open the stream on Kodi 19.5 and 20
but to me playback works maybe a bit slow to starts

you can use inputstream adaptive to play this stream but will works only on Kodi 19
because on Kodi 20 inputstream adaptive is needed some fixes to do

you are also using an old kodi version `20.0-ALPHA2` that suggest you to update to official v20 release

can you also explain in what way you play the stream?

**Comment by joaopa00** [comment]
I put the link in a file myvideo.strm in my usb stick. And I play it in kodu in such a way: video/files/MyStick/myvideo.strm

In fact, the problem occurs only in Linux.

**Comment by joaopa00** [comment]
>Kodi 20 inputstream adaptive is needed some fixes to do

Are they foreseen?

**Comment by CastagnaIT** [comment]
my tests has been done on Ubuntu 22.04 on specified Kodi versions
i also used STRM file, in specifics with this content

```
#KODIPROP:inputstream=inputstream.ffmpegdirect
https://cdn-ue1-prod.tsv2.amagi.tv/avod/simplestream-lds-ldtimln/ODYPPCS001EP001/ODYPPCS001EP001.m3u8
```

> In fact, the problem occurs only in Linux. In ubuntu, repos, only alpha version of Nexus is available for now. WIll try the official version as soon as it is released in ubuntu repos.

Kodi 20 is officially released and there is already on Ubuntu
i think you have wrong PPA installed

so i am not able to reproduce your problems on my linux because to me playback works correctly

>> Kodi 20 inputstream adaptive is needed some fixes to do
> Are they foreseen?

we will investigate in future

**Comment by joaopa00** [comment]
I use the official repo from Canonical. I willwait Canonical to updat it.

**Comment by joaopa00** [comment]
I updated to the kodi repo. That works. I suppose that the official Ubuntu shipped version (Nexus alpha) had problems.
Thank you for for very useful feedback.
I can close this ticket safely then...
