### ISSUE TITLE
Kodi 20 crashes when playing recursive slideshow

### ISSUE THREAD

**Issue by Hessayon8** [xbmc/xbmc#22643]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 20 crashes when playing a recursive slideshow.  Sometimes it will play 20 or so photos and other times it crashes immediately.  I reloaded Kodi 19.5 and the recursive slideshow works perfectly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I have used Kodi for a good few years to randomly play my extensive photograph collection, 20,000 photos.  On right clicking the photo file I would select recursive slideshow and the show would begin and play for many hours. 

## Actual Behavior

Sometimes on right clicking the recursive slideshow kodi would crash straight away and on other occasions it will play 30 or so photos before crashing.  A bit of experimenting showed that it would play a folder of about 100 photos when the photo size was around 1.45Mb.  It would not play folders containing my normal size photos around 7Mb.
I reloaded kodi 19.5 which works perfectly on my other computer and it functioned as expected.
  

### To Reproduce

1. Select folder containing many sub folders containing many large photos
2. right click recursive slideshow 
3.
4.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ X] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 (Skin estuary)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KOPRajs** [comment]
I've experienced a similar issue upon opening a folder with large (up to 15 MB JPEG) photos - Kodi 20.0 RC2 crashed. However I was not able to reproduce it, so no log either, sorry.

In my case, I've just opened the folder, not the slideshow. Thumbs were already generated from Leia, but it was probably for the first time I've opened this folder in Nexus. The crashed happened immediately after opening the folder.

Running on Amlogic ARMv8.

**Comment by Hessayon8** [comment]
I couldn't provide a log as I had reloaded 19.5 which worked perfectly.  When I get some time in a week or so I may reload 20.0 and get the required log sheet.  I thought it was a universal problem but as there has only been one other comment perhaps it is something to do with my windows 10 set up.

**Comment by KOPRajs** [comment]
I've just experienced the issue again on Nexus 20.0, should we re-open the issue or should I create a new one?

This time it crashed while playing recursive slideshow of a folder with regular _JPEG_ photos (about 5-20 MB per photo). There was also music from _MP3_ playing in background. I can't reproduce the issue, it just happens randomly from time to time, so I can't create a debug log.
The regular log simply ends with:
```
2023-03-04 08:21:11.747 T:4443     info <general>: Loading skin file: SlideShow.xml, load type: KEEP_IN_MEMORY

############### END LOG FILE ################

############ END kodi CRASH LOG #############
```
The crash occured about 2 minutes later.

Platform is CoreELEC 20.0 (Amlogic-ng).

**Comment by GregSawin** [comment]
FYI, I've experienced this issue on an AFTV w/Kodi 20.1 and at least in my case it was due to 1 image.  I opened up the picture folder, viewed the 1st image then kept hitting next, counting as I went, until it crashed.  I confirmed a few more times which image was causing it, removed that image and haven't seen the problem since.  The image thumbnail was showing up fine so it's not like you can use them to find the issue.  And the image appears fine on my computer but for some odd reason the Kodi full image viewer doesn't like it, while the Kodi thumbnail maker was ok with it.  Like you, nothing was logged when it crashed so that wasn't helpful.  I ended up using an image editor to save a new copy of the image which kodi can display without crashing.

**Comment by Hessayon8** [comment]
All,

I went back to 19 which is fine.  I don't have time to produce the log.  If
anybody else wishes to do so please carry on.  There is obviously a bug
somewhere.

Richard

**Comment by CrystalP** [comment]
@GregSawin You could create an issue for that reproduceable crash if you can share the original problem picture and a debug log. Since it's a crash, a stack trace or crash dump could be useful as well, if available.
The ffmpeg upgrade in v21 may have taken care of the problem already (back up your user data first)
