### ISSUE TITLE
Android: UI hangs until Library Scan finishes

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#22701]
## Bug report
Whenever Kodi Matrix and Nexus is doing a library scan on Android, if you task switch the library scan will continue in the background (which is great, btw). When resuming Kodi, the GUI never reinitializes until the library scan finishes, leaving the user sitting at a Grey screen for minutes, hours, and days until everything is reconciled.

### Describe the bug
Here is a clear and concise description of what the problem is:

UI stalls.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

UI shouldn't stall during a library scan.

## Actual Behavior

UI stalls.

## Possible Fix

Run the library scan outside of the GUI thread.

### To Reproduce

1. Library scan
2. Minimize Kodi (hit the home button on the remote)
3. Open Kodi

### Debuglog

The debuglog can be found here:

Scanning....

### Screenshots 
Here are some links or screenshots to help explain the problem:

Grey Screen.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Nexus and Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Donski74** [comment]
When you're running a Fire Stick, pressing Home on the remote will indeed take you out of Kodi and leave Kodi running in the background. Now the issue is that when you choose to run an app like Kodi directly from the Home screen it will restart it instead of reopening it where you left off. One way to get around this is to go into Setting/Manage Installed Applications/Kodi then Launch Application. This way you enter the app right where you left off. I prefer to use an app called "Background Apps & Process List" and launch it that way.

I don't believe it's a Kodi issue, I see it as an Android issue.

**Comment by KyleSanderson** [comment]
> When you're running a Fire Stick, pressing Home on the remote will indeed take you out of Kodi and leave Kodi running in the background. Now the issue is that when you choose to run an app like Kodi directly from the Home screen it will restart it instead of reopening it where you left off. One way to get around this is to go into Setting/Manage Installed Applications/Kodi then Launch Application.

This is patently false, the stall still happens.

This way you enter the app right where you left off. I prefer to use an app called "Background Apps & Process List" and launch it that way.
> 
> I don't believe it's a Kodi issue, I see it as an Android issue.

This is 100% a Kodi issue. Does this happen with Prime Video? Netflix? Apple TV?

**Comment by Donski74** [comment]
I just tried what I posted and it works for me. I'm running a Fire Stick 4Kmax.

Here's what I did. 
I went into Kodi, Settings/Media/Library/Videos. Right click on TV Shows and choose Change content. Changed Local information only to The Movie Database then back again to Local information only. The reason for this is that it will clear my TV Shows from the database and allow me to scan them back in. Click on OK and YES to refresh all items with that path. At this point you can see in the upper right corner the scanning progress as it enters each episode into the database. I hit the home button and start watching YouTube videos. I can exit YouTube and enter Kodi as I said through Settings and I can see progress has happened in the scan. I can even click the home button and start to watch YouTube videos again then get on another Fire Stick and look at TV Shows to see the progress being made as Episodes are added.

So I know this works for me.

Now remember that I said "One way to get around this is to go into Setting/Manage Installed Applications/Kodi then Launch Application. This way you enter the app **right where you left off**." Now if you already had a grey screen it will only take you back to that same grey screen you had before. Maybe I don't know what you mean by stall or there's something else that's going on that I don't know about. My version does not stall, I'm running Kodi Nexus 20.0.

I would like to mention that I am not a programmer working on Kodi, I'm just another user trying to help with suggestions from my experiences using it.

**Comment by Donski74** [comment]
To prevent a grey screen maybe we can suggest beginning start (hard reset) with a force stop, but I'd be afraid it would mess with some addons and database sharing. There's a difference between a hard reset and a soft reset, and in Kodi I'm sure there's more levels than that. A hard reset will reinitialize all the values and many times it will fix a lot of problems with things you may have messed up while running the program while a soft reset can bring you in and continue where you left off. 

This is an open source project with a lot of people working on it for free in their spare time, it's hard to get everybody's hard work to play nice together causing conflicts and sometimes it causes your grey screen of death. If you're paying for a program then you expect it to not have any bugs, Kodi is not only free but it blows away any other program because of its features. I hate to be the one telling you this but with all the other important issues they're dealing with that prevent things from working, if they accept this one it would be low on their priority list unless someone knows of an easy fix.

As long as I have a workaround then I'm a happy camper.

**Comment by KyleSanderson** [comment]
Please stop responding with absolute garbage. This is a legit bug.

**Comment by dolenec** [comment]
Agre with @KyleSanderson .

Same bug and yes.. it is a bug..

**Comment by thexai** [comment]
> This is a legit bug.

Not without debug log
