### ISSUE TITLE
Subtitle position does not work as expected for Kodi Nexus on Xbox

### ISSUE THREAD

**Issue by Hawkedon** [xbmc/xbmc#22753]
### Describe the bug
In previous versions for Kodi, I was able to adjust the subtitle position to make it stay at the bottom of the screen by using "fixed" position and the "video calibration" dialog. I could see the subtitle position was moving when I was adjusting it in the "video calibration" dialog.

In Kodi Nexus, no matter what I set for the subtitle position ("bottom of screen"/ "manual", etc.), the subtitle is always in the bottom of the video, not the bottom of the screen. When I set position to "manual" and adjust it in the "video calibration" dialog, the subtitle is just in there still and it never moves like what I could see in previous versions of Kodi (I can see the bar in the dialog is moving though).

How can I make it working like before?

## Expected Behavior

Subtitle positioning should work like the previous version for manual/fixed positioning.

## Actual Behavior

It ignores user settings.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/akozekubaj.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox Series X
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
more likely you are using a skin that has been not updated for Kodi 20
use original kodi skin and request to the skin author to update his Skins for kodi 20 platform

**Comment by Hawkedon** [comment]
I tried the default Estuary skin, and got the same result. Do you need the log for Estuary skin?

**Comment by CastagnaIT** [comment]
so is possible that you are playing a video that have subtitles with metadata, and you havent enabled style overrides,
in this case you cannot change the subtitle position,
because is the default behaviour to allow subtitles to be displayed as designated by the authors

to force disable metadata positions, you have to enable setting "override subtitle style" to "positions"
pay attention when you select "override subtitle style" item, to read the info description that appears to below screen
that explain you what happens

**Comment by Hawkedon** [comment]
Thanks! Setting "override subtitle style" to "positions" seems working for me, but the font size is not the same as without this option (much larger). Is this expected? I thought this option is only for position, not for style, right? And what will happen for the ASS position tags ("\pos" for example)? Will these tags be ignored with this option (e.g., all subtitles lines will be at the bottom of screen)?

**Comment by CastagnaIT** [comment]
as explained in setting info description using overrides will cause side effects
you can only try & test each override setting

tags are forced behaviours, and cannot be changed
it is possible that override settings corrupt some tag effects, but we cannot know exaclty the side effects,
since subtitle rendering is done by external library, not by kodi itself

if you want remove author specs, more that this cannot be done

**Comment by Hawkedon** [comment]
Thanks!
