### ISSUE TITLE
Resume of PVR playback at wrong timestamp in MySQL setup

### ISSUE THREAD

**Issue by lomion0815** [xbmc/xbmc#22949]
### Describe the bug
I am using 2 Kodi installations on 2 different devices. MySQL database is in use.
When I stop playback of a recording (pvr.hts addon) the position is saved.
When I start playback of the recording on the second device, then the pop up "Resume at" shows the correct time (where I stopped at device 1) but playback resumes at the previous position.
When I restart device 2 after stopping playback at device 1 and before starting playback at device 2 then the correct position is resumed (because it was read from DB at startup).

Remark: Kodi behaves correctly for movies therefor this seems to be related to the PVR code!

## Expected Behavior
Resuming playback of PVR recordings based on the timestamp in the DB.

## Actual Behavior
Resuming playback of PVR recordings is based on the locally (in memory) stored timestamp.

## Possible Fix
Use the timestamp from the DB which is available since the "Resume at" pop up shows the correct time to resume.

### Debuglog
Can be provided if required settings are stated

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec
 - Kodi version: Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by lrusak** [comment]
Please post a debug log.

**Comment by lomion0815** [comment]
Debuglog can be found [here](https://paste.kodi.tv/utideconig.kodi)
In this log I started the recording once (9min 42 secs). Changed position on second device to 4 min 15 sec (not in log). Then started again (Pop shows 9min 42 sec but this I did not find in the log) but started at 9 min 44 secs or so.

**Comment by ksooo** [comment]
Have you activated server side play count in the settings of the tvh addons? Should not be required if you use shared video db, just need this information to try to reproduce the issue.

**Comment by lomion0815** [comment]
At first it was activated. I turned it off then (on both devices) but did not change the behaviour.

**Comment by ksooo** [comment]
I have a similar setup. 2 devices, shared video database, pvr.hts connected to same tvh server on every device.

With server-side playstate enabled on both devices I cannot reproduce your issue. And it is hard to believe that this does not work for you, as the code is straight forward and shared video db is not used in this configuration, and the resume value is fetched every ten seconds from the tvh server. Maybe you were to fast (< 10 secs playback on device 2 after stop playback on device 1)?
 
With server-play playstate disabled on both devices I can reproduce with one small exception: Can you please double check that on device 2 the correct resume time appears in the resume popup, but playback actually starts at another time? Looking at the code, this almost cannot be. What I see on device 2 is wrong (old) time in popup and playback starts at old resume point. Not what we want and with same resulting buggy behavior, but slightly different to what you describe. In this configuration, root cause of the bug is that the resume time value is not re-fetched from the video database, the code simply does not know about changes of the value and would need to refetch the value from the on every playback request, like it is done for normal (non PVR) videos.

**Comment by lomion0815** [comment]
You are absolutely right, I was too fast!
I now checked the logs for "AddOnLog: pvr.hts: Getting play position ..." and after receiving such log entry the playback is synchronized on all three devices it tested with.
Therefore I thank you for your support and will close this ticket!

If you like I can test the behavior you mentioned with server-playstate off tomorrow.

**Comment by ksooo** [comment]
> If you like I can test the behavior you mentioned with server-playstate off tomorrow.

 Thanks, not needed. I know what the problem is and will put it on my todo list.
