### ISSUE TITLE
Running in full screen mode. Kodi is fine. But when I Alt+Tab to desktop. My desktop is covered in green and blue mosaic.

### ISSUE THREAD

**Issue by maxiwu** [xbmc/xbmc#23140]
### Describe the bug
Here is a clear and concise description of what the problem is:
Running in full screen mode. Kodi is fine. But when I Alt+Tab to desktop. My desktop is covered in green and blue mosaic.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
I am expecting my desktop works normally.

## Actual Behavior
Everything in Desktop screen tear apart in green/blue mosiac

## Possible Fix
I don't know. Turn off hardware acceleration? debug with Vega GPU?

### To Reproduce
1. run Kodi in Windows 11
2. Turn on full screen
3. Alt+Tab to desktop

### Debuglog
The debuglog can be found here:
https://gist.githubusercontent.com/maxiwu/245a286b96176a89a8a6abb540c14854/raw/12a693f92aebd9963f9a04ccaa43e144b6945c89/Kodi.log

### Screenshots
Here are some links or screenshots to help explain the problem:
The screenshot using Win+S is normal.

### Your Environment
Used Operating system:
Ryzen 7 4800H Laptop running Windows 11.
KODI 64 bit version.

 - Operating system version/name:
 - Kodi version: Kodi v20.1 (Nexus)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
` info <general>: DX::DeviceResources::GetVideoDriverVersion: video driver version is AMD 27.20.11028.11001`

This video driver is too old and is not designed for use in Windows 11.

Windows 11 uses WDDM 3.0 at least or 3.1 or 3.2. 

You should update video driver to newer one and version number should start with 30. or 31.  i.e. `31.0.12029.1042`

> The screenshot using Win+S is normal.

This also demonstrates the problem is external to Kodi (HW / video driver)
