### ISSUE TITLE
[Windows] HDR10 passthrough using limited range is broken on NVIDIA cards in master branch

### ISSUE THREAD

**Issue by thexai** [xbmc/xbmc#23357]
### Describe the bug
Here is a clear and concise description of what the problem is:

HDR10 passthrough using limited color range is broken on NVIDIA cards in master branch.

Previously was (and still) working fine with RTX 2060 on v20/Nexus

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback fine using HDR10 passthrough with limited color range output.

## Actual Behavior
Kodi halts in `IsFormatConversionSupported`:

https://github.com/xbmc/xbmc/blob/d6b9189f5ca69886c4195e7695632197e27dd9f6/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp#L119

Done several extensive tests:

- This only affects NVIDIA (probably also AMD) but is working fine on Intel (NUC8i3BEK).
- In NVIDIA behavior varies depending on hardware used.
- Tested various NVIDIA drivers (535.98, 528,49, 517.48) and no differences found.

| Model        |  Driver version   | IsFormatConversionSupported | black level  |
|    :---:         |         :---:             |                   :----:                        |        :---:      |
| RTX 2060   |    535.98             |            failed                              |    correct    |
| RTX 4070   |    535.98             |            failed                              |    wrong     |

The main reason of behavior change in v21 is that color conversions are strictly validated with `IsFormatConversionSupported` also this is even more broken using newer RTX 40x because black level is wrong if bypass `IsFormatConversionSupported`

In summary: 

- In master branch is broken for all NVIDIA graphics cards.
- In Nexus seems only broken in new RTX 40x, this is probably the reason of no complaints so far.
- It seems that NVIDIA is going in the direction of not supporting HDR10 limited range output and we could say that with older RTX 20x, 30x and GTX 10x, 16x graphics, it is working fine by chance because IsFormatConversionSupported fails anyway.

## Possible Fix

`IsFormatConversionSupported` seems well implemented and no issues found. Is not possible bypass / remove because in newer graphics black level obtained is wrong. Tested alternative TOPLEFT color space `DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020` and the result is the same.

I have some idea that I have tried and it works but I need to think about how to implement it correctly since it could cause other side effects, basically is always use full range in the video driver and move range conversion to swap chain. This is move this functionality  from video driver to Win32 API then it is very unlikely that there will be behavior variations due different hardware.

### To Reproduce

1. Configure limited color range in settings 
2. Play HDR10 video in a setup that supports HDR passthrough

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/edawolasid.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Windows 11 22H2
 - Kodi version: v21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
The description doesn't say, but this is a dxva-only problem, correct? Pixel shaders are fine?
Strange result with RTX 2060.

I think there are 2 separate points.

1/ what to do with the return value of IsFormatConversionSupported 
2/ what to do about limited range and dxva processor lacking support

For 1/ I think we're in agreement that in preparation for release, an unsupported conversion should not fail Configure() but only log a warning for an unsupported conversion and possible fallback to an imperfect conversion.

For 2/
The API for the swap chain color space is Windows 10+ only. Windows 8.1 is still supported in v21, so the solution doesn't seem practical.

For my AMD, the rendering falls back to Pixel Shaders in your scenario. IsBT2020Supported() called by GetWeight() returns false.
IsBT2020Supported() makes the assumption that a processor support for RGB Studio SDR output is always the same as support for RGB Studio HDR output. For my AMD it's true.
The assumption is broken with the RTX 4070. It supports full and studio in SDR, but only full in HDR (see your log output of CProcessorHD::ListSupportedConversions)
IsBT2020Supported was originally meant to check HDR to SDR options, not HDR to HDR.

Another strange thing in your log:
> DXVA::CProcessorHD::IsFormatConversionSupported: conversion from P010 / YCBCR_STUDIO_G22_LEFT_P2020 to R10G10B10A2_UNORM / RGB_STUDIO_G22_NONE_P2020 is NOT supported

For passthrough of HDR, G22 transfer is unexpected, instead of G2084. There is no need to avoid tone-mapping by dxva in a passthrough situation. The G22 transfer test happens because of InitProcessor setting m_bSupportHDR10Limited to false. Same thing happens on my AMD if I bypass the GetWeight() check.

Even if that changed, the RTX4070 would still answer false to IsFormatConversionSupported(), but maybe the processor would fallback on full range and give a picture.

So for solutions, I'd say, either:
a/ fix GetWeight/IsBT2020Supported to return false and fallback to pixel shaders
or
b/ make dvxa processor output full range and have the output shader convert the range.

drawback of a/: can't use the fancy dxva scalers with limited output since they are coupled with dxva color conversion in dxva render method.
however a/ is less intrusive.

**Comment by CrystalP** [comment]
possible solution / workaround c/ Set Kodi in full range and rely on the GPU driver's output format for the conversion (select RGB full or limited in driver's control panel).
Might be problematic for legacy drivers and drivers provided by Microsoft / Windows Update without the vendor control panel, as I don't remember a range selection in Windows' standard control panel.

**Comment by thexai** [comment]
> Another strange thing in your log:
> 
> DXVA::CProcessorHD::IsFormatConversionSupported: conversion from P010 / YCBCR_STUDIO_G22_LEFT_P2020 to R10G10B10A2_UNORM / RGB_STUDIO_G22_NONE_P2020 is NOT supported

This is because previously is checked support of `DXGI_COLOR_SPACE_RGB_STUDIO_G2084_NONE_P2020` and if not supported is used `DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P2020` as fallback. Two bad things here: is a assumed `DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P2020` always is supported and is assumed correct picture. This as worked for a while witch GTX 10x, RTX 20 but not in RTX 4070.

I'm preparing a PR that eliminates this workaround (as is not valid anymore) and fallback to Pixel Shaders in GetWeight. 

I have discarded the initial idea I had (conversion in swap chain) for various reasons:

- Too complicated.
- It's another workaround.
- Double video range conversion: limited to full (in driver) and full to limited in swap chain.

Is supposed that main reason of use limited range is avoid unnecessary video conversions and improve precision (avoid errors due scale change and quantization).

Then for HDR10 in DXVA only "nominal" color spaces will be used `DXGI_COLOR_SPACE_RGB_STUDIO_G2084_NONE_P2020` and `DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020` depending on output range and if these are not supported will be fallback to Pixel Sahders. 

This will simplify things and avoid "unexpected" results.

**Comment by CrystalP** [comment]
Yes might as well not put too much effort in it - not sure how many people use the limited mode, probably only "bit perfect" purists.
Agreed that it looks like manufacturers are gradually removing support for limited RGB.

**Comment by wojtekLs** [comment]
Just huge + for this. Getting fedup with heavilymarketed close-to-noexistance "quality" of RTXes.

we have our ownoutplementaion of MOB_Dickheads()

Nikita you shit

**Comment by wojtekLs** [comment]
> manufacturers are gradually removing support for limited RGB.

@CrystalP any reasoning why they may be doing this?

**Comment by CrystalP** [comment]
@wojtekLs I would guess because it's not a common use case. Computer screens are full range.

For bit perfect, it looks like these days you can stay in NV12 or P010 without back and forth conversions from decode up to the screen. Then the display internally convert the YCbCr to RGB to driver the screen, same way it does for a bluray source.
