### ISSUE TITLE
V20.0+ Profile switch results in hang on logout (Android/Shield arm64-v8a) after SMB shares added (clean install)

### ISSUE THREAD

**Issue by cods69** [xbmc/xbmc#23592]
### Describe the bug
Here is a clear and concise description of what the problem is:

I only noticed this after an sdcard fail and re-installing 20.2 (which has been updated incrementally since Matrix days)
After fresh install on NVidia Shield (2019 pro), an easily replicated hang occurs when exiting an added profile with content scanned in.
Bonus points: Browse for new share looses the share visibility that was created after this hang/exit issue (or thereabouts), but seems to still have access to the directory.
<= 19.5 none of these problems occur >= 20.0 problem begins

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Log out of profile should go to profile selection screen.

## Actual Behavior

Log out of profile (with some SMB scanned content) blanks kodi to background only with clock.  Must be forced to close from android to exit.

## Possible Fix

Revert to 19.5

### To Reproduce

1. Any version of Kodi (Android 64v8a) after 20.0 inclusive, clean install.  (19.5 and prior work normally)
2. Immediately create 2 sub profiles (all options to separate/start fresh) from master.
3. Log off Master and switch to each new profile to enable.
4. Optionally exit/start Kodi again.  Switch to first new profile.
5. Options/media/video/add videos/browse/add network location/Windows SMB share using ip/share folder/user/passwd/ok
6. Select your share and scan in a small test media directory using an info provider (I use music videos with theaudiodb - music videos).
7. Back out and exit app.
8. Start again, Log in to new profile with scanned data, then to log off current profile = hang on empty screen with the clock the only thing on the screen.  Must force app exit from Android to move on - restarting will return to master profile (which can always be switched out ok).

### Debuglog

The debuglog can be found here:
Kodi hangs and refreshes debug log on restart.  Easily replicated issue, however.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I've always struggled with profiles (restricting kids access to murderous rampage movies) and followed a suggestion from here https://forum.kodi.tv/showthread.php?tid=360172
After only using the master profile to create the additional 2 profiles, I came across the exit profile hang issue (as well as finding the network share disappears from the "Browse for new Share" screen after this problem begins.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android latest release (NVShield) 
 - Kodi version: 20.0, 20.1, 20.2, 21.0-Omega_alpha2-arm64-v8a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by joseluismarti** [comment]
Hi, we are trying to correct this issue, when you can test [this devel build](https://jenkins.kodi.tv/job/android-arm64-docker/3327/artifact/kodi-20230903-c9e99fa1-PR23713-arm64-v8a.apk).
Please give us your feedback on whether the issue is solved and if any new ones arise.

**Comment by cods69** [comment]
Apologies for the gap in response.  
I've just tested 21.0-Beta1 (20.90.801) and the same issue still exists.  Following exact procedure as above to reproduce.
Attaching logs I've pulled from this test.
[kodi.log](https://github.com/xbmc/xbmc/files/13245956/kodi.log)
[kodi.old.log](https://github.com/xbmc/xbmc/files/13245957/kodi.old.log)

**Comment by cods69** [comment]
Additional note - updating to 20.2 release after installing profiles to 19.5 as per above.
First run on updated version locks again when switching from SMB loaded profile.  Kill app, then Kodi loads empty master profile.
Switch to SMB loaded profile, allow full scan.  Exit and start Kodi again.  Next switch from SMB loaded profile to another now works.  
No logs to provide yet.  Can be done if someone would like them.  (It's just a bit arduous to get back to this point so please ping me if they will be handy).  Thanks again.

**Comment by tperetzke** [comment]
I confirm this behaviour for all 20.x versions as well as for 21.0 Beta2

My steps to reproduce:
- Amazon FireTV Cube (3rd generation) (Android, FireOS fully patched)
- Kodi Nexus 20.2 or Kodi 20.0 Omega Beta2 (ARM7A 32bit)
- Fresh and clean install as described in first post of this thread (without any addons)
- Set up 4 profiles (2 with and 2 without PIN / all profiles with independent/uncoupled share-settings)
- Profiles without SMB-shares can leave their session by using the Logoff-entry via Power-button-menu
- Exactly in that moment when an SMB-share is set up (IP + user/pass + successful connection-test) in one of those profiles, this profile is immediately unable to leave via the Logoff-menu-entry behind the Power-button-icon
Result: Screen blanks to its background color from the currently logged in profile, only the clock is visible, but stands still (freeze). You can only kill the Kodi app from here on (I waited ~30 minutes - no change / I also pulled the network cable, since I thought I could trigger a pushed up timeout - but had no effect)

Interesting for the developers maybe: It is possible to directly *switch* to another profile:
(Something in the code works differently here, when following this (annoying) procedure)
1. Load into a profile with SMB shares
2. Click the cog-/gear-icon (settings) right from the power-icon
3. Navigate to the "Profiles"-icon (last row, 2nd from the right in the default-skin / Estuary-skin)
4. Here you'll have to type in the Master-PIN (since one profile got an individual PIN)
5. Navigate (on the left menu) to "Profiles"-entry (on the main screen you'll see now all profiles with huge person-icons)
6. Just navigate to the one you want to switch to (only navigate! do not click!)
7. On the profile-icon you'll need to click now the menu-button on your remote to open the context-menu 
8. In the context menu choose "Load Profile"
9. Kodi switches successfully to the desired profile

**Comment by btanner2** [comment]
I can 100% confirm this issue for all Kodi versions >= 20.0. I used profiles since the beginning of their introduction in Kodi on multiple FireTv Sticks, which all connects to a NAS via SMB. I had always created two new profiles (adults & kids) and I never changed the master profile in any way. I never had any problems with using profiles or switching between them. 

Problems started first with Version 20.0. Changing between profiles makes Kodi freeze. I had to kill Kodi manually every time and restart it. Very annoying. This is exactly the reason I had to stay with version 19.5 until today.

I am very unhappy to read here, the issue still exists in Kodi 21 Beta 2. I put all my hopes in this new version. The bug exists since 16 January 2023 (release date of Kodi v20.0), which is almost a year now.

Is there really nothing what could be done, to track this issue down?

I really love Kodi, but I do not want to stay forever with version 19.5.

Brian

**Comment by cods69** [comment]
Problem still exists in V21RC2.  More details to come after fresh install test, but some details are [here](https://forum.kodi.tv/showthread.php?tid=374045&pid=3189807#pid3189807) for now.

**Comment by cods69** [comment]
Confirmed problem still exists on V21 RC2, with both 'Over the top' install over 19.5, as well as fresh install.
Something I took from this test is, after all procedures are performed as per OP, I can still log out/in of the master profile, which has no SMB shares defined, unlike the other created profiles.  
Hopefully there is a hint in that somewhere for a dev to cast an eye over it.

**Comment by joseluismarti** [comment]
A fix (#24883) has been added in profiles which will probably solve this issue, try a devel build of 22.0 Alpha 1 ([apk](https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/))

**Comment by cods69** [comment]
Great stuff!  
Tested kodi-20240328-122a3696-master-arm64-v8a.apk with over the top install, as well as fresh install as per OP.
Profiles are now switching again.  
Any ideas which release this PR/backport will make it in to, and roughly when?  Shall I close this issue when it's released, or now?
Thanks again to all contributors.  Greatly appreciated!

**Comment by ksooo** [comment]
The fix will be in v21 final and v22.

**Comment by cods69** [comment]
Tested V21 Release over the top install and looks great! 
Thanks again to all involved.  Very much appreciated.

**Comment by tperetzke** [comment]
Can confirm this as well in v21... works again. 
Great work guys!!
Thanks a lot!
