### ISSUE TITLE
Some subtitles are being cropped

### ISSUE THREAD

**Issue by akovia** [xbmc/xbmc#23737]
### Describe the bug

Certain videos have subtitles that are being cropped off screen. 
I'm not versed enough in subtitles to know what the common factor is, but it has happened on multiple occasions.
I can try and hunt down other examples if the issue can't be discerned from this example alone.

Every other player that I've tried seems to render the subtitles correctly.

## Expected Behavior

All subtitles should be visible on screen.

## Actual Behavior

Subtitles are cropped and not completely visible.

### To Reproduce

1.  Watch a video file that is affected. (Please see attached subtitle file.)

### Debuglog

https://paste.kodi.tv/vonihafane.kodi

### Screenshots 

Video file displayed in Kodi, and same file in Haruna media player.
https://i.ibb.co/7Kw9kV7/Kodi-Cropped-Subs.jpg

Video file displayed in Aegisub to see the subtitle positioning in the file.
https://i.ibb.co/TbDYF8Z/Kodi-Cropped-Subs-2.jpg

## Additional context or screenshots (if appropriate)

Here is a copy of the subtitle file.
[Subtitle File](https://mega.nz/file/AB5UTQSJ#6o5CezulVba9iIpjgLQTCETqAkaMqbSK4Xhbko1s9Kc)
Can share the video file as well if needed

Experiencing the same behavior on my Linux desktop, and Nvidia Shield.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 **Operating system version/name:**
 - Linux / 6.4.12-arch1-1 (64-bit)
 - Android / 9.1.1(33.2.0.157)
 
 **Kodi version:** 
 - 20.2 (20.2.0) Git:20230821-nogitfound

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
I was also able to replicate this issue...

https://forum.kodi.tv/showthread.php?tid=374372

**Comment by CrystalP** [comment]
You included the media info of the file in the forum, and the font "Katsudon DEMO" used by the style "Name5" of the sub is not in the list.

It's obvious from the screenshots that Kodi is substituting a different and larger font, and since Name5 uses centered aligment, some text gets cut off.

I downloaded the font, muxed it with the sub in another video of similar dimensions and the text is OK (don't pay attention to the other texts, they use default fonts)

![image](https://github.com/xbmc/xbmc/assets/489377/2e4ac922-0df6-4257-9f49-c95b314d40d9)

For best results, videos should include all the fonts used by the subs.

I'd guess that other players find the font somewhere on your system but Kodi doesn't.
Did all the screenshots come from the same box?
Android may be different, but on Windows Kodi finds fonts installed in the system (tested and worked in this case), so there may be an Android bug there, I don't know.

**Comment by CastagnaIT** [comment]
your log is not useful, since debug information is not enabled,
if it were enabled it would most likely print that there is some problem with the fonts

as i can see on your screenshot i confirm what said by @CrystalP
the font referred to style "Name5" is missing or have a wrong name
since its not loaded, fallback to kodi default font

kodi font vs Katsudon DEMO more likely have differents characteristics are displayed also with different size
imo this is not a kodi bug but a correct behaviour

**Comment by akovia** [comment]
Thanks @CrystalP  and @CastagnaIT 
Those all sounds like reasonable solutions and will try them tonight when I get home. 

I think I may have overlooked it being a font issue because I tried the override setting and didn't see a change at all. I incorrectly thought that a default font would display properly in the absence or the custom font.

I agree that this isn't technically a bug now that I understand what's happening, but I also don't think it would hurt to handle errors like this a little more gracefully. The other players I've tried seem to overcome the issue and wondered if Kodi might be able to do the same. Possibly even a notification when fonts can't be loaded? 
Just a thought.

Sounds like I'll be able to fix this now and will know what to do in the future.
Thanks so much!

**Comment by CrystalP** [comment]
Maybe Kodi could provide a better substitution (large difference with other players you showed), but I don't know how that mechanism works in Kodi and if it's influenced by user settings.
Tried VLC and its substitution is also too large, but barely. mpv does exactly the same as VLC.

**Comment by akovia** [comment]
Maybe there really isn't a good solution. 

I have VLC installed on my Nvidia Shield, so will see how that reacts tonight as well. I'm assuming you are trying these on Windows? I wonder if there was something about Haruna that was just blind luck, or they are actually doing something to overcome the issue by trying to font match somehow.

A friend of mine is watching the same series/files on his Jeffyfin media player, so I will try to get his feedback as well. I'm just happy I'll be able to fix this myself vs having to wait for an update, but I can imagine this has to be frustrating for people not technically capable or inclined to track down the issue. 

Being able to fail gracefully is always a plus, even if at no fault of the player. But it may not even be possible.

**Comment by CastagnaIT** [comment]
the size depends from many factors like
-the font used, that can have different height/resolution
-the style set for a line of text ("Name5" style have font size set to 70 thats not so lower)
-the playres scale set
-and more likely other things thats im not aware

overriding settings are the only things that we can act

the font fallback isnt handled by kodi, is fully managed by external libass library and we have no control over this thing,
if libass find a compatible font it take a substitution font automatically, otherwise will fallback to kodi font

> I incorrectly thought that a default font would display properly in the absence or the custom font.

the major problem here is that has been used `/pos` tag on the text, this is the reason why then the font go out of the screen
the current ass subtitle has been written for that specific fonts, not to use it with other fonts,
otherwise in order to avoid this problem, the author of that subtitle file should use the regular text alignment and not `/pos` tag

> Possibly even a notification when fonts can't be loaded?

there is no direct way to know when its missing, in general also i dont think its good thing add a notification because many subtitles can be played also without original fonts with no problem, show every time a message will result annoying for many users, should the user itself take care to add the appropriate fonts for his subtitles files

to take in account that font fallback behaviour can change by operative system used,
e.g. on android there is no access to system installed fonts, where on windows there is,
then where there is possibility to get system fonts, there are more chance that will find a compatible font

**Comment by CastagnaIT** [comment]
however iirc there should be an issue opened for the problem that `\pos` tag dont position the text perfectly on screen with kodi
that should be the reason why there is some displacement of the text comparing with other players like vlc

**Comment by akovia** [comment]
Thank you @CastagnaIT for such a good explanation!

That all makes sense, and of course it's never as simple as you hope it would be. It's definitely no big deal for me to get the proper fonts and put them where Kodi can find them. Be it alongside the video files, or a central folder to help avoid unnecessary bloat. I'm excited to be able to fix this and see the subtitles as intended.

I think most fansubbers are very good at including the fonts because I haven't run into this very often.
