### ISSUE TITLE
Kodi 20.2 60fps 4K/HDR BUG, AMD Windows 11

### ISSUE THREAD

**Issue by Simkin84** [xbmc/xbmc#23759]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 20.2 does not sync to 24fps on 4K HDR videos, but stay on 60fps. This works fine on previous kodi releases from 20.1 and earlier

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect kodi to sync refresh rate to display 24fps, it does not. 

## Actual Behavior

Video stays at 60fps, 4K HDR videos like UHD BluRay's

## Possible Fix

Not sure

### To Reproduce

1. Reproduce with AMD APU/GPU, Windows 11 and UHD HDR Video
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/losebobomu.kodi 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2 Windows 11 Home

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
As discussed on forum in https://forum.kodi.tv/showthread.php?tid=374325

This comes from PR #23241 which fixes a color space issue with a swap chain recreation, but unfortunately in Windows 11 it also causes the refresh rate to go back to desktop rate (60Hz instead of 24Hz for example).
Fix was reverted with PR #23522 for Intel and nVidia since they didn't have color space issue and they now work correctly in Win 10 and 11.
At the time the behavior of AMD+Win11 combination was not known but with this new issue it is now clear that it suffers from both problems. AMD color space issue and Windows 11 problem with rate switching, and different fix will be required to preserve the new refresh rate while recreating a swap chain (or maybe another way to fix the color space issue can be found...)
