### ISSUE TITLE
Kodi 21 crash on watching IPTV

### ISSUE THREAD

**Issue by 78andyp** [xbmc/xbmc#23803]
### Describe the bug
Here is a clear and concise description of what the problem is:

Load Kodi
Watch IPTV
After a few minutes (seems to be anywhere between 2-20m) crashes to desktop
Crash dump always shows memcpy error in VC runtimes I think

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash

## Actual Behavior

Crash

## Possible Fix

Unsure

### To Reproduce

As above

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/beyenovemo.kodi

Crash DMP - https://file.io/hCyzDrMCH8qP

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 22H2
 - Kodi version: 21 alpha 3

[kodi_stacktrace-21.0-ALPHA3 Git_20230921-34bab8bb60-20230923-111755.zip](https://github.com/xbmc/xbmc/files/12741183/kodi_stacktrace-21.0-ALPHA3.Git_20230921-34bab8bb60-20230923-111755.zip)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@78andyp the crashdump is no longer available. Can you attach it to the bug report instead of using an external site? Thanks.

**Comment by 78andyp** [comment]
@enen92 Hi. Thanks for looking. I've attached it to the first post. Andy

**Comment by CrystalP** [comment]
Since this is your custom build, the .pdb needed to use the dump is not available, can you do the same with an install of official alpha3?

**Comment by 78andyp** [comment]
Of course.
Please find attached.

Dump - [kodi_crashlog-21.0-ALPHA3 Git_20230908-4d639b82d1-20230929-145502.zip](https://github.com/xbmc/xbmc/files/12768777/kodi_crashlog-21.0-ALPHA3.Git_20230908-4d639b82d1-20230929-145502.zip)

Log - https://paste.kodi.tv/qojihinuja.kodi

Thanks
Andy

**Comment by 78andyp** [comment]
Additional log with logging for ffmpeg, AV and PVR enabled.

Log - (too large to post normally) - [kodi.log.zip](https://github.com/xbmc/xbmc/files/12777658/kodi.log.zip)

Crashdump - [kodi_stacktrace-21.0-ALPHA3 Git_20230930-31cdd8f395-20231001-165500.zip](https://github.com/xbmc/xbmc/files/12777661/kodi_stacktrace-21.0-ALPHA3.Git_20230930-31cdd8f395-20231001-165500.zip)

PDB - https://file.io/blhRXEgDk33c

Thanks
Andy

**Comment by CrystalP** [comment]
The crash is in ffmpeg. Please try with dxva2 turned off.

This is the call stack using the symbols:
![image](https://github.com/xbmc/xbmc/assets/489377/837303cc-7164-4746-8150-b2397f28a5da)

It's different from the crash reported in #23547 (different crash location ff_dxva2_get_surface_index() instead of ff_h264_update_thread_context() here)

**Comment by CrystalP** [comment]
I tried the channel from your log (The Weather Channel) and no problem after a couple hours of playback... Windows 10, AMD and nVidia GPU, bare bones Kodi install.

**Comment by 78andyp** [comment]
Thanks.

You are right about DXVA2 turned off - it ran all night.

It is however very jerky after the first few minutes, with little or no AV sync.
If I stop and start the stream it's fine for another few minutes.
The log seems to have a massive number of AV sync issues.
This could of course be completely unrelated - shall I open another ticket?
(Internet is about 300Mbps, ethernet connection is 2.5Gbps)

Debug log - 
[kodi.old.zip](https://github.com/xbmc/xbmc/files/12781788/kodi.old.zip)

Thanks
Andy

**Comment by CrystalP** [comment]
mmm no jerkyness/slowdown or AV sync issues here with software decode. Sometimes a pause for buffering (same with dxva), that's it.
I get sync issues mostly for the commercials segments, otherwise the log is clean.
My internet connection is much slower than yours...
Whatever is happening should not cause an exception in ffmpeg but without repro it's difficult to take this further.
You could try the forums, maybe someone else has the same thing and a solution.

**Comment by 78andyp** [comment]
Thanks.

I've managed to fix the jerkiness by commenting out the following:

`void CVideoPlayer::UpdateCorrection(DemuxPacket* pkt, double correction)
{
  pkt->m_ptsOffsetCorrection = correction;

/* if (pkt->dts != DVD_NOPTS_VALUE)
    pkt->dts -= correction;
  if(pkt->pts != DVD_NOPTS_VALUE)
    pkt->pts -= correction; */
}`

I've just watched the weather channel successfully for over an hour.
The only reason I looked ath dts/pts is there were lots of errors with ffmpeg logging enabled.

It clearly isn't the correct answer - I now need to understand what I've actullay done and the implications!!

For the time being I'll try and add some code that turns off DXVA2 whenever I watch TV automatically.

Thank you for your help.
Andy

**Comment by CrystalP** [comment]
Interesting, there were changes in seek handling for PVR  just prior to alpha 3 release and there could be side effects. The ffmpeg bump of v21 earlier may have played a role as well because of ffmpeg changes.
Maybe alpha 2 could give you better results, or 20.2. A known good version would help figure things out.
You could report this as a separate issue/ticket. Repro may still be tricky but your ability to apply and test patches will help.

In a few (most?) of your logs, the last thing before the crash is the dxva decoder reopening. It's likely either Kodi or ffmpeg uses a deallocated resource from the previous context.
On my system after waiting long enough I can see a few as well in the log but they don't result in a crash.

**Comment by CrystalP** [comment]
I don't want to hijack this issue, but since you are one of the few with an ARC gpu, would you please take a look at https://forum.kodi.tv/showthread.php?tid=374618

**Comment by 78andyp** [comment]
Hi
Thanks
I've narrowed down use cases and the PTS/DTS adjustments a bit more. I will open another bug here.
I will also try with 21a2 first.
More than happy to look at the VSR - I will swap the ARC GPU back into my media center box tomorrow.
Cheers
Andy

**Comment by CrystalP** [comment]
The crash described in #23800 also happens in Windows, it could be that commenting out avcodec_flush_buffers() may help here as well, who knows.

**Comment by 78andyp** [comment]
@CrystalP 
I commented out the flush and let IPTV run all night.
It still crashed - although it looks like it's something to do with writing to a file (????) and the ffmpeg bits of the log do look better.

Crash dump - 
[kodi_crashlog-21.0-BETA1 Git_20231023-fa756036a0-dirty-20231024-094902.dmp](https://github.com/xbmc/xbmc/files/13113561/kodi_crashlog-21.0-BETA1.Git_20231023-fa756036a0-dirty-20231024-094902.dmp)
PDB - https://easyupload.io/36q706
Log - (RAR'd as massive with ffmpeg debug logging but renamed to zip to upload here) 
[kodi.avf.zip](https://github.com/xbmc/xbmc/files/13113585/kodi.avf.zip)

<img width="490" alt="image" src="https://github.com/xbmc/xbmc/assets/99039295/e6bb4807-5a8f-476a-b251-0752a8ef2aff">

<img width="361" alt="image" src="https://github.com/xbmc/xbmc/assets/99039295/8135274a-72ce-4e6b-ad89-d6a0e23caae6">

If this is unrealated I'll open another bug.

Thanks
Andy

**Comment by CrystalP** [comment]
There are signs of memory exhaustion but does it come from the iptv addon (preexisting) or leaking d3d resources (commented out ffmpeg flush)? It's more difficult to say with integrated graphics using the system memory (Intel igpu this time?)

If running all night with software decoding succeeds (and memory usage appears normal / stable in task manager) the problem is most likely going to be ffmpeg leakage.


Looking at the log:

Last decoder recreation had problems:
`error <general>: DXVA::CContext::CreateSurfaces: failed creating decoder texture array. Error -7FF8FFF2 - E_OUTOFMEMORY (Not enough memory resources are available to complete this operation.)`


The crash happened in a different place though: the episode guide fetching (last lines of the log, and crashing thread name is "EPGUpdater" in the .dmp) and is also memory related. But could also be memory fragmentation after a long time.

`warning <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::WriteCallback - (0x29b3ed13aa0) Failed to grow overflow buffer from 3538062 bytes to 3554446 bytes`

It's a separate issue but it's more important to fix the reason of the inability to grow said buffer than not crashing in a no memory situation (infrequent hopefully).


There was also a screen resolutions enumeration for no reason at then end? but it's difficult to read with all the ffmpeg stuff,

Thanks for the .pdb but it's only useful with the matching .exe. They work as a pair for debuggers.


I'm also concerned that you have very frequent decoder recreations (sometimes every few seconds), there may be an issue there as well and it would exacerbate a memory leak. I didn't have nearly the same amount on the same stream (weather channel).

**Comment by 78andyp** [comment]
Hi

Sorry I'd built a new exe with an added line to show every missed flush.

I ran it again overnight.

Memory in task manager stable at about 260MB. Yes this is a laptop with iGPU and an ARC 370M dGPU.

Playback very choppy (which as above happens after a while) but no crash - with DXVA enabled.

Log - 
[kodi.zip](https://github.com/xbmc/xbmc/files/13164118/kodi.zip) (rename .RAR)

I've turned ffmpeg logging off this time.

**Comment by 78andyp** [comment]
I let it run overnight again - this time I applied patch #23996 first.
At some point in the early hours (looking at the logs) IPTV stopped.
No crashes though.
Logs - [kodi.zip](https://github.com/xbmc/xbmc/files/13176453/kodi.zip)

**Comment by CrystalP** [comment]
If it's not crashing in ffmpeg anymore I'd suggest closing this and creating another issue for the sync / stuttering.

**Comment by 78andyp** [comment]
Thanks. Will do.
