### ISSUE TITLE
[webOS] Crash when playing AV1 video file

### ISSUE THREAD

**Issue by quietvoid** [xbmc/xbmc#23897]
### Describe the bug
Cannot play an AV1 file.

## Expected Behavior
The file should play.

## Actual Behavior
Kodi crashes.

## Possible Fix
Downgrading to 35680593 fixes the issue.

### To Reproduce
1. Launch Kodi on webOS 5+ with AV1 support
2. Try playing an AV1 file
3. Kodi crashes

### Debuglog
The debuglog can be found here: [kodi.log](https://github.com/xbmc/xbmc/files/12850986/kodi.log)
Crash report: [2023-09-04-nightly-crash-report.txt](https://github.com/xbmc/xbmc/files/12850926/2023-09-04-nightly-crash-report.txt)

## Additional context or screenshots (if appropriate)
This seems to be a regression caused by https://github.com/xbmc/xbmc/pull/23834

### Your Environment
Used Operating system:
 - [x] webOS

 - Operating system version/name: webOS 7, LG OLED C2
 - Kodi version: `org.xbmc.kodi_20231004-0f289470-master_arm.ipk`

**Comment by sundermann** [comment]
I have tracked the issue down further. It seems to be related to the stub `libacbAPI` library. Remove that library and replace it with something else like `libshairplay.so.0`: `cp libshairplay.so.0 libAcbAPI.so.1`. I'm not sure why this is happening because functions from `libacbAPI` are never called on webOS 5+ and `-zlazy` is the default (else we would see segfault when trying to resolve the functions anyway)
