### ISSUE TITLE
Brightness and Contrast settings are enabled when not supported by HW

### ISSUE THREAD

**Issue by jlewis-austin** [xbmc/xbmc#23962]
### Describe the bug
Here is a clear and concise description of what the problem is:

It's commonly reported that Brightness and Contrast settings have no effect for platforms with no support for those filter capabilities, but AFAICT no open issues for the bug itself--the UI shouldn't offer a setting known to be unsupported.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

While playing a video with player configured to use HW rendering, go to video settings, adjust the Brightness slider and observe the screen brightness (contrast) change.

## Actual Behavior

On platforms where the HW doesn't report support for the brightness or contrast FilterCaps, Kodi queries the driver and ignores those settings if they're reported as unsupported, so nothing happens when the sliders are adjusted. Surface Pro Arm devices are affected.

## Possible Fix

There is also a query for filter support when setting up the video settings GUI, but this one is hard-coded to return true from `CWinRenderer::Supports(ERENDERFEATURE feature)` and doesn't distinguish between the DXVA, Shader, and SW renderers. A possible fix would be to actually query the device if the current configuration uses the HW renderer.

### To Reproduce

1. Use an affected device that supports HW acceleration but not brightness or contrast (e.g. Surface Pro Arm device). Alternatively, override the device-reported capabilities by masking out the brightness and contrast caps after the call to m_pEnumerator->GetVideoProcessorCaps() in  CProcessorHD::InitProcessor():
`m_vcaps.FilterCaps &= 0xfffc`
2. Ensure HW acceleration is configured: Go to Settings>>Player and make sure the settings gear is set to Advanced or Expert. Under Videos, set _Render method_ to DXVA
3. Select a video and start playback
4. While playing, go to Settings>>Video Settings and adjust the Brightness and Contrast sliders. Neither has any effect.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/13056527/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The player appears to be broken when GUI features have no effect.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:  Windows 11 22H2
 - Kodi version: 20.2.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CrystalP** [comment]
You are correct that Kodi assumes brightness & contrast control availability unconditionnally and it had been a valid assumption so far. I didn't know Kodi ran on arm surface tablets and the log shows differences in the features support.

It's a problem though that the graphics driver claims to support brightness, contrast, hue and saturation controls as the following log lines show:
```
DXVA::CProcessorHD::InitProcessor: filter 0 has following params - max: 100, min: -100, default: 0
DXVA::CProcessorHD::InitProcessor: filter 1 has following params - max: 100, min: -100, default: 0
DXVA::CProcessorHD::InitProcessor: filter 2 has following params - max: 100, min: -100, default: 0
DXVA::CProcessorHD::InitProcessor: filter 3 has following params - max: 100, min: -100, default: 0
```
The presence of those lines means that the graphics driver set the FilterCaps bits you referred to in reproduction step 1, and it also responded with a success to the subsequent GetVideoProcessorFilterRange() request for each filter instead of erroring out.

It means that it's not possible to hide the settings or use an alternative method based on the support reported by the driver.
A Kodi bug is possible but I don't see where, the code setting the control values is very simple.

Is there a driver update available with a bug fix maybe, or some OS graphics options that could impact the ability of an application to set those controls?

Does the pixel shaders render method work correctly? It's also hardware accelerated and you wouldn't be missing anything, on the contrary.

**Comment by jlewis-austin** [comment]
Sorry, my mistake--I attached the log from my modified build I was using to simulate the driver claiming support for those options. I'll update the log. I'm investigating whether the driver has a bug or actually doesn't support it, but so far it appears to be the latter.
The pixel shader and SW methods do work correctly, so a possible feature request could be to adjust the weighting formula to use brightness/contrast support as at least a tiebreaker for the auto detect algorithm. Right now, both DXVA and pixel shaders are getting a weight of 1000, and the tie goes to DXVA.

**Comment by jlewis-austin** [comment]
Log from installed UWP app updated above

**Comment by thexai** [comment]
The render method DVXA is preferred when using hardware video decoding (DXVA2) because it is a more efficient path (video decoded on GPU memory and rendered from same GPU memory without any copy or transformation). The brightness  adjustment does not seem to be a relevant reason (probably 99% of people do not use it) and if you need to use it it is because you have another problem in your hardware or played media is bad.

Regardless of this, if something works on ARM it's by chance... UWP builds are currently only for Xbox (which is not ARM). And what can be downloaded from Store for desktop is not the pure UWP build but the same regular x86/x64 build (.exe) packaged for the Store.

**Comment by CrystalP** [comment]
I'm on the fence about what to do and also not clear about the use case. Is it that you want to adjust brightness/contrast for specific files, or that you're looking for a global adjustment of Kodi's window (even when not playing video)? Like to adapt when when moving the tablet to a different environment? If so, aren't there OS levels controls to adjust the picture? or ambient light sensors or similar? (not a tablet owner here)

What we can probably do (and we entered beta, so only fixes for now) is to disable the controls when the dxva processor doesn't support them to avoid raising expectations and make things clearer.

**Comment by jlewis-austin** [comment]
> Regardless of this, if something works on ARM it's by chance... UWP builds are currently only for Xbox (which is not ARM). And what can be downloaded from Store for desktop is not the pure UWP build but the same regular x86/x64 build (.exe) packaged for the Store.

@thexai   Well, not exactly by chance :)  Windows on Arm is compatible with x86 apps via emulation, so the expectation is that those apps "just work" with decent performance. I haven't gathered any performance data, but Kodi appears to work fine.

I only threw out the auto detect idea because the current weighting algorithm suggests there is no preference between shaders and DXVA. If that were truly the case, it would make sense to include other factors.

@CrystalP I'm not aware of any use cases requiring new features--this issue is just about the fix to disable the controls when not applicable so it doesn't appear that the functionality is broken.

**Comment by zhouxinghong** [comment]
It is completely impossible to adjust the brightness, contrast, color, and saturation.
kodi 22
Windows 10
