### ISSUE TITLE
[RetroPlayer] GameAgents dialog does not show players

### ISSUE THREAD

**Issue by scott967** [xbmc/xbmc#24072]
### Describe the bug
Here is a clear and concise description of what the problem is:

Attempting to skin gameagents window in DialogGameControllers.xml.  Testing current Estuary implementation gets a list of attached controllers in list id="5"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Unknown what should happen (doesn't seem to be documented) but comments in Estuary skin file suggest list "5" is supposed to be a list of players.

## Actual Behavior

gameagents dialog window list "5" is populated with attached controllers.

### To Reproduce

1. Install arcade emulators in Kodi
2. Attach a couple of USB DirectInput Controllers in Windows 10
3. Install arcade game core "packman.zip"
4. Configure (best as I can) controllers/game
5. Start "packman" in retroplayer and open the "players" dialog

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/rokaceneba.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

![screenshot00003](https://github.com/xbmc/xbmc/assets/11218744/47bc8918-3bf8-4e70-8212-abbc4b38e822)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Skinning DialogGameControllers.xml

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64 22H2
 - Kodi version:21 20231105 nightly.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
The log shows the controller port map:

```

2023-11-07 13:56:12.547 T:3052    debug <general>: ===== Peripheral Map =====
2023-11-07 13:56:12.548 T:3052    debug <general>: /1/game.controller.default:
2023-11-07 13:56:12.548 T:3052    debug <general>:     peripheral.joystick/0 [CH PRO PEDALS USB ]
2023-11-07 13:56:12.548 T:3052    debug <general>: 
2023-11-07 13:56:12.548 T:3052    debug <general>: /2/game.controller.default:
2023-11-07 13:56:12.548 T:3052    debug <general>:     peripheral.joystick/1 [T.16000M]
2023-11-07 13:56:12.548 T:3052    debug <general>: ==========================
```

The screenshot shows the players populating in Estuary correctly, right? Is this a problem in skin.aeonmq5.omegamod? Can you post example XML and a screenshot that shows the problem?

**Comment by garbear** [comment]
OK, I think I see what issue this PR is referring to. It is correct in that the window shows controllers not players. However, this limitation was documented in the window's PR (https://github.com/xbmc/xbmc/pull/23548). I expressed reservation over this limitation, but felt it was better to ship something partially useful (list of controllers) instead of functionally complete (list of players).

I'll open a PR that explains this and better documents the window's behavior.

**Comment by scott967** [comment]
Yes any bit explanation would help for skinning as I don't really understand retrogaming input management and how players/ports/controls work together.  I am using Estuary as a reference in all cases.  Trying to look at retropie which seems to be a model? Are inputs managed at the emulator level or game level?

**Comment by garbear** [comment]
@scott967 Documentation has been added in:

* https://github.com/xbmc/xbmc/pull/24055
* https://github.com/xbmc/xbmc/pull/24073
* https://github.com/xbmc/xbmc/pull/24079

Also, because my Player Viewer still had a lot of conceptual uses of the Player Manager, the variable naming got confusing when I stripped out management. Naming is improved in https://github.com/xbmc/xbmc/pull/24406.

With this work, is there anything left against the current state of master that is still confusing, or can this issue be closed?

**Comment by garbear** [comment]
@scott967 Is this issue ready to be closed?

**Comment by scott967** [comment]
Will close for now.  When the dust settles on versions/extras will go back and see how controller skinning is looking.
