### ISSUE TITLE
Different movie version found popping up 24,345 times.

### ISSUE THREAD

**Issue by KyleSanderson** [xbmc/xbmc#24238]
### Describe the bug
Here is a clear and concise description of what the problem is:
Upgraded to Omega B2 and added my Movie folder.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The library scan to just run...

## Actual Behavior
"Would you like to convert it into an additional version of the original?"

## Possible Fix
This is beyond terrible UX, I can't believe this shipped in a near release version. I don't care if it found a duplicate, that's great! Transparently handle it by default.

### To Reproduce

1. Add a library with multiple copies of the same file.
2. Perform a library scan.
3. Get 24,345 popups.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] macOS
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Beta 2.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KyleSanderson** [comment]
Good lord. I just said yes and there's 3 other popups on this... This is not the right place or time for library management.

**Comment by KarellenX** [comment]
@KyleSanderson 

There is a setting to adjust this behaviour. The default mode should be reversed so there is no interruption to scanning. I believe that will be changed in an upcoming pr.

As for the 23,000 pop-ups, a debuglog will be helpful

![vidvers](https://github.com/xbmc/xbmc/assets/44626605/2c7b174a-35d9-4b0d-93a8-97cad58335d4)

**Comment by thexai** [comment]
The setting exist (it is debatable whether it should be activated by default but it is not a bug).

**Comment by KyleSanderson** [comment]
> The setting exist (it is debatable whether it should be activated by default but it is not a bug).

Uh - no. This is the worst possible outcome for a default feature. It's popping up during playback which goes against nearly 20 years of style guidelines. Absolutely horrific.

**Comment by KarellenX** [comment]
@KyleSanderson 

Please provide a debug log that captures the issue.
Also a screenshot of the message so we can see what you are seeing.

What I find common in your other closed (and somewhat insulting report) is that you are consistently asked for debug logs which you fail to provide each and every time.

I don't know, how would you feel if we open another report with "_Who is this KyleSanderson that never provides debug logs, then gets angry when he gets no help?_"

**Comment by bacon-cheeseburger** [comment]
@KyleSanderson

**Comment by bacon-cheeseburger** [comment]
@KyleSanderson 
I'm not sure why you don't provide the requested logs but it seems like you have a good handle on some of these bugs, along with the skill set to fix them. Since nobody, especially the Kodi community as a whole, benefits from repeated back & forths with other devs, I'd propose using that time & energy to fix the bugs and submit the PR's instead. At the end of the day I think we'd all like to see Kodi actively developed and in a better state tomorrow than it was in today. Generally speaking, it's far better when people create solutions instead of more problems.

Specifically regarding this issue, of course any feature or default setting that produces a bad user experience should be reconsidered at a minimum, but preferably resolved to no longer do so.
