### ISSUE TITLE
kodi unable to use proxy

### ISSUE THREAD

**Issue by upibis** [xbmc/xbmc#24255]
### Describe the bug
Here is a clear and concise description of what the problem is:

every time that I set up an active proxy ( socks or http-s) of any kind ( anonimity levels ) the external ip don't change. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when I set up an active proxy with high anonimity level, it should change the external ip and let go the internet traffic trough it but don't happen

## Actual Behavior

I set up an active proxy ( especially socks type ) and kodi doesn't change external ip

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2 nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
> every time that I set up an active proxy ( socks or http-s) of any kind ( anonimity levels ) the external ip don't change.

Note that "external IP" displayed in kodi settings is not an indication of if proxy is used or not. Also is not and indication external IP reported on router or in some place of OS / device used.

Proxy does not change external IP used. Proxy changes destination IP: all connections are "redirected" to Proxy IP and destination machine only can seen Proxy IP (and not external IP of client): 


NO proxy:

`External IP  ---------------->  Destination IP`


With proxy:

`External IP ----------------> Proxy IP ----------------> Destination IP`


In addition to this, it turns out that technically the IP that can be displayed in Kodi settings is not the external IP that we have talked about here but the _internal_ IP of the local network (e.g. 192.168.1.xx). So it has even less to do with whether you are using a proxy or not.

The way to know if a proxy is being used or not is with the debug log (which you have not provided), probably activating specific log components.

Please use forum for support instead:
https://forum.kodi.tv/forumdisplay.php?fid=164
