### ISSUE TITLE
Duration in album information screen is rendered twice

### ISSUE THREAD

**Issue by neo1973** [xbmc/xbmc#24342]
### Describe the bug
In the album information screen the duration is rendered two times over each other with a slight offset (bottom right corner):
![Screenshot_20231228_150623](https://github.com/xbmc/xbmc/assets/3134317/48a65fd3-a26a-4744-a4a6-f6574bd1a260)

## Expected Behavior
The label is only rendered once.

## Actual Behavior
The label is rendered twice.

## Possible Fix
I narrowed it down to those two labels but I don't understand what's wrong with the visibility conditions:

https://github.com/xbmc/xbmc/blob/f07a9a87497ff0c589220d2e6eb9fa77d6b2e78b/addons/skin.estuary/xml/Includes.xml#L383-L397

https://github.com/xbmc/xbmc/blob/f07a9a87497ff0c589220d2e6eb9fa77d6b2e78b/addons/skin.estuary/xml/Includes.xml#L433-L448

### To Reproduce

1. Go to music
2. Select an album. On the bottom right of the screen the duration is shown
3. Open the context menu and select Information
4. In the information screen the duration label is rendered again over the previously show duration label

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/pawacowoqi.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: master (f07a9a87497ff0c589220d2e6eb9fa77d6b2e78b)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
@jjd-uk maybe something you can look into?

**Comment by jjd-uk** [comment]
Will take a look, most likely my fault since I introduced media flags for music.

**Comment by jjd-uk** [comment]
Strange but I don't see the issue on Windows, and I'm not sure why the rendering would be handled differently for this between Linux & Windows. Anyway I think I can guess at the problem even if I can't observe it for myself, and that's the flags within the nav windows are also shown within the dialog. This does not happen for me on Windows, so to get the flags shown in the music info dialog I also had to add them to the dialog, so there are added at https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/MyMusicNav.xml#L36 and https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/DialogMusicInfo.xml#L535

The simply addition of some visibility exclusions at these locations will probably fix the issue you are seeing, just need to do some testing.

**Comment by jjd-uk** [comment]
@neo1973 can you test if https://github.com/jjd-uk/xbmc/commit/4e0c87e9ebc075e744ceb992e233b954dca4261e works for you, if it does I'll PR.

**Comment by jjd-uk** [comment]
@neo1973 Are you able to try changing:

https://github.com/jjd-uk/xbmc/blob/4e0c87e9ebc075e744ceb992e233b954dca4261e/addons/skin.estuary/xml/Includes.xml#L436

From `<visible>Container.Content(albums) + ![Window.IsActive(songinformation) | Window.IsActive(musicinformation)]</visible>`

To `<visible>Container.Content(albums) + ![Window.IsVisible(songinformation) | Window.IsVisible(musicinformation)]</visible>`

and

https://github.com/jjd-uk/xbmc/blob/4e0c87e9ebc075e744ceb992e233b954dca4261e/addons/skin.estuary/xml/MyMusicNav.xml#L35

From `<include condition="!Skin.HasSetting(hide_mediaflags) + ![Window.IsActive(songinformation) | Window.IsActive(musicinformation)]">MediaFlags</include>`

To `<include condition="!Skin.HasSetting(hide_mediaflags) + ![Window.IsVisible(songinformation) | Window.IsVisible(musicinformation)]">MediaFlags</include>`

I want to know if there any difference for you using `IsVisible` for those conditions instead of `IsActive`.

**Comment by neo1973** [comment]
@jjd-uk: After applying the changes the issue is gone completely :smiley:

**Comment by jjd-uk** [comment]
Excellent, as thought the IsVisible takes better account of any animations.
