### ISSUE TITLE
Kodi Omega Android Nightly - Quad plays as 'Dolby Audio' (stereo only)

### ISSUE THREAD

**Issue by HomerJau** [xbmc/xbmc#24546]
### Describe the bug
Here is a clear and concise description of what the problem is:
I have recently started testing various surround/spatial audio formats on a new Amazon Firestick 4K Max (2nd gen 2023) using latest Kodi v21 Omega Android nightlies.

When I play  Quad FLAC music file with less than 6 channels my AVR shows it is receiving Stereo only (the Denon AVR shows 'Dolby Audio') which then is upmixed by the AVR - wrong).

This is a critical bug for users with Quad music collections.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
All Quad formatted files should play as multi-channel files (not stereo) with the discreet channels sent to the AVR, just like they always have in previous Kodi releases (and do now with LibreElec v21 nightly)

## Actual Behavior
Quad in a 5.1 formatted file (Quad + Silent C and Silent LFE) - this plays a quad on the FTV (correct)
Quad in a 5.0 formatted file (Quad + Silent C) - stereo output only (wrong)
Quad in a 4.0 formatted file (Quad with channel mask L, R, Ls, Rs) - stereo output only (wrong)
Quad in a 4.0 formatted file (Quad with channel mask L, R, Lb Rb - stereo output only (wrong)

## Possible Fix
These exact same files ALL play correctly in LibreElec v12 Beta 2 Generic (Kodi v21 Omega build 17 Jan). These same files have always played correctly in recent Kodi releases (Matrix etc). I assume the Kodi IEC Packer needs a fix (unsure).

### To Reproduce
Steps to reproduce the behaviour:
I have created 4 x 30 sec FLAC test files with the typical channel layouts used by Quad enthusiasts over the years:

Link to zip file containing 4 x FLACs and a FTV Kodi.log file: (78MB)
https://1drv.ms/u/s!Aqs3ia6BNDDHsAwowhnjZHCusXcy?e=zTJXy7

Play these on a Fire TV 4K Max with Kodi Omega Nightly (I suspect other Android devices may have same issue)

### Debuglog
The debuglog can be found here:
A Kodi.log file is in the test file zip linked above:

### Screenshots 
Here are some links or screenshots to help explain the problem:
(none)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Historically  Quad enthusiasts have decoded 4 channel FLAC. Mnay AVR could not play pur 4 channel files so the 4 different formats in the test files are all very commonly used. Kodi needs to support all 4 to be used in the quad community. (it always has BTW)

### Your Environment
Used Operating system:

 - [X ] Android  (Amazon Fire TV 4K Max @nd Gen (2023 model)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
kodi-20240118-65630714-master-armeabi-v7a.apk

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HomerJau** [comment]
Adding more info: The same quad test files play correctly on my Windows PC (the Kodi v21 Beta 2 release)

**Comment by fritsch** [comment]
There is zero to be fixed for kodi, see below:

2024-01-20 15:13:55.214 T:7237     info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 96000 format: AE_FMT_S16LE (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 147840 m_frames: 4620 m_frameSize: 8 channels: 4
2024-01-20 15:13:55.214 T:7237    debug <general>: CActiveAESink::OpenSink - AUDIOTRACK Initialized:
2024-01-20 15:13:55.214 T:7237    debug <general>:   Output Device : AudioTrack (IEC)
2024-01-20 15:13:55.214 T:7237    debug <general>:   Sample Rate   : 96000
2024-01-20 15:13:55.214 T:7237    debug <general>:   Sample Format : AE_FMT_S16NE
**2024-01-20 15:13:55.214 T:7237    debug <general>:   Channel Count : 4
2024-01-20 15:13:55.214 T:7237    debug <general>:   Channel Layout: FL, FR, SL, SR**
2024-01-20 15:13:55.214 T:7237    debug <general>:   Frames        : 4620
2024-01-20 15:13:55.214 T:7237    debug <general>:   Frame Size    : 8
2024-01-20 15:13:55.222 T:7237    debug <general>: Could not acquire timestamp


We are succesfully opening exactly the same 4 channels we open on windows. The rest is done - as always - and you should know that from the forum by the FireTV firmware.

You can verify this by providing a logcat in parallel. Here you will see that they llike to DD+ everything that is not DTS, DTS-HD, Atmos or TrueHD.

You can influence that amazon firmware a bit by setting Sound to "PCM" in their settings, that should make the 4.0 work, but is most likely not what you like. Additionally some people report success when setting their AVR to "PURE DIRECT".

In general I have to tell everyyone who reads this:

Kodi does on Android THE 100% EXACT thing as it does on WASAPI or on ALSA. It opens AudioTrack with the best available format - but after that Android is free to do whatever it wants without a single influence by kodi.

That looks like this:

2.0 PCM -> SampleRate of Input / Float32
Multi-Channel-PCM -> SampleRate of Input / S16NE, cause Android devices (besides the Shield) can only output multi channel in 16 bit precision.

**Comment by fritsch** [comment]
PS: File that bug with amazon.

There was wise kodi developer some years ago: "First decide for the features you need, then decide for your hardware!"

**Comment by fritsch** [comment]
@thexai if you have a minute could you test one of those 4.0 samples and see if the Shield also does not properly handle it? If no device can ... we simply play it as 5.1 with the additional channels muted.

**Comment by HomerJau** [comment]
@fritsch wrote this:
---------
2.0 PCM -> SampleRate of Input / Float32
Multi-Channel-PCM -> SampleRate of Input / S16NE, cause Android devices (besides the Shield) can only output multi channel in 16 bit precision.
-----------

The Fire TV 4K Max 2nd gen (2023) spec state:
PCM/Wave. Up to 192 kHz, 8 channels, 16-bit and **24-bit**

I'm wondering whether its possible to to test 24 bit since Kodi is forcing S16NE (16 bit conversion)

**Comment by fritsch** [comment]
"Since kodi is forcing". I always like that ... as you cannot approach closed development team of amazon and simply ask what they do in firmware  ... kodi, the oss evil in the game ... 

Android is not so flexible as you think it is. Also kodi is not a shield mediaplayer or a amazon mediaplayer. 

Why not play your 4.0 audio files with exoplayer? What do you get? 24 bit precission and 4.0 channels?

**Comment by fritsch** [comment]
Read: https://developer.android.com/reference/android/media/AudioFormat#encoding
Test: https://jenkins.kodi.tv/job/android-arm-docker/5285/artifact/kodi-20240120-4977d536-hdr-armeabi-v7a.apk

This outputs highest quality from kodi as to the Android specification Float32. Reason: all ffmpeg decoders decode into float .

What you also might not have gotten: Kodi uses Audiotrack, we don't program / write to the hardware,  but talk to this sound server - it can decide whatever it wants as you see with your quad 4.0.

Therefore with above build, kodi outputs the absolute highest quality Android can cope with - and even better: the audiotrack can decide if it outputs it as 24 bit or 32 bit (both exist on Android) or even fallback to 16bit.

Curious if you see a difference in the "sample format" your AVR receives. Channel stuff stays the same.

**Comment by fritsch** [comment]
Commits:
Fill-Up: https://github.com/fritsch/xbmc/commit/e452922691dcdc139eb9bc7d620ac202db65ddbd
HighPrecision (as Exoplayer) calls it: https://github.com/fritsch/xbmc/commit/4977d536a7c4cea22bf13eb5ef6d80fc8aac1ae1 (You see it right, we had that in kodi for a long time, but (especially amazon) devices were broken with it - no matter the advertizing. I think also this time their 24 bit and HighPrecision is only meant for Stereo Output. You will tell us.

**Comment by HomerJau** [comment]
@fritsch I had already found the Android AudioFormat info and was starting to read about compiling Android Kodi to do my own testing on using a 32bit AudioFormat (I assumed this was a dead issue as far as you were concerned). Thank you for continuing to look at this.

GOOD NEWS: Using your latest Jenkins build
96kHz FLAC is output at 96kHz to my AVR!!
The test Quads are all outputting 4 channel audio (in 5.1 format) and playing correctly!!
192kHz multichannel is playing correctly (192kHz showing on my AVR)

This is awesome! THANK YOU!!!

What can be done to get any of your changes into the official Kodi Android build?

If it cant be added could you please provide me with the code changes and I'll fork and maintain/build with these fixes moving forward for the users over on QuadrapghonicQuad forum. (and anyone else into highres audio on the FTV)

**Comment by HomerJau** [comment]
Sorry, I forgot to add its playing as 24bit:

My log:
2024-01-21 08:43:13.956 T:5978     info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 96000 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 443520 m_frames: 4620 m_frameSize: 24 channels: 6
2024-01-21 08:43:13.956 T:5978    debug <general>: CActiveAESink::OpenSink - AUDIOTRACK Initialized:
2024-01-21 08:43:13.956 T:5978    debug <general>:   Output Device : AudioTrack (IEC)
2024-01-21 08:43:13.956 T:5978    debug <general>:   Sample Rate   : 96000
2024-01-21 08:43:13.956 T:5978    debug <general>:   Sample Format : AE_FMT_FLOAT
2024-01-21 08:43:13.956 T:5978    debug <general>:   Channel Count : 6
2024-01-21 08:43:13.956 T:5978    debug <general>:   Channel Layout: FL, FR, FC, LFE, BL, BR
2024-01-21 08:43:13.956 T:5978    debug <general>:   Frames        : 4620
2024-01-21 08:43:13.956 T:5978    debug <general>:   Frame Size    : 24

**Comment by fritsch** [comment]
So - one by one. 

a)  if (info.Count() == 4))
return CJNIAudioFormat::CHANNEL_OUT_QUAD;
https://developer.android.com/reference/android/media/AudioFormat#CHANNEL_OUT_QUAD <- constant value: 204 -> now, check your original logfile:
2024-01-20 15:13:42.599 T:7237     info <general>: Trying to open: samplerate: 96000, **channelMask: 204,** encoding: 2

See, this is what I tried to tell you before. We _exactly_ and 100% opened CHANNEL_OUT_QUAD and this is exactly what your device ignores and does not understand. The speaker masks in Android work like this: FL | FR | BL | BR = 0x08 | 0x04 | 0x80 | 0x40 == 0xee == 204 == CHANNEL_OUT_QUAD

So - yeah, kodi is programmed to end up 100% with the perfect channel mask, which your device does not support, which is why it needed filling up.

b) Exactly. And I kindly asked you to check what your AVR **receives**. Android and also amazon's exxoplayer fork do either do 16 bit Int or for their "High Precission" Audio as they call it, they transport Float32 to Audiotrack, but it seems you still confuse the outut of kodi with what your ears hear ... that's not the case. [1]

Also what you don't seem to understand your device is not the center of the universe. Exactly a) goes wrong with YOUR device. Why should I implement the fill-up workaround when it would break for example nvidia shield's perfect 4.0?

Don't be that "self centric", kodi is not a FireTV Max Gen2 mediaplayer, especially as HighPrecission multi channel playback was disabled _for everyone_ last time cause its predecessor could not cope with it. Find out by foum search. [2]

Now homework for you: Please find out, which precision your AVR shows for the multichannel float output.

[1]:  https://github.com/amzn/exoplayer-amazon-port/blob/amazon/r2.18.7/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L279
[2]: https://github.com/xbmc/xbmc/pull/19003 <- it was google's chromecast :-( which after one of the Cube 3rd gens that could not do it.

Next steps _after_ your did your homework:

Multi-Channel-Float: I will PR this and guard it for device >= Android TV 11.0.0 API level 30
Speaker-Fill-Up: If the Shield can play 4.0 properly, nothing will happen, as there is proof we have one device implementing Quad channel mask properly. If the Shield cannnot open it, fill-up can be considered. And no, this has nothing to do with the Shield, but with honoring devices that implement the API properly. It can't be that a multi billion dollar company amazon, does not get these right ... for this I need to wait for a Shield tester, I don't have one. If you find one yourself let him play your 4 samples, provide debuglog (while it will look exactly like yours) and say what output he / she got. I asked @thexai for help here, as he has a capable setup.


Finally: If you have question on what I wrote and why I wrote it, please ask - we don't want to turn in cycles.

**Comment by thexai** [comment]
Tested FLAC samples on Shield (current master code) and played as multi channel only the 5.1 sample, all others played as stereo.

Also tested on Intel NUC - Windows 11 using same AVR (for compare) and all samples played as Multi channel.

**Comment by fritsch** [comment]
That's a bummer. Then I sent a PR.

**Comment by HomerJau** [comment]
Excellent. Thanks @fritsch  and @thexai
