### ISSUE TITLE
Kodi on Xbox One stopped working since 20.3

### ISSUE THREAD

**Issue by MarkusRodler** [xbmc/xbmc#24548]
### Describe the bug
Here is a clear and concise description of what the problem is:

I used Kodi on Xbox One since the first release and now it has updated to 20.3 and it stopped working. I start the app and after about 55 seconds watching the Kodi logo it closes the app without any info.
I don't have any extensions installed and I have configured a smb drive years ago. On Windows the current version from the store works with the same setup.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi startscreen appears

## Actual Behavior

App closes quietly

### To Reproduce

1. Power on Xbox One
2. Update Kodi to latest version
3. Start Kodi

### Debuglog

The debuglog can be found here:
I don't know how I can provide one

### Screenshots
Here are some links or screenshots to help explain the problem:

It wouldn't make sense to screenshot the Kodi logo

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.3.0.70

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
Without log is not possible know what happens. Anyway since there are not more reports like this in forums, not seems a general bug but some isolated glitch in your setup.

The more easy way to fix probably is uninstall app from Xbox and download again from store. 
With this **all settings and local media library are lost** but should fix your issue.

The more reliable way:

- Uninstall app.
- Wait 2-3 minutes (sometimes uninstall continues in background deleting things).
- Power off Xbox.
- Power on and install Kodi again.
