### ISSUE TITLE
Weird behavior when playing queued versions

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#24592]
### Describe the bug

Playing a version queued with the "Choose version" dialog causes "Choose version" dialog to pop up again.

Playing a version queued from the "multiple versions as folder" causes navigation into the movie versions again instead of playing the version.

It's possible I don't understand how the queue and playlist features are supposed to work though.

## Expected Behavior

The queued version plays (no version chooser or browsing into the movie versions again)

### To Reproduce

Queuing from "Choose dialog"
1. Settings: configure the "Default select action" as Queue item
2. Settings: configure "Show videos with multiple versions as folder" to off
3. Setting: "Select default video version" to off
4. Go to library and select a movie with multiple versions
5. The version chooser opens, select a version
6. go to playlist, Play
7. "Choose version" opens again but should not.

Queuing from the versions folder
1. Settings: configure "Show videos with multiple versions as folder" to ON
2. Go to library and select a movie with multiple versions
3. Navigate to a version
4. Use context menu Queue item
5. Go to playlist, The movie is there. Play
6. Navigation to the versions of the movie, the playback doesn't start.
The same thing happens from versions folder with "Queue item" as default action.

### Debuglog

The debuglog can be found here: not relevant https://paste.kodi.tv/irrelevant.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21 master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by ksooo** [comment]
> go to playlist, Play

How do you trigger "Play"? By clicking an item in the playlist?

**Comment by scott967** [comment]
There's actually 2 issues.
Show versions as folder setting selected (haven't tested if this is necessary)
Assume one or more movie versions are queued in videoplaylist.
Open videoplaylist window
Navigate to a movie version
1  Open the movieinfo dialog for a movie version and select "play"  The selectvideoversion dialog opens
2.  Open the context menu and select play.  The video fails to play.
For case 1, this makes no sense as the desired version was already selected (eg in videos window)
For case 2, a debug log is here:
https://paste.kodi.tv/ipoqupovom.kodi
the problem is this:
`error <general>: CVideoPlayer::OpenInputStream - error opening [videodb://movies/videoversions/0?mediaid=21&videoversionid=0]`

**Comment by CrystalP** [comment]
> How do you trigger "Play"? By clicking an item in the playlist?

Yes. I've been looking unsuccessfully for a way to chain automatically the playback of multiple items of a playlist to see what happens with queued versions. I would expect surprises there too.

**Comment by ksooo** [comment]
Okay, let me take this. I will look for a fix.
