### ISSUE TITLE
manual subtitle posistion dose nothing

### ISSUE THREAD

**Issue by Spike1377** [xbmc/xbmc#24913]
### Describe the bug
i cant make the subtitles go lower, manual subtitle position dose nothing and just lets the subtiles use the default position

others have this problem[https://forum.kodi.tv/showthread.php?tid=373983](
https://forum.kodi.tv/showthread.php?tid=373983)
but control+ =/- dose nothing for me

## Expected Behavior
subtitles should follow the [video calibration screen](https://github.com/xbmc/xbmc/assets/113913612/9cba38d6-8feb-45fc-bb92-e6bc7e14938b) when set to manual

(i dont watch pokomon that much at all (you dont care))

## Actual Behavior
i say for them to go lower but nope they just use the default position when set to manual

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/14801249/kodi.log)

## video:
https://github.com/xbmc/xbmc/assets/113913612/943afcc1-c6c2-490e-9f2e-287b5583307a

### Your Environment
 - [x] GNU+Linux
fedora baced
 - Operating system version/name: was Nobara Linux but i got sick of it and changed it to fedoira
 - Kodi version: 20.5

also why are all the game addons missing from exitence and only mame advanced launcher shows up? on my phone lots of games addons shows up

**Comment by CastagnaIT** [comment]
this is not a bug,
you are using subtitles that contains metadata for position and styles
so you cant force change subtitle position as you wish without cause very ugly side effects like off-screen subs

often web streaming videos like N€tflix make use of "webvtt" format
this format have metadata, you can try force "disable" metadata
by enabling `Override subtitles styles` on Kodi subtitles settings

ofc if you enable "overrides" side effects can be happens such as unclear conversations due to overlapped text

**Comment by Hitcher** [comment]
You're trying to change the position in the wrong place. It's Settings > System > Display > Video Calibration...

https://kodi.wiki/images/9/91/Settings-System-Display-04.jpg

**Comment by thexai** [comment]
Also can be adjusted here:

![screenshot00000](https://github.com/xbmc/xbmc/assets/58434170/71fd6062-6a44-46dd-b8f4-5b798f4e84be)

Position on screen = Bottom of screen
Vertical margin = change %

**Comment by Spike1377** [comment]
[CastagnaIT](https://github.com/CastagnaIT)s methord was the only one that worked but now they wont goto the top when there are things at the bottom. good enough, thanks. wait no theres gotta be a better way
