### ISSUE TITLE
Kodi crashes on window resize

### ISSUE THREAD

**Issue by Stokestack** [xbmc/xbmc#24954]
### Describe the bug
Here is a clear and concise description of what the problem is:

Any resizing of the Kodi window on Mac will quickly result in a crash.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Resizing without crashing.

## Actual Behavior

Crashing

## Possible Fix

None known.

### To Reproduce

1.  Launch Kodi
2. Resize its window with the mouse

### Debuglog

The debuglog can be found here:
Crash log attached.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screen grab attached.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 14.4.1 Sonoma, Apple Silicon
 - Kodi version: 21.0

[
[KodiCrash.txt](https://github.com/xbmc/xbmc/files/14898234/KodiCrash.txt)

https://github.com/xbmc/xbmc/assets/196304/21dcd1c1-ed3c-4461-bfc7-c8726ece9a2c

](url)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by avatar333** [comment]
Thank you @Stokestack for reporting this issue, I am experiencing the same problem. I have attached my log file as a reference (all other parameters posted above match my own).
[kodi.log](https://github.com/xbmc/xbmc/files/14913925/kodi.log)

**Comment by enen92** [comment]
> Thank you @Stokestack for reporting this issue, I am experiencing the same problem. I have attached my log file as a reference (all other parameters posted above match my own). [kodi.log](https://github.com/xbmc/xbmc/files/14913925/kodi.log)

Log file is for an android device in which Kodi only supports fullscreen

**Comment by enen92** [comment]
Confirming the issue with an external display after trying hard to make it crash. Unfortunately fixing this doesn't seem to be easy since using `NSView` pretty much implies we should render on the main thread (resizing "steals" the context from Kodi app thread). Maybe with the developments for Kodi P* we're able to first move rendering to a new thread and afterwards we could probably be able to make it run on whenever thread platforms want it to run.

**Comment by Stokestack** [comment]
Interesting. It happens almost immediately for me on my MBPs screen (no secondary screen).

**Comment by enen92** [comment]
I think I've found a way to fix it :) will provide test builds shortly.

**Comment by enen92** [comment]
@Stokestack can you give these a go (depending on the arch of your mac):
arm64: https://mirrors.kodi.tv/test-builds/osx/arm64/kodi-20240413-e011e3f1-macos_avoid_refreshresize-4121-arm64.dmg
x86: https://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20240413-e011e3f1-macos_avoid_refreshresize-33863-x86_64.dmg

**Comment by Stokestack** [comment]
Thanks! Well, it no longer crashes. But the font is smushed or stretched in a pretty amusing way. Screen grab attached.


https://github.com/xbmc/xbmc/assets/196304/8c31e9e1-98ec-48d2-af1c-ef35fe01fbff

**Comment by enen92** [comment]
You mean during live resize or afterwards?
During live resize it is somehow expected since what the patch does is to avoid rendering the gui layer until the resize operation is completed. You can see in the Screencast that when you release the mouse the view is refreshed and Kodi renders again (while resizing it is just scaling the previous texture). To solve it properly we need to render on the main thread but splitting rendering and app threads have been a goal of the Kodi team since...forever.
If you're refering to the state after resize it's a different issue, already reported in https://github.com/xbmc/xbmc/issues/24644. It might need skin reloading or something similar because if you stop and start Kodi again it looks proper again.

**Comment by Stokestack** [comment]
Thanks for the follow-up. The text remains distorted after resizing. That's why I stopped resizing several times in the video and let the window sit there.
