### ISSUE TITLE
Caching not working properly

### ISSUE THREAD

**Issue by Dexer125** [xbmc/xbmc#25051]
### Describe the bug
Here is a clear and concise description of what the problem is:

Since v21 Caching is not working correctly. After filling forward to 100% video plays for some minutes, depending on size, and then after some time cache is slowly emptying. After reaching 0% it never fills up and video freezes. To make it load again I need to pause playback, wait some time and then play again.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behavior is that cache will be constantly filled as it works on v20.5. 

## Actual Behavior

On v21 cache is not constantly filled. After first fill, cache is emptying and then never fills back. 

## Possible Fix

Review Caching: difference between v20.5 and v21 except GUI options.

### To Reproduce

1. Play video over network via SMB or stream, etc.
2. Open Player Debug Info
3. Check video Cache forward fill

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/ijanirutaz](url)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 12
 - Kodi version: 21
 - Device: Nokia 8010

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
The cache functionality consists on accumulate data when the connection bandwidth is greater than the bandwidth needed for content playback.

If the bandwidth of the connection (Internet or internal if WiFi is being used) is not sufficient on a sustained basis, the cache is of no use. Cache never can "increase the available bandwidth" or make "the WiFi work better".

If the bandwidth is on average sufficient but somewhat unstable (with short speed drops) it can help. Also if the content has higher than average bitrate spikes. Even so, these are quite theoretical concepts but of little application in reality: current connections are usually quite stable and the bitrate of the content does not have important variations because it originally comes from Blu-Ray which also requires bitrates limited by its own physical limitations of the medium and the reader. And in the case of content created for streaming on the platforms, exactly the same: the content has already been designed so that it does not have significant bitrate variations.

Even so, the cache also helps in another sense: it runs in a different thread from the main/player thread, so it avoids CPU spikes that can directly affect the smoothness of the playback. That is, it is a task that does not need to be executed in strict real time as is the audio/video playback itself.

It is true that the behavior of the cache has changed a little in v21 but they are subtle changes and in no way do they make it work, but rather the opposite. For example, before the cache was filled before starting playback and now it is not. But if we are in a scenario where the cache is progressively emptied because the bandwidth is not enough, that is of no use: no one is going to want to watch a movie waiting for the cache to fill up every 30 seconds to have another 25 seconds of fluid playback.

For this specific device (Nokia 8010 4GB RAM), it is known that it has serious HW - Firmware limitations/deficiencies and there are many complaints on the internet....

You are basing this issue on arguments that do not hold up. In the forum you say that WiFi has a bandwidth of 1Gbps (https://forum.kodi.tv/showthread.php?tid=377176&pid=3193985#pid3193985) and this is not credible. The other argument is that in v20.5 it worked well... that's why I asked you for a debug log with v20.5, which of course you have not been able to provide.

An Internet search is enough to find the reality:

> I got mine today because i thought wow it has GBIT and WIFI 6 AX type.... to be honest, alot of bullcrap.
> 
> In my house everything is unifi hardware, and unifi 6 LR wifi setup. on all my AX wifi devices i get GBIT transfer speed....on this box...... it shows WIFI6 but its AC and NOT AX. speed stopped steady at 350 Mbps up and down. in my unifi controller it showed me 5G @ 80Mhz. so i plugged in a cable, and speedtest stopped around 99 Mbit.. so i checked in my unifi controller what speed it was linked on. it showed FE in stead of Gbe. it also had trouble playing 4K 60/80 GB Videofiles through plex on directplay. my sony bravia plays it well, this box has stuttering during playback.

> Nokia 8010 is an useless streaming box. Not sure why Nokia jump into this arena without knowing what they are doing. The firmware is buggy and it does not have any DTS Audio. What a freaking joke! Never owned shield before but they can produce a perfect device half a decade ago but a decent company, Nokia can only come up with such a crap today. I am looking to flash custom firmware if available because I passed the returned date. Will never consider any of their product in future.

https://www.reddit.com/r/ShieldAndroidTV/comments/10c3f0m/nokia_streaming_box_8010_serious_alternative_to/


Closing this as is not Kodi Cache issue but your device/setup issues.
