### ISSUE TITLE
Music db performance

### ISSUE THREAD

**Issue by quickmic** [xbmc/xbmc#25227]
global performance issue (musicdb design flaw) across Kodi versions:

views are poor designed

e.g.: albumview (but all musicdb views are affected)
`SELECT album.idAlbum AS idAlbum, strAlbum, strMusicBrainzAlbumID, strReleaseGroupMBID, album.strArtistDisp AS strArtists, album.strArtistSort AS strArtistSort, album.strGenres AS strGenres, album.strReleaseDate as strReleaseDate, album.strOrigReleaseDate as strOrigReleaseDate, album.bBoxedSet AS bBoxedSet, album.strMoods AS strMoods, album.strStyles AS strStyles, strThemes, strReview, strLabel, strType, strReleaseStatus, album.strImage as strImage, album.fRating, album.iUserrating, album.iVotes, bCompilation, bScrapedMBID,lastScraped,dateAdded, dateNew, dateModified, (SELECT ROUND(AVG(song.iTimesPlayed)) FROM song WHERE song.idAlbum = album.idAlbum) AS iTimesPlayed, strReleaseType, iDiscTotal, (SELECT MAX(song.lastplayed) FROM song WHERE song.idAlbum = album.idAlbum) AS lastplayed, iAlbumDuration FROM album`

double ->  "song.idAlbum = album.idAlbum"

you can review via "EXPLAIN QUERY PLAN"
seems all musicdbs versions are affected.

potential performance gain 100% (double)

Probably use JOIN.

**Comment by sarbes** [comment]
That's not a bug, there is no impairment. A lot of Kodi code can be improved, but that's not worth to track an issue for each place of potential.

**Comment by quickmic** [comment]
I didn't say it's a bug but that's exactly the answer I expected. Kodi design flaws in general never been addressed.
You can close the case, I'll fix it myself.

**Comment by sarbes** [comment]
I can surely write down 50 of such "issues", which I'm slowly getting rid off. Just read through the commit history, there is a lot of improvements going on (from lot's of different people). I don't understand where you get your impression.

Declaring such shortcomings as bugs doesn't help anybody. And this is a bug tracker after all.

And in the end, it is still a non-commercial open source project where everybody is free to choose what to contribute. Just because you think your issue is important, doesn't mean it is for others. If there is something you'd like to change, best do it yourself.

**Comment by howie-f** [comment]
> I'll fix it myself (like so many others).

> everybody is free to choose what to contribute.

we even do accept pullrequests that fix the ugliest speling misthakes in documentation for example.
so please just pr your fix and i volunteer to review and test. thanks
