### ISSUE TITLE
Bookmark issue

### ISSUE THREAD

**Issue by quickmic** [xbmc/xbmc#25301]
### Describe the bug
Bookmarks broken

### To Reproduce

1.  open a movie FROM widget WITH resumepoint
2.  add a bookmark
3.  stop movie
4.  play same movie FROM resumpoint
5.  movie will start from beginning

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21

Final comment, I guess needless to say, the complete bookmark/widget/favorites design is completely wrong. I think you know that. Maybe in far far future those design flaws will be addressed.
The core issue is, that bookmark adds "new" files (and new bookmark to the "new" files).
When you added multiversion support, this "new file" must be added as a link in the multiversion table too and it would work again. 
As mentioned, all these problems are related to poor widget etc. handing in general.
That's also the reason why bookmarks (favorites etc) are all inconsistent, as they add "new" files.
The core issue are e.g. "videodb:// links, messing up the whole "access" system. Fixing that would require a complete and consistent code base.

**Comment by ksooo** [comment]
> I guess needless to say, the complete bookmark/widget/favorites design is completely wrong.

 No, that's not needless. Can you please explain what "all wrong" means exactly?

> The core issue is, that bookmark adds "new" files (and new bookmark to the "new" files).

If "adds new files" means that when creating a bookmark new entries in the path and files table of the video db created, instead of creating the bookmark for an existing path/file entry in the db, that is the case and a bug, yes.

> As mentioned, all these problems are related to poor widget etc. handing in general.
That's also the reason why bookmarks (favorites etc) are all inconsistent, as they add "new" files.

You described a use case when it happens for bookmarks in this issue, thanks for this. This is helpful.

Can you also provide a use case where it happens for favourites and even more imprtant, for "etc"?
