### ISSUE TITLE
Save retro games in the srm format instead of sav

### ISSUE THREAD

**Issue by update-freak** [xbmc/xbmc#25587]
**Detailed Description**
I use Kodi to play retrogames from gba or snes within Kodi.
I want to sync the savegame to different devices:
- Play on every Browser with selfhosted RomM https://github.com/rommapp/romm --> Synchronisation via Syncthing
- Play on Android device with RetroArch --> Synchronisation via FolderSync while the Synchronisation is triggered via Tasker
RomM (EmulatorJS) and RetroArch will save the savegame in the srm-format, but Kodi saves in the sav-format.

This makes it not possible to have a synced save game over all these devices.
Therefore it would be good to add the possibilty to also save in the srm-format

### Context
- benefit: same savegame format for all emulators (RomM (EmulatorJS), RetroArch) and therefore continuous gaming on all devices.

### Additional context, screenshots or links
- RomM: https://github.com/rommapp/romm
- EmulatorJS: https://github.com/EmulatorJS/EmulatorJS
- RetroArch: https://github.com/libretro/RetroArch
- Syncthing: https://github.com/syncthing/syncthing

**Comment by garbear** [comment]
This is a pretty hefty feature request, because our use cases are very different and we save a lot of metadata in addition to the core's serialized memory. For example, we also store all the pixels of the frame so that they can be quickly rendered in the UI.

Do you have any documentation on the srm format? We could possibly reverse engineer it by reading the source code of emulator frontends, and output an srm file, but it would be missing all the metadata we need, and we couldn't re-import it into Kodi after playing in another emulator because it's missing the metadata.

Finally, we use github issues for but reports, not feature requests. We prefer feature requests to be introduced in the forum. So while srm support is a good idea, this issue isn't the place to discuss it.

**Comment by update-freak** [comment]
Hi @garbear 
thank you for you comment. Unfortunately, I didn't have any documentation about the srm-format.
Yes, youre right. This isn't the right place. Sry, for that. I created an thread in the forum: https://forum.kodi.tv/showthread.php?tid=378432
Therefore I will close this ticket to continue the discussion there.
