### ISSUE TITLE
[Video] Addon Very Large Buffer

### ISSUE THREAD

**Issue by CrystalP** [xbmc/xbmc#25932]
### Describe the bug

Found while testing the internet archive video add-on that Kodi seems to be buffering a lot more than is necessary to maintain smooth playback.

Same thing with v22 and v21. Most likely not limited to Windows.

## Expected Behavior

Not sure what is reasonable buffering for streamed videos (like local files 4 to 8 seconds?) but a few minutes seems too much.

## Actual Behavior

wiki hasn't been updated yet to explain the new player debug info but it looks like over 2 minutes get buffered if you give it time:

![image](https://github.com/user-attachments/assets/e8f4b14c-0318-4c64-b41e-503e89f1747d)

that also seems reflected in the osd progress bar:

![image](https://github.com/user-attachments/assets/4ab80bb6-752c-408e-99bd-f60c78b4a85b)

## Possible Fix

Looks like the formula that decides how much to buffer needs tweaking, or maybe for some reason the size is not correctly enforced.
Target capacity in seconds taking into account the video bitrate, the network bandwidth and latency.

@thexai maybe you have an idea what's going on, having tweaked the cache a few times.

### To Reproduce

1. New portable installation
2. Install the video addon Internet Archive
3. Launch the addon
4. Accept default addon settings
5. Go to "Search by Title", search for "the wooden horse"
6. Play "The Wooden Horse" (it has two versions, 1080p and 480p, both show the problem)
7. Open the player debug info (ctrl-shift-o) and watch the buffered time increase up to over 2 minutes eventually

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/todihisuci.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2
 - Kodi version: 22 master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by thexai** [comment]
125.95 seconds is "the playback time of current cached bytes"

cached bytes = 22.56 MB
stream bitrate is only 0,77 Mbit/s = 0.09625 Mbyte/s

playback time = 22.56 / 0.09625 = 234 seconds

(all this is only one estimation because no takes into account audio bitrate and stream is not constant 0,77 Mbit/s all the time, this number fluctuates and is only this value in the screenshot).

The design says that cache is "size based" and ideally always should be filled at ~100%. 
Then the playback time depends of stream bitrate.

Someone could propose to change it to "time based" and say they always want 20 seconds of cache... but be careful because then it could happen that if the stream has 400 Mbit/s (e.g. jellyfish) the cache could reach 1 GB and crash because device not has enough free RAM.

The main question here is: 
There are any problem with having 125 seconds of playback in the cache?

**Comment by thexai** [comment]
For reference:

https://github.com/xbmc/xbmc/pull/22881
https://github.com/xbmc/xbmc/pull/24117

**Comment by CrystalP** [comment]
lots of info to absorb, thank you.
