### ISSUE TITLE
Subtitle moves when kodi in window

### ISSUE THREAD

**Issue by ymca11** [xbmc/xbmc#25962]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I want to move the subtitles more to the bottom, I click Ctrl + down arrow till it say 1080 at the top of the screen.
If I make kodi in window mode then return to full screen , the place of the subtitle moves to the default place.
Then I need to correct it again each time I change the Kodi window.
The placement is not constant each time I open Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should save the position of the subtitle even if I change Kodi window or close it and open it.

## Actual Behavior

Subtitle placement always changes if Kodi window changes or Kodi is closed.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
> Subtitle placement always changes if Kodi window changes

this behavior was intended as it is,
it's been years and i don't remember precisely the reason,
but should be because you can't re-calculate the position when you change the "resolution" / size of the kodi window

> or close it and open it

when you move subtitles e.g. with keyboard shortcuts the position is only temporary,
so every time you stop a video will be resetted, this is not a bug but by design behaviour
if you want keep subtitles position permanently you must use Screen calibration settings
