### ISSUE TITLE
Audio starts with delay after video

### ISSUE THREAD

**Issue by lynx31** [xbmc/xbmc#26077]
### Describe the bug
Here is a clear and concise description of what the problem is:

Whenever a video is played or unpaused audio will start with a delay that be up to 10 seconds or more

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio should start together with video

## Actual Behavior

Audio starts only after a delay (sometimes over 10 seconds). To be clear, audio and video are in sync, there is just an initialization delay

## Possible Fix

None found

### To Reproduce

1. Run Kodi 
2. Select video to play
3. Start video

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ukedesagih.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 22.0-ALPHA1 (21.90.700), but also other versions

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fritsch** [comment]
Bug in your amazon device. See the **superviseaudiodelay** hack you  have to use ... audio resumes up to three times and has to be killed, cause the sink dies under the hood.

See all the:
**Sink got stuck with ...  - ask AE for reopening**
messages

If you want inferior audio quality but kind of faster resume, choose RAW sink instead of IEC sink ... you will loose certain PT formats with that.
